import type { ContentEntity, ContentManifest, LocalizedContentVersion, LocalizedImage } from "../../lib/content/types";
import { dumbbellProducts } from "../../app/products/dumbbells/productData";
import { weightPlateProducts } from "../../app/products/weight-plates/productData";
import { racksBenchesProducts } from "../../app/products/racks-benches/productData";
import { gymAccessoryProducts } from "../../app/products/gym-accessories/productData";
import { ptBrEditorialAuthor, ptBrTechnicalReviewer } from "./pt-br-existing-growth";
import { checklist as ptChecklist, definition as ptDefinition, quick as ptQuick, rich as ptRich, table as ptTable } from "./pt-br-content-helpers";
import { spanishEditorialAuthor, spanishTechnicalReviewer, checklist as esChecklist, definition as esDefinition, quick as esQuick, rich as esRich, table as esTable } from "./es-content-helpers";
import { koAnswer, koChecklist, koDefinition, koreanEditorialAuthor, koreanTechnicalReviewer, koTable, koText } from "./ko-content-helpers";

const releaseDate = "2026-07-22T02:00:00.000Z";

type Family = "dumbbells" | "plates" | "racks" | "accessories";
type Grade = "B" | "C";
type ProductSource = { slug: string; name: string; range: string; type: string; image: string; gallery?: string[] };
type Selection = { grade: Grade; family: Family; slug: string; pt: string; es: string; ko: string };

const selections: Selection[] = [
  { grade:"B",family:"dumbbells",slug:"twelve-sided-steel-dumbbell",pt:"Halter dodecagonal de aço",es:"Mancuerna dodecagonal de acero",ko:"12각 스틸 덤벨" },
  { grade:"B",family:"dumbbells",slug:"cpu-square-dumbbell-kg",pt:"Halter quadrado em CPU",es:"Mancuerna cuadrada de CPU",ko:"CPU 사각 덤벨" },
  { grade:"B",family:"dumbbells",slug:"cpu-heavy-dumbbell-kg",pt:"Halter pesado em CPU",es:"Mancuerna pesada de CPU",ko:"CPU 중량 덤벨" },
  { grade:"B",family:"dumbbells",slug:"sus304-dumbbell-kg",pt:"Halter em aço inoxidável SUS304",es:"Mancuerna de acero inoxidable SUS304",ko:"SUS304 스테인리스 덤벨" },
  { grade:"B",family:"dumbbells",slug:"tpu-round-dumbbell-kg",pt:"Halter redondo em TPU",es:"Mancuerna redonda de TPU",ko:"TPU 원형 덤벨" },
  { grade:"B",family:"dumbbells",slug:"selectorized-adjustable-dumbbell-kg",pt:"Halter ajustável com seletor",es:"Mancuerna ajustable con selector",ko:"셀렉터형 조절식 덤벨" },
  { grade:"B",family:"dumbbells",slug:"cpu-hexagonal-dumbbell-kg",pt:"Halter sextavado em CPU",es:"Mancuerna hexagonal de CPU",ko:"CPU 육각 덤벨" },
  { grade:"B",family:"dumbbells",slug:"cpu-twelve-sided-dumbbell",pt:"Halter dodecagonal em CPU",es:"Mancuerna dodecagonal de CPU",ko:"CPU 12각 덤벨" },
  { grade:"B",family:"dumbbells",slug:"cpu-dumbbell-full-range",pt:"Linha completa de halteres em CPU",es:"Gama completa de mancuernas de CPU",ko:"CPU 덤벨 풀 레인지" },
  { grade:"C",family:"dumbbells",slug:"neoprene-dumbbell-kg",pt:"Halter de neoprene",es:"Mancuerna de neopreno",ko:"네오프렌 덤벨" },
  { grade:"C",family:"dumbbells",slug:"tpu-small-dumbbell-kg",pt:"Halter compacto em TPU",es:"Mancuerna compacta de TPU",ko:"TPU 소형 덤벨" },
  { grade:"C",family:"dumbbells",slug:"cpu-compact-dumbbell",pt:"Halter compacto em CPU",es:"Mancuerna compacta de CPU",ko:"CPU 컴팩트 덤벨" },
  { grade:"C",family:"dumbbells",slug:"cpu-hexagonal-dumbbell-wide",pt:"Halter sextavado largo em CPU",es:"Mancuerna hexagonal ancha de CPU",ko:"CPU 와이드 육각 덤벨" },

  { grade:"B",family:"plates",slug:"cpu-color-bumper-plate",pt:"Anilha bumper colorida em CPU",es:"Disco bumper de color en CPU",ko:"CPU 컬러 범퍼 플레이트" },
  { grade:"B",family:"plates",slug:"rubber-weight-plate",pt:"Anilha de peso emborrachada",es:"Disco de peso recubierto de caucho",ko:"고무 코팅 웨이트 플레이트" },
  { grade:"B",family:"plates",slug:"rubber-barbell-plate",pt:"Anilha emborrachada para barra olímpica",es:"Disco de caucho para barra olímpica",ko:"고무 바벨 플레이트" },
  { grade:"B",family:"plates",slug:"full-rubber-barbell-plate",pt:"Anilha totalmente emborrachada",es:"Disco completamente recubierto de caucho",ko:"풀 러버 바벨 플레이트" },
  { grade:"B",family:"plates",slug:"black-competition-plate",pt:"Anilha de competição preta",es:"Disco de competición negro",ko:"블랙 컴피티션 플레이트" },
  { grade:"B",family:"plates",slug:"solid-steel-barbell-plate",pt:"Anilha de aço maciço",es:"Disco de acero macizo",ko:"솔리드 스틸 바벨 플레이트" },
  { grade:"B",family:"plates",slug:"custom-solid-steel-barbell-plate",pt:"Anilha personalizada de aço maciço",es:"Disco personalizado de acero macizo",ko:"커스텀 솔리드 스틸 플레이트" },
  { grade:"B",family:"plates",slug:"heavy-solid-steel-plate",pt:"Anilha pesada de aço maciço",es:"Disco pesado de acero macizo",ko:"헤비 솔리드 스틸 플레이트" },
  { grade:"B",family:"plates",slug:"seven-hole-cast-iron-plate",pt:"Anilha de ferro fundido com sete pegadas",es:"Disco de hierro fundido con siete agarres",ko:"7홀 주철 웨이트 플레이트" },
  { grade:"B",family:"plates",slug:"tpu-olympic-plate",pt:"Anilha olímpica em TPU",es:"Disco olímpico de TPU",ko:"TPU 올림픽 플레이트" },
  { grade:"B",family:"plates",slug:"pu-grip-plate",pt:"Anilha em PU com pegadas",es:"Disco de PU con agarres",ko:"PU 그립 플레이트" },
  { grade:"C",family:"plates",slug:"gold-steel-barbell-plate",pt:"Anilha de aço com acabamento dourado",es:"Disco de acero con acabado dorado",ko:"골드 스틸 바벨 플레이트" },
  { grade:"C",family:"plates",slug:"spray-weight-plate",pt:"Anilha de peso com pintura pulverizada",es:"Disco de peso con pintura pulverizada",ko:"도장 웨이트 플레이트" },
  { grade:"C",family:"plates",slug:"star-tpu-plate",pt:"Anilha estrela em TPU",es:"Disco estrella de TPU",ko:"스타 TPU 플레이트" },
  { grade:"C",family:"plates",slug:"pu-color-plate",pt:"Anilha colorida em PU",es:"Disco de color en PU",ko:"PU 컬러 플레이트" },
  { grade:"C",family:"plates",slug:"cpu-mini-bumper-plate",pt:"Mini anilha bumper em CPU",es:"Mini disco bumper de CPU",ko:"CPU 미니 범퍼 플레이트" },
  { grade:"C",family:"plates",slug:"pu-plate-set",pt:"Conjunto de anilhas em PU",es:"Juego de discos de PU",ko:"PU 플레이트 세트" },
  { grade:"C",family:"plates",slug:"four-grip-cpu-plate",pt:"Anilha em CPU com quatro pegadas",es:"Disco de CPU con cuatro agarres",ko:"CPU 4그립 플레이트" },

  { grade:"B",family:"racks",slug:"compact-cable-power-rack",pt:"Power rack compacto com cabos",es:"Jaula de potencia compacta con poleas",ko:"컴팩트 케이블 파워랙" },
  { grade:"B",family:"racks",slug:"dual-pulley-smith-rack",pt:"Smith rack com polias duplas",es:"Rack Smith con doble polea",ko:"듀얼 풀리 스미스 랙" },
  { grade:"B",family:"racks",slug:"storage-functional-trainer",pt:"Treinador funcional com armazenamento",es:"Entrenador funcional con almacenamiento",ko:"수납형 펑셔널 트레이너" },
  { grade:"B",family:"racks",slug:"cable-crossover-functional-trainer",pt:"Treinador funcional crossover",es:"Entrenador funcional de cruce de poleas",ko:"케이블 크로스오버 펑셔널 트레이너" },
  { grade:"B",family:"racks",slug:"adjustable-weight-bench",pt:"Banco de musculação ajustável",es:"Banco de musculación ajustable",ko:"조절식 웨이트 벤치" },
  { grade:"B",family:"racks",slug:"smith-squat-frame",pt:"Estrutura Smith para agachamento",es:"Estructura Smith para sentadillas",ko:"스미스 스쿼트 프레임" },
  { grade:"B",family:"racks",slug:"half-frame-squat-rack",pt:"Half rack para agachamento",es:"Half rack para sentadillas",ko:"하프 프레임 스쿼트 랙" },
  { grade:"B",family:"racks",slug:"cable-crossover-machine",pt:"Máquina crossover de cabos",es:"Máquina de cruce de poleas",ko:"케이블 크로스오버 머신" },
  { grade:"B",family:"racks",slug:"full-frame-squat-rack",pt:"Power rack fechado para agachamento",es:"Jaula completa para sentadillas",ko:"풀 프레임 스쿼트 랙" },
  { grade:"B",family:"racks",slug:"smith-cable-crossover-machine",pt:"Smith Machine com crossover de cabos",es:"Máquina Smith con cruce de poleas",ko:"스미스 케이블 크로스오버 머신" },
  { grade:"C",family:"racks",slug:"private-home-gym-rack-system",pt:"Sistema de rack para academia particular",es:"Sistema de rack para gimnasio privado",ko:"프라이빗 홈짐 랙 시스템" },
  { grade:"C",family:"racks",slug:"home-gym-functional-trainer",pt:"Treinador funcional para home gym",es:"Entrenador funcional para gimnasio doméstico",ko:"홈짐 펑셔널 트레이너" },
  { grade:"C",family:"racks",slug:"custom-home-gym-rack",pt:"Rack personalizado para home gym",es:"Rack personalizado para gimnasio doméstico",ko:"맞춤형 홈짐 랙" },
  { grade:"C",family:"racks",slug:"cable-cross-functional-trainer",pt:"Treinador funcional cable cross",es:"Entrenador funcional cable cross",ko:"케이블 크로스 펑셔널 트레이너" },
  { grade:"C",family:"racks",slug:"six-column-functional-trainer",pt:"Treinador funcional de seis colunas",es:"Entrenador funcional de seis columnas",ko:"6컬럼 펑셔널 트레이너" },
  { grade:"C",family:"racks",slug:"eight-column-training-rack",pt:"Rack de treinamento de oito colunas",es:"Rack de entrenamiento de ocho columnas",ko:"8컬럼 트레이닝 랙" },
  { grade:"C",family:"racks",slug:"wall-mounted-functional-trainer",pt:"Treinador funcional fixado na parede",es:"Entrenador funcional de pared",ko:"벽면형 펑셔널 트레이너" },
  { grade:"C",family:"racks",slug:"floor-plate-cable-crossover",pt:"Crossover de cabos com bases de piso",es:"Cruce de poleas con bases de suelo",ko:"플로어 플레이트 케이블 크로스오버" },
  { grade:"C",family:"racks",slug:"three-in-one-smith-functional-trainer",pt:"Treinador funcional Smith três em um",es:"Entrenador funcional Smith tres en uno",ko:"3-in-1 스미스 펑셔널 트레이너" },
  { grade:"C",family:"racks",slug:"smith-dual-pulley-trainer",pt:"Treinador Smith com polias duplas",es:"Entrenador Smith con doble polea",ko:"스미스 듀얼 풀리 트레이너" },

  { grade:"B",family:"accessories",slug:"vinyl-kettlebell",pt:"Kettlebell revestido em vinil",es:"Kettlebell revestido de vinilo",ko:"비닐 코팅 케틀벨" },
  { grade:"B",family:"accessories",slug:"competition-kettlebell",pt:"Kettlebell de competição",es:"Kettlebell de competición",ko:"컴피티션 케틀벨" },
  { grade:"B",family:"accessories",slug:"rubber-coated-gym-handle-sets",pt:"Conjunto de puxadores emborrachados",es:"Juego de agarres recubiertos de caucho",ko:"고무 코팅 케이블 핸들 세트" },
  { grade:"B",family:"accessories",slug:"aluminum-gym-handles",pt:"Puxadores de academia em alumínio",es:"Agarres de gimnasio de aluminio",ko:"알루미늄 케이블 핸들" },
  { grade:"B",family:"accessories",slug:"solid-steel-gym-handles",pt:"Puxadores de academia em aço maciço",es:"Agarres de gimnasio de acero macizo",ko:"솔리드 스틸 케이블 핸들" },
  { grade:"B",family:"accessories",slug:"lat-pulldown-handles",pt:"Puxadores para pulley e lat pulldown",es:"Agarres para jalón al pecho",ko:"랫풀다운 핸들" },
  { grade:"B",family:"accessories",slug:"cable-machine-attachments",pt:"Acessórios para máquinas de cabos",es:"Accesorios para máquinas de poleas",ko:"케이블 머신 어태치먼트" }
];

const sourceCatalog = new Map<string, { family: Family; source: ProductSource }>();
for (const [family, products] of [["dumbbells",dumbbellProducts],["plates",weightPlateProducts],["racks",racksBenchesProducts],["accessories",gymAccessoryProducts]] as const) {
  for (const source of products) sourceCatalog.set(source.slug, { family, source });
}

const roots = {
  "pt-BR": { dumbbells:["/pt/produtos/halteres","dumbbells-category","Halteres"],plates:["/pt/produtos/anilhas","weight-plates-category","Anilhas"],racks:["/pt/produtos/racks-e-bancos","racks-benches-category","Racks e bancos"],accessories:["/pt/produtos/acessorios-de-academia","gym-accessories-category","Acessórios"] },
  es: { dumbbells:["/es/productos/mancuernas","dumbbells-category","Mancuernas"],plates:["/es/productos/discos-de-peso","weight-plates-category","Discos de peso"],racks:["/es/productos/racks-y-bancos","racks-benches-category","Racks y bancos"],accessories:["/es/productos/accesorios-de-gimnasio","gym-accessories-category","Accesorios"] },
  ko: { dumbbells:["/ko/products/dumbbells","dumbbells-category","덤벨"],plates:["/ko/products/weight-plates","weight-plates-category","웨이트 플레이트"],racks:["/ko/products/racks-benches","racks-benches-category","랙과 벤치"],accessories:["/ko/products/gym-accessories","gym-accessories-category","헬스장 액세서리"] }
} as const;

function publicSlug(locale: "pt-BR"|"es"|"ko", selection: Selection) {
  if (locale === "ko") return selection.slug;
  const text = locale === "pt-BR" ? selection.pt : selection.es;
  return text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
}

function localRange(range: string, locale: "pt-BR"|"es"|"ko") {
  if (!/\d/.test(range)) {
    if (locale === "pt-BR") return "configuração, dimensões e acessórios conforme o modelo cotado";
    if (locale === "es") return "configuración, dimensiones y accesorios según el modelo cotizado";
    return "견적 모델에 따른 구성, 크기 및 액세서리 선택";
  }
  if (locale === "pt-BR") return range.replace(/available/gi,"disponíveis").replace(/custom weight options/gi,"opções de peso sob consulta").replace(/increments/gi,"incrementos").replace(/planning/gi,"planejamento").replace(/sets/gi,"conjuntos").replace(/options/gi,"opções").replace(/for gym projects/gi,"para projetos de academia").replace(/\band\b/gi,"e").replace(/\bor\b/gi,"ou").replace(/\bto\b/gi,"a");
  if (locale === "es") return range.replace(/available/gi,"disponibles").replace(/custom weight options/gi,"opciones de peso bajo consulta").replace(/increments/gi,"incrementos").replace(/planning/gi,"planificación").replace(/sets/gi,"juegos").replace(/options/gi,"opciones").replace(/for gym projects/gi,"para proyectos de gimnasio").replace(/\band\b/gi,"y").replace(/\bor\b/gi,"o").replace(/\bto\b/gi,"a");
  return range.replace(/available/gi,"선택 가능").replace(/custom weight options/gi,"맞춤 중량 협의").replace(/increments/gi,"단위 구성").replace(/planning/gi,"구성 협의").replace(/sets/gi,"세트").replace(/options/gi,"옵션").replace(/for gym projects/gi,"헬스장 프로젝트용").replace(/\band\b/gi,"및").replace(/\bor\b/gi,"또는").replace(/\bto\b/gi,"~");
}

function localMaterial(type: string, locale: "pt-BR"|"es"|"ko") {
  const maps = {
    "pt-BR": [[/Solid steel/gi,"aço maciço"],[/Stainless steel/gi,"aço inoxidável"],[/steel/gi,"aço"],[/Cast iron/gi,"ferro fundido"],[/Rubber/gi,"borracha"],[/coating/gi,"revestimento"],[/plate/gi,"anilha"],[/Kettlebell/gi,"kettlebell"],[/Gym handles/gi,"puxadores de academia"],[/Cable attachments/gi,"acessórios de cabos"],[/attachment/gi,"acessório"],[/Functional Rack/gi,"rack funcional"],[/Power Rack/gi,"power rack"],[/Project Solution/gi,"solução de projeto"],[/Home Gym System/gi,"sistema para home gym"],[/Bench/gi,"banco"],[/trainer/gi,"treinador"],[/Adjustable/gi,"ajustável"]],
    es: [[/Solid steel/gi,"acero macizo"],[/Stainless steel/gi,"acero inoxidable"],[/steel/gi,"acero"],[/Cast iron/gi,"hierro fundido"],[/Rubber/gi,"caucho"],[/coating/gi,"recubrimiento"],[/plate/gi,"disco"],[/Kettlebell/gi,"kettlebell"],[/Gym handles/gi,"agarres de gimnasio"],[/Cable attachments/gi,"accesorios de poleas"],[/attachment/gi,"accesorio"],[/Functional Rack/gi,"rack funcional"],[/Power Rack/gi,"jaula de potencia"],[/Project Solution/gi,"solución de proyecto"],[/Home Gym System/gi,"sistema de gimnasio doméstico"],[/Bench/gi,"banco"],[/trainer/gi,"entrenador"],[/Adjustable/gi,"ajustable"]],
    ko: [[/Solid steel/gi,"솔리드 스틸"],[/Stainless steel/gi,"스테인리스 스틸"],[/steel/gi,"스틸"],[/Cast iron/gi,"주철"],[/Rubber/gi,"고무"],[/coating/gi,"코팅"],[/plate/gi,"플레이트"],[/Kettlebell/gi,"케틀벨"],[/Gym handles/gi,"케이블 핸들"],[/Cable attachments/gi,"케이블 어태치먼트"],[/attachment/gi,"어태치먼트"],[/Functional Rack/gi,"펑셔널 랙"],[/Power Rack/gi,"파워랙"],[/Project Solution/gi,"프로젝트 솔루션"],[/Home Gym System/gi,"홈짐 시스템"],[/Bench/gi,"벤치"],[/trainer/gi,"트레이너"],[/Adjustable/gi,"조절식"]]
  } as const;
  const translated = maps[locale].reduce((value,[pattern,replacement])=>value.replace(pattern,replacement),type);
  const cleanup = {
    "pt-BR": [[/All-in-One Rack/gi,"rack multifuncional"],[/Custom treinador/gi,"estação personalizada"],[/Cable Crossover/gi,"crossover com cabos"],[/Home Gym Rack/gi,"rack para home gym"],[/Smith Functional treinador/gi,"estação funcional Smith"],[/Color bumper anilha/gi,"anilha bumper colorida"],[/Competition weight anilha/gi,"anilha de competição"],[/Custom aço maciço anilha/gi,"anilha personalizada de aço maciço"],[/Heavy aço maciço anilha/gi,"anilha pesada de aço maciço"],[/Seven-hole ferro fundido anilha/gi,"anilha de ferro fundido com sete pegadas"],[/TPU Olympic anilha/gi,"anilha olímpica em TPU"],[/PU grip anilha/gi,"anilha em PU com pegadas"],[/Gold aço anilha/gi,"anilha de aço dourada"],[/Spray finish anilha/gi,"anilha com pintura pulverizada"],[/Decorative TPU anilha/gi,"anilha decorativa em TPU"],[/PU color anilha/gi,"anilha colorida em PU"],[/Mini bumper anilha/gi,"anilha bumper compacta"],[/PU anilha set/gi,"conjunto de anilhas em PU"],[/Four-grip CPU anilha/gi,"anilha CPU com quatro pegadas"],[/Full borracha anilha/gi,"anilha integral em borracha"],[/borracha barbell anilha/gi,"anilha de barra revestida em borracha"],[/Competition kettlebell/gi,"kettlebell de competição"],[/Lat pulldown acessório/gi,"puxador para pulley alto"],[/Cable acessório set/gi,"conjunto de puxadores para cabo"],[/Neoprene/gi,"neoprene"]],
    es: [[/All-in-One Rack/gi,"rack multifunción"],[/Custom entrenador/gi,"estación personalizada"],[/Cable Crossover/gi,"cruce de poleas"],[/Home Gym Rack/gi,"rack para gimnasio doméstico"],[/Smith Functional entrenador/gi,"estación funcional Smith"],[/Color bumper disco/gi,"disco bumper de color"],[/Competition weight disco/gi,"disco de competición"],[/Custom acero macizo disco/gi,"disco personalizado de acero macizo"],[/Heavy acero macizo disco/gi,"disco pesado de acero macizo"],[/Seven-hole hierro fundido disco/gi,"disco de hierro fundido con siete agarres"],[/TPU Olympic disco/gi,"disco olímpico de TPU"],[/PU grip disco/gi,"disco de PU con agarres"],[/Gold acero disco/gi,"disco de acero dorado"],[/Spray finish disco/gi,"disco con acabado pulverizado"],[/Decorative TPU disco/gi,"disco decorativo de TPU"],[/PU color disco/gi,"disco de PU de color"],[/Mini bumper disco/gi,"disco bumper compacto"],[/PU disco set/gi,"juego de discos de PU"],[/Four-grip CPU disco/gi,"disco CPU con cuatro agarres"],[/Full caucho disco/gi,"disco integral de caucho"],[/caucho barbell disco/gi,"disco para barra recubierto de caucho"],[/Competition kettlebell/gi,"kettlebell de competición"],[/Lat pulldown accesorio/gi,"agarre para jalón al pecho"],[/Cable accesorio set/gi,"juego de accesorios para polea"],[/Neoprene/gi,"neopreno"]],
    ko: [[/All-in-One Rack/gi,"올인원 랙"],[/Custom 트레이너/gi,"맞춤형 트레이너"],[/Cable Crossover/gi,"케이블 크로스오버"],[/Home Gym Rack/gi,"홈짐 랙"],[/Smith Functional 트레이너/gi,"스미스 기능성 트레이너"],[/Color bumper 플레이트/gi,"컬러 범퍼 플레이트"],[/Competition weight 플레이트/gi,"경기용 원판"],[/Custom 솔리드 스틸 플레이트/gi,"맞춤형 솔리드 스틸 원판"],[/Heavy 솔리드 스틸 플레이트/gi,"고중량 솔리드 스틸 원판"],[/Seven-hole 주철 플레이트/gi,"7그립 주철 원판"],[/TPU Olympic 플레이트/gi,"TPU 올림픽 원판"],[/PU grip 플레이트/gi,"그립형 PU 원판"],[/Gold 스틸 플레이트/gi,"골드 스틸 원판"],[/Spray finish 플레이트/gi,"도장 마감 원판"],[/Decorative TPU 플레이트/gi,"TPU 디자인 원판"],[/PU color 플레이트/gi,"컬러 PU 원판"],[/Mini bumper 플레이트/gi,"미니 범퍼 플레이트"],[/PU 플레이트 set/gi,"PU 원판 세트"],[/Four-grip CPU 플레이트/gi,"4그립 CPU 원판"],[/Full 고무 플레이트/gi,"전면 고무 원판"],[/고무 barbell 플레이트/gi,"고무 코팅 바벨 원판"],[/Competition 케틀벨/gi,"경기용 케틀벨"],[/Lat pulldown 어태치먼트/gi,"랫풀다운 그립"],[/Cable 어태치먼트 set/gi,"케이블 액세서리 세트"],[/Neoprene/gi,"네오프렌"]]
  } as const;
  return cleanup[locale].reduce((value,[pattern,replacement])=>value.replace(pattern,replacement),translated);
}

function profileFocus(family: Family, locale: "pt-BR"|"es"|"ko") {
  const values = {
    "pt-BR": { dumbbells:"equilíbrio entre faixa de pesos, formato da cabeça, empunhadura, estabilidade no rack e consistência visual do conjunto",plates:"compatibilidade com barras e máquinas, leitura do peso, diâmetro, espessura, centro, manuseio e proteção do piso",racks:"geometria, área operacional, pontos de ajuste, percurso, estabilidade, montagem, fluxo de usuários e acesso para manutenção",accessories:"geometria da pegada, rotação, acabamento, conexão, conforto, resistência ao uso repetido e organização do mix" },
    es: { dumbbells:"equilibrio entre rango de pesos, forma de la cabeza, empuñadura, estabilidad en el soporte y coherencia visual del juego",plates:"compatibilidad con barras y máquinas, lectura del peso, diámetro, espesor, centro, manipulación y protección del suelo",racks:"geometría, superficie operativa, ajustes, recorrido, estabilidad, montaje, circulación y acceso para mantenimiento",accessories:"geometría del agarre, giro, acabado, conexión, comodidad, resistencia al uso repetido y organización del surtido" },
    ko: { dumbbells:"중량 구성, 헤드 형상, 그립, 랙 보관 안정성, 세트 전체의 외관 일관성",plates:"바와 머신 호환성, 중량 표기, 직경, 두께, 센터 홀, 취급성, 바닥 보호",racks:"프레임 형상, 실제 사용 면적, 조절 위치, 작동 범위, 안정성, 조립, 사용자 동선, 정비 접근성",accessories:"그립 형상, 회전 구조, 마감, 연결 규격, 사용감, 반복 사용 내구성, 세트 구성" }
  } as const;
  return values[locale][family];
}

function imageSet(source: ProductSource, name: string, locale: "pt-BR"|"es"|"ko", family: Family): LocalizedImage[] {
  const gallery = [source.image,...(source.gallery ?? [])].filter((item,index,array)=>array.indexOf(item)===index);
  const process = family === "dumbbells" ? "/assets/dumbbell-production.webp" : family === "plates" ? "/assets/factory-process/plate-surface-treatment.webp" : "/assets/factory-cases/packaging-area-pbf.webp";
  const captions = locale === "pt-BR" ? [`Vista real do produto ${name}`,`Detalhes reais de ${name}`,`Produção, inspeção e embalagem relacionadas a ${name}`] : locale === "es" ? [`Vista real del producto ${name}`,`Detalles reales de ${name}`,`Producción, inspección y embalaje relacionados con ${name}`] : [`${name} 실제 제품 이미지`,`${name} 실제 제품 세부`,`${name} 생산·검사·포장 정보`];
  return [gallery[0],gallery[1] ?? process,process].filter((item,index,array)=>array.indexOf(item)===index).slice(0,3).map((src,index)=>({id:`image-${index+1}`,src,alt:captions[index] ?? captions.at(-1)!,caption:captions[index] ?? captions.at(-1)!}));
}

function base(locale: "pt-BR"|"es"|"ko", slug: string, publicPath: string, title: string, description: string, h1: string, body: LocalizedContentVersion["body"], faq: LocalizedContentVersion["faq"], schemaData: LocalizedContentVersion["schemaData"], images: LocalizedImage[], internalLinks: LocalizedContentVersion["internalLinks"]): LocalizedContentVersion {
  return { locale,translationStatus:"localized",reviewStatus:"approved",publishStatus:"published",slug,publicPath,title,description,h1,body,faq,author:locale==="pt-BR"?ptBrEditorialAuthor:locale==="es"?spanishEditorialAuthor:koreanEditorialAuthor,reviewedBy:locale==="pt-BR"?ptBrTechnicalReviewer:locale==="es"?spanishTechnicalReviewer:koreanTechnicalReviewer,schemaData,images,internalLinks,canonicalData:{mode:"self"},hreflangData:{include:true},updatedAt:releaseDate,publishedAt:releaseDate,version:1 };
}

function portugueseVersion(entity: ContentEntity, selection: Selection, source: ProductSource): LocalizedContentVersion {
  const name=selection.pt, slug=publicSlug("pt-BR",selection), root=roots["pt-BR"][selection.family], path=`${root[0]}/${slug}`, range=localRange(source.range,"pt-BR"), material=localMaterial(source.type,"pt-BR"), focus=profileFocus(selection.family,"pt-BR");
  const keyword=selection.family==="accessories"?`${name.toLowerCase()} no atacado`:`fabricante de ${name.toLowerCase()}`;
  const body=[
    ptQuick("resposta",`${name} é uma opção para compradores profissionais que precisam definir ${focus}. A cotação deve identificar modelo, faixa ${range}, quantidade, aplicação, personalização, destino e critérios de aceitação; dados não confirmados ficam sujeitos à validação da referência escolhida.`),
    ptDefinition("definicao",name,`${name} pertence à família comercial de ${root[2].toLowerCase()} e utiliza ${material}. O nome do produto não substitui uma ficha de compra: dimensões, peso, construção, itens incluídos, acabamento e embalagem precisam estar vinculados ao mesmo código e à amostra aprovada.`),
    ptRich("posicionamento","Onde este produto cria valor",`No mercado brasileiro, ${name} faz sentido quando o comprador consegue relacionar o produto ao canal, à intensidade de uso e ao espaço disponível. A decisão deve considerar volume, prazo, manutenção prevista e custo total de propriedade.`,`Academias avaliam operação, limpeza e manutenção; distribuidores consideram giro, reposição e apresentação; importadores calculam embalagem, peso bruto e custo posto; marcas próprias acrescentam logo, cor, arquivos e continuidade entre lotes.`),
    ptRich("aplicacoes","Aplicações comerciais e público comprador",`O briefing deve explicar se ${name} será usado em academia comercial, studio, hotel, condomínio, showroom, linha de distribuição ou projeto de marca própria. A frequência, o perfil dos usuários e a forma de armazenamento alteram os riscos e os critérios de inspeção.`,`Uma compra responsável não usa a expressão “profissional” como especificação. O comprador descreve fluxo, ambiente, equipamentos relacionados, rotina de manutenção e expectativa de reposição para que a configuração proposta seja comparável.`),
    ptRich("vantagem","Valor de compra e limites",`O principal valor de ${name} está em ${focus}. Esse valor só é real quando medidas, materiais, compatibilidade e condições de uso são verificáveis. Aparência semelhante não demonstra construção equivalente.`,`A página não declara carga, tolerância, vida útil ou certificação não confirmada. Quando o dado depende do modelo, ele deve aparecer na proposta, desenho, manual, amostra ou plano de QC antes da produção.`),
    ptTable("especificacoes","Especificações para solicitar na cotação",["Campo","Base desta linha","Confirmação necessária"],[["Produto",name,"Código e versão"],["Faixa",range,"Opções e unidades"],["Material",material,"Construção e acabamento"],["Aplicação","Uso comercial B2B","Ambiente e intensidade"],["Dimensões","Conforme modelo","Desenho com unidades"],["OEM","Logo, cor e embalagem sob análise","Método, MOQ e amostra"],["QC","Plano ligado à ficha aprovada","Método, tolerância e amostragem"]],`Dados de compra para ${name}`),
    ptRich("materiais","Materiais e construção",`${material} descreve a base comercial, mas o comprador ainda deve confirmar interfaces, espessuras relevantes, acabamento, componentes de contato e peças sujeitas a desgaste. Para ${name}, a revisão técnica deve concentrar-se em ${focus}.`,`Uma amostra recebe código, data e arquivos associados. Mudanças de matéria-prima, molde, ferragem, cor ou fornecedor de componente devem ser informadas antes do lote, porque podem afetar encaixe, aparência, manuseio ou manutenção.`),
    ptRich("dimensoes","Dimensões, peso e compatibilidade",`A faixa informada é ${range}. Antes de pedir preço final, confirme se os valores representam unidade, par, conjunto, carga selecionável ou capacidade do sistema. Toda medida precisa de unidade e ponto de referência.`,`Compatibilidade deve ser testada com barra, rack, estação, acessórios, piso ou área operacional realmente previstos. Não basta afirmar que o produto segue um padrão quando o diâmetro, encaixe, percurso ou espaço de segurança não foi documentado.`),
    ptRich("processo","Processo de fabricação",`O fluxo de ${name} começa com ficha e materiais aprovados, segue por preparação, formação ou usinagem, acabamento, montagem quando aplicável, identificação, inspeção e embalagem. Cada etapa crítica deve ter um resultado observável.`,`A PowerBaseFit relaciona código do produto, arte, amostra, ordem de produção, registro de QC e packing list. Essa rastreabilidade ajuda a localizar variações e reduz o risco de produzir uma configuração diferente daquela usada para aprovar preço e aparência.`),
    ptRich("qc","Controle de qualidade",`O plano de inspeção para ${name} cobre identidade, quantidade, medidas críticas, peso ou faixa, função, superfície, marcação e embalagem. O foco específico é ${focus}.`,`Amostragem e limites são definidos antes da produção. Fotos sem código, lote, escala e critério não substituem medição. Dependendo do risco e do valor, o comprador pode combinar QC de processo, inspeção final e verificação independente pré-embarque.`),
    ptTable("comparacao","Como comparar fornecedores",["Critério","Resposta fraca","Evidência útil"],[["Modelo","Igual à foto","Código, desenho e lista de itens"],["Material","Qualidade premium",`Construção em ${material} e referência aprovada`],["Dimensões","Tamanho padrão","Medidas com unidade e tolerância"],["OEM","Logo disponível","Método, posição, arte, MOQ e amostra"],["Embalagem","Caixa de exportação","Unidades, peso, dimensões e pallet"],["Prazo","Entrega rápida","Etapas, aprovações e data de prontidão"]]),
    ptRich("embalagem","Embalagem, transporte e recebimento",`A embalagem precisa proteger as superfícies e interfaces de ${name}, limitar movimento interno e distribuir o peso de forma segura. Confirme unidades por caixa, peso líquido e bruto, dimensões, etiqueta, pallet e ordem de abertura.`,`O importador brasileiro calcula frete, seguro, tributos, despesas de destino, transporte interno, descarga e armazenagem conforme Incoterm. No recebimento, fotografe pallets, conte volumes e verifique danos antes de misturar o lote ao estoque.`),
    ptRich("oem","OEM, ODM e marca própria",`Logo, cor, marcação, etiqueta, manual e caixa podem ser avaliados conforme modelo e quantidade. O fluxo passa por briefing, arquivo vetorial, análise de aplicação, amostra, aprovação, produção, inspeção e embarque.`,`Mudança de geometria, material, molde, ferramenta ou mecanismo não é apenas personalização visual. Ela exige escopo de desenvolvimento, responsabilidade técnica, custo, prazo, propriedade dos arquivos e nova validação.`),
    ptRich("reposicao","Reposição e consistência de lote",`Para repetir ${name}, mantenha código, fotos aprovadas, ficha, medidas, arquivos de logo, padrão de cor, embalagem e relatório de inspeção. Um novo pedido não deve depender somente do nome do produto.`,`A fábrica compara a nova ordem com a referência anterior e registra mudanças antes da produção. Isso é especialmente importante quando o conjunto precisa manter aparência, encaixe ou organização ao lado de unidades já instaladas.`),
    ptChecklist("checklist","Checklist de compra",["Definir aplicação, usuários e canal","Informar quantidades por SKU","Confirmar faixa, unidade e composição","Solicitar desenho e itens incluídos","Verificar material, acabamento e interfaces","Aprovar logo, cor e embalagem","Definir medidas e função aceitáveis","Confirmar caixa, pallet e peso bruto","Informar destino e Incoterm","Planejar inspeção, recebimento e reposição"]),
    ptRich("cotacao","Como solicitar cotação",`Envie o link de ${name}, quantidades, aplicação, personalização, embalagem, destino e prazo objetivo. A equipe separará dados confirmados de pontos que ainda precisam de escolha antes de informar preço, MOQ, amostra e cronograma.`,`Uma proposta comparável mostra moeda, validade, Incoterm, escopo, itens opcionais, premissas e responsabilidades. Produto, arte, embalagem e QC devem usar versões compatíveis antes da autorização do lote.`)
  ];
  const faq=[{id:"faq-1",question:`Qual é o MOQ de ${name}?`,answer:"O MOQ depende do modelo, mix, cor, logo e embalagem. Envie quantidades por referência para separar condições padrão e personalizadas."},{id:"faq-2",question:`É possível solicitar amostra de ${name}?`,answer:"Sim, quando configuração e disponibilidade permitirem. Objetivo, custo, transporte, versão e correções da amostra precisam ficar registrados."},{id:"faq-3",question:"Como o produto é inspecionado?",answer:`O plano verifica identidade, medidas, peso ou faixa, função, superfície, marca e embalagem, com critérios ajustados ao risco de ${name}.`},{id:"faq-4",question:"Posso aplicar minha marca?",answer:"Logo, cor, etiqueta e caixa podem ser avaliados. Mudanças estruturais exigem revisão técnica e validação separada."},{id:"faq-5",question:"Quais dados são necessários para o frete?",answer:"Informe destino, quantidades, embalagem e Incoterm. A classificação e os requisitos locais devem ser confirmados pelo importador."}];
  return base("pt-BR",slug,path,`${name}: fabricante e fornecimento B2B | PowerBaseFit`,`${keyword} com materiais, especificações, fabricação, QC, embalagem de exportação, OEM, marca própria e cotação para compradores B2B.`,`${name} para academias, distribuidores e marca própria`,body,faq,{sku:entity.versions.en?.schemaData.sku??`PBF-${selection.slug.toUpperCase()}`,brand:"PowerBaseFit",manufacturer:"PowerBaseFit",material,category:root[2],specifications:[{name:"Produto",value:name},{name:"Faixa",value:range}],breadcrumbs:[{name:"Início",path:"/pt"},{name:"Produtos",path:"/pt/produtos"},{name:root[2],path:root[0]},{name,path}],extra:{primaryKeyword:keyword,searchIntent:"avaliação de fornecedor e cotação B2B"}},imageSet(source,name,"pt-BR",selection.family),[{targetContentId:root[1],label:`Ver ${root[2].toLowerCase()}`},{targetContentId:"factory",label:"Fabricação e controle de qualidade"},{targetContentId:"oem-private-label",label:"OEM e marca própria"},{targetContentId:"contact",label:"Solicitar cotação"}]);
}

function spanishVersion(entity: ContentEntity, selection: Selection, source: ProductSource): LocalizedContentVersion {
  const name=selection.es, slug=publicSlug("es",selection), root=roots.es[selection.family], path=`${root[0]}/${slug}`, range=localRange(source.range,"es"), material=localMaterial(source.type,"es"), focus=profileFocus(selection.family,"es");
  const keyword=selection.family==="accessories"?`${name.toLowerCase()} al por mayor`:`fabricante de ${name.toLowerCase()}`;
  const body=[
    esQuick("respuesta",`${name} es una opción para compradores profesionales que necesitan definir ${focus}. La oferta debe identificar referencia, rango ${range}, cantidad, aplicación, personalización, destino y criterios de aceptación; cualquier dato pendiente se valida contra el modelo seleccionado.`),
    esDefinition("definicion",name,`${name} pertenece a la familia comercial de ${root[2].toLowerCase()} y utiliza ${material}. El nombre no sustituye una especificación: dimensiones, peso, construcción, elementos incluidos, acabado y embalaje deben quedar vinculados al mismo código y a la muestra aprobada.`),
    esRich("posicionamiento","Valor comercial de esta referencia",`Para España y Latinoamérica, ${name} tiene valor cuando se relaciona con el canal, la intensidad y el espacio disponible. La decisión debe considerar volumen, plazo, mantenimiento previsto y coste total de propiedad.`,`El operador estudia uso y mantenimiento; el distribuidor añade rotación y reposición; el importador calcula bultos y coste puesto; una marca privada necesita coherencia de logo, color, archivos y lotes.`),
    esRich("aplicaciones","Aplicaciones y compradores",`El briefing indica si ${name} irá a un gimnasio comercial, estudio, hotel, comunidad, showroom, catálogo de distribución o proyecto de marca propia. Frecuencia, usuarios y almacenamiento cambian los riesgos y la inspección.`,`La palabra “profesional” no es una especificación. Describa tráfico, entorno, equipos relacionados, limpieza, mantenimiento y expectativa de reposición para recibir propuestas comparables.`),
    esRich("ventaja","Ventajas y límites de compra",`El valor principal de ${name} se encuentra en ${focus}. Solo es verificable cuando medidas, materiales, compatibilidad y condiciones de uso están documentados. Una fotografía parecida no demuestra construcción equivalente.`,`No se publican cargas, tolerancias, vida útil ni certificaciones sin respaldo del modelo. Los datos variables deben figurar en oferta, plano, manual, muestra o plan de control antes de producir.`),
    esTable("especificaciones","Especificaciones para solicitar oferta",["Campo","Base de la línea","Confirmación necesaria"],[["Producto",name,"Código y versión"],["Rango",range,"Opciones y unidades"],["Material",material,"Construcción y acabado"],["Aplicación","Compra profesional B2B","Entorno e intensidad"],["Dimensiones","Según modelo","Plano con unidades"],["OEM","Logo, color y caja bajo revisión","Método, MOQ y muestra"],["QC","Plan ligado a ficha aprobada","Método, tolerancia y muestreo"]],`Datos de compra de ${name}`),
    esRich("materiales","Materiales y construcción",`${material} describe la base comercial, pero todavía deben revisarse interfaces, espesores relevantes, acabado, componentes de contacto y piezas de desgaste. En ${name}, el análisis se centra en ${focus}.`,`La muestra lleva código, fecha y archivos. Un cambio de materia prima, molde, herraje, color o proveedor de componente se comunica antes del lote porque puede modificar ajuste, aspecto, manipulación o mantenimiento.`),
    esRich("dimensiones","Dimensiones, peso y compatibilidad",`El rango comunicado es ${range}. Confirme si cada cifra representa unidad, pareja, juego, carga seleccionable o capacidad. Toda medida necesita unidad y punto de referencia.`,`La compatibilidad se prueba con barra, rack, estación, accesorio, suelo o zona operativa previstos. No basta citar un estándar si diámetro, acoplamiento, recorrido o espacio seguro no aparecen en documentos.`),
    esRich("proceso","Proceso de fabricación",`El proceso de ${name} comienza con ficha y materiales aprobados, continúa con preparación, conformado o mecanizado, acabado, montaje cuando corresponda, identificación, inspección y embalaje. Cada etapa crítica debe producir una evidencia.`,`PowerBaseFit relaciona código, arte, muestra, orden, registro de QC y packing list. Esta trazabilidad ayuda a localizar variaciones y reduce el riesgo de fabricar algo diferente de la referencia cotizada.`),
    esRich("qc","Control de calidad",`El plan para ${name} cubre identidad, cantidad, medidas críticas, peso o rango, función, superficie, marcado y embalaje. El foco concreto es ${focus}.`,`Muestreo y límites se acuerdan antes de producir. Las fotos sin código, lote, escala y criterio no sustituyen mediciones. Según riesgo y valor, pueden combinarse control de proceso, inspección final y revisión independiente.`),
    esTable("comparacion","Cómo comparar proveedores",["Criterio","Respuesta débil","Evidencia útil"],[["Modelo","Como en la foto","Código, plano y lista de piezas"],["Material","Calidad premium",`Construcción en ${material} y referencia aprobada`],["Dimensiones","Tamaño estándar","Medidas, unidades y tolerancia"],["OEM","Logo disponible","Método, posición, arte, MOQ y muestra"],["Embalaje","Caja de exportación","Unidades, peso, medidas y palé"],["Plazo","Entrega rápida","Etapas, aprobaciones y fecha de disponibilidad"]]),
    esRich("embalaje","Embalaje, transporte y recepción",`El embalaje protege superficies e interfaces de ${name}, limita el movimiento y distribuye el peso. Confirme unidades por caja, pesos neto y bruto, medidas, etiqueta, palé y orden de apertura.`,`El importador calcula transporte, seguro, aduana, impuestos, gastos de destino, entrega interior, descarga y almacenaje según Incoterm. Al recibir, documente palés, cuente bultos y revise daños antes de mezclar el lote.`),
    esRich("oem","OEM, ODM y marca privada",`Logo, color, marcado, etiqueta, manual y caja pueden estudiarse según referencia y volumen. El proceso pasa por briefing, archivo vectorial, revisión, muestra, aprobación, serie, inspección y envío.`,`Cambiar geometría, material, molde, herramienta o mecanismo no es una personalización visual. Requiere alcance de desarrollo, responsabilidad, coste, calendario, propiedad de archivos y nueva validación.`),
    esRich("reposicion","Reposición y coherencia de lote",`Para repetir ${name}, conserve código, fotos aprobadas, ficha, medidas, logotipo, patrón de color, embalaje e informe. Un pedido nuevo no debe depender únicamente del nombre comercial.`,`La fábrica compara la nueva orden con la referencia anterior y registra cambios antes de producir, especialmente cuando el producto debe mantener aspecto, acoplamiento u organización junto a unidades instaladas.`),
    esChecklist("checklist","Checklist de compra",["Definir aplicación, usuarios y canal","Indicar cantidades por SKU","Confirmar rango, unidad y composición","Solicitar plano y contenido","Verificar material, acabado e interfaces","Aprobar logo, color y embalaje","Definir medidas y función aceptables","Confirmar caja, palé y peso bruto","Indicar destino e Incoterm","Planificar inspección, recepción y reposición"]),
    esRich("cotizacion","Cómo solicitar cotización",`Envíe el enlace de ${name}, cantidades, aplicación, personalización, embalaje, destino y fecha objetivo. El equipo separará datos confirmados y puntos abiertos antes de indicar precio, MOQ, muestra y calendario.`,`Una oferta comparable muestra moneda, validez, Incoterm, alcance, opcionales, supuestos y responsabilidades. Producto, arte, embalaje y QC deben compartir versiones compatibles antes de autorizar la serie.`)
  ];
  const faq=[{id:"faq-1",question:`¿Cuál es el MOQ de ${name}?`,answer:"Depende de referencia, mezcla, color, logo y embalaje. Envíe cantidades por SKU para separar condiciones estándar y personalizadas."},{id:"faq-2",question:`¿Se puede pedir una muestra de ${name}?`,answer:"Sí, cuando configuración y disponibilidad lo permitan. Objetivo, coste, transporte, versión y correcciones deben documentarse."},{id:"faq-3",question:"¿Cómo se inspecciona el producto?",answer:`El plan revisa identidad, dimensiones, peso o rango, función, superficie, marca y embalaje con criterios adaptados al riesgo de ${name}.`},{id:"faq-4",question:"¿Puedo aplicar mi propia marca?",answer:"Logo, color, etiqueta y caja pueden estudiarse. Los cambios estructurales requieren revisión técnica y validación separada."},{id:"faq-5",question:"¿Qué datos hacen falta para el transporte?",answer:"Indique destino, cantidades, embalaje e Incoterm. El importador confirma clasificación y requisitos locales."}];
  return base("es",slug,path,`${name}: fabricante y suministro B2B | PowerBaseFit`,`${keyword} con materiales, especificaciones, fabricación, QC, embalaje de exportación, OEM, marca privada y oferta para compradores profesionales.`,`${name} para gimnasios, distribuidores y marca privada`,body,faq,{sku:entity.versions.en?.schemaData.sku??`PBF-${selection.slug.toUpperCase()}`,brand:"PowerBaseFit",manufacturer:"PowerBaseFit",material,category:root[2],specifications:[{name:"Producto",value:name},{name:"Rango",value:range}],breadcrumbs:[{name:"Inicio",path:"/es"},{name:"Productos",path:"/es/productos"},{name:root[2],path:root[0]},{name,path}],extra:{primaryKeyword:keyword,searchIntent:"evaluación de proveedor y solicitud de oferta B2B"}},imageSet(source,name,"es",selection.family),[{targetContentId:root[1],label:`Ver ${root[2].toLowerCase()}`},{targetContentId:"factory",label:"Fabricación y control de calidad"},{targetContentId:"oem-private-label",label:"OEM y marca privada"},{targetContentId:"contact",label:"Solicitar cotización"}]);
}

function koreanVersion(entity: ContentEntity, selection: Selection, source: ProductSource): LocalizedContentVersion {
  const name=selection.ko, slug=selection.slug, root=roots.ko[selection.family], path=`${root[0]}/${slug}`, range=localRange(source.range,"ko"), material=localMaterial(source.type,"ko"), focus=profileFocus(selection.family,"ko"), keyword=`${name} 제조업체`;
  const body=[
    koAnswer("quick","빠른 답변",`${name}은 ${focus}을 구체적으로 비교해야 하는 B2B 제품입니다. 견적 요청에는 모델, ${range}, 수량, 사용 환경, 커스텀 범위, 도착지, 합격 기준을 포함해야 하며 확인되지 않은 수치나 성능은 해당 모델 검토 전 확정하지 않습니다.`),
    koDefinition("definition",name,`${name}은 ${root[2]} 제품군에 속하며 기본 재질·구성은 ${material}입니다. 제품명만으로는 구매 사양이 되지 않으므로 치수, 중량, 구조, 포함 부품, 마감, 포장 조건을 동일한 코드와 승인 샘플에 연결해야 합니다.`),
    koText("positioning","제품 포지셔닝과 구매 가치",`한국의 헬스장 운영자, 유통업체, 수입업체, 피트니스 브랜드가 ${name}을 검토할 때 핵심은 채널과 사용 강도, 설치 공간을 먼저 정하는 것입니다. 수량, 납기, 유지관리 계획 및 총소유비용도 함께 검토해야 합니다.`,`운영자는 사용성과 정비를, 유통업체는 회전율과 재주문을, 수입업체는 포장과 도착 원가를, 자체 브랜드는 로고·색상·파일 버전과 로트 일관성을 함께 확인합니다.`),
    koText("application","적용 환경과 대상 구매자",`${name}이 상업용 헬스장, PT 스튜디오, 호텔, 아파트 커뮤니티, 쇼룸, 유통 재고, 자체 브랜드 프로젝트 중 어디에 사용되는지 설명해야 합니다. 사용 빈도와 사용자 구성, 보관 방식은 검사 항목과 위험을 바꿉니다.`,`‘프로용’이라는 표현은 사양이 아닙니다. 예상 이용 인원, 설치 환경, 연결 장비, 청소와 유지보수, 재주문 계획을 제공해야 서로 다른 공급업체의 제안을 같은 기준으로 비교할 수 있습니다.`),
    koText("value","제품 장점과 확인해야 할 한계",`${name}의 구매 가치는 ${focus}에서 나옵니다. 이 가치는 치수, 재질, 호환성, 사용 조건이 문서로 확인될 때만 유효하며 비슷한 사진만으로 동일한 구조나 성능을 판단할 수 없습니다.`,`모델별로 달라지는 하중, 허용오차, 수명, 인증 정보는 임의로 공개하지 않습니다. 필요한 수치는 견적서, 도면, 매뉴얼, 샘플 또는 QC 계획에서 확인한 뒤 생산 기준에 반영합니다.`),
    koTable("specifications","견적 요청용 사양표",["항목","현재 기준","주문 전 확인"],[["제품",name,"코드와 버전"],["구성 범위",range,"옵션과 단위"],["재질",material,"구조와 마감"],["용도","B2B 상업용 구매","환경과 사용 강도"],["치수","모델별 확인","단위가 포함된 도면"],["OEM","로고·색상·포장 검토 가능","방식·MOQ·샘플"],["QC","승인 사양 기준","측정법·허용오차·샘플링"]],`${name} 구매 사양`),
    koText("material","재질과 구조",`${material}은 기본 분류이며 실제 구매에서는 접촉 부위, 주요 두께, 표면 마감, 연결 구조, 마모 부품을 추가로 확인해야 합니다. ${name}의 기술 검토는 ${focus}에 집중합니다.`,`샘플에는 코드와 승인일, 관련 파일을 부여합니다. 원재료, 금형, 하드웨어, 색상 또는 부품 공급처가 바뀌면 결합, 외관, 취급성, 정비에 영향을 줄 수 있으므로 양산 전에 알리고 다시 확인해야 합니다.`),
    koText("dimensions","치수·중량·호환성",`표시된 구성 범위는 ${range}입니다. 각 값이 단품, 한 쌍, 세트, 선택 중량 또는 시스템 용량 중 무엇을 의미하는지 구분하고 모든 치수에 단위와 기준점을 표시해야 합니다.`,`바, 랙, 머신, 액세서리, 바닥 또는 실제 운영 공간과의 호환성을 확인합니다. 직경, 결합부, 작동 범위, 안전 공간이 문서화되지 않았다면 ‘표준 규격’이라는 말만으로 승인하지 않습니다.`),
    koText("process","제조 공정",`${name}의 공정은 승인 사양과 자재 확인, 성형·가공, 표면 처리, 필요한 조립, 식별 표시, 검사, 포장 순서로 진행됩니다. 중요 단계마다 확인 가능한 결과와 기록이 있어야 합니다.`,`PowerBaseFit은 제품 코드, 아트워크, 샘플, 생산 지시, QC 기록, 포장 명세를 같은 참조번호로 연결합니다. 이 방식은 견적 및 승인 모델과 다른 구성이 생산되는 위험을 줄이고 변동 원인을 추적하는 데 도움이 됩니다.`),
    koText("qc","품질 관리",`${name}의 검사 계획은 제품 식별, 수량, 주요 치수, 중량 또는 구성 범위, 기능, 표면, 표시, 포장을 포함합니다. 핵심 검사항목은 ${focus}입니다.`,`샘플링과 합격 기준은 생산 전에 정합니다. 코드, 로트, 크기 기준, 판정 조건이 없는 사진은 측정을 대신할 수 없습니다. 주문 위험과 금액에 따라 공정 검사, 최종 검사, 선적 전 제3자 검사를 조합할 수 있습니다.`),
    koTable("comparison","공급업체 비교표",["비교 항목","불충분한 답변","확인 가능한 자료"],[["모델","사진과 동일","코드·도면·구성품 목록"],["재질","프리미엄 품질",`${material} 구조와 승인 기준`],["치수","표준 크기","단위·허용오차가 있는 측정값"],["OEM","로고 가능","방식·위치·아트워크·MOQ·샘플"],["포장","수출용 박스","입수·중량·치수·팔레트"],["납기","빠른 출고","승인 단계와 생산 완료 예정일"]]),
    koText("packing","포장·운송·입고 검사",`포장은 ${name}의 표면과 결합부를 보호하고 내부 움직임을 제한하며 중량을 안전하게 분산해야 합니다. 박스당 수량, 순중량·총중량, 외형 치수, 라벨, 팔레트, 개봉 순서를 확인합니다.`,`수입업체는 Incoterm에 따라 운임, 보험, 통관, 세금, 목적지 비용, 내륙 운송, 하역, 보관을 계산합니다. 입고 시 팔레트와 박스를 촬영하고 수량과 손상을 확인한 뒤 기존 재고와 혼합합니다.`),
    koText("oem","OEM·ODM·자체 브랜드",`로고, 색상, 중량 표기, 라벨, 매뉴얼, 박스는 모델과 수량에 따라 검토할 수 있습니다. 브리프, 벡터 파일, 적용 검토, 샘플, 승인, 양산, 검사, 선적 순으로 관리합니다.`,`형상, 재질, 금형, 공구, 메커니즘 변경은 단순 로고 작업이 아닙니다. 개발 범위, 기술 책임, 비용, 일정, 파일 소유권, 재검증 조건을 별도로 합의해야 합니다.`),
    koText("reorder","재주문과 로트 일관성",`${name}을 재주문할 때 제품 코드, 승인 사진, 사양서, 치수, 로고 파일, 색상 기준, 포장, 검사 보고서를 보관해야 합니다. 새 주문을 제품명 하나로만 요청하면 이전 구성과 비교하기 어렵습니다.`,`공장은 새 발주서를 이전 기준과 대조하고 변경사항을 생산 전에 기록합니다. 이미 설치되거나 판매된 제품 옆에서 외관, 결합, 진열 방식이 유지되어야 하는 경우 특히 중요합니다.`),
    koChecklist("checklist","B2B 구매 체크리스트",["사용 환경·사용자·판매 채널 정의","SKU별 수량 제공","구성 범위와 단위 확인","도면과 포함 부품 요청","재질·마감·결합부 검토","로고·색상·포장 승인","치수와 기능 합격 기준 설정","박스·팔레트·총중량 확인","도착지와 Incoterm 제공","검사·입고·재주문 계획 수립"]),
    koText("quote","견적 요청 방법",`${name} 링크, SKU별 수량, 적용 환경, 커스텀 범위, 포장, 도착지, 목표 일정을 보내 주십시오. PowerBaseFit은 확인된 정보와 선택이 필요한 항목을 구분한 뒤 가격, MOQ, 샘플, 생산 일정을 제안합니다.`,`비교 가능한 견적에는 통화, 유효기간, Incoterm, 포함 범위, 옵션, 전제조건, 책임 구분이 있어야 합니다. 양산 승인 전 제품, 아트워크, 포장, QC 문서의 버전이 서로 일치하는지 확인합니다.`)
  ];
  const faq=[{id:"faq-1",question:`${name}의 MOQ는 얼마입니까?`,answer:"모델, SKU 구성, 색상, 로고, 포장에 따라 달라집니다. 품목별 수량을 보내면 표준 조건과 커스텀 조건을 나누어 안내합니다."},{id:"faq-2",question:`${name} 샘플을 먼저 받을 수 있습니까?`,answer:"구성과 재고 조건이 허용되면 가능합니다. 샘플 목적, 비용, 운송, 버전, 수정사항을 문서로 관리해야 합니다."},{id:"faq-3",question:"품질 검사는 어떻게 진행합니까?",answer:`제품 식별, 치수, 중량 또는 범위, 기능, 표면, 로고, 포장을 ${name}의 위험과 승인 기준에 맞춰 검사합니다.`},{id:"faq-4",question:"자체 브랜드 로고를 적용할 수 있습니까?",answer:"로고, 색상, 라벨, 박스를 검토할 수 있습니다. 구조 변경은 별도 기술 검토와 검증이 필요합니다."},{id:"faq-5",question:"운임 견적에 필요한 정보는 무엇입니까?",answer:"도착지, 수량, 포장, Incoterm을 알려 주십시오. 품목 분류와 현지 수입 요건은 수입자가 확인해야 합니다."}];
  return base("ko",slug,path,`${name} 제조업체·OEM 공급 | PowerBaseFit`,`${keyword}. 재질, 사양, 제조 공정, QC, 수출 포장, OEM, 자체 브랜드와 B2B 견적 정보를 확인하십시오.`,`${name} 상업용 공급 및 자체 브랜드 제작`,body,faq,{sku:entity.versions.en?.schemaData.sku??`PBF-${selection.slug.toUpperCase()}`,brand:"PowerBaseFit",manufacturer:"PowerBaseFit",material,category:root[2],specifications:[{name:"제품",value:name},{name:"구성 범위",value:range}],breadcrumbs:[{name:"홈",path:"/ko"},{name:"제품",path:"/ko/products"},{name:root[2],path:root[0]},{name,path}],extra:{primaryKeyword:keyword,searchIntent:"공급업체 비교 및 B2B 견적 요청"}},imageSet(source,name,"ko",selection.family),[{targetContentId:root[1],label:`${root[2]} 전체 보기`},{targetContentId:"factory",label:"제조 공정과 품질 관리"},{targetContentId:"oem-private-label",label:"OEM 및 자체 브랜드"},{targetContentId:"contact",label:"B2B 견적 요청"}]);
}

export function withCommercialCompletionBC(manifest: ContentManifest): ContentManifest {
  const byId = new Map(selections.map((selection)=>[`product:${selection.family}:${selection.slug}`,selection]));
  const found = new Set<string>();
  const entities = manifest.entities.map((entity)=>{
    const selection=byId.get(entity.id); if(!selection) return entity;
    found.add(entity.id);
    const record=sourceCatalog.get(selection.slug);
    if(!record||record.family!==selection.family) throw new Error(`Batch 2 source mismatch: ${entity.id}`);
    if(entity.versions["pt-BR"]||entity.versions.es||entity.versions.ko) throw new Error(`Batch 2 duplicates localized page: ${entity.id}`);
    return {...entity,versions:{...entity.versions,"pt-BR":portugueseVersion(entity,selection,record.source),es:spanishVersion(entity,selection,record.source),ko:koreanVersion(entity,selection,record.source)}};
  });
  const missing=selections.filter((selection)=>!found.has(`product:${selection.family}:${selection.slug}`));
  if(missing.length) throw new Error(`Batch 2 references unknown entities: ${missing.map((item)=>item.slug).join(", ")}`);
  return {...manifest,entities};
}

export const commercialCompletionBCSelections = selections;
