import type { ContentEntity, ContentManifest, LocalizedContentVersion, LocalizedImage } from "../../lib/content/types";
import { racksBenchesProducts } from "../../app/products/racks-benches/productData";
import { ptBrEditorialAuthor, ptBrTechnicalReviewer } from "./pt-br-existing-growth";
import { checklist as ptChecklist, definition as ptDefinition, quick as ptQuick, rich as ptRich, table as ptTable } from "./pt-br-content-helpers";
import { spanishEditorialAuthor, spanishTechnicalReviewer, checklist as esChecklist, definition as esDefinition, quick as esQuick, rich as esRich, table as esTable } from "./es-content-helpers";
import { koAnswer, koChecklist, koDefinition, koreanEditorialAuthor, koreanTechnicalReviewer, koTable, koText } from "./ko-content-helpers";

const releaseDate = "2026-07-22T09:30:00.000Z";
type TargetLocale = "pt-BR" | "es" | "ko";
type ProductSource = (typeof racksBenchesProducts)[number];
type LocalProfile = {
  name: string;
  slug: string;
  keyword: string;
  intent: string;
  definition: string;
  applications: string;
  buyers: string;
  decision: string;
  distinction: string;
  risk: string;
  configuration: string;
  comparison: string;
};
type Selection = {
  slug: string;
  score: number;
  tier: "A" | "B";
  kind: "wall" | "bench" | "storage-bench" | "single" | "multi";
  locales: Record<TargetLocale, LocalProfile>;
};

const selections: Selection[] = [
  {
    slug: "wall-folding-functional-trainer", score: 69, tier: "B", kind: "wall",
    locales: {
      "pt-BR": { name:"Treinador funcional dobrável de parede",slug:"treinador-funcional-dobravel-de-parede",keyword:"estação funcional dobrável de parede",intent:"avaliar uma solução compacta de cabos para studios, condomínios e salas com uso compartilhado",definition:"Equipamento de cabos instalado junto à parede, com estrutura recolhível para liberar parte da área quando não está em uso. A proposta precisa tratar fixação, zona de abertura, percurso dos cabos e condição da parede como partes do produto.",applications:"É indicado para studios de personal, academias de condomínio, hotéis e salas corporativas onde cada metro quadrado precisa cumprir mais de uma função. O fechamento não elimina a necessidade de área segura durante o exercício.",buyers:"Compradores de projetos compactos, distribuidores de equipamentos profissionais e marcas de home gym premium procuram uma solução que combine uso guiado, armazenamento lateral e apresentação organizada.",decision:"Antes de cotar, levante material da parede, pontos estruturais, rodapé, tomadas, pé-direito, circulação e exercícios previstos. A compatibilidade do local vale mais do que escolher apenas pela profundidade fechada.",distinction:"Diferente de uma torre independente, este modelo transfere parte das exigências de estabilidade para a instalação. Também não deve ser comparado a um elástico ou polia leve de porta: estrutura, cabos, ferragens e inspeção pertencem a outra categoria de compra.",risk:"Os maiores riscos são especificar fixadores sem conhecer o substrato, medir somente o equipamento fechado e ignorar o envelope de movimento. Manual, desenho e responsabilidade de instalação precisam acompanhar a proposta.",configuration:"estrutura dobrável, pontos de fixação, conjunto de cabos, polias e acessórios conforme referência aprovada",comparison:"Compare profundidade aberta e fechada, largura útil, envelope de cabos, acesso à manutenção e requisitos de ancoragem." },
      es: { name:"Entrenador funcional plegable de pared",slug:"entrenador-funcional-plegable-de-pared",keyword:"estación funcional plegable de pared",intent:"evaluar una solución compacta de poleas para estudios, comunidades y salas de uso compartido",definition:"Equipo de poleas instalado junto a una pared con estructura abatible para recuperar parte del espacio cuando no se utiliza. La fijación, la zona de apertura, el recorrido del cable y el soporte mural forman parte de la especificación.",applications:"Encaja en estudios de entrenamiento personal, gimnasios de comunidades, hoteles y salas corporativas donde la superficie tiene varios usos. Plegarlo no reduce el espacio de seguridad necesario durante el ejercicio.",buyers:"Lo valoran responsables de proyectos compactos, distribuidores profesionales y marcas de gimnasio doméstico premium que necesitan entrenamiento guiado, almacenamiento lateral y una instalación ordenada.",decision:"Antes de pedir precio, documente material de pared, puntos resistentes, zócalo, enchufes, altura libre, circulación y ejercicios previstos. La compatibilidad del emplazamiento pesa más que la profundidad del equipo cerrado.",distinction:"A diferencia de una torre autoportante, parte de la estabilidad depende de la instalación. Tampoco equivale a una polea ligera de puerta: bastidor, cables, herrajes y control pertenecen a una compra profesional distinta.",risk:"Los fallos más probables son elegir anclajes sin conocer el soporte, medir solo el equipo plegado y olvidar la envolvente de movimiento. La oferta debe incluir plano, instrucciones y responsabilidad de montaje.",configuration:"bastidor abatible, puntos de anclaje, cables, poleas y accesorios según la referencia aprobada",comparison:"Compare fondo abierto y cerrado, anchura útil, recorrido de cables, acceso de mantenimiento y requisitos de anclaje." },
      ko: { name:"벽면 접이식 펑셔널 트레이너",slug:"wall-folding-functional-trainer",keyword:"벽면 접이식 케이블 머신",intent:"PT 스튜디오와 공용 운동실을 위한 공간 절약형 케이블 장비 검토",definition:"벽 가까이에 설치하고 사용하지 않을 때 프레임을 접어 일부 공간을 확보하는 케이블 운동 장비입니다. 벽체 고정, 개폐 영역, 케이블 이동 범위와 벽 구조가 모두 구매 사양에 포함됩니다.",applications:"PT 스튜디오, 아파트 커뮤니티, 호텔, 기업 운동실처럼 한 공간을 여러 용도로 쓰는 장소에 적합합니다. 접을 수 있어도 운동 중 안전 영역과 사용자 동선은 별도로 확보해야 합니다.",buyers:"공간이 제한된 프로젝트 담당자, 전문 장비 유통사, 프리미엄 홈짐 브랜드가 케이블 운동과 정돈된 보관을 함께 제공할 때 검토합니다.",decision:"견적 전에 벽체 재질, 구조 지점, 걸레받이, 콘센트, 천장 높이, 통로와 예정 운동을 기록해야 합니다. 접었을 때 깊이보다 설치 장소와의 호환성이 먼저입니다.",distinction:"독립형 타워와 달리 안정성의 일부가 설치 품질에 좌우됩니다. 문에 거는 가벼운 풀리 제품과도 다르므로 프레임, 케이블, 하드웨어와 검사 기준을 전문 장비 수준으로 비교해야 합니다.",risk:"벽체를 확인하지 않고 앵커를 정하거나 접힌 크기만 측정하는 것이 주요 위험입니다. 동작 범위, 도면, 설치 지침과 책임 범위를 발주 전에 확정해야 합니다.",configuration:"접이식 프레임, 벽체 고정부, 케이블, 풀리 및 승인된 구성의 액세서리",comparison:"펼친 크기와 접힌 크기, 유효 폭, 케이블 동작 영역, 정비 접근성과 앵커 조건을 비교합니다." }
    }
  },
  {
    slug: "incline-flat-decline-bench", score: 73, tier: "A", kind: "bench",
    locales: {
      "pt-BR": { name:"Banco inclinável, plano e declinável",slug:"banco-inclinavel-plano-declinavel",keyword:"banco regulável inclinado plano declinado",intent:"comprar um banco versátil para área de halteres e treino em rack",definition:"Banco regulável que trabalha em posições inclinada, plana e declinada. A categoria é definida pelo conjunto de ângulos utilizáveis, estabilidade em cada posição e relação entre assento, encosto e apoio do usuário.",applications:"Atende áreas de halteres, exercícios dentro ou diante de racks e programas que alternam supino, remadas apoiadas e movimentos sentados. A posição declinada exige atenção especial ao apoio e à entrada do usuário.",buyers:"Academias comerciais, studios de força, hotéis e distribuidores buscam um único banco para ampliar exercícios sem multiplicar modelos no salão ou no estoque.",decision:"Compare posições realmente traváveis, altura na configuração plana, distância entre almofadas, largura da base e facilidade de movimentação. A quantidade de ângulos sozinha não determina uma boa compra.",distinction:"Um banco IFD oferece declínio, enquanto muitos bancos ajustáveis param na posição plana. Ele também difere de um banco olímpico fixo, pois precisa circular entre halteres e racks sem perder estabilidade.",risk:"Folga no mecanismo, apoio irregular no piso e conflito entre base e rack prejudicam o uso. O comprador deve validar cada posição, pontos de pega, rodas, estofamento e instruções de ajuste.",configuration:"encosto e assento reguláveis para posições inclinada, plana e declinada, conforme desenho aprovado",comparison:"Compare amplitude de ajuste, estabilidade no declínio, altura plana, mobilidade, pegada de transporte e compatibilidade com racks." },
      es: { name:"Banco inclinado, plano y declinado",slug:"banco-inclinado-plano-declinado",keyword:"banco regulable inclinado plano declinado",intent:"comprar un banco versátil para zona de mancuernas y trabajo con rack",definition:"Banco regulable capaz de trabajar en posiciones inclinada, plana y declinada. La categoría depende de los ángulos utilizables, la estabilidad en cada posición y la relación entre asiento, respaldo y apoyo del usuario.",applications:"Sirve para zonas de mancuernas, ejercicios dentro o delante de racks y programas que alternan press, remos apoyados y movimientos sentados. El declive requiere especial atención al apoyo y al acceso del usuario.",buyers:"Gimnasios comerciales, estudios de fuerza, hoteles y distribuidores buscan un solo banco que amplíe ejercicios sin multiplicar referencias en sala o almacén.",decision:"Compare posiciones bloqueables, altura en plano, separación entre almohadillas, anchura de base y facilidad de traslado. El número de ángulos por sí solo no demuestra una compra adecuada.",distinction:"Un banco IFD incorpora declive, mientras muchos bancos ajustables terminan en plano. También se diferencia de un banco olímpico fijo porque debe moverse entre mancuernas y racks conservando estabilidad.",risk:"Holgura en el mecanismo, apoyo irregular y choque entre base y rack reducen la utilidad. Valide cada posición, puntos de agarre, ruedas, tapizado e instrucciones de ajuste.",configuration:"respaldo y asiento regulables para posiciones inclinada, plana y declinada según plano aprobado",comparison:"Compare amplitud de ajuste, estabilidad en declive, altura plana, movilidad, asa de transporte y compatibilidad con racks." },
      ko: { name:"인클라인 플랫 디클라인 벤치",slug:"incline-flat-decline-bench",keyword:"인클라인 플랫 디클라인 조절 벤치",intent:"덤벨 존과 랙 운동에 사용할 다각도 상업용 벤치 구매",definition:"인클라인, 플랫, 디클라인 위치를 지원하는 조절식 벤치입니다. 실제 사용 가능한 각도, 각 위치의 안정성, 좌판과 등받이 및 사용자 지지 관계가 제품 범위를 결정합니다.",applications:"덤벨 구역, 파워랙 안팎의 운동, 프레스와 지지형 로우 및 앉은 동작을 번갈아 수행하는 프로그램에 사용합니다. 디클라인 위치에서는 사용자 진입과 하체 지지 구조를 별도로 확인해야 합니다.",buyers:"상업용 헬스장, 근력 전문 스튜디오, 호텔과 유통사가 여러 벤치 모델을 늘리지 않고 운동 범위를 넓히려 할 때 선택합니다.",decision:"실제로 잠기는 각도, 플랫 높이, 패드 사이 간격, 베이스 폭과 이동 방식을 비교하십시오. 조절 단계의 숫자만으로 구매 품질을 판단할 수 없습니다.",distinction:"IFD 벤치는 플랫까지만 지원하는 일반 조절 벤치와 달리 디클라인을 포함합니다. 고정형 올림픽 벤치와도 달리 덤벨 존과 랙 사이를 이동할 수 있어야 합니다.",risk:"조절부 유격, 고르지 않은 바닥 접촉, 랙과 베이스 간섭은 사용성을 낮춥니다. 각 위치, 이동 손잡이, 바퀴, 패드와 조절 안내를 샘플에서 확인해야 합니다.",configuration:"승인 도면에 따른 인클라인·플랫·디클라인 등받이와 좌판 조절 구조",comparison:"조절 범위, 디클라인 안정성, 플랫 높이, 이동성, 운반 손잡이와 랙 호환성을 비교합니다." }
    }
  },
  {
    slug: "heavy-duty-adjustable-bench", score: 74, tier: "A", kind: "bench",
    locales: {
      "pt-BR": { name:"Banco ajustável reforçado",slug:"banco-ajustavel-reforcado",keyword:"banco ajustável profissional reforçado",intent:"selecionar um banco de uso intenso para racks e área de pesos livres",definition:"Banco regulável priorizado para ambientes de maior frequência, com estrutura de aço, mecanismo de ajuste e estofamento avaliados como um sistema. “Reforçado” precisa ser demonstrado por construção e documentação, não apenas pelo nome.",applications:"É usado em academias comerciais, centros de treinamento e estações de power rack onde diferentes alunos mudam a posição várias vezes ao dia. Mobilidade e manutenção importam tanto quanto sensação de solidez.",buyers:"Operadores de academias, distribuidores e compradores de redes valorizam estabilidade repetível, reposição de peças de desgaste e padrão visual compatível com uma linha profissional.",decision:"Solicite desenho do chassi, posições, pontos de solda relevantes, material das almofadas, método de trava e dados do modelo cotado. Capacidade declarada só deve ser comparada quando o método e a configuração forem equivalentes.",distinction:"Comparado a um banco compacto, este produto privilegia uso intenso e presença estável; pode ocupar mais área e exigir logística diferente. Comparado ao IFD, a prioridade pode ser robustez, não necessariamente oferecer declínio.",risk:"Peso comercial sem método de ensaio, solda encoberta, rodas pequenas e peças de ajuste sem reposição são sinais de risco. A aprovação deve incluir movimento repetido e inspeção após montagem.",configuration:"chassi reforçado, encosto regulável, ferragens comerciais, rodas e pegador conforme a referência",comparison:"Compare construção do chassi, mecanismo de trava, estabilidade lateral, acesso para manutenção, peças de desgaste e embalagem." },
      es: { name:"Banco ajustable reforzado",slug:"banco-ajustable-reforzado",keyword:"banco ajustable profesional reforzado",intent:"seleccionar un banco de uso intensivo para racks y zona de peso libre",definition:"Banco regulable orientado a entornos de alta frecuencia, donde bastidor de acero, mecanismo y tapizado se evalúan como un conjunto. “Reforzado” debe demostrarse mediante construcción y documentación, no por el nombre comercial.",applications:"Se utiliza en gimnasios comerciales, centros de entrenamiento y puestos de jaula donde distintos usuarios cambian la posición muchas veces al día. Movilidad y mantenimiento pesan tanto como la sensación de solidez.",buyers:"Operadores, distribuidores y cadenas valoran estabilidad repetible, repuestos para piezas de desgaste y una imagen coherente con su línea profesional.",decision:"Solicite plano del bastidor, posiciones, soldaduras relevantes, material de almohadillas, sistema de bloqueo y datos de la referencia. Compare capacidades solo cuando método y configuración sean equivalentes.",distinction:"Frente a un banco compacto, prioriza uso intensivo y apoyo estable, aunque pueda ocupar más y cambiar la logística. Frente a un IFD, la prioridad puede ser robustez y no necesariamente el declive.",risk:"Una carga comercial sin método, soldaduras ocultas, ruedas insuficientes y ajustes sin repuesto elevan el riesgo. La aprobación debe incluir maniobras repetidas e inspección tras montaje.",configuration:"bastidor reforzado, respaldo regulable, herrajes comerciales, ruedas y asa según referencia",comparison:"Compare bastidor, bloqueo, estabilidad lateral, mantenimiento, piezas de desgaste y protección del embalaje." },
      ko: { name:"헤비듀티 조절식 벤치",slug:"heavy-duty-adjustable-bench",keyword:"상업용 헤비듀티 조절 벤치",intent:"랙과 프리웨이트 존의 고빈도 사용 벤치 선정",definition:"사용 빈도가 높은 환경을 위해 강철 프레임, 조절 장치와 패드를 하나의 시스템으로 평가하는 벤치입니다. 헤비듀티라는 명칭은 구조와 검증 자료로 확인해야 하며 이름만으로 하중 성능을 뜻하지 않습니다.",applications:"상업용 헬스장, 트레이닝 센터, 파워랙 구역에서 여러 사용자가 하루에도 반복해서 각도를 바꾸는 상황에 적합합니다. 견고함뿐 아니라 이동과 유지관리도 중요합니다.",buyers:"헬스장 운영사, 유통사와 체인 구매자는 반복되는 안정성, 마모 부품의 재공급과 전문 라인의 외관 일관성을 검토합니다.",decision:"프레임 도면, 조절 위치, 주요 용접부, 패드 재질, 잠금 방식과 견적 모델 자료를 요청하십시오. 하중 표시는 동일한 시험법과 구성일 때만 비교해야 합니다.",distinction:"컴팩트 벤치보다 고빈도 사용과 안정된 지지를 우선해 더 많은 공간과 물류비가 들 수 있습니다. IFD 벤치와 비교할 때는 디클라인보다 내구 구조가 핵심일 수 있습니다.",risk:"시험법 없는 하중 수치, 확인하기 어려운 용접부, 작은 이동 바퀴, 교체할 수 없는 조절 부품은 위험 요소입니다. 반복 조절과 조립 후 검사를 승인 절차에 포함해야 합니다.",configuration:"강화 프레임, 조절 등받이, 상업용 하드웨어, 바퀴와 손잡이의 승인 구성",comparison:"프레임 구조, 잠금 장치, 좌우 안정성, 정비 접근, 마모 부품과 포장 보호를 비교합니다." }
    }
  },
  {
    slug: "compact-adjustable-bench", score: 64, tier: "B", kind: "bench",
    locales: {
      "pt-BR": { name:"Banco ajustável compacto",slug:"banco-ajustavel-compacto",keyword:"banco ajustável compacto para academia",intent:"equipar studios, hotéis e salas menores com um banco regulável de baixa ocupação",definition:"Banco de ângulo regulável cuja proposta principal é reduzir a área de estacionamento e facilitar o reposicionamento. Compacto descreve a relação entre uso e espaço; não autoriza reduzir estabilidade ou apoio do usuário.",applications:"Funciona em studios, hotéis, condomínios e salas de treinamento com poucos equipamentos, especialmente quando precisa ser guardado após a sessão ou dividido entre rack e halteres.",buyers:"Projetistas de áreas pequenas, distribuidores e marcas de equipamentos residenciais profissionais procuram dimensões controladas, manobra simples e embalagem eficiente.",decision:"Meça o local de uso e o local de guarda, além do corredor de movimentação. Confirme altura plana, comprimento de apoio, largura da base, rodas e se os pés entram sob o rack previsto.",distinction:"Não é apenas uma versão menor do banco reforçado. O projeto precisa equilibrar menor pegada, ergonomia, estabilidade e facilidade de transporte, com limites de aplicação claramente documentados.",risk:"Encurtar apoio, aproximar articulações ou estreitar excessivamente a base pode afetar experiência e estabilidade. Não aceite dimensões genéricas: valide o desenho e o produto montado.",configuration:"estrutura compacta, ângulos reguláveis, rodas ou pegador e estofamento conforme modelo aprovado",comparison:"Compare área guardada, área em uso, altura plana, comprimento útil, raio de giro e encaixe sob o rack." },
      es: { name:"Banco ajustable compacto",slug:"banco-ajustable-compacto",keyword:"banco ajustable compacto para gimnasio",intent:"equipar estudios, hoteles y salas pequeñas con un banco regulable de poca ocupación",definition:"Banco regulable cuya propuesta principal es reducir el espacio de estacionamiento y facilitar el cambio de posición. Compacto describe la relación entre uso y superficie; no permite reducir estabilidad ni apoyo del usuario.",applications:"Funciona en estudios, hoteles, comunidades y salas con pocos equipos, especialmente cuando se guarda después de la sesión o se comparte entre jaula y zona de mancuernas.",buyers:"Diseñadores de espacios pequeños, distribuidores y marcas de equipamiento doméstico profesional buscan dimensiones controladas, maniobra sencilla y embalaje eficiente.",decision:"Mida la zona de uso, el lugar de almacenamiento y el pasillo de traslado. Confirme altura plana, longitud de apoyo, anchura de base, ruedas y entrada de las patas bajo la jaula prevista.",distinction:"No es simplemente una versión reducida del banco reforzado. Debe equilibrar menor huella, ergonomía, estabilidad y transporte con límites de aplicación documentados.",risk:"Acortar apoyos, acercar articulaciones o estrechar demasiado la base puede afectar experiencia y estabilidad. No acepte medidas genéricas: valide plano y unidad montada.",configuration:"estructura compacta, ángulos regulables, ruedas o asa y tapizado según modelo aprobado",comparison:"Compare espacio guardado y operativo, altura plana, longitud útil, radio de giro y entrada bajo el rack." },
      ko: { name:"컴팩트 조절식 벤치",slug:"compact-adjustable-bench",keyword:"소형 공간용 조절식 벤치",intent:"PT 스튜디오·호텔·소형 운동실에 배치할 공간 효율형 벤치 구매",definition:"보관 면적을 줄이고 위치 이동을 쉽게 하는 데 초점을 둔 각도 조절 벤치입니다. 컴팩트는 사용성과 공간의 관계를 설명하며 안정성이나 사용자 지지 면적을 임의로 줄인다는 뜻이 아닙니다.",applications:"장비 수가 제한된 PT 스튜디오, 호텔, 커뮤니티 운동실에서 사용하고 세션 후 보관하거나 랙과 덤벨 구역 사이에서 공유할 때 적합합니다.",buyers:"소형 시설 설계자, 유통사와 전문 홈짐 브랜드는 통제된 크기, 쉬운 이동과 효율적인 포장을 중요하게 봅니다.",decision:"운동 위치와 보관 위치, 이동 통로를 모두 측정하십시오. 플랫 높이, 유효 패드 길이, 베이스 폭, 바퀴와 예정 랙 아래로 프레임이 들어가는지 확인해야 합니다.",distinction:"헤비듀티 벤치를 단순 축소한 제품이 아닙니다. 작은 설치 면적과 인체 지지, 안정성, 운반 편의 사이의 균형 및 사용 한계를 문서로 확인해야 합니다.",risk:"지지 길이를 줄이거나 힌지를 가깝게 두고 베이스를 지나치게 좁히면 경험과 안정성이 달라집니다. 일반 치수 대신 도면과 조립 샘플을 검증해야 합니다.",configuration:"컴팩트 프레임, 각도 조절부, 바퀴 또는 손잡이와 승인된 패드 구성",comparison:"보관 면적, 사용 면적, 플랫 높이, 유효 길이, 회전 반경과 랙 하부 진입을 비교합니다." }
    }
  },
  {
    slug: "olympic-bench-plate-storage", score: 62, tier: "B", kind: "storage-bench",
    locales: {
      "pt-BR": { name:"Banco olímpico com suporte para anilhas",slug:"banco-olimpico-com-suporte-para-anilhas",keyword:"banco olímpico com suporte para anilhas",intent:"planejar uma estação de supino com armazenamento integrado para área de pesos livres",definition:"Estação de supino que combina banco, suporte da barra e pinos para guardar anilhas. A compra deve ser tratada como posto fixo de treinamento, considerando acesso do usuário, carga e descarga das anilhas e circulação ao redor.",applications:"É direcionado a academias comerciais, escolas, clubes e áreas de força que querem concentrar supino e estoque de anilhas no mesmo módulo. O layout precisa evitar conflito entre quem treina e quem retira peso.",buyers:"Projetistas, operadores e distribuidores avaliam organização do salão, capacidade de reposição, combinação com barras e anilhas e custo logístico de uma estrutura integrada.",decision:"Peça distâncias entre apoios, posições da barra, altura do banco, localização e diâmetro dos pinos, área operacional e desenho de montagem. Confirme compatibilidade com o conjunto de barras e anilhas do projeto.",distinction:"Diferente de um banco móvel, permanece dedicado ao supino. Em relação a banco e árvore de anilhas separados, economiza deslocamento, mas concentra usuários e exige analisar a retirada segura dos discos.",risk:"Pinos mal posicionados podem interferir na pegada, no spotter ou no corredor. Misturar desenho de banco com anilhas de centro incompatível também cria retrabalho e deve ser evitado na ficha do projeto.",configuration:"banco de supino, suportes de barra e pinos integrados para anilhas conforme desenho aprovado",comparison:"Compare ergonomia do supino, posições da barra, acesso do spotter, capacidade física dos pinos e circulação de usuários." },
      es: { name:"Banco olímpico con almacenamiento de discos",slug:"banco-olimpico-con-almacenamiento-discos",keyword:"banco olímpico con soporte para discos",intent:"planificar un puesto de press banca con almacenamiento integrado para zona de peso libre",definition:"Estación de press que combina banco, soportes de barra y pernos para guardar discos. Debe comprarse como puesto fijo, considerando acceso del usuario, carga y descarga de discos y circulación alrededor.",applications:"Se dirige a gimnasios comerciales, colegios, clubes y zonas de fuerza que concentran press y almacenamiento en un mismo módulo. La distribución debe evitar conflicto entre quien entrena y quien retira peso.",buyers:"Proyectistas, operadores y distribuidores evalúan orden de sala, reposición, combinación con barras y discos y coste logístico de una estructura integrada.",decision:"Solicite distancia entre soportes, posiciones de barra, altura del banco, ubicación y diámetro de pernos, zona operativa y plano de montaje. Confirme compatibilidad con barras y discos del proyecto.",distinction:"A diferencia de un banco móvil, queda dedicado al press. Frente a banco y árbol separados ahorra desplazamiento, pero concentra usuarios y exige revisar la retirada segura de los discos.",risk:"Pernos mal situados pueden interferir con agarre, ayudante o pasillo. Combinar el banco con discos de centro incompatible genera retrabajo y debe evitarse en la ficha del proyecto.",configuration:"banco de press, soportes de barra y pernos integrados para discos según plano aprobado",comparison:"Compare ergonomía, posiciones de barra, acceso del ayudante, capacidad física de pernos y circulación." },
      ko: { name:"원판 보관형 올림픽 벤치",slug:"olympic-bench-plate-storage",keyword:"원판 보관 올림픽 벤치프레스",intent:"프리웨이트 존의 벤치프레스와 원판 보관을 통합한 스테이션 계획",definition:"벤치, 바벨 거치대와 원판 보관용 슬리브를 하나로 구성한 벤치프레스 스테이션입니다. 사용자 접근, 원판 탈착과 주변 동선을 포함한 고정형 운동 구역으로 구매해야 합니다.",applications:"벤치프레스와 원판 재고를 한 모듈에 모으려는 상업용 헬스장, 학교, 클럽과 근력 구역에 적합합니다. 운동자와 원판을 꺼내는 사용자의 동선이 충돌하지 않아야 합니다.",buyers:"시설 설계자, 운영사와 유통사는 정리 상태, 재주문 호환성, 바와 원판 구성, 통합 프레임의 물류 비용을 함께 평가합니다.",decision:"바 거치 간격과 위치, 벤치 높이, 원판 슬리브 위치와 직경, 실제 사용 영역 및 조립 도면을 요청하십시오. 프로젝트의 바와 원판 규격에 맞는지 확인해야 합니다.",distinction:"이동식 벤치와 달리 벤치프레스 전용 위치에 놓입니다. 벤치와 원판 트리를 따로 둘 때보다 이동은 줄지만 사용자가 집중되므로 원판을 안전하게 꺼낼 공간이 필요합니다.",risk:"슬리브 위치가 나쁘면 그립, 보조자와 통로를 방해합니다. 센터홀이 맞지 않는 원판을 함께 발주하는 오류도 프로젝트 사양표에서 차단해야 합니다.",configuration:"승인 도면에 따른 벤치프레스, 바 거치대 및 통합 원판 보관 슬리브",comparison:"프레스 인체공학, 바 위치, 보조자 접근, 슬리브의 물리적 수용 범위와 사용자 동선을 비교합니다." }
    }
  },
  {
    slug: "multi-jungle-functional-trainer", score: 66, tier: "B", kind: "multi",
    locales: {
      "pt-BR": { name:"Estação multifuncional Multi Jungle",slug:"estacao-multifuncional-multi-jungle",keyword:"multi estação profissional para academia",intent:"comparar uma multiestação de cabos para academias com vários usuários simultâneos",definition:"Sistema modular de treinamento por cabos que reúne vários postos em uma estrutura central. A configuração final depende dos módulos selecionados, torres de peso, acessórios e capacidade operacional planejada.",applications:"É adequada a academias comerciais, centros de treinamento e clubes com fluxo suficiente para justificar um núcleo compartilhado. Pode organizar puxadas, remadas e outras funções sem espalhar várias torres isoladas.",buyers:"Redes, importadores de projetos e distribuidores analisam rendimento por metro quadrado, número de usuários, facilidade de supervisão e possibilidade de ampliar ou repor módulos.",decision:"Defina exercícios e postos antes de pedir preço. Envie planta, corredores, energia se aplicável, pé-direito, rota de entrada e expectativa de usuários; depois compare a mesma configuração entre fornecedores.",distinction:"Não existe uma única composição “Multi Jungle”. Ela difere de uma estação de cinco postos fechada porque pode ter lógica modular e combinações específicas. Nome semelhante não garante os mesmos módulos.",risk:"Cotação sem diagrama de configuração causa diferenças grandes de escopo. Cabos, pilhas, proteções, acessórios, ligações e montagem precisam aparecer na lista de fornecimento.",configuration:"núcleo multiestação com módulos de cabos, torres, proteções e acessórios definidos no projeto",comparison:"Compare funções incluídas, usuários simultâneos, área operacional, montagem, manutenção e possibilidade de expansão." },
      es: { name:"Estación multifunción Multi Jungle",slug:"estacion-multifuncional-multi-jungle",keyword:"multiestación profesional para gimnasio",intent:"comparar una multiestación de poleas para gimnasios con varios usuarios simultáneos",definition:"Sistema modular de entrenamiento por poleas que reúne varios puestos alrededor de una estructura central. La configuración depende de módulos, torres de peso, accesorios y capacidad operativa prevista.",applications:"Conviene a gimnasios comerciales, centros de entrenamiento y clubes con flujo suficiente para justificar un núcleo compartido. Puede concentrar jalones, remos y otras funciones sin repartir torres aisladas.",buyers:"Cadenas, importadores de proyectos y distribuidores estudian rendimiento por metro cuadrado, usuarios, supervisión y posibilidad de ampliar o reponer módulos.",decision:"Defina ejercicios y puestos antes de solicitar precio. Envíe plano, pasillos, energía si procede, altura libre, ruta de entrada y usuarios previstos; después compare la misma configuración.",distinction:"No existe una única composición Multi Jungle. Se diferencia de una estación cerrada de cinco puestos porque puede seguir una lógica modular. Un nombre parecido no garantiza los mismos módulos.",risk:"Una oferta sin diagrama genera diferencias importantes de alcance. Cables, pilas, carenados, accesorios, uniones y montaje deben figurar en la lista de suministro.",configuration:"núcleo multiestación con módulos de poleas, torres, protecciones y accesorios definidos por proyecto",comparison:"Compare funciones, usuarios simultáneos, superficie operativa, montaje, mantenimiento y ampliación." },
      ko: { name:"멀티 정글 펑셔널 트레이너",slug:"multi-jungle-functional-trainer",keyword:"상업용 멀티 스테이션 웨이트 머신",intent:"여러 사용자가 동시에 운동하는 상업용 케이블 멀티 스테이션 비교",definition:"중앙 구조 주위에 여러 케이블 운동 스테이션을 결합한 모듈형 시스템입니다. 최종 구성은 선택한 모듈, 웨이트 스택, 액세서리와 계획된 사용자 수에 따라 달라집니다.",applications:"공용 코어 장비를 사용할 충분한 회원 흐름이 있는 상업용 헬스장, 트레이닝 센터와 클럽에 적합합니다. 여러 개의 독립 타워 대신 풀다운, 로우 등의 기능을 한 구역에 배치할 수 있습니다.",buyers:"체인 운영사, 프로젝트 수입사와 유통사는 면적당 활용도, 동시 사용자, 감독 편의와 모듈 확장·재공급 가능성을 검토합니다.",decision:"가격을 요청하기 전에 필요한 운동과 스테이션을 정하십시오. 평면도, 통로, 필요한 전원, 천장 높이, 반입 경로와 예상 사용자를 보내 동일 구성을 비교해야 합니다.",distinction:"멀티 정글은 하나의 고정 조합을 뜻하지 않습니다. 모듈 방식일 수 있어 완성형 5스테이션과 다르며 비슷한 제품명만으로 포함 모듈을 판단할 수 없습니다.",risk:"구성도가 없는 견적은 공급 범위가 크게 달라질 수 있습니다. 케이블, 스택, 보호 커버, 액세서리, 연결 부품과 설치 범위를 목록화해야 합니다.",configuration:"프로젝트에서 정의한 케이블 모듈, 웨이트 타워, 보호 커버와 액세서리 구성",comparison:"포함 기능, 동시 사용자, 실제 사용 면적, 설치, 유지관리와 확장 가능성을 비교합니다." }
    }
  },
  {
    slug: "single-station-functional-trainer", score: 65, tier: "B", kind: "single",
    locales: {
      "pt-BR": { name:"Estação funcional individual",slug:"estacao-funcional-individual",keyword:"estação funcional individual profissional",intent:"comprar uma estação de cabos para um usuário em studio, hotel ou sala compacta",definition:"Equipamento de cabos organizado para um usuário por vez, com uma zona operacional definida. A expressão “individual” descreve capacidade simultânea, não limita automaticamente a variedade de exercícios.",applications:"Atende studios de personal, hotéis, condomínios e academias que precisam completar uma área sem instalar um núcleo multiestação. Também funciona como unidade de reposição ou expansão pontual.",buyers:"Operadores de espaços compactos e distribuidores valorizam implantação simples, acesso à manutenção e uma lista clara de puxadores incluídos.",decision:"Escolha a estação pelos movimentos necessários, curso, posições de ajuste, acesso à pilha e relação com paredes e outros equipamentos. Reserve circulação para troca de acessórios.",distinction:"Ocupa e atende menos pessoas que uma multiestação, mas pode oferecer implantação e manutenção mais simples. Não deve ser confundida com uma polia residencial leve sem torre e proteção equivalentes.",risk:"Contar somente a pegada do chassi ignora braços, cabos e usuário. Acessórios omitidos, altura de cabo incompatível e acesso bloqueado à pilha geram problemas de operação.",configuration:"uma zona de usuário, torre de resistência, percurso de cabo e conjunto de acessórios conforme modelo",comparison:"Compare movimentos, curso, ajustes, espaço real, acesso à pilha, acessórios e tempo de instalação." },
      es: { name:"Estación funcional individual",slug:"estacion-funcional-individual",keyword:"estación funcional individual profesional",intent:"comprar una estación de poleas para un usuario en estudio, hotel o sala compacta",definition:"Equipo de poleas organizado para un usuario cada vez con zona operativa definida. “Individual” describe la capacidad simultánea y no limita automáticamente la variedad de ejercicios.",applications:"Sirve a estudios personales, hoteles, comunidades y gimnasios que completan una zona sin instalar un núcleo multiestación. También puede ampliar o sustituir una unidad concreta.",buyers:"Operadores de espacios compactos y distribuidores valoran implantación sencilla, mantenimiento accesible y una relación clara de agarres incluidos.",decision:"Elija por movimientos, recorrido, ajustes, acceso a la pila y relación con paredes y otros equipos. Reserve circulación para cambiar accesorios.",distinction:"Ocupa y atiende a menos personas que una multiestación, pero simplifica implantación y mantenimiento. No equivale a una polea doméstica ligera sin torre ni protección comparables.",risk:"Medir solo el bastidor ignora brazos, cables y usuario. Accesorios omitidos, altura incompatible y acceso bloqueado a la pila generan problemas de operación.",configuration:"una zona de usuario, torre de resistencia, recorrido de cable y accesorios según modelo",comparison:"Compare movimientos, recorrido, ajustes, espacio real, acceso a pila, accesorios e instalación." },
      ko: { name:"싱글 스테이션 펑셔널 트레이너",slug:"single-station-functional-trainer",keyword:"상업용 싱글 스테이션 케이블 머신",intent:"PT 스튜디오·호텔·소형 운동실의 1인용 케이블 스테이션 구매",definition:"한 번에 한 명이 사용하도록 운동 영역을 구성한 케이블 장비입니다. 싱글 스테이션은 동시 사용 인원을 설명하며 운동 종류가 적다는 뜻은 아닙니다.",applications:"대형 멀티 스테이션 없이 케이블 구역을 보완하려는 PT 스튜디오, 호텔, 커뮤니티와 헬스장에 적합합니다. 특정 장비 교체나 단계적 확장에도 사용할 수 있습니다.",buyers:"소형 시설 운영사와 유통사는 간단한 설치, 정비 접근성과 포함 그립 목록의 명확성을 중요하게 봅니다.",decision:"필요한 동작, 케이블 이동 거리, 조절 위치, 스택 접근과 벽·주변 장비 관계를 기준으로 선택하십시오. 액세서리 교체 통로도 남겨야 합니다.",distinction:"멀티 스테이션보다 적은 공간과 사용자를 담당하지만 설치와 정비가 단순할 수 있습니다. 타워와 보호 구조가 다른 가벼운 가정용 풀리와 동일하게 비교하면 안 됩니다.",risk:"프레임 면적만 계산하면 사용자와 케이블 영역을 빠뜨립니다. 누락된 액세서리, 맞지 않는 케이블 높이, 막힌 스택 접근은 운영 문제를 만듭니다.",configuration:"1인 운동 구역, 저항 타워, 케이블 동작 범위와 모델별 액세서리 구성",comparison:"운동 종류, 케이블 이동, 조절, 실제 면적, 스택 접근, 액세서리와 설치 시간을 비교합니다." }
    }
  },
  {
    slug: "three-station-functional-trainer", score: 63, tier: "B", kind: "multi",
    locales: {
      "pt-BR": { name:"Estação funcional de três postos",slug:"estacao-funcional-tres-postos",keyword:"estação de musculação três postos",intent:"dimensionar uma estação para três usuários em academias médias e clubes",definition:"Sistema integrado com três posições de trabalho definidas para compartilhar estrutura e, conforme configuração, torres ou conexões. O número de postos deve corresponder a posições realmente utilizáveis ao mesmo tempo.",applications:"É uma alternativa para academias médias, clubes, condomínios e centros educacionais que precisam de mais capacidade que uma torre individual sem ocupar o espaço de uma estação maior.",buyers:"Projetistas e operadores comparam fila prevista, exercícios prioritários, visibilidade dos usuários e equilíbrio entre investimento, área e capacidade.",decision:"Mapeie quais três funções serão instaladas e se compartilham resistência ou acessórios. Simule entrada, saída e troca de puxadores com todos os postos ocupados.",distinction:"A vantagem não é apenas ter três lados. O valor aparece quando cada posto resolve uma demanda real e pode operar sem cabos, usuários ou ajustes interferirem entre si.",risk:"Contar placas decorativas como postos, compartilhar uma torre sem explicar limitações ou posicionar assentos em corredores cria falsa capacidade. A configuração deve ser desenhada e nominada.",configuration:"três posições funcionais identificadas, torres e acessórios definidos na lista do projeto",comparison:"Compare funções por posto, independência de uso, filas, área, visibilidade, manutenção e consumo de acessórios." },
      es: { name:"Estación funcional de tres puestos",slug:"estacion-funcional-tres-puestos",keyword:"estación de musculación de tres puestos",intent:"dimensionar una estación para tres usuarios en gimnasios medianos y clubes",definition:"Sistema integrado con tres posiciones de trabajo definidas que comparten estructura y, según configuración, torres o conexiones. El número debe corresponder a puestos utilizables simultáneamente.",applications:"Es una alternativa para gimnasios medianos, clubes, comunidades y centros educativos que necesitan más capacidad que una torre individual sin ocupar lo mismo que una estación mayor.",buyers:"Proyectistas y operadores comparan cola prevista, ejercicios prioritarios, visibilidad y equilibrio entre inversión, superficie y capacidad.",decision:"Defina las tres funciones y si comparten resistencia o accesorios. Simule entrada, salida y cambio de agarres con todos los puestos ocupados.",distinction:"La ventaja no consiste solo en tener tres lados. Aporta valor cuando cada puesto resuelve una demanda y funciona sin interferencia de cables, usuarios o ajustes.",risk:"Contar paneles como puestos, compartir torre sin explicar límites o colocar asientos en pasillos crea capacidad ficticia. La configuración debe dibujarse y nombrarse.",configuration:"tres posiciones funcionales identificadas, torres y accesorios definidos en la lista del proyecto",comparison:"Compare funciones por puesto, independencia, colas, superficie, visibilidad, mantenimiento y accesorios." },
      ko: { name:"3스테이션 펑셔널 트레이너",slug:"three-station-functional-trainer",keyword:"상업용 3스테이션 웨이트 머신",intent:"중형 헬스장과 클럽의 3인 동시 운동 스테이션 계획",definition:"세 개의 명확한 운동 위치가 프레임과 구성에 따라 타워 또는 연결부를 공유하는 통합 시스템입니다. 스테이션 수는 실제로 동시에 사용할 수 있는 위치를 기준으로 해야 합니다.",applications:"싱글 타워보다 많은 사용자를 수용하면서 대형 시스템 면적은 부담스러운 중형 헬스장, 클럽, 커뮤니티와 교육 시설에 적합합니다.",buyers:"설계자와 운영사는 예상 대기, 우선 운동, 사용자 관찰성과 투자·면적·수용력의 균형을 비교합니다.",decision:"세 위치에 어떤 기능을 둘지, 저항이나 액세서리를 공유하는지 정하십시오. 모든 위치가 사용 중일 때 진입, 퇴장과 그립 교체를 시뮬레이션해야 합니다.",distinction:"단순히 세 면을 가진 것이 장점은 아닙니다. 각 위치가 실제 수요를 해결하고 케이블, 사용자와 조절 동작이 간섭 없이 작동해야 가치가 있습니다.",risk:"장식 패널을 스테이션으로 계산하거나 공유 스택 한계를 숨기고 좌석을 통로에 두면 허수 용량이 됩니다. 구성도와 기능 명칭을 확정해야 합니다.",configuration:"식별된 3개 운동 위치, 프로젝트 목록에 정의된 타워와 액세서리",comparison:"위치별 기능, 독립 사용, 대기, 면적, 관찰성, 정비와 액세서리 소비를 비교합니다." }
    }
  },
  {
    slug: "five-station-functional-trainer", score: 64, tier: "B", kind: "multi",
    locales: {
      "pt-BR": { name:"Estação funcional de cinco postos",slug:"estacao-funcional-cinco-postos",keyword:"estação de musculação cinco postos",intent:"planejar alta capacidade de treinamento por cabos em academias comerciais",definition:"Equipamento integrado com cinco posições funcionais especificadas para atender vários usuários. O comprador deve conhecer a função, torre, assento, apoio e acessórios de cada posto, não apenas o número comercial.",applications:"Serve academias comerciais, clubes e centros de treinamento com pico de utilização que precisam concentrar funções de força e cabos em uma zona supervisionável.",buyers:"Redes, distribuidores de projetos e investidores analisam capacidade por horário, variedade de exercícios, área total, montagem e custo de parada para manutenção.",decision:"Use dados de fluxo para escolher cinco postos. Verifique se as funções mais procuradas estão presentes, se os usuários conseguem circular e se técnicos alcançam cabos e pilhas sem desmontar módulos vizinhos.",distinction:"Em relação à estação de três postos, oferece maior capacidade, mas exige mais área, peças, montagem e coordenação. Em relação a máquinas isoladas, concentra operação e risco de indisponibilidade.",risk:"Uma falha comum pode afetar vários postos. Por isso, identificação de cabos, peças de reposição, manual, acesso técnico e testes simultâneos precisam estar no plano de compra.",configuration:"cinco posições funcionais nomeadas, torres, cabos, proteções, assentos e acessórios definidos",comparison:"Compare capacidade no pico, variedade, área, acesso técnico, peças comuns, montagem e impacto de parada." },
      es: { name:"Estación funcional de cinco puestos",slug:"estacion-funcional-cinco-puestos",keyword:"estación de musculación de cinco puestos",intent:"planificar alta capacidad de entrenamiento por poleas en gimnasios comerciales",definition:"Equipo integrado con cinco posiciones funcionales especificadas para varios usuarios. El comprador debe conocer función, torre, asiento, apoyo y accesorios de cada puesto, no solo la cifra comercial.",applications:"Sirve a gimnasios comerciales, clubes y centros con horas punta que necesitan concentrar fuerza y poleas en una zona supervisable.",buyers:"Cadenas, distribuidores de proyectos e inversores analizan capacidad horaria, variedad, superficie, montaje y coste de parada por mantenimiento.",decision:"Utilice datos de afluencia para elegir cinco puestos. Verifique funciones demandadas, circulación y acceso técnico a cables y pilas sin desmontar módulos vecinos.",distinction:"Frente a tres puestos ofrece más capacidad, pero exige más área, piezas, montaje y coordinación. Frente a máquinas aisladas concentra operación y riesgo de indisponibilidad.",risk:"Un fallo común puede afectar varios puestos. Identificación de cables, repuestos, manual, acceso técnico y pruebas simultáneas deben formar parte del plan.",configuration:"cinco posiciones nombradas, torres, cables, protecciones, asientos y accesorios definidos",comparison:"Compare capacidad punta, variedad, superficie, acceso técnico, repuestos comunes, montaje e impacto de parada." },
      ko: { name:"5스테이션 펑셔널 트레이너",slug:"five-station-functional-trainer",keyword:"상업용 5스테이션 웨이트 머신",intent:"상업용 헬스장의 고수용량 케이블 운동 구역 계획",definition:"여러 사용자를 위해 다섯 개 기능 위치를 명시한 통합 장비입니다. 구매자는 숫자만 보지 말고 각 위치의 기능, 타워, 좌석, 지지부와 액세서리를 확인해야 합니다.",applications:"피크 시간대 사용량이 많고 근력·케이블 기능을 감독 가능한 한 구역에 모으려는 상업용 헬스장, 클럽과 트레이닝 센터에 적합합니다.",buyers:"체인, 프로젝트 유통사와 투자자는 시간당 수용력, 운동 다양성, 전체 면적, 설치와 정비 중단 비용을 분석합니다.",decision:"이용 흐름 자료로 5개 위치의 필요성을 판단하십시오. 인기 기능이 포함되는지, 사용자 통로가 충분한지, 인접 모듈을 해체하지 않고 케이블과 스택을 정비할 수 있는지 확인해야 합니다.",distinction:"3스테이션보다 수용력은 높지만 면적, 부품, 설치와 조정이 더 필요합니다. 독립 머신보다 운영이 집중되는 만큼 한 문제의 영향 범위도 커질 수 있습니다.",risk:"공용 부품의 문제가 여러 위치를 멈출 수 있습니다. 케이블 식별, 예비 부품, 매뉴얼, 기술자 접근과 동시 작동 시험을 구매 계획에 포함해야 합니다.",configuration:"명명된 5개 기능 위치, 정의된 타워, 케이블, 커버, 좌석과 액세서리",comparison:"피크 수용력, 운동 다양성, 면적, 정비 접근, 공용 부품, 설치와 중단 영향을 비교합니다." }
    }
  }
];

const sources = new Map(racksBenchesProducts.map((source) => [source.slug, source]));

function images(source: ProductSource, profile: LocalProfile, locale: TargetLocale): LocalizedImage[] {
  const labels = locale === "pt-BR"
    ? [`Vista real de ${profile.name}`,`Estrutura e acabamento relacionados à fabricação de ${profile.name}`,`Área real de embalagem para exportação de ${profile.name}`]
    : locale === "es"
      ? [`Vista real de ${profile.name}`,`Estructura y acabado relacionados con la fabricación de ${profile.name}`,`Zona real de embalaje de exportación para ${profile.name}`]
      : [`${profile.name} 실제 제품 전체 모습과 상업용 설치 참고 이미지`,`${profile.name} 프레임 제작 공정 및 표면 마감 참고 이미지`,`${profile.name} 수출 포장 준비와 출하 작업 구역 참고 이미지`];
  return [source.image,"/assets/factory-cases/pbf-squat-rack-chrome-plates.webp","/assets/factory-cases/packaging-area-pbf.webp"].map((src,index)=>({id:`image-${index+1}`,src,alt:labels[index],caption:labels[index]}));
}

function sharedVersion(entity: ContentEntity, selection: Selection, locale: TargetLocale): LocalizedContentVersion {
  const source = sources.get(selection.slug);
  if (!source) throw new Error(`Missing C completion source: ${selection.slug}`);
  const p = selection.locales[locale];
  const prefix = locale === "pt-BR" ? "/pt/produtos/racks-e-bancos" : locale === "es" ? "/es/productos/racks-y-bancos" : "/ko/products/racks-benches";
  const category = locale === "pt-BR" ? "Racks e bancos" : locale === "es" ? "Racks y bancos" : "랙과 벤치";
  const categoryId = "racks-benches-category";
  const path = `${prefix}/${p.slug}`;
  const material = locale === "pt-BR"
    ? "estrutura de aço reforçada, pontos de solda, acabamento em pintura a pó e ferragens comerciais conforme o modelo"
    : locale === "es"
      ? "estructura de acero reforzada, soldaduras, acabado de pintura en polvo y herrajes comerciales según el modelo"
      : "모델별 강화 강철 프레임, 용접부, 분체도장 마감과 상업용 하드웨어";
  const dimensions = locale === "pt-BR" ? "confirmar no desenho aprovado, incluindo área operacional" : locale === "es" ? "confirmar en el plano aprobado, incluida la superficie operativa" : "실제 사용 면적을 포함한 승인 도면에서 확인";
  const weight = locale === "pt-BR" ? "peso líquido e bruto confirmados por configuração" : locale === "es" ? "peso neto y bruto confirmados por configuración" : "구성별 순중량과 총중량 확인";

  const body = locale === "pt-BR" ? [
    ptQuick("resposta",`${p.name} é indicado para ${p.intent}. A decisão deve começar pela configuração real, planta do local, fluxo de usuários e critérios mensuráveis; dimensões, peso, capacidade e itens incluídos são confirmados para o código cotado, sem dedução a partir de fotografias.`),
    ptDefinition("definicao",p.name,p.definition),
    ptRich("aplicacoes","Aplicações comerciais",p.applications,p.buyers),
    ptRich("decisao","Como definir a configuração correta",p.decision,p.distinction),
    ptTable("especificacoes","Ficha técnica para a RFQ",["Campo","Base de avaliação","Documento de confirmação"],[["Produto",p.name,"Código e desenho"],["Configuração",p.configuration,"Lista de fornecimento"],["Material",material,"Ficha de materiais e acabamento"],["Dimensões",dimensions,"Desenho com unidades"],["Peso",weight,"Packing list do modelo"],["Instalação","Conforme layout e manual","Plano de montagem"],["Capacidade","Não presumida","Método e resultado do modelo"]],`Dados que precisam acompanhar a cotação de ${p.name}`),
    ptRich("materiais","Materiais e construção",`A base desta linha usa ${material}. O comprador deve relacionar espessuras, perfis, chapas, eixos, buchas, cabos, estofamento ou pinos ao mesmo código de produto. Materiais visuais semelhantes podem responder de forma diferente quando geometria, solda e ferragens mudam.`,`A inspeção de entrada verifica identidade e condição dos materiais definidos na ficha aprovada. Substituições exigem registro e nova avaliação; não devem aparecer silenciosamente entre amostra e produção.`),
    ptRich("dimensoes","Dimensões, peso e implantação",`Para ${p.name}, dimensões são ${dimensions}. Registre comprimento, largura, altura, envelope de movimento, acesso de manutenção e rota de entrada. O peso deve separar ${weight}, número de volumes e distribuição por caixa.`,`A planta precisa mostrar equipamento, usuário, área de ajuste, circulação e distância de paredes ou outras máquinas. Essa verificação reduz mudanças no recebimento e ajuda a calcular ocupação, instalação e frete.`),
    ptRich("fabricacao","Processo de fabricação",`A produção começa com corte e posicionamento de furos conforme desenho, segue por preparação de gabaritos, soldagem, polimento e tratamento antes da pintura a pó. Componentes móveis, guias, cabos ou mecanismos de ajuste são montados conforme a configuração de ${p.name}.`,`O controle de versão liga desenho, lista de materiais, cor, marca e embalagem ao pedido. A primeira unidade ou amostra de produção deve ser comparada à referência antes de liberar o restante do lote.`),
    ptRich("qc","Controle de qualidade",`O plano de QC combina inspeção visual e medições de dimensões, alinhamento, estabilidade, ajustes, movimento e acabamento. Em produtos com cabos, verifica percurso, terminais, polias, tensão e acesso; em bancos, posições, folgas, apoio e estofamento.`,`Critérios de aceitação, tolerâncias, tamanho da amostra e evidências devem ser acordados antes da produção. ${p.risk}`),
    ptTable("comparacao","Comparação para decisão de compra",["Critério",p.name,"Alternativa a comparar"],[["Uso principal",p.intent,"Outra capacidade ou formato"],["Configuração",p.configuration,"Módulo separado ou maior"],["Espaço",dimensions,"Área e circulação próprias"],["Decisão",p.comparison,"Comparar com o mesmo escopo"],["Risco crítico",p.risk,"Registrar mitigação na RFQ"]],`Comparação orientada ao projeto, não apenas ao preço`),
    ptRich("embalagem","Embalagem, transporte e recebimento",`A desmontagem para exportação deve equilibrar volume e facilidade de montagem. Proteja pintura, quinas, estofamento, cabos, guias e ferragens; identifique caixas e mantenha parafusos e acessórios vinculados ao módulo correto.`,`Antes do embarque, confirme quantidade de volumes, dimensões, peso bruto, empilhamento permitido e documentação. No recebimento, fotografe as caixas, confira a packing list e separe danos de transporte de problemas de montagem.`),
    ptRich("oem","OEM, ODM e personalização",`PowerBaseFit pode avaliar cor de estrutura, aplicação de logo, placas de marca, seleção de acessórios e embalagem para marca própria. Cada opção depende de método, quantidade, arquivo, posição e aprovação de amostra.`,`ODM ou alteração estrutural exige revisão de desenho, compatibilidade, custo de desenvolvimento e nova validação. MOQ e prazo são informados após definir o escopo, não como promessa genérica para todas as versões.`),
    ptChecklist("checklist","Checklist do comprador",["Enviar planta, aplicação e número esperado de usuários","Definir configuração, itens incluídos e acessórios","Solicitar desenho com dimensões e área operacional","Confirmar peso líquido, peso bruto e volumes","Aprovar materiais, cor, logo e amostra","Acordar QC, tolerâncias e evidências","Revisar embalagem, montagem, peças e Incoterm"]),
    ptRich("cotacao","Como solicitar uma cotação comparável",`Envie o link de ${p.name}, quantidade, destino, Incoterm, prazo, layout, configuração e personalização. Informe se o projeto exige amostra, inspeção independente, peças extras, instalação ou combinação com outros equipamentos.`,`A proposta deve separar produto, opcionais, embalagem, documentação e custos não incluídos. Só compare fornecedores quando cada um responder à mesma versão da RFQ.`)
  ] : locale === "es" ? [
    esQuick("respuesta",`${p.name} está pensado para ${p.intent}. La decisión empieza por la configuración real, plano, flujo de usuarios y criterios medibles; medidas, peso, capacidad y elementos incluidos se confirman para el código ofertado, sin deducirlos de fotografías.`),
    esDefinition("definicion",p.name,p.definition),
    esRich("aplicaciones","Aplicaciones comerciales",p.applications,p.buyers),
    esRich("decision","Cómo definir la configuración",p.decision,p.distinction),
    esTable("especificaciones","Ficha técnica para la RFQ",["Campo","Base de evaluación","Confirmación"],[["Producto",p.name,"Código y plano"],["Configuración",p.configuration,"Lista de suministro"],["Material",material,"Ficha de materiales y acabado"],["Dimensiones",dimensions,"Plano con unidades"],["Peso",weight,"Packing list del modelo"],["Instalación","Según layout y manual","Plan de montaje"],["Capacidad","No se presume","Método y resultado del modelo"]],`Datos que deben acompañar la oferta de ${p.name}`),
    esRich("materiales","Materiales y construcción",`La base de la línea utiliza ${material}. Perfiles, espesores, chapas, ejes, casquillos, cables, tapizado o pernos deben vincularse al mismo código. Una apariencia parecida no demuestra la misma respuesta si cambian geometría, soldadura y herrajes.`,`La recepción de materiales comprueba identidad y condición frente a la ficha aprobada. Toda sustitución se registra y reevalúa; no debe introducirse entre muestra y serie sin autorización.`),
    esRich("dimensiones","Dimensiones, peso e implantación",`Para ${p.name}, las medidas se deben ${dimensions}. Registre largo, ancho, alto, envolvente de movimiento, mantenimiento y ruta de entrada. El peso debe separar ${weight}, número de bultos y reparto por caja.`,`El plano muestra equipo, usuario, ajustes, circulación y distancia a paredes o máquinas. Así se reducen cambios durante la recepción y se calculan ocupación, instalación y transporte.`),
    esRich("fabricacion","Proceso de fabricación",`La producción comienza con corte y posicionamiento de orificios según plano, continúa con utillaje, soldadura, pulido y tratamiento antes de pintura en polvo. Piezas móviles, guías, cables o ajustes se montan según la configuración de ${p.name}.`,`El control de versión vincula plano, materiales, color, marca y embalaje al pedido. La primera unidad o muestra de producción se compara con la referencia antes de liberar el resto.`),
    esRich("qc","Control de calidad",`El plan combina inspección visual y medición de dimensiones, alineación, estabilidad, ajustes, movimiento y acabado. En equipos de cable revisa recorrido, terminales, poleas, tensión y acceso; en bancos, posiciones, holguras, apoyo y tapizado.`,`Criterios, tolerancias, muestra y evidencias se acuerdan antes de producir. ${p.risk}`),
    esTable("comparacion","Comparación para decidir",["Criterio",p.name,"Alternativa"],[["Uso",p.intent,"Otra capacidad o formato"],["Configuración",p.configuration,"Módulo separado o mayor"],["Espacio",dimensions,"Área y circulación propias"],["Decisión",p.comparison,"Comparar el mismo alcance"],["Riesgo",p.risk,"Registrar mitigación en RFQ"]],`Comparación de proyecto y no solo de precio`),
    esRich("embalaje","Embalaje, transporte y recepción",`El desmontaje para exportación debe equilibrar volumen y montaje. Proteja pintura, esquinas, tapizado, cables, guías y herrajes; identifique cajas y mantenga tornillos y accesorios asociados al módulo correcto.`,`Confirme bultos, dimensiones, peso bruto, apilado y documentos. Al recibir, fotografíe cajas, compruebe packing list y distinga daños de transporte de incidencias de montaje.`),
    esRich("oem","OEM, ODM y personalización",`PowerBaseFit puede estudiar color de bastidor, logo, placas de marca, accesorios y embalaje de marca privada. Cada opción depende de método, cantidad, archivo, posición y muestra aprobada.`,`Un cambio ODM o estructural requiere revisar plano, compatibilidad, desarrollo y validación. MOQ y plazo se informan cuando el alcance está definido.`),
    esChecklist("checklist","Checklist del comprador",["Enviar plano, aplicación y usuarios previstos","Definir configuración, suministro y accesorios","Solicitar plano con dimensiones y superficie operativa","Confirmar peso neto, bruto y bultos","Aprobar materiales, color, logo y muestra","Acordar QC, tolerancias y evidencias","Revisar embalaje, montaje, repuestos e Incoterm"]),
    esRich("cotizacion","Cómo solicitar una oferta comparable",`Envíe el enlace de ${p.name}, cantidad, destino, Incoterm, plazo, layout, configuración y personalización. Indique muestra, inspección independiente, repuestos, instalación o combinación con otros equipos.`,`La oferta separa producto, opcionales, embalaje, documentación y exclusiones. Compare proveedores solo cuando respondan a la misma versión de RFQ.`)
  ] : [
    koAnswer("answer","빠른 답변",`${p.name}은 ${p.intent}을 위한 제품입니다. 실제 구성, 배치도, 사용자 흐름과 측정 가능한 기준부터 결정해야 하며 치수, 중량, 수용력과 포함 품목은 사진으로 추정하지 않고 견적 코드별 자료에서 확인합니다.`),
    koDefinition("definition",p.name,p.definition),
    koText("applications","상업용 적용 환경",p.applications,p.buyers),
    koText("decision","구성 선택 기준",p.decision,p.distinction),
    koTable("specifications","RFQ 기술 사양표",["항목","평가 기준","확인 문서"],[["제품",p.name,"코드와 도면"],["구성",p.configuration,"공급 범위표"],["재질",material,"재질·마감 사양"],["치수",dimensions,"단위 포함 도면"],["중량",weight,"모델 패킹리스트"],["설치","레이아웃과 매뉴얼 기준","조립 계획"],["수용력","임의 추정 금지","모델별 방법과 결과"]],`${p.name} 견적에 필요한 확인 자료`),
    koText("materials","재질과 구조",`이 제품군은 ${material}을 기준으로 합니다. 프로파일, 두께, 판재, 축, 부싱, 케이블, 패드 또는 슬리브를 같은 제품 코드에 연결해야 합니다. 외관이 비슷해도 형상, 용접과 하드웨어가 다르면 결과가 달라질 수 있습니다.`,`입고 검사는 승인 사양과 재질의 식별 및 상태를 확인합니다. 대체 재질은 기록하고 다시 평가해야 하며 샘플과 양산 사이에 승인 없이 바꾸면 안 됩니다.`),
    koText("dimensions","치수, 중량과 설치 계획",`${p.name}의 치수는 ${dimensions}합니다. 길이, 폭, 높이, 운동 동작 영역, 정비 공간과 반입 경로를 기록하십시오. 중량은 ${weight}하고 포장 수량과 박스별 배분을 구분해야 합니다.`,`평면도에는 장비, 사용자, 조절 영역, 통로와 벽·주변 머신 간격이 보여야 합니다. 이 검토는 입고 후 변경을 줄이고 면적, 설치와 운송비 계산에 도움이 됩니다.`),
    koText("manufacturing","제조 공정",`생산은 승인 도면에 따른 강재 절단과 홀 위치 가공에서 시작해 지그 준비, 용접, 연마와 분체도장 전처리로 이어집니다. 이동 부품, 가이드, 케이블 또는 조절 장치는 ${p.name}의 구성에 따라 조립합니다.`,`도면, 재질표, 색상, 브랜드와 포장의 버전을 주문과 연결합니다. 첫 생산품 또는 샘플을 기준과 대조한 뒤 나머지 로트 생산을 승인해야 합니다.`),
    koText("qc","품질관리",`QC 계획은 외관 검사와 치수, 정렬, 안정성, 조절, 움직임 및 마감 측정을 결합합니다. 케이블 장비는 이동 경로, 단말, 풀리, 장력과 접근을 보고 벤치는 위치, 유격, 지지와 패드를 확인합니다.`,`합격 기준, 허용오차, 샘플 수와 증빙은 생산 전에 합의합니다. ${p.risk}`),
    koTable("comparison","구매 비교표",["기준",p.name,"비교 대안"],[["주요 용도",p.intent,"다른 수용력 또는 형식"],["구성",p.configuration,"분리형 또는 대형 모듈"],["공간",dimensions,"자체 사용 영역과 통로"],["결정",p.comparison,"같은 공급 범위 비교"],["핵심 위험",p.risk,"RFQ에 대응책 기록"]],`가격만이 아닌 프로젝트 조건 비교`),
    koText("packing","포장, 운송과 입고",`수출용 분해는 부피와 조립 편의의 균형을 맞춰야 합니다. 도장, 모서리, 패드, 케이블, 가이드와 하드웨어를 보호하고 박스를 식별해 볼트와 액세서리가 올바른 모듈에 연결되도록 합니다.`,`출하 전에 포장 수, 치수, 총중량, 적재 조건과 문서를 확인합니다. 입고 시 박스를 촬영하고 패킹리스트를 대조해 운송 손상과 조립 문제를 구분하십시오.`),
    koText("commissioning","조립과 현장 인수",`${p.name} 조립 전에는 박스 번호와 부품표를 대조하고 프레임을 임시로 세운 상태에서 모든 체결부를 즉시 최종 조이지 않습니다. 기준면, 좌우 정렬, 케이블 또는 조절부의 움직임을 확인한 뒤 지정 순서와 토크 기준에 따라 마감해야 합니다.`,`현장 인수 기록에는 설치 위치, 제품 코드, 누락 부품, 외관 상태, 작동 확인과 수정 사항을 남깁니다. 설치팀이 공장 QC와 같은 도면 버전을 사용해야 운송, 조립 또는 제조 단계에서 발생한 문제를 구분할 수 있습니다.`),
    koText("service","유지관리와 재주문 관리",`운영자는 ${p.name}의 점검 주기를 사용 빈도와 설치 환경에 맞춰 정해야 합니다. 체결부, 움직이는 접점, 케이블 또는 조절 장치, 패드, 표면과 바닥 접촉을 정기적으로 확인하고 이상이 있으면 사용을 중지한 뒤 원인을 기록합니다. 점검 담당자와 조치 날짜를 남기면 반복되는 문제와 소모품 교체 시점을 더 정확하게 판단할 수 있습니다.`,`재주문을 위해 제품 코드, 도면 버전, 색상, 로고 파일, 액세서리 목록, 포장 방식과 이전 QC 기록을 보관하십시오. 이름이 같은 제품이라도 버전이 달라질 수 있으므로 사진만으로 부품 호환성을 판단하지 않습니다.`),
    koText("oem","OEM·ODM과 맞춤 제작",`PowerBaseFit은 프레임 색상, 로고, 브랜드 플레이트, 액세서리와 자체 브랜드 포장을 검토할 수 있습니다. 각 옵션은 적용 방식, 수량, 파일, 위치와 승인 샘플에 따라 달라집니다.`,`ODM 또는 구조 변경은 도면, 호환성, 개발 비용과 재검증이 필요합니다. MOQ와 납기는 범위를 정의한 뒤 해당 구성에 맞춰 안내합니다.`),
    koChecklist("checklist","구매자 체크리스트",["배치도, 용도와 예상 사용자 제공","구성, 포함 품목과 액세서리 정의","치수와 실제 사용 면적 도면 요청","순중량, 총중량과 포장 수 확인","재질, 색상, 로고와 샘플 승인","QC, 허용오차와 증빙 합의","포장, 조립, 예비 부품과 Incoterm 검토"]),
    koText("quotation","비교 가능한 견적 요청",`${p.name} 링크, 수량, 도착지, Incoterm, 목표 일정, 레이아웃, 구성과 맞춤 범위를 보내십시오. 샘플, 독립 검사, 예비 부품, 설치 또는 다른 장비와의 조합도 명시합니다.`,`견적은 제품, 옵션, 포장, 문서와 제외 비용을 구분해야 합니다. 모든 공급업체가 같은 RFQ 버전에 답할 때만 가격과 조건을 비교하십시오.`)
  ];

  const faq = locale === "pt-BR" ? [
    {id:"faq-1",question:`Quais dados preciso enviar para cotar ${p.name}?`,answer:`Envie quantidade, destino, planta, uso, configuração, personalização e prazo. Medidas, peso e itens incluídos serão vinculados ao código selecionado.`},
    {id:"faq-2",question:`Como comparar ${p.name} entre fabricantes?`,answer:`Use a mesma RFQ e compare ${p.comparison} Inclua materiais, desenho, QC, embalagem, montagem e exclusões.`},
    {id:"faq-3",question:"É possível personalizar logo e cor?",answer:"Sim, quando método, quantidade e superfície permitirem. Arquivo, posição, referência de cor, amostra, MOQ e prazo são aprovados antes da produção."},
    {id:"faq-4",question:"Como são confirmados dimensões e peso?",answer:"Pelo desenho e packing list do modelo cotado. O comprador deve confirmar unidades, configuração, peso líquido, peso bruto e número de volumes."},
    {id:"faq-5",question:"Qual inspeção é recomendada antes do embarque?",answer:"Verificação de identidade, dimensões, montagem, estabilidade, função, acabamento, marca, acessórios e embalagem conforme critérios e amostragem acordados."}
  ] : locale === "es" ? [
    {id:"faq-1",question:`¿Qué datos hacen falta para cotizar ${p.name}?`,answer:"Cantidad, destino, plano, uso, configuración, personalización y plazo. Medidas, peso y suministro se vinculan al código elegido."},
    {id:"faq-2",question:`¿Cómo comparar ${p.name} entre fabricantes?`,answer:`Utilice la misma RFQ y compare ${p.comparison} Incluya materiales, plano, QC, embalaje, montaje y exclusiones.`},
    {id:"faq-3",question:"¿Se pueden personalizar logo y color?",answer:"Sí, si método, volumen y superficie lo permiten. Archivo, posición, color, muestra, MOQ y plazo se aprueban antes de producir."},
    {id:"faq-4",question:"¿Cómo se confirman dimensiones y peso?",answer:"Mediante plano y packing list del modelo ofertado, indicando unidades, configuración, peso neto, bruto y número de bultos."},
    {id:"faq-5",question:"¿Qué inspección conviene antes del embarque?",answer:"Identidad, dimensiones, montaje, estabilidad, función, acabado, marca, accesorios y embalaje según criterios y muestreo acordados."}
  ] : [
    {id:"faq-1",question:`${p.name} 견적에 어떤 정보가 필요합니까?`,answer:"수량, 도착지, 배치도, 용도, 구성, 맞춤 범위와 일정을 보내십시오. 치수, 중량과 포함 품목은 선택 코드에 연결해 확인합니다."},
    {id:"faq-2",question:`${p.name} 공급업체를 어떻게 비교합니까?`,answer:`동일한 RFQ로 ${p.comparison} 재질, 도면, QC, 포장, 설치와 제외 항목도 함께 비교합니다.`},
    {id:"faq-3",question:"로고와 색상을 맞춤 제작할 수 있습니까?",answer:"방식, 수량과 표면이 적합하면 가능합니다. 파일, 위치, 색상 기준, 샘플, MOQ와 납기를 생산 전에 승인합니다."},
    {id:"faq-4",question:"치수와 중량은 어떻게 확인합니까?",answer:"견적 모델의 도면과 패킹리스트로 단위, 구성, 순중량, 총중량과 포장 수를 확인합니다."},
    {id:"faq-5",question:"출하 전 어떤 검사가 필요합니까?",answer:"합의한 기준과 샘플링에 따라 제품 식별, 치수, 조립, 안정성, 기능, 마감, 로고, 액세서리와 포장을 검사합니다."}
  ];

  const title = locale === "pt-BR" ? `${p.name} profissional | Fabricante OEM` : locale === "es" ? `${p.name} profesional | Fabricante OEM` : `${p.name} 제조업체·OEM 공급`;
  const description = locale === "pt-BR" ? `${p.keyword} para projetos B2B: especificações, dimensões, fabricação, QC, embalagem, OEM, ODM e cotação direta com a PowerBaseFit.` : locale === "es" ? `${p.keyword} para proyectos B2B: especificaciones, medidas, fabricación, QC, embalaje, OEM, ODM y oferta directa de PowerBaseFit.` : `${p.keyword} B2B 구매 정보: 사양, 치수, 제조, QC, 수출 포장, OEM·ODM 및 PowerBaseFit 견적 절차.`;
  const h1 = locale === "pt-BR" ? `${p.name} para projetos profissionais` : locale === "es" ? `${p.name} para proyectos profesionales` : `${p.name} 상업용 프로젝트 공급`;
  const home = locale === "pt-BR" ? {name:"Início",path:"/pt"} : locale === "es" ? {name:"Inicio",path:"/es"} : {name:"홈",path:"/ko"};
  const products = locale === "pt-BR" ? {name:"Produtos",path:"/pt/produtos"} : locale === "es" ? {name:"Productos",path:"/es/productos"} : {name:"제품",path:"/ko/products"};
  return {
    locale,translationStatus:"localized",reviewStatus:"approved",publishStatus:"published",slug:p.slug,publicPath:path,title,description,h1,body,faq,
    author:locale === "pt-BR" ? ptBrEditorialAuthor : locale === "es" ? spanishEditorialAuthor : koreanEditorialAuthor,
    reviewedBy:locale === "pt-BR" ? ptBrTechnicalReviewer : locale === "es" ? spanishTechnicalReviewer : koreanTechnicalReviewer,
    schemaData:{sku:entity.versions.en?.schemaData.sku ?? `PBF-${selection.slug.toUpperCase()}`,brand:"PowerBaseFit",manufacturer:"PowerBaseFit",material,category,specifications:[{name:locale === "pt-BR"?"Configuração":locale === "es"?"Configuración":"구성",value:p.configuration},{name:locale === "pt-BR"?"Dimensões":locale === "es"?"Dimensiones":"치수",value:dimensions},{name:locale === "pt-BR"?"Peso":locale === "es"?"Peso":"중량",value:weight}],breadcrumbs:[home,products,{name:category,path:prefix},{name:p.name,path}],extra:{primaryKeyword:p.keyword,searchIntent:p.intent}},
    images:images(source,p,locale),internalLinks:[{targetContentId:categoryId,label:locale === "pt-BR"?"Ver racks e bancos":locale === "es"?"Ver racks y bancos":"랙과 벤치 보기"},{targetContentId:"factory",label:locale === "pt-BR"?"Fabricação e controle de qualidade":locale === "es"?"Fabricación y control de calidad":"제조 및 품질관리"},{targetContentId:"oem-private-label",label:locale === "pt-BR"?"OEM e marca própria":locale === "es"?"OEM y marca privada":"OEM·자체 브랜드"},{targetContentId:"contact",label:locale === "pt-BR"?"Solicitar cotação":locale === "es"?"Solicitar oferta":"견적 요청"}],
    canonicalData:{mode:"self"},hreflangData:{include:true},updatedAt:releaseDate,publishedAt:releaseDate,version:1
  };
}

export function withCommercialCompletionC(manifest: ContentManifest): ContentManifest {
  const byId = new Map(selections.map((selection)=>[`product:racks:${selection.slug}`,selection]));
  const found = new Set<string>();
  const entities = manifest.entities.map((entity)=>{
    const selection = byId.get(entity.id);
    if (!selection) return entity;
    found.add(entity.id);
    for (const locale of ["pt-BR","es","ko"] as const) if (entity.versions[locale]) throw new Error(`C completion duplicates ${entity.id} ${locale}`);
    return {...entity,versions:{...entity.versions,"pt-BR":sharedVersion(entity,selection,"pt-BR"),es:sharedVersion(entity,selection,"es"),ko:sharedVersion(entity,selection,"ko")}};
  });
  const missing = [...byId.keys()].filter((id)=>!found.has(id));
  if (missing.length) throw new Error(`C completion missing entities: ${missing.join(", ")}`);
  return {...manifest,entities};
}

export const commercialCompletionCSelections = selections;
