import type { CaseLocale } from "./compact-chrome-dumbbell-case";

export const caseSectionExpansions: Partial<Record<CaseLocale, string[]>> = {
  en: [
    "The purpose of this case is to turn a single verified visual reference into a useful buying discussion. The set can be assessed as a compact light-weight module: the dumbbells provide graduated resistance, while the rack defines storage and presentation. A buyer can use the image to communicate the desired visual direction, then replace assumptions with approved specifications. This distinction matters in B2B sourcing because a photograph confirms arrangement and appearance, but commercial acceptance depends on measurable documents, samples and inspection criteria.",
    "Capacity planning should start with expected simultaneous use rather than the number of pairs visible in a catalog. A hotel room with occasional independent users has a different demand pattern from a coached studio running small-group sessions. Project teams should map exercises, likely peak occupancy and the weights most frequently selected. If several users need the same middle weights, duplicate pairs may deliver more operational value than extending the range with rarely used sizes. The rack plan must then reflect the revised quantity rather than forcing the program into a fixed display.",
    "The purchasing file should separate observable features from supplier-confirmed data. Observable features include the X-shaped frame, chrome appearance, paired arrangement and kilogram identification. Confirmed data should include the construction drawing, dimensions, product and packed weights, finish reference, tolerance, handle geometry, rack load rating, assembly method and carton configuration. Recording these items in one approval sheet reduces ambiguity between the quotation, sample, production batch and pre-shipment inspection.",
    "",
    "",
    "",
    "",
    "",
    ""
  ],
  es: [
    "La función del caso no es presentar una fotografía atractiva de forma aislada, sino convertirla en un punto de partida verificable para compras B2B. La aplicación combina una gama de resistencia progresiva con un sistema de almacenamiento definido. El comprador puede señalar el aspecto, la organización y la lectura visual que busca; después debe sustituir cualquier suposición por planos, ficha técnica, muestra y criterios de inspección. Esta metodología permite comparar propuestas de distintos proveedores sin confundir semejanza visual con equivalencia técnica. También ayuda a que compras, operaciones y responsables del gimnasio utilicen el mismo documento durante la aprobación.",
    "Los requisitos de la instalación cambian según el modelo de negocio. Un hotel puede valorar una estación intuitiva, silenciosa y fácil de mantener; un estudio de entrenamiento personal necesita cambios rápidos y una progresión útil para sesiones dirigidas; un centro comercial con alta rotación debe analizar duplicación de pesos, resistencia del soporte y tiempos de reposición. Conviene registrar usuarios simultáneos, ejercicios principales, horas punta y experiencia del público. Si varios clientes utilizan habitualmente 4, 5 o 6 kg, disponer de pares adicionales puede ser más útil que ampliar una serie con cargas poco solicitadas. La distribución final debe basarse en esa demanda y no únicamente en la simetría del catálogo.",
    "La solución debe documentarse como un conjunto de dos componentes relacionados. Para las mancuernas se confirman construcción fija, peso nominal, tolerancia, longitud, diámetro y textura de la empuñadura, método de marcación y protección superficial. Para el soporte se confirman material, dimensiones cargado y vacío, capacidad, geometría de los apoyos, estabilidad, niveladores, tornillería y procedimiento de montaje. También hay que comprobar la compatibilidad física: una mancuerna puede cumplir su ficha y aun así asentarse mal en un apoyo demasiado estrecho. Una prueba con la serie completa permite revisar separación, acceso de las manos, contacto entre piezas y equilibrio cuando faltan pares en un lado.",
    "Elegir cromado no debería basarse solo en una percepción premium. Su principal ventaja en esta aplicación es una forma compacta y una identificación clara dentro de un entorno cuidado. El comprador debe contrastarla con la humedad, frecuencia de limpieza, productos químicos utilizados y nivel de trato brusco esperado. En zonas con usuarios supervisados, el acabado puede conservarse mejor que en áreas de alto impacto. El rango de 1 a 10 kg resulta coherente cuando se buscan incrementos pequeños; si el programa incluye fuerza avanzada, debe complementarse. El soporte vertical es apropiado cuando falta longitud de pared, siempre que el equipo del proyecto valide acceso, estabilidad y distancia a otras estaciones.",
    "El valor comercial aparece cuando la estación resuelve una tarea concreta. Puede mejorar el orden visual de un estudio, ofrecer al huésped una selección comprensible o liberar espacio en la línea principal de una academia. También facilita que el personal detecte rápidamente un par ausente. Sin embargo, la estación no genera por sí sola una propuesta de entrenamiento completa. La oferta del centro debe definir qué ejercicios se realizarán, qué banco o superficie se utilizará y qué cargas adicionales estarán disponibles. Para compradores que distribuyen equipos, el mismo conjunto puede funcionar como referencia de exposición, pero el surtido, manuales, repuestos y embalaje deben adaptarse al canal local y al servicio posventa previsto.",
    "Una rutina operativa protege tanto el equipo como la experiencia del usuario. Al abrir y cerrar la sala, el responsable puede confirmar que las parejas están completas, que las marcas se leen y que ningún apoyo está deformado. Durante la limpieza se debe evitar dejar líquido en uniones, ranuras o zonas de contacto. La inspección periódica incluye movimiento de las cabezas, estado del moleteado, bordes, tornillos, niveladores y estabilidad del bastidor. También conviene registrar incidencias y fecha de revisión. Este historial permite distinguir desgaste normal de un problema recurrente y aporta información concreta cuando se solicita una pieza de recambio o se prepara una reposición del mismo modelo.",
    "Desde la fábrica, el control empieza antes de producir. La lista aprobada debe indicar cada peso, número de unidades o pares, acabado, marca y embalaje. La muestra sirve para fijar tono, brillo, grabado, agarre y ajuste en el soporte. Durante la producción se pueden establecer controles de materia prima, mecanizado, unión, superficie, masa, legibilidad y montaje. Antes del envío, una inspección por muestreo o por alcance acordado compara el lote con la muestra y la orden. En exportación también se revisan protección entre superficies, resistencia de cajas, identificación de bultos, lista de empaque y separación de herrajes. La experiencia del proveedor debe demostrarse con documentos aplicables al pedido, no con afirmaciones generales.",
    "Al comparar ofertas, el precio unitario no es suficiente. El comprador debe revisar qué incluye cada propuesta: número real de piezas, rack, repuestos, herramientas, cajas, palés, documentación y condiciones de garantía. Debe preguntar cómo se confirma la tolerancia, qué ocurre si una marca llega dañada y si el modelo podrá reponerse con el mismo aspecto. El coste logístico se evalúa con peso bruto, volumen, número de bultos y método de carga. Para importación, también se comprueban marcado, idioma de instrucciones y requisitos del mercado de destino con asesores locales. Una consulta bien estructurada facilita una cotización comparable y reduce cambios tardíos que afectan plazo, embalaje o coste."
  ],
  "pt-BR": [
    "Este caso transforma uma referência visual real em um roteiro de especificação para compras profissionais. A imagem permite alinhar aparência, organização e proposta de uso, mas não deve ser usada para presumir material, capacidade ou desempenho. Em uma negociação B2B, o ideal é registrar o que está visível e abrir uma coluna separada para aquilo que a fábrica precisa confirmar. Assim, comprador, equipe técnica e fornecedor trabalham com a mesma base. A aprovação passa por desenho, ficha, amostra e critérios de inspeção, evitando que expressões como “igual à foto” substituam medidas e requisitos objetivos durante a produção.",
    "A necessidade muda bastante entre hotel, condomínio, studio de personal e academia de alto fluxo. Um hotel pode priorizar operação simples, aparência e manutenção; o studio avalia progressão para diferentes alunos e velocidade de troca; uma academia precisa considerar uso simultâneo e reposição. O planejamento deve listar exercícios, público, horário de pico e pesos mais procurados. Em aulas ou sessões compartilhadas, duplicar algumas cargas intermediárias pode ser mais útil do que manter apenas um par de cada peso. A decisão também influencia o rack: a quantidade final deve caber com folga, permitir acesso das mãos e manter estabilidade quando usuários retiram vários pares ao mesmo tempo.",
    "Para especificar a solução, os halteres e o rack precisam ser avaliados separadamente e em conjunto. Nos halteres, confirme peso nominal e tolerância, construção fixa, dimensões, diâmetro e textura da pegada, marcação, acabamento e método de união. No rack, confirme estrutura, dimensão carregada, capacidade, pontos de apoio, base, niveladores, parafusos e montagem. Depois, faça uma verificação de compatibilidade com a série completa. O teste mostra se cada peça assenta corretamente, se existe contato metal com metal indesejado, se as marcações continuam visíveis e se a retirada do par não prende os dedos ou obriga movimentos desconfortáveis.",
    "A escolha do cromado precisa combinar posicionamento visual e ambiente de uso. O acabamento pode contribuir para uma área limpa e compacta, comum em hotelaria e studios, mas deve ser compatível com umidade, produtos de limpeza e intensidade de operação. O intervalo de 1 a 10 kg favorece progressões pequenas, aquecimento e exercícios acessórios; não atende sozinho um programa avançado de força. O rack em X economiza comprimento de parede, porém sua base e os halteres projetados exigem área operacional. É importante desenhar a estação na planta e verificar passagens, abertura de portas, proximidade de espelhos, bancos e equipamentos de cardio.",
    "O valor para a operação está na combinação entre acesso rápido e organização. Em um studio, o profissional encontra a carga sem interromper a sessão; em hotel ou condomínio, o hóspede reconhece a sequência sem assistência; em academia maior, o conjunto pode criar uma zona leve independente. A equipe também identifica com facilidade quando um par não voltou ao lugar. Ainda assim, a solução deve estar ligada ao programa real. Banco, tapete, piso, instruções de uso e pesos complementares precisam ser definidos. Para distribuidores brasileiros, o conjunto pode integrar uma linha premium compacta, desde que disponibilidade de reposição, manual, garantia e embalagem estejam alinhadas ao canal de venda.",
    "Uma rotina de controle simples aumenta a vida útil. A equipe confere pares, marcações, folgas, riscos profundos, parafusos, apoios e nivelamento. Produtos com cabeça solta, aresta ou deformação saem de uso até avaliação. Na higienização, o pano deve estar apenas umedecido com produto compatível, seguido de secagem, sem deixar líquido acumulado nas uniões. Vale registrar data e tipo de ocorrência. Esse histórico ajuda a fábrica ou distribuidor a analisar causa, enviar componente correto e distinguir desgaste, montagem inadequada e problema de fabricação. O manual do modelo aprovado deve definir torque, periodicidade e produtos proibidos.",
    "Do lado da fabricação, o pedido começa com uma lista fechada por peso, pares, rack, logo, acabamento e embalagem. A amostra aprovada estabelece brilho, gravação, sensação da pegada e encaixe. Na produção, os controles podem abranger matéria-prima, usinagem, união, superfície, massa, leitura das marcas e montagem. Antes do embarque, o lote é comparado com amostra e ordem de compra. Para exportação ao Brasil, também se revisam separação entre peças, proteção contra umidade, resistência da caixa, identificação dos volumes, ferragens e instruções. Capacidade do fornecedor deve ser demonstrada com processo, registro e resposta a desvios aplicáveis a este produto.",
    "Na comparação comercial, verifique o conteúdo total da proposta e não apenas o valor por quilograma. Confirme número de unidades, rack, peças de reposição, ferramenta, embalagem, palete, peso bruto, volume e condições de garantia. Pergunte como é tratado um item fora da tolerância, um acabamento danificado ou uma falta na carga. O importador deve revisar classificação, marcações, instruções e demais obrigações do mercado com profissionais locais. Também precisa considerar descarga, movimentação e montagem no destino. Uma boa cotação apresenta cada peso em linha separada, prazos condicionados à personalização e critérios claros de amostra, inspeção, aceite e reposição."
  ],
  fr: [
    "Ce cas sert de support à une démarche d’achat vérifiable. La photo aligne les équipes sur l’allure, l’organisation et l’usage envisagé, mais elle ne remplace ni un plan ni une spécification. Dans un dossier B2B, il est utile de séparer les caractéristiques observées des données à confirmer par le fabricant. Cette méthode évite qu’une formule vague comme « identique à l’image » soit interprétée différemment par l’acheteur, l’usine et l’inspecteur. La référence finale doit associer dessin coté, fiche technique, échantillon approuvé, nomenclature et critères de contrôle, afin que la commande et le lot produit restent comparables.",
    "Les besoins d’un hôtel, d’un studio de coaching et d’un club très fréquenté ne sont pas interchangeables. L’hôtel recherche souvent une utilisation intuitive et une présentation soignée. Le studio privilégie les petits paliers et la rapidité entre deux exercices. Le club doit modéliser l’occupation aux heures de pointe, les doublons et le réassort. Le chef de projet peut recenser les exercices, les profils, la fréquence et les poids les plus demandés. Si plusieurs pratiquants utilisent simultanément les charges médianes, des paires supplémentaires sont parfois plus pertinentes qu’une extension vers des poids rarement choisis. Le rangement est ensuite dimensionné sur cette liste réelle.",
    "La solution comprend deux produits qui doivent être qualifiés ensemble. Pour les haltères, le dossier précise masse nominale et tolérance, dimensions, construction fixe, diamètre et moletage de la poignée, marquage et finition. Pour le rack, il précise matériau, encombrement chargé, charge admissible, géométrie des berceaux, stabilité, pieds, visserie et montage. Un essai avec la série complète vérifie l’assise de chaque haltère, l’accès des mains, les contacts susceptibles de rayer la surface et l’équilibre en charge partielle. Cette validation évite qu’un rack théoriquement compatible produise, en pratique, des gestes difficiles ou un rangement instable.",
    "Le chrome doit être choisi pour son adéquation au projet, pas uniquement pour son image haut de gamme. Il offre ici une forme dense et une lecture nette des charges, intéressantes dans les univers hôteliers ou les studios bien entretenus. L’acheteur doit toutefois confronter la finition à l’humidité, aux produits de nettoyage et à la fréquence de manipulation. La plage de 1 à 10 kg répond aux progressions fines et au travail accessoire, mais elle ne constitue pas une offre de force complète. Le rack vertical réduit la longueur occupée ; son implantation doit néanmoins intégrer le recul de l’utilisateur, les poids saillants et les circulations réglementaires.",
    "La valeur opérationnelle dépend de la tâche résolue. Dans un studio, le coach change rapidement de charge. Dans un hôtel, le client comprend la séquence sans assistance. Dans un club plus vaste, la station peut détourner le travail léger de la zone lourde. Le rangement aide aussi le personnel à repérer immédiatement une paire manquante. Il faut cependant relier cette station à un parcours cohérent : banc, sol, espace de mouvement, consignes et charges complémentaires. Pour un distributeur, le même ensemble peut devenir une référence de showroom, à condition que le stock, les pièces, la notice, la garantie et le service après-vente soient adaptés au marché servi.",
    "L’entretien repose sur une procédure courte mais documentée. À chaque contrôle, l’équipe vérifie la présence des paires, la lisibilité, le serrage, les appuis, les pieds et la stabilité. Un jeu dans une tête, une arête ou une déformation impose le retrait temporaire. Le nettoyage utilise un produit validé, appliqué sans saturer les assemblages, puis un séchage. Un registre des anomalies, avec date et photo, facilite l’analyse avec le fournisseur. Il permet de distinguer usure normale, mauvaise utilisation, erreur de montage et défaut récurrent. Les fréquences et produits autorisés doivent provenir de la notice du modèle approuvé.",
    "La maîtrise industrielle commence avec une nomenclature précise : chaque poids, quantité, finition, logo, rack et conditionnement. L’échantillon fixe le niveau de brillance, la gravure, la prise en main et l’ajustement dans les supports. La production peut ensuite contrôler matière, usinage, liaison, surface, masse, marquage et montage selon un plan défini. L’inspection avant expédition rapproche le lot de l’échantillon et de la commande. Pour l’export, les surfaces polies sont séparées, immobilisées et protégées contre l’humidité. La résistance des cartons, le repérage des colis, les accessoires et la notice sont vérifiés avant chargement.",
    "La comparaison des offres doit porter sur un périmètre identique. Il faut vérifier le nombre de pièces, le rack, les pièces de rechange, l’outillage, les cartons, les palettes, le poids brut, le volume, la garantie et le traitement des écarts. L’acheteur demande comment une masse hors tolérance, un marquage endommagé ou un colis manquant sera géré. Il contrôle également avec ses spécialistes locaux les obligations de marquage, de notice et d’importation. Le transport ne s’arrête pas au port : déchargement, manutention, accès au bâtiment et montage doivent être anticipés. Une demande structurée rend les prix, délais et responsabilités réellement comparables."
  ],
  de: [
    "Dieses Beispiel übersetzt eine sichtbare Gerätekombination in einen belastbaren Beschaffungsprozess. Das Bild eignet sich, um Gestaltung, Ordnung und beabsichtigte Nutzung abzustimmen, reicht aber nicht als technische Vorgabe. Im B2B-Projekt sollten sichtbare Merkmale und vom Lieferanten zu bestätigende Daten getrennt erfasst werden. So wird aus „wie auf dem Foto“ eine prüfbare Referenz aus Zeichnung, Datenblatt, Stückliste, Freigabemuster und Abnahmekriterien. Einkauf, Betreiber und Qualitätsprüfung arbeiten damit auf derselben Grundlage. Änderungen an Griff, Kennzeichnung, Oberfläche oder Gestell müssen vor der Serie dokumentiert und erneut freigegeben werden, statt erst bei der Warenannahme aufzufallen.",
    "Die Anlagenanforderung wird aus Nutzern und Betriebsmodell abgeleitet. Ein Hotel benötigt eine verständliche, leicht kontrollierbare Station mit moderater Belegung. Ein Personal-Training-Studio bewertet feine Lastsprünge und einen schnellen Zugriff während betreuter Einheiten. Ein stärker frequentierter Club muss parallele Nutzung, zusätzliche Paare und Ersatzbeschaffung modellieren. Projektteams sollten Übungen, Zielgruppen, Stoßzeiten und häufige Gewichte auflisten. Werden mittlere Lasten gleichzeitig gebraucht, sind doppelte Paare oft sinnvoller als selten genutzte Randgrößen. Diese Entscheidung verändert Stückliste, Gestellkapazität und Stellfläche. Auch Reinigung, Aufsicht, Wartungsverantwortung und der gewünschte Zeitraum für Nachlieferungen gehören in das Anforderungsprofil.",
    "Hanteln und Ständer werden einzeln spezifiziert und anschließend als System geprüft. Für die Hanteln gehören Nenngewicht, Toleranz, Abmessungen, feste Konstruktion, Griffdurchmesser, Rändelung, Kopfverbindung, Kennzeichnung und Oberfläche in die Unterlagen. Beim Gestell sind Werkstoff, beladene Maße, Tragfähigkeit, Aufnahmen, Standfläche, Stellfüße, Schrauben und Montage festzulegen. Eine Passprobe mit allen Gewichten zeigt, ob die Hanteln sicher aufliegen, Hände genügend Platz haben und polierte Flächen nicht aneinanderreiben. Zusätzlich sollte geprüft werden, wie sich das Gestell bei einseitiger oder teilweiser Beladung verhält. Erst diese Systemprüfung belegt die praktische Kompatibilität.",
    "Die Auswahl von Chromhanteln ist eine Abwägung aus Raumeindruck, Beanspruchung und Pflege. Die kompakte Bauform und klare Gewichtsanzeige passen zu gepflegten Hotel- und Studioumgebungen. Bei hoher Luftfeuchte, aggressiven Reinigern oder unsachgemäßem Ablegen muss die konkrete Oberflächenausführung besonders kritisch geprüft werden. Der Bereich von 1 bis 10 kg unterstützt kleine Steigerungen, Aufwärmen und Nebenübungen; für fortgeschrittenes Krafttraining bleibt er ein Ergänzungsmodul. Das X-Gestell spart Wandlänge, nicht jedoch den gesamten Bedienraum. Im Plan sind Greifzone, hervorstehende Hanteln, Türschwenkbereiche, Spiegel, Bänke und Fluchtwege zu berücksichtigen.",
    "Der betriebliche Nutzen entsteht durch eindeutig zugeordnete Ablageplätze und schnellen Zugriff. Trainer können Lasten wechseln, ohne Scheiben umzubauen. Hotelgäste erkennen die Reihenfolge selbstständig. In größeren Anlagen hält eine eigene Leichtzone den Hauptbereich für schwere Hanteln frei. Gleichzeitig sieht das Personal, ob ein Paar fehlt oder falsch abgelegt wurde. Die Station ersetzt dennoch kein vollständiges Trainingskonzept. Benötigte Bank, Boden, Bewegungsfläche, Nutzerhinweise und zusätzliche Lasten sind separat zu definieren. Für einen Händler kommen außerdem Ersatzteilfähigkeit, einheitliche Nachbestellung, deutschsprachige Unterlagen und ein nachvollziehbarer Gewährleistungsprozess hinzu. Diese Faktoren bestimmen die langfristige Lieferfähigkeit stärker als ein einmalig günstiger Einkaufspreis.",
    "Ein dokumentierter Kontrollplan erhöht Zuverlässigkeit und Lebensdauer. Täglich oder nach festgelegtem Intervall werden Vollständigkeit, Lesbarkeit, Kopfverbindung, Griff, Aufnahmen, Schrauben, Stellfüße und Standfestigkeit geprüft. Bei Spiel, scharfer Beschädigung oder Verformung wird das Teil bis zur Klärung gesperrt. Reinigungsmittel müssen zur bestätigten Oberfläche passen; Flüssigkeit darf nicht in Verbindungen stehen bleiben, anschließend wird getrocknet. Ein Fehlerprotokoll mit Datum, Foto und betroffener Gewichtsgröße unterstützt Ursachenanalyse und Ersatzteilzuordnung. Es unterscheidet normalen Verschleiß, Fehlbedienung, Montagefehler und Serienabweichung. Prüfintervall, Drehmoment und zulässige Pflegemittel sollten in der freigegebenen Anleitung stehen.",
    "Herstellerseitig beginnt Prozesssicherheit mit einer vollständigen Auftragsstückliste. Sie nennt jede Gewichtsgröße, Stück- oder Paarzahl, Gestell, Logo, Oberfläche, Zubehör und Verpackung. Das Freigabemuster legt Glanz, Gravur, Griffgefühl und Passung fest. In der Serie können Materialeingang, Bearbeitung, Verbindung, Oberfläche, Masse, Kennzeichnung und Montage anhand definierter Prüfpunkte überwacht werden. Vor dem Versand wird der Lieferumfang gegen Bestellung, Muster und Packliste geprüft. Für den Export sind polierte Teile zu trennen und gegen Bewegung und Feuchte zu schützen. Kartonfestigkeit, Beschlagkennzeichnung, Montageanleitung, Palettierung und Bruttogewichte müssen zur gewählten Transportkette passen. Lieferkompetenz zeigt sich in diesen Nachweisen und im Umgang mit Abweichungen.",
    "Angebote lassen sich nur vergleichen, wenn ihr Umfang gleich ist. Der Käufer prüft Anzahl der Einzelteile, Gestell, Ersatzteile, Werkzeug, Kartons, Paletten, Brutto- und Volumendaten, Garantie und Reklamationsweg. Er fragt, wie eine Gewichtstoleranz überschreitende Hantel, eine beschädigte Markierung oder ein fehlender Karton behandelt wird. Für den Zielmarkt sind Kennzeichnung, Anleitung, Produktsicherheit und Importpflichten mit zuständigen Fachstellen zu klären. Zur Logistik gehören auch Entladung, innerbetrieblicher Transport, Türmaße und Montageort. Eine strukturierte Anfrage mit Zeichnung, Mengenmatrix, Prüfplan und gewünschtem Liefertermin macht Preis, Lieferzeit und Verantwortung nachvollziehbar und reduziert kostenintensive Änderungen kurz vor Produktionsende."
  ],
  it: [
    "Il caso deve funzionare come riferimento verificabile per l’acquisto, non come semplice immagine promozionale. La fotografia allinea le parti su aspetto, ordine e destinazione d’uso, ma non definisce materiale, tolleranza o capacità. In un progetto B2B conviene distinguere ciò che è osservabile dai dati che il produttore deve confermare. La frase “come in foto” viene così sostituita da disegno quotato, scheda, distinta, campione approvato e criteri di collaudo. Ufficio acquisti, gestore e controllo qualità possono seguire la stessa versione. Qualunque modifica a impugnatura, marcatura, finitura o supporto viene registrata prima della produzione, evitando contestazioni tardive.",
    "I requisiti cambiano con il tipo di struttura. Un hotel privilegia una postazione intuitiva e facile da controllare; uno studio personal valuta piccoli incrementi e rapidità durante le sessioni; una palestra affollata deve calcolare uso simultaneo, doppie coppie e tempi di reintegro. Il responsabile raccoglie esercizi, profilo degli utenti, picchi e pesi più richiesti. Se le misure centrali vengono usate insieme, duplicarle può offrire più valore che estendere la gamma verso carichi poco utilizzati. La matrice finale determina quantità e capacità della rastrelliera. Nel brief entrano anche pulizia, supervisione, responsabilità manutentiva e disponibilità futura dello stesso modello.",
    "Manubri e rastrelliera vanno qualificati separatamente e poi verificati come sistema. Per i manubri si indicano peso nominale e tolleranza, dimensioni, costruzione fissa, diametro e zigrinatura, unione delle teste, marcatura e superficie. Per il rack si indicano materiale, ingombro a pieno carico, portata, alloggiamenti, base, piedini, ferramenta e montaggio. Una prova con tutte le coppie controlla appoggio, spazio per le mani e contatti che potrebbero segnare il cromo. Occorre osservare anche il comportamento con carico parziale o sbilanciato. Solo questa prova dimostra che prodotti formalmente compatibili funzionano bene nell’uso quotidiano.",
    "Il cromato si sceglie valutando immagine, ambiente e intensità d’uso. La forma compatta e la lettura chiara dei pesi possono valorizzare hotel e studi curati. Umidità, detergenti non idonei e ricollocazione brusca richiedono invece maggiore attenzione alla finitura. La progressione 1–10 kg è utile per riscaldamento, spalle, esercizi accessori e utenti che richiedono piccoli passaggi; non sostituisce una gamma pesante. Il rack a X riduce lo sviluppo lungo la parete, ma il layout deve comprendere spazio di presa, elementi sporgenti, porte, specchi, panche e percorsi di sicurezza. L’efficienza si misura sulla zona operativa, non sulla sola base.",
    "Il valore commerciale deriva da ordine e accesso immediato. Il trainer cambia carico senza regolare meccanismi; l’ospite comprende la sequenza; il club può separare il lavoro leggero dalla fila principale. Il personale individua rapidamente una coppia mancante. La stazione deve comunque far parte di un’offerta coerente, con panca, pavimento, spazio di movimento, istruzioni e carichi complementari. Per distributori e rivenditori italiani contano anche continuità estetica dei riordini, disponibilità ricambi, manuale, garanzia e gestione dell’assistenza. Un assortimento ben presentato ma non reintegrabile può creare più problemi di una scelta leggermente meno appariscente ma sostenuta nel tempo.",
    "Una procedura di controllo protegge utenti e prodotto. Si verificano completezza, leggibilità, fissaggio delle teste, impugnature, sedi, viti, piedini e stabilità. Una parte allentata, tagliente o deformata viene esclusa fino all’analisi. La pulizia usa un prodotto compatibile in quantità controllata e termina con asciugatura; non si lascia liquido nelle giunzioni. Registrare data, foto e peso coinvolto facilita il confronto con il fornitore e l’invio del ricambio corretto. Lo storico distingue usura, uso improprio, montaggio e difetto ripetuto. Frequenza, coppie di serraggio e sostanze vietate devono essere definite nel manuale del modello approvato.",
    "Dal punto di vista produttivo, la qualità parte da una distinta chiusa per peso, coppie, rack, logo, finitura, accessori e imballo. Il campione fissa brillantezza, incisione, sensazione della presa e accoppiamento. La serie può essere controllata su materia prima, lavorazione, unione, superficie, massa, marcatura e montaggio. Prima della spedizione, lotto, ordine e packing list vengono riconciliati. Per l’export le superfici lucide devono essere separate e bloccate, con protezione dall’umidità. Resistenza dei cartoni, etichette, ferramenta, istruzioni, pallet e pesi lordi devono corrispondere al trasporto previsto. L’esperienza del fornitore si misura nella tracciabilità e nella gestione delle non conformità.",
    "Il confronto economico deve usare lo stesso perimetro. Si controllano pezzi effettivi, rastrelliera, ricambi, utensili, cartoni, pallet, peso lordo, volume, garanzia e procedura di reclamo. Il buyer chiede come verranno gestiti un peso fuori tolleranza, una marcatura rovinata o un collo mancante. Marcatura, istruzioni, sicurezza e obblighi di importazione vanno verificati con professionisti del mercato di destinazione. Anche scarico, movimentazione, accessi e montaggio incidono sul progetto. Una richiesta con matrice dei pesi, quantità, disegno, livello di ispezione, packaging e data obiettivo rende confrontabili prezzo e tempi e riduce le revisioni in fase avanzata."
  ],
  sv: [
    "Det här exemplet ska användas som ett verifierbart inköpsunderlag, inte som en fristående inspirationsbild. Fotot kan samordna önskat utseende, ordning och användning, men det bekräftar inte material, tolerans eller lastkapacitet. I en professionell upphandling skiljs observerbara egenskaper från leverantörens bindande uppgifter. Formuleringen ”som på bilden” ersätts med måttsatt ritning, datablad, stycklista, godkänt prov och kontrollkriterier. Då arbetar inköp, drift och inspektör mot samma version. Ändringar av grepp, märkning, yta eller ställ dokumenteras och godkänns före serien, vilket passar nordiska projekt där spårbarhet och tydlig ansvarsfördelning värderas högt.",
    "Kravbilden måste spegla verksamheten. Ett hotellgym behöver enkel användning, lugn visuell miljö och lätt tillsyn. En PT-studio behöver små belastningssteg och snabb åtkomst under coachade pass. En klubb med fler samtidiga användare behöver modellera dubbletter, toppbelastning och framtida komplettering. Projektgruppen listar övningar, användarprofiler, samtidighet och vanligaste vikter. Om flera tränar med mellanvikterna samtidigt ger extra par ofta större nytta än sällan använda yttervikter. Den verkliga matrisen styr ställets kapacitet och golvytan. Kraven bör också omfatta städmetod, ansvar för kontroll, önskad reservdelsservice och hur länge samma modell ska kunna återbeställas.",
    "Hantlar och ställ specificeras var för sig och provas sedan tillsammans. För hantlarna dokumenteras nominell vikt, tolerans, mått, fast konstruktion, greppdiameter, räffling, huvudinfästning, märkning och ytfinish. För stället dokumenteras material, lastade mått, kapacitet, hållare, bas, justerfötter, infästningar och montering. Ett fullt passningsprov visar om varje par ligger stabilt, om händerna får plats och om polerade ytor riskerar kontakt. Stället bör även provas när vikter saknas på ena sidan, eftersom verklig användning sällan innebär helt symmetrisk last. Den kombinerade kontrollen är viktigare än två separata produktblad som aldrig verifierats mot varandra.",
    "Krom väljs efter miljö och drift, inte bara efter ett exklusivt uttryck. Den kompakta formen och tydliga viktavläsningen passar välskötta hotell och mindre studior. Hög luftfuktighet, aggressiva rengöringsmedel och hård återplacering kräver däremot särskild granskning av ytan. Serien 1–10 kg stödjer små progressioner, uppvärmning och kompletterande övningar men är inte en komplett styrkelinje för alla medlemmar. X-stället sparar vägglängd, medan driftzonen fortfarande måste rymma användarens grepp och de utskjutande hantlarna. Dörrar, speglar, bänkar, städvägar och utrymning markeras i en skalenlig plan innan beställning.",
    "Det kommersiella värdet ligger i förutsägbar ordning och direkt åtkomst. Coachen byter snabbt belastning, hotellgästen förstår sorteringen och en större klubb kan avlasta sin tunga hantelrad. Personalen ser också när ett par är borta. Stationen behöver ändå kopplas till ett komplett användningsscenario med bänk, golv, rörelseyta, instruktioner och kompletterande belastningar. För en nordisk distributör är konsekventa återbeställningar, reservdelar, manual, garanti och dokumenterad reklamationsprocess centrala. Långsiktig leveranssäkerhet kan vara viktigare än lägsta inköpspris, särskilt när samma visuella serie ska användas i flera anläggningar eller vid senare utbyggnad.",
    "En enkel men dokumenterad rutin skyddar utrustningen. Kontrollera par, märkning, huvudinfästning, grepp, hållare, skruvar, fötter och stabilitet enligt fast intervall. Utrustning med glapp, vass skada eller deformation tas ur bruk. Rengör med godkänt medel, undvik vätska i fogar och torka ytan. Ett avvikelseregister med datum, bild, vikt och plats ger leverantören användbar information och hjälper verksamheten skilja normalt slitage från felhantering, montageproblem eller seriefel. Manualen för den godkända modellen ska ange intervall, eventuella åtdragningsmoment och förbjudna kemikalier. Rutinen bör ingå i anläggningens ordinarie arbetsmiljö- och underhållssystem.",
    "Tillverkarens kontroll börjar med en låst stycklista för varje vikt, antal par, ställ, logotyp, finish, tillbehör och emballage. Det godkända provet fastställer glans, gravyr, greppkänsla och passning. I produktionen kontrolleras material, bearbetning, sammanfogning, yta, massa, märkning och montering enligt avtalad plan. Före leverans stäms parti, order och packlista av. Polerade delar separeras och fixeras för export, med fuktskydd där transportkedjan kräver det. Kartongstyrka, kollimärkning, beslag, instruktion, pall och bruttovikt verifieras. Leverantörens kapacitet bedöms genom dessa konkreta underlag och hur avvikelser hanteras, inte genom generella påståenden.",
    "Jämför offerter med samma omfattning. Kontrollera exakt antal delar, ställ, reservdelar, verktyg, kartonger, pallar, brutto- och volymdata, garanti och reklamationsflöde. Fråga hur en vikt utanför tolerans, skadad märkning eller saknat kolli hanteras. Produktmärkning, instruktioner, kemikaliekrav och importansvar granskas med relevanta lokala specialister. Planera även lossning, intern transport, dörrmått och montering på plats. En tydlig förfrågan innehåller viktmatris, mängd, ritning, provkrav, inspektionsnivå, emballage och önskat leveransfönster. Då kan pris, ledtid och ansvar jämföras utan att kvalitet reduceras till en allmän etikett."
  ],
  vi: [
    "Sử dụng hình ảnh thật để thống nhất về hình thức, cách sắp xếp và mục đích dự kiến, nhưng không thay thế bản vẽ hay thông số. Trong mua hàng B2B, nên tách rõ đặc điểm quan sát được và dữ liệu nhà máy phải xác nhận. Cụm từ “giống ảnh” được thay bằng bản vẽ kích thước, bảng thông số, danh mục, mẫu duyệt và tiêu chí kiểm tra. Bộ phận mua hàng, vận hành và kiểm định dùng cùng một phiên bản. Mọi thay đổi về tay cầm, dấu kg, bề mặt hoặc giá phải được ghi nhận trước khi sản xuất hàng loạt.",
    "Yêu cầu khác nhau giữa khách sạn, studio PT và phòng gym đông người. Khách sạn thường ưu tiên dễ hiểu, gọn và dễ kiểm soát. Studio cần bước tăng nhỏ, đổi tạ nhanh trong buổi hướng dẫn. Phòng gym thương mại phải tính số người dùng đồng thời, mức tạ cần thêm cặp và khả năng bổ sung sau này. Chủ dự án nên liệt kê bài tập, nhóm người dùng, giờ cao điểm và mức tạ thường dùng. Nếu nhiều khách cùng cần tạ trung bình, thêm cặp có thể hữu ích hơn mở rộng đến mức ít dùng. Ma trận này quyết định số lượng, sức chứa của giá và diện tích vận hành.",
    "Tạ và giá được xác định riêng rồi thử như một hệ thống. Với tạ, cần ghi khối lượng danh định, sai số, kích thước, kết cấu cố định, đường kính và độ nhám tay cầm, liên kết đầu tạ, dấu và lớp hoàn thiện. Với giá, cần ghi vật liệu, kích thước khi đầy tải, tải trọng, vị trí đỡ, chân đế, chân cân bằng, bu-lông và cách lắp. Thử toàn bộ dải giúp kiểm tra tạ có nằm chắc, tay có đủ chỗ và bề mặt có cọ xát hay không. Cũng phải quan sát độ ổn định khi lấy tạ lệch một bên vì đây là tình trạng thực tế thường gặp.",
    "Mạ crôm phải phù hợp môi trường chứ không chỉ tạo cảm giác cao cấp. Hình dáng gọn và dấu kg rõ có thể phù hợp khách sạn hoặc studio được bảo dưỡng tốt. Độ ẩm cao, hóa chất mạnh và đặt tạ mạnh đòi hỏi đánh giá kỹ lớp bề mặt. Dải 1–10 kg hỗ trợ khởi động, vai, tay và tăng tải nhỏ; nó không thay thế dải tạ nặng cho phòng gym sức mạnh. Giá chữ X tiết kiệm chiều dài tường nhưng vùng sử dụng vẫn cần chỗ đứng, lấy và trả tạ. Bản vẽ mặt bằng phải thể hiện cửa, gương, ghế, thiết bị gần đó, lối vệ sinh và lối thoát.",
    "Giá trị vận hành đến từ việc dễ tìm và dễ trả đúng vị trí. Huấn luyện viên đổi tải nhanh, khách sạn có trạm tự hiểu, còn câu lạc bộ lớn tách bài nhẹ khỏi dãy tạ chính. Nhân viên cũng thấy ngay khi thiếu một cặp. Tuy nhiên, trạm cần gắn với kịch bản đầy đủ gồm ghế, sàn, vùng chuyển động, hướng dẫn và tải bổ sung. Với nhà nhập khẩu hoặc phân phối tại Việt Nam, cần xem khả năng đặt lại cùng kiểu, phụ tùng, tài liệu, bảo hành và xử lý khiếu nại. Nguồn cung ổn định lâu dài đôi khi quan trọng hơn giá mua thấp của lô đầu tiên.",
    "Quy trình kiểm tra ngắn nhưng có ghi chép sẽ bảo vệ thiết bị. Theo lịch, nhân viên kiểm tra đủ cặp, dấu kg, liên kết đầu tạ, tay cầm, chỗ đỡ, bu-lông, chân và độ ổn định. Thiết bị lỏng, sắc hoặc biến dạng phải ngừng sử dụng. Dùng chất vệ sinh được chấp thuận, không để nước trong khe và lau khô. Nhật ký ghi ngày, ảnh, mức tạ và vị trí giúp nhà cung cấp phân tích và gửi đúng linh kiện. Nó cũng phân biệt hao mòn bình thường, sử dụng sai, lắp sai và lỗi lặp lại. Hướng dẫn của mẫu duyệt phải nêu chu kỳ, lực siết nếu có và hóa chất không được dùng.",
    "Kiểm soát sản xuất bắt đầu từ danh mục khóa theo từng mức kg, số cặp, giá, logo, bề mặt, phụ kiện và bao bì. Mẫu duyệt xác nhận độ bóng, khắc dấu, cảm giác cầm và độ khớp. Trong sản xuất có thể kiểm tra vật liệu, gia công, liên kết, bề mặt, khối lượng, dấu và lắp ráp theo kế hoạch. Trước khi giao, lô hàng được đối chiếu với đơn và packing list. Khi xuất khẩu, bề mặt bóng phải được ngăn cách, cố định và chống ẩm phù hợp. Thùng, nhãn kiện, phụ kiện, hướng dẫn, pallet và trọng lượng tổng cần khớp tuyến vận chuyển. Năng lực nhà máy được chứng minh bằng hồ sơ và cách xử lý sai lệch.",
    "Khi so sánh báo giá, cần dùng cùng phạm vi. Kiểm tra số món thực tế, giá đỡ, phụ tùng, dụng cụ, thùng, pallet, trọng lượng tổng, thể tích, bảo hành và quy trình khiếu nại. Hỏi cách xử lý tạ sai số, dấu hỏng hoặc thiếu kiện. Yêu cầu về nhãn, hướng dẫn, an toàn và nhập khẩu cần được xác nhận với đơn vị chuyên môn tại thị trường đích. Cũng phải tính dỡ hàng, di chuyển nội bộ, kích thước cửa và lắp tại chỗ. Một RFQ rõ gồm ma trận kg, số lượng, bản vẽ, mẫu, mức kiểm tra, bao bì và thời gian mong muốn giúp so sánh giá, tiến độ và trách nhiệm chính xác."
  ],
  ko: [
    "이 사례의 목적은 한 장의 실제 사진을 검증 가능한 구매 자료로 바꾸는 데 있습니다. 사진은 디자인 방향, 중량 배열, 보관 방식과 예상 용도를 설명하지만 소재, 허용오차나 랙 정격을 보증하지 않습니다. 상업용 구매에서는 눈으로 확인되는 특징과 제조사가 문서로 확정해야 하는 항목을 분리해야 합니다. “사진과 동일”이라는 표현 대신 치수 도면, 제품 사양서, 품목표, 승인 샘플과 검사 기준을 사용합니다. 그러면 구매 담당자, 시설 운영자와 검사자가 같은 기준으로 견적, 샘플, 양산품과 선적품을 비교할 수 있습니다. 손잡이, 각인, 표면 또는 거치부 변경은 생산 전에 기록하고 다시 승인해야 합니다.",
    "시설 요구사항은 운영 형태와 동시 사용자 수에서 시작합니다. 호텔 피트니스는 직관적인 사용, 정돈된 인상과 간단한 관리가 중요합니다. PT 스튜디오는 코칭 중 빠른 중량 교체와 세밀한 단계가 중요합니다. 이용자가 많은 상업 시설은 인기 중량의 추가 쌍, 피크 시간과 추후 보충 가능성을 계산해야 합니다. 프로젝트팀은 주요 운동, 회원 수준, 동시 사용 인원과 자주 선택되는 중량을 표로 만듭니다. 중간 중량을 여러 명이 함께 사용한다면 거의 사용하지 않는 고중량을 추가하는 것보다 같은 중량을 복수로 준비하는 편이 효율적일 수 있습니다. 최종 수량은 랙 용량과 실제 설치 면적에 반영되어야 합니다.",
    "덤벨과 랙은 각각 사양을 정한 뒤 하나의 시스템으로 시험합니다. 덤벨 문서에는 표시 중량, 허용오차, 전체 치수, 고정식 구조, 그립 지름과 널링, 헤드 결합, 표시 방식과 마감이 포함됩니다. 랙 문서에는 프레임 소재, 적재 상태 치수, 허용하중, 거치 형상, 베이스, 조절발, 체결부와 조립 방법을 기재합니다. 전 중량을 실제로 올려 각 덤벨이 안정적으로 놓이는지, 손가락 공간이 충분한지, 크롬 면끼리 닿는지 확인합니다. 한쪽 덤벨만 여러 개 빠진 상태에서도 흔들림이나 기울어짐이 없는지 봐야 합니다. 개별 사양의 충족만으로 실제 호환성을 대신할 수 없습니다.",
    "크롬 타입은 외관뿐 아니라 환경과 관리 수준을 고려해 선택합니다. 조밀한 형태와 명확한 kg 표시는 관리가 잘 되는 호텔이나 소형 스튜디오에 어울릴 수 있습니다. 높은 습도, 강한 세정제와 거친 재거치는 표면 수명을 줄일 수 있으므로 확정된 마감의 관리 조건을 확인해야 합니다. 1–10kg 구성은 워밍업, 어깨·팔 운동, 보조 운동과 작은 증가폭에 적합하지만 모든 근력 회원을 위한 전체 라인은 아닙니다. X형 랙은 벽면 길이를 줄이지만 사용자가 서서 꺼내는 공간은 필요합니다. 출입문, 거울, 벤치, 다른 기구와 피난 동선을 축척 도면에서 검토해야 합니다.",
    "운영상 가치는 정해진 위치와 즉시 접근에서 나옵니다. 트레이너는 조절 장치 없이 빠르게 부하를 변경하고, 호텔 이용자는 중량 순서를 스스로 이해하며, 대형 클럽은 가벼운 보조 운동을 메인 덤벨 존에서 분리할 수 있습니다. 직원은 누락된 쌍을 바로 찾을 수 있습니다. 다만 이 스테이션만으로 전체 프로그램이 완성되지는 않습니다. 벤치, 바닥, 동작 공간, 안내와 추가 중량을 함께 정해야 합니다. 한국 시장의 수입사와 유통사는 동일 디자인의 재주문, 교체 부품, 한글 안내, 보증 범위와 A/S 처리도 확인해야 합니다. 초기 가격보다 지속적인 공급과 정확한 응답이 더 큰 운영 가치를 만들 수 있습니다.",
    "점검은 짧아도 기록으로 남겨야 합니다. 정한 주기에 따라 쌍의 완전성, kg 표시, 헤드 결합, 그립, 거치부, 볼트, 조절발과 랙 안정성을 확인합니다. 풀림, 날카로운 손상이나 변형이 있으면 즉시 사용을 중지합니다. 승인된 세정제를 소량 사용하고 연결부에 액체가 고이지 않게 한 뒤 건조합니다. 날짜, 사진, 중량과 발생 위치를 기록하면 공급사가 원인을 분석하고 맞는 부품을 보내기 쉽습니다. 기록은 정상 마모, 부적절한 사용, 조립 오류와 반복되는 생산 문제를 구분하는 데도 도움이 됩니다. 검사 주기, 체결 토크와 금지 약품은 승인 모델의 관리 문서에 포함되어야 합니다.",
    "제조 관리의 출발점은 중량별 수량, 랙, 로고, 마감, 부속품과 포장을 포함한 확정 품목표입니다. 승인 샘플은 광택, 각인, 그립 감각과 랙 맞춤 상태를 고정합니다. 양산 중에는 원자재, 가공, 결합, 표면, 중량, 표시와 조립을 합의된 계획에 따라 검사할 수 있습니다. 선적 전에는 생산 로트, 주문서와 포장명세서를 대조합니다. 수출 포장에서는 광택 면을 분리하고 움직이지 않게 고정하며 운송 조건에 맞춰 방습합니다. 상자 강도, 박스 표시, 하드웨어 라벨, 조립 안내, 팔레트와 총중량도 확인합니다. 공급 능력은 일반적인 홍보 문구보다 이런 기록과 부적합 처리 방식으로 판단합니다.",
    "견적 비교는 동일한 범위를 기준으로 해야 합니다. 실제 제품 수, 랙, 예비 부품, 공구, 박스, 팔레트, 총중량, 부피, 보증과 클레임 절차를 확인합니다. 허용오차를 벗어난 중량, 손상된 각인 또는 누락된 박스를 어떻게 처리하는지 질문합니다. 제품 표시, 안내, 안전과 수입 의무는 대상 시장의 전문 기관과 검토해야 합니다. 항구 도착 이후의 하역, 실내 이동, 출입문 크기와 설치 위치도 비용과 일정에 영향을 줍니다. 중량 매트릭스, 수량, 도면, 샘플, 검사 수준, 포장과 목표 납기를 포함한 RFQ는 공급사의 가격, 리드타임과 책임을 같은 기준에서 비교하게 합니다."
  ],
  pl: [
    "Celem tego przykładu jest przekształcenie prawdziwej fotografii w weryfikowalny materiał zakupowy. Zdjęcie uzgadnia wygląd, porządek i przewidywane zastosowanie, lecz nie potwierdza materiału, tolerancji ani nośności. W zakupach B2B warto oddzielić cechy widoczne od danych, które producent ma potwierdzić dokumentem. Określenie „jak na zdjęciu” zastępują rysunek wymiarowy, karta, lista części, zatwierdzona próbka i kryteria odbioru. Dzięki temu zakupy, operator i inspektor porównują ofertę, próbkę, serię oraz wysyłkę według tej samej wersji. Zmiana uchwytu, oznaczenia, powierzchni lub stojaka powinna zostać zapisana i ponownie zaakceptowana przed produkcją.",
    "Wymagania obiektu wynikają z modelu pracy. Hotel potrzebuje prostej, estetycznej stacji łatwej do kontroli. Studio trenerskie ocenia małe skoki obciążenia i szybki dostęp podczas zajęć. Klub o dużym ruchu musi policzyć użytkowników jednoczesnych, dodatkowe pary i możliwość uzupełnienia. Zespół projektu sporządza listę ćwiczeń, profili, godzin szczytu i najczęściej wybieranych wag. Jeśli kilka osób używa jednocześnie środkowych obciążeń, duplikaty mogą przynieść większą wartość niż rzadko wykorzystywane skrajne rozmiary. Ta matryca wyznacza liczbę sztuk, pojemność stojaka i powierzchnię. W briefie należy również określić sprzątanie, nadzór, odpowiedzialność za serwis i oczekiwany okres dostępności modelu.",
    "Hantle i stojak specyfikuje się osobno, a następnie sprawdza jako system. Dla hantli podaje się masę nominalną, tolerancję, wymiary, stałą konstrukcję, średnicę i radełkowanie chwytu, połączenie głowic, oznaczenie oraz wykończenie. Dla stojaka podaje się materiał, wymiary z pełnym obciążeniem, udźwig, podpory, podstawę, stopki, śruby i montaż. Próba z pełnym zakresem pokazuje, czy każdy ciężar leży pewnie, dłonie mają miejsce, a polerowane powierzchnie nie ocierają się. Należy również sprawdzić stabilność przy częściowym i jednostronnym rozładowaniu. Dopiero taka próba potwierdza praktyczną zgodność obu produktów.",
    "Chrom wybiera się po ocenie wnętrza, wilgotności i intensywności obsługi, a nie wyłącznie ze względu na wygląd premium. Zwarta forma i czytelne oznaczenia pasują do zadbanych hoteli oraz studiów. Silne środki, wilgoć i gwałtowne odkładanie wymagają dokładniejszej oceny powierzchni. Zakres 1–10 kg wspiera rozgrzewkę, barki, ćwiczenia dodatkowe i małe progresje, ale nie tworzy pełnej strefy siłowej. Stojak X ogranicza długość przy ścianie, jednak powierzchnia użytkowa obejmuje osobę i wystające hantle. Na planie trzeba uwzględnić drzwi, lustra, ławki, inne urządzenia, trasę sprzątania i drogę ewakuacyjną.",
    "Wartość operacyjna wynika z szybkiego dostępu i jednoznacznych miejsc odkładania. Trener zmienia obciążenie bez regulacji mechanizmu, gość hotelowy rozumie kolejność, a duży klub oddziela lekkie ćwiczenia od głównej strefy. Personel od razu widzi brak pary. Stacja musi jednak działać w pełnym scenariuszu z ławką, podłogą, przestrzenią ruchu, instrukcją i dodatkowymi ciężarami. Dla polskiego importera lub dystrybutora ważne są także zgodność kolejnych partii, części, dokumentacja, gwarancja i procedura reklamacyjna. Stabilność dostaw i możliwość odtworzenia wyglądu przy rozbudowie bywają istotniejsze niż najniższa cena pierwszej partii.",
    "Krótka, udokumentowana kontrola chroni sprzęt i użytkownika. Według harmonogramu sprawdza się kompletność, oznaczenia, połączenie głowic, chwyty, podpory, śruby, stopki i stabilność. Element z luzem, ostrym uszkodzeniem lub deformacją wycofuje się do wyjaśnienia. Powierzchnię czyści się zatwierdzonym środkiem, nie pozostawia cieczy w połączeniach i osusza. Rejestr z datą, zdjęciem, wagą i miejscem pomaga dostawcy ustalić przyczynę oraz dobrać część. Pozwala odróżnić zużycie, niewłaściwe użytkowanie, błąd montażu i powtarzalną niezgodność. Instrukcja zatwierdzonego modelu powinna określić częstotliwość, momenty dokręcania i niedozwolone preparaty.",
    "Kontrola producenta zaczyna się od zamkniętej listy według wag, par, stojaka, logo, powierzchni, akcesoriów i opakowania. Próbka ustala połysk, grawer, odczucie chwytu i dopasowanie. W produkcji kontroluje się materiał, obróbkę, łączenie, powierzchnię, masę, oznaczenie i montaż zgodnie z uzgodnionym planem. Przed wysyłką porównuje się partię, zamówienie i packing list. Polerowane części są rozdzielone, unieruchomione i zabezpieczone przed wilgocią. Sprawdza się kartony, oznaczenia, okucia, instrukcje, palety i masy brutto. Zdolność dostawcy ocenia się na podstawie takich zapisów oraz sposobu obsługi niezgodności, a nie ogólnych deklaracji.",
    "Oferty trzeba porównywać w identycznym zakresie. Należy potwierdzić liczbę elementów, stojak, części zapasowe, narzędzia, kartony, palety, masę brutto, objętość, gwarancję i ścieżkę reklamacji. Kupujący pyta, jak zostanie rozwiązana waga poza tolerancją, uszkodzone oznaczenie lub brak paczki. Oznakowanie, instrukcje, bezpieczeństwo i obowiązki importowe weryfikuje się z odpowiednimi specjalistami rynku docelowego. Plan obejmuje też rozładunek, transport wewnętrzny, szerokość drzwi i montaż. Jasne zapytanie zawiera matrycę wag, ilości, rysunek, próbkę, poziom inspekcji, opakowanie i termin, dzięki czemu cena i odpowiedzialność są rzeczywiście porównywalne."
  ],
  ar: [
    "الغرض من هذه الحالة هو تحويل صورة حقيقية إلى مرجع شراء يمكن التحقق منه، وليس استخدام الصورة كدعاية منفصلة. تساعد الصورة على الاتفاق حول الشكل والترتيب والغرض المتوقع، لكنها لا تؤكد الخامة أو السماحية أو قدرة التحميل. في الشراء المهني يجب فصل الخصائص المرئية عن البيانات التي يلتزم المصنع بتأكيدها. تُستبدل عبارة «مثل الصورة» برسم ذي أبعاد، ومواصفة، وقائمة مكونات، وعينة معتمدة، ومعايير فحص. بهذه الطريقة تعمل فرق المشتريات والتشغيل والتفتيش وفق النسخة نفسها. أي تغيير في المقبض أو العلامة أو السطح أو الحامل يجب تسجيله واعتماده قبل الإنتاج، وليس بعد وصول الشحنة.",
    "تختلف متطلبات المنشأة حسب نموذج التشغيل. فندق صغير يحتاج محطة سهلة الفهم ومرتبة وسهلة المراقبة. استوديو التدريب يحتاج خطوات وزن دقيقة ووصولاً سريعاً أثناء الجلسة. النادي مرتفع الاستخدام يحتاج حساب المستخدمين المتزامنين والأزواج الإضافية وإمكانية إعادة الطلب. يسجل فريق المشروع التمارين والفئات وساعات الذروة والأوزان الأكثر استخداماً. إذا استخدم عدة أشخاص الأوزان المتوسطة معاً، فقد تكون الأزواج المكررة أهم من إضافة أوزان نادرة الاستخدام. تحدد هذه المصفوفة الكمية وسعة الحامل والمساحة. ويجب أن يشمل الطلب طريقة التنظيف ومسؤولية الصيانة والمدة المطلوبة لتوافر الطراز نفسه.",
    "يتم تحديد مواصفات الدمبل والحامل كل على حدة ثم اختبارهما كنظام. تشمل بيانات الدمبل الوزن الاسمي والسماحية والأبعاد والبناء الثابت وقطر المقبض والتخشين وتثبيت الرأس والعلامة والتشطيب. وتشمل بيانات الحامل الخامة والأبعاد عند التحميل الكامل والقدرة وشكل مواضع التخزين والقاعدة والأرجل والمسامير والتركيب. اختبار المجموعة كاملة يوضح ثبات كل قطعة ومساحة اليد واحتمال احتكاك الأسطح المصقولة. كما يجب فحص الحامل عند إزالة عدة أزواج من جانب واحد، لأن الاستخدام الفعلي لا يبقى متوازناً دائماً. هذا الاختبار أهم من الاعتماد على ورقتي مواصفات منفصلتين.",
    "يُختار الكروم بعد تقييم البيئة وطريقة التشغيل، وليس للمظهر الفاخر فقط. الشكل المدمج ووضوح علامات الوزن يناسبان الفنادق والاستوديوهات التي تتم صيانتها جيداً. أما الرطوبة العالية والمنظفات القوية وإعادة الأوزان بعنف فتتطلب مراجعة دقيقة للتشطيب. نطاق 1–10 كجم مناسب للإحماء والكتف والذراع والتمارين المساعدة والزيادة الصغيرة، لكنه ليس خط قوة كاملاً لكل المستخدمين. يوفر حامل X طول الجدار، لكن منطقة التشغيل تشمل مساحة وقوف المستخدم والأجزاء البارزة. يجب إظهار الأبواب والمرايا والمقاعد والمعدات القريبة ومسار التنظيف ومخارج الطوارئ على المخطط.",
    "تأتي القيمة التشغيلية من الوصول المباشر ومكان العودة الواضح. يغير المدرب الحمل بسرعة، ويفهم نزيل الفندق التسلسل، ويمكن للنادي الكبير فصل العمل الخفيف عن منطقة الدمبل الثقيلة. ويلاحظ الموظف فوراً أي زوج مفقود. مع ذلك، يجب ربط المحطة بسيناريو متكامل يشمل المقعد والأرضية ومساحة الحركة والتعليمات والأوزان المكملة. للمستورد أو الموزع في السوق العربية أهمية إضافية لاستمرارية الشكل بين الدفعات، وتوافر القطع، والوثائق، والضمان، وطريقة معالجة المطالبات. قد تكون موثوقية التوريد والاستجابة بعد البيع أهم من أقل سعر في الطلب الأول.",
    "يحمي الفحص الموثق المعدات والمستخدمين. وفق جدول محدد يتم التأكد من اكتمال الأزواج ووضوح العلامات وثبات الرؤوس والمقابض ومواضع التخزين والمسامير والأرجل واستقرار الحامل. تُوقف أي قطعة بها ارتخاء أو حافة حادة أو تشوه. يُستخدم منظف معتمد بكمية مناسبة، ولا يُترك سائل في الوصلات، ثم يجفف السطح. سجل يحتوي على التاريخ والصورة والوزن والموقع يساعد المورد على تحليل السبب وإرسال القطعة الصحيحة. كما يميز بين البلى العادي وسوء الاستخدام وخطأ التركيب والعيب المتكرر. يجب أن يحدد دليل الطراز المعتمد دورية الفحص والعزم والمواد المحظورة.",
    "تبدأ مراقبة المصنع بقائمة نهائية لكل وزن وعدد الأزواج والحامل والشعار والتشطيب والملحقات والتعبئة. تثبت العينة مستوى اللمعان والنقش وإحساس المقبض والملاءمة. أثناء الإنتاج يمكن فحص الخامة والتشغيل والربط والسطح والكتلة والعلامات والتركيب وفق خطة متفق عليها. قبل الشحن تتم مطابقة الدفعة مع الطلب وقائمة التعبئة. تُفصل الأسطح اللامعة وتُثبت وتحمي من الرطوبة حسب مسار النقل. تُراجع قوة الكرتون وعلامات الطرود وملصقات المسامير والتعليمات والمنصات والأوزان الإجمالية. تُقاس قدرة المورد بهذه السجلات وطريقة معالجة عدم المطابقة، لا بعبارات عامة عن الخبرة.",
    "تُقارن العروض ضمن النطاق نفسه. يجب تأكيد عدد القطع والحامل وقطع الغيار والأدوات والكرتون والمنصات والوزن الإجمالي والحجم والضمان ومسار الشكوى. يسأل المشتري عن معالجة وزن خارج السماحية أو علامة تالفة أو طرد مفقود. تُراجع متطلبات العلامات والتعليمات والسلامة والاستيراد مع مختصين في سوق الوجهة. تشمل الخطة أيضاً التفريغ والنقل داخل المبنى وعرض الأبواب وموقع التجميع. طلب سعر واضح يحتوي على مصفوفة الأوزان والكمية والرسم والعينة ومستوى الفحص والتعبئة والموعد المطلوب، وبذلك تصبح الأسعار والمهل والمسؤوليات قابلة للمقارنة."
  ]
};

export const caseSectionSupplements: Partial<Record<CaseLocale, string[]>> = {
  de: [
    "Für die Bedarfsanalyse empfiehlt sich ein kurzes Lastenheft, das nicht nur die gewünschte Optik nennt. Darin stehen Nutzergruppen, betreute und unbetreute Trainingszeiten, erwartete gleichzeitige Belegung sowie die Übungen, für die leichte Kurzhanteln vorgesehen sind. Ein Hotelbetrieb kann beispielsweise Wert auf eine selbsterklärende Reihenfolge, leise Ablage und ein gepflegtes Erscheinungsbild legen. Ein Personal-Training-Studio benötigt dagegen häufig kleine Gewichtsschritte und schnellen Zugriff während einer Einheit. In einem größeren Fitnessstudio ist zusätzlich zu prüfen, ob stark nachgefragte mittlere Gewichte doppelt vorhanden sein müssen. Aus diesen Angaben entsteht eine belastbare Stückliste. Sie verhindert, dass der Einkauf allein aufgrund eines symmetrischen Produktfotos eine Zusammenstellung bestellt, die im täglichen Betrieb nicht zur tatsächlichen Nachfrage passt.",
    "Zur Flächenplanung gehört mehr als die Grundfläche des leeren Ständers. Maßgeblich ist der betriebsbereite Zustand mit vollständig eingesetzten Hanteln. Projektverantwortliche sollten den Zugriff von beiden Seiten, die Ausweichbewegung beim Herausnehmen, angrenzende Laufwege, Türen, Spiegel, Bänke und Bodenübergänge berücksichtigen. Eine maßstäbliche Einzeichnung im Raumplan hilft, Engstellen früh zu erkennen. Vor der Freigabe ist außerdem zu klären, ob der Untergrund eben und ausreichend tragfähig ist, ob Stellfüße vorgesehen sind und wie der Ständer gegen unbeabsichtigtes Verschieben gesichert wird. Bei der Abnahme vor Ort werden Standfestigkeit, Wackeln, erreichbare Griffhöhen und der Abstand zwischen benachbarten Hanteln praktisch geprüft. Das Ergebnis sollte dokumentiert werden, damit Montage, Betrieb und spätere Nachbestellung dieselbe Referenz verwenden.",
    "Deutsche und europäische Beschaffer erwarten nachvollziehbare Angaben zur Lieferfähigkeit. Deshalb sollte das Angebot zwischen Musterzeit, Serienfertigung und Transport unterscheiden und klar benennen, welche Termine erst nach Freigabe von Zeichnung, Kennzeichnung und Verpackung beginnen. Zur Lieferantenbewertung gehören eine eindeutige Material- und Oberflächenspezifikation, Prüfmittel für die Gewichtskontrolle, dokumentierte Zwischenprüfungen sowie ein Verfahren für Abweichungen. Bei wiederkehrenden Bestellungen ist die Änderungslenkung wichtig: Werkstoff, Griffgeometrie, Gravur oder Auflage dürfen nicht stillschweigend verändert werden. Der Käufer kann deshalb eine Versionsnummer für Zeichnung und Freigabemuster verlangen. Für die Versandplanung sind Brutto- und Nettogewicht, Kartonmaße, Packstückzahl, Palettenbild, Stapelgrenzen und Schutz gegen Feuchtigkeit oder Scheuern erforderlich. Ebenfalls zu vereinbaren sind Ersatzteilumfang, Reklamationsweg, Reaktionszeit und die Kennzeichnung einzelner Gewichte. Diese Informationen machen Angebote vergleichbar und zeigen, ob ein Hersteller nicht nur ein Muster, sondern eine konsistente Serie und spätere Ergänzung liefern kann."
  ],
  it: [
    "Prima dell’ordine è utile trasformare le esigenze della struttura in una scheda condivisa. La scheda indica profilo degli utenti, esercizi previsti, ore di maggiore affluenza, numero di persone che possono usare contemporaneamente la zona e frequenza di pulizia. In un boutique studio possono essere prioritari passaggi di peso ravvicinati e un’immagine ordinata; in un hotel contano intuitività e ingombro; in una palestra commerciale occorre valutare anche i doppioni delle pezzature più richieste. Questa analisi consente di decidere se la sequenza da 1 a 10 kg è sufficiente, se servono coppie aggiuntive o se la stazione deve essere affiancata da manubri più pesanti. La distinta finale deve riflettere l’uso reale, non soltanto la composizione visibile nella fotografia.",
    "Nel layout va considerato il rack completamente carico. Il progettista verifica accesso su entrambi i lati, spazio per afferrare e riporre ogni coppia, passaggi, specchi, porte, panche e giunti della pavimentazione. Un disegno quotato riduce il rischio che una soluzione compatta sulla carta interferisca con il movimento dell’utente. In fase di consegna conviene controllare planarità, piedini, serraggio, stabilità e ordine delle sedi. Il personale riceve inoltre una semplice procedura: riportare ogni peso nella posizione corretta, segnalare oscillazioni o bordi danneggiati e isolare un elemento non sicuro fino alla verifica. In questo modo estetica e funzionalità restano coerenti nel tempo.",
    "Per confrontare fornitori, il buyer italiano dovrebbe richiedere una proposta scomposta per set, rack, ricambi, personalizzazione e imballo. Tempi di campionatura e produzione vanno indicati separatamente, con il punto esatto da cui decorre la consegna. Sono utili il disegno revisionato, la tolleranza di peso, il criterio di controllo della finitura, le dimensioni dei colli e il piano di carico. Per ordini ripetuti, ogni modifica di materiale, presa, marcatura o supporto deve essere comunicata e approvata. Il fascicolo commerciale comprende anche istruzioni di montaggio, elenco ferramenta, procedura di reclamo e disponibilità dei componenti soggetti a usura. Questi elementi permettono di valutare affidabilità e costo complessivo, non solo il prezzo iniziale."
  ],
  sv: [
    "En svensk eller nordisk beställare tjänar på att börja med en kort behovsbeskrivning som kan delas mellan inköp, drift och träningsansvarig. Den bör ange användargrupper, övningar, bemannade och obemannade tider, förväntad samtidig användning samt vilka vikter som sannolikt används mest. Ett hotellgym kan prioritera enkel orientering, låg ljudnivå och ett välordnat uttryck. En mindre studio kan behöva täta viktsteg och snabb åtkomst under coachade pass. I en större anläggning kan extra par av mellanvikter vara mer värdefulla än en längre serie som sällan används. Behovsbilden ska därför styra antal, intervall och förvaring. På så sätt blir inköpslistan kopplad till verksamheten och inte enbart till den symmetriska uppställning som syns på referensbilden.",
    "Ytbedömningen ska göras med stället fullt lastat. Förutom fotavtrycket behöver projektören räkna med hantlarnas utskjutande delar, handutrymme vid lyft, rörelsen när användaren backar från stället och fria stråk till annan utrustning. Dörrslag, speglar, bänkar, mattkanter och nivåskillnader i golvet bör markeras på ritningen. Vid installation kontrolleras att underlaget är plant, att eventuella ställfötter har rätt kontakt och att stället inte vrider sig när vikter tas bort ojämnt. En praktisk provning med flera användare kan visa om grepphöjder och avstånd fungerar för den tänkta målgruppen. Resultatet dokumenteras med mått och fotografier så att en senare komplettering kan utföras enligt samma förutsättningar.",
    "Nordiska inköp lägger ofta stor vikt vid tydlighet, spårbarhet och långsiktig leverans. Offerten bör därför skilja på provtid, produktionsledtid och transport samt ange vilka godkännanden som startar respektive fas. Leverantören ska kunna redovisa material, ytbehandling, viktkontroll, monteringskontroll och hantering av avvikelser för just den beställda modellen. Vid återkommande order behövs versionsstyrning, så att grepp, märkning, stödpunkt eller emballage inte ändras utan besked. Transportunderlaget ska innehålla brutto- och nettovikt, kartongmått, antal kollin, pallmönster, staplingsgräns och skydd mot fukt och nötning. Köparen bör även fråga om reservdelar, reklamationsflöde, svarstid och möjlighet att ersätta en enstaka vikt. En sådan specifikation gör total kostnad och leveransrisk synlig. Den underlättar också intern granskning av arbetsmiljö, skötsel och livslängd innan beställningen godkänns.",
    "Före slutligt godkännande kan driftgruppen dessutom göra en enkel provvecka med den fastställda placeringen. Personalen noterar köbildning, felplacerade vikter, städåtkomst och om märkningen kan läsas i lokalens normala belysning. Små justeringar av riktning, avstånd eller instruktioner kan då genomföras innan lösningen upprepas i fler rum."
  ],
  ko: [
    "국내 피트니스 시설의 구매 검토에서는 먼저 이용 장면을 구체적으로 정리하는 것이 좋다. 회원 연령대, 초보자 비중, 여성 회원 비중, 개인 운동과 수업 운영 비율, 피크 시간의 동시 사용자 수, 자주 진행하는 동작을 목록으로 만든다. 호텔 피트니스룸은 처음 방문한 이용자도 무게 순서를 쉽게 이해하고 조용하게 반납할 수 있는 구성이 중요하다. 퍼스널 트레이닝 스튜디오는 수업 흐름을 끊지 않는 빠른 교체와 세밀한 증량이 중요하다. 상업용 헬스장은 중간 무게의 사용 빈도와 추가 세트 필요성을 함께 본다. 여러 회원이 같은 시간에 4kg, 5kg, 6kg을 자주 쓴다면 범위를 무조건 늘리는 것보다 해당 무게를 추가하는 편이 운영에 유리할 수 있다. 이렇게 만든 수요표를 기준으로 최종 수량과 랙 구성을 결정해야 사진에 보이는 배열을 그대로 주문하는 오류를 줄일 수 있다.",
    "공간 검토는 빈 랙의 가로와 세로 치수만 확인해서는 충분하지 않다. 모든 덤벨을 거치한 상태에서 돌출되는 폭, 손을 넣는 간격, 덤벨을 들어 올린 뒤 한 걸음 물러나는 동선, 인접 벤치와 유산소 장비의 위치를 함께 확인한다. 출입문이 열리는 방향, 거울과의 거리, 바닥 매트의 이음부, 청소 장비가 지나가는 길도 배치도에 표시한다. 설치 시에는 바닥 수평, 조절발 접촉, 체결 상태, 한쪽 덤벨을 여러 개 뺐을 때의 흔들림을 점검한다. 키와 숙련도가 다른 사용자가 위쪽과 아래쪽 거치대에 안전하게 접근할 수 있는지도 실제 동작으로 확인한다. 검수 결과는 치수, 사진, 조립 상태와 함께 기록하면 동일 모델을 추가 구매하거나 다른 지점에 설치할 때 기준 자료로 활용할 수 있다.",
    "공급사 평가는 샘플 외관만으로 끝내지 않는다. 견적서에는 각 무게의 수량, 랙, 예비 부품, 로고와 표기 방식, 포장 단위가 분리되어야 한다. 도면 승인, 샘플 승인, 양산, 출하 검사, 선적 준비에 필요한 기간을 각각 제시하도록 요청하면 납기 위험을 더 정확하게 볼 수 있다. 양산 관리에서는 원재료 확인, 가공 치수, 고정 상태, 표면 상태, 중량 허용 오차, 각인 가독성, 랙 조립과 안착 상태를 확인한다. 반복 주문에서는 손잡이 형상, 마감 색조, 각인 위치, 거치부 재질이 사전 통보 없이 바뀌지 않도록 도면 버전과 승인 샘플을 연결한다. 포장 자료에는 개별 보호 방식, 박스 크기, 총중량, 박스 수, 팔레트 적재, 습기 방지, 부품 상자 위치가 포함되어야 한다. 국내 도착 후에는 하역, 층간 이동, 엘리베이터 크기, 현장 조립 인력까지 고려한다. 불량이나 누락이 발생했을 때 사진과 로트 정보로 접수하는 절차, 답변 시간, 단품 보충 가능 여부도 계약 전에 확인하는 것이 좋다. 이 자료가 있어야 가격뿐 아니라 공급 안정성, 유지 관리, 재구매 가능성을 함께 비교할 수 있다.",
    "운영팀은 인수 직후 기준 상태를 남겨 두는 것이 좋다. 각 덤벨의 표기, 표면, 손잡이, 흔들림을 확인하고 랙의 수평과 볼트 체결 상태를 사진으로 기록한다. 일상 점검에서는 모든 무게가 제자리에 있는지, 거치부가 변형되지 않았는지, 손에 걸리는 모서리가 없는지 확인한다. 세척제는 승인된 방법과 희석 비율을 사용하고 물기가 연결 부위에 남지 않게 마른 천으로 마무리한다. 이상이 발견된 제품은 계속 사용하지 않고 분리한 뒤 모델, 무게, 위치, 증상을 기록해 공급사에 전달한다. 간단한 점검표를 유지하면 반복되는 문제를 찾기 쉽고 부품 요청도 정확해진다. 회원에게는 덤벨을 바닥에 던지지 않고 지정된 위치에 돌려놓는 안내를 제공한다. 이러한 관리가 정돈된 인상, 안전한 사용, 제품 수명을 함께 지키는 현실적인 방법이다."
  ],
  pl: [
    "Polski inwestor powinien rozpocząć od krótkiego opisu potrzeb, wspólnego dla działu zakupów, trenera i osoby odpowiedzialnej za obiekt. Dokument powinien określać grupy użytkowników, planowane ćwiczenia, udział treningów indywidualnych i zajęć prowadzonych, godziny szczytu oraz liczbę osób korzystających jednocześnie ze strefy. W hotelu ważna może być intuicyjna kolejność, cicha obsługa i uporządkowany wygląd. Studio treningu personalnego zwykle zwraca uwagę na małe skoki obciążenia i szybkie zmiany podczas sesji. Klub komercyjny powinien dodatkowo sprawdzić, czy najczęściej wybierane środkowe ciężary wymagają podwójnych par. Na tej podstawie powstaje rzeczywista lista ilościowa. Dzięki temu zakup nie ogranicza się do odtworzenia symetrycznego układu ze zdjęcia, lecz odpowiada programowi treningowemu i przewidywanemu natężeniu ruchu.",
    "Analiza przestrzeni obejmuje stojak w pełni załadowany, a nie wyłącznie jego pustą podstawę. Na rzucie należy uwzględnić wystające hantle, miejsce na dłoń, ruch potrzebny do zdjęcia pary oraz krok użytkownika odchodzącego od stojaka. Sprawdza się także drzwi, lustra, ławki, sprzęt cardio, krawędzie mat i główne przejścia. Podczas montażu kontroluje się równość podłoża, kontakt stopek, dokręcenie połączeń i zachowanie konstrukcji przy nierównomiernym zdjęciu kilku par. Próba z osobami o różnym wzroście pokazuje, czy górne i dolne gniazda są dostępne oraz czy sąsiednie hantle nie utrudniają chwytu. Wynik warto zapisać w protokole odbioru wraz z wymiarami i zdjęciami. Taki zapis ułatwia późniejsze doposażenie, przeniesienie stanowiska lub odtworzenie tej samej konfiguracji w kolejnym obiekcie.",
    "Przy ocenie dostawcy liczy się zdolność do powtarzalnej realizacji, a nie tylko jakość pojedynczej próbki. Oferta powinna oddzielać czas wykonania próbki, produkcji seryjnej i transportu oraz wskazywać, które zatwierdzenie uruchamia każdy etap. Należy uzgodnić materiał, wykończenie, tolerancję masy, sposób kontroli mocowania głowic, czytelność oznaczeń i dopasowanie do gniazd stojaka. Dla kolejnych zamówień potrzebne jest zarządzanie wersjami, aby uchwyt, grawer, powierzchnia albo opakowanie nie zostały zmienione bez akceptacji. Dane logistyczne obejmują masę brutto i netto, wymiary kartonów, liczbę paczek, układ palety, ograniczenia piętrzenia oraz ochronę przed wilgocią i ocieraniem. Kupujący powinien również ustalić dostępność pojedynczych ciężarów, części do stojaka, procedurę reklamacji i przewidywany czas odpowiedzi. W przypadku importu weryfikuje się instrukcję, oznakowanie i dokumenty wymagane na rynku docelowym z właściwym specjalistą. Taki zakres pozwala porównać koszt całkowity, ryzyko dostawy i możliwości obsługi po sprzedaży.",
    "Przed zatwierdzeniem układu zespół może przeprowadzić krótką próbę operacyjną. Obserwuje dostęp, odkładanie par, widoczność oznaczeń, sprzątanie oraz zachowanie stojaka przy częściowym obciążeniu. Wnioski zapisuje się przed powieleniem rozwiązania."
  ],
  ar: [
    "يبدأ التخطيط الجيد بوصف واضح لطريقة الاستخدام، وليس بصورة المنتج وحدها. يسجل المشتري فئات المستخدمين، والتمارين المتوقعة، وساعات الذروة، وعدد الأشخاص الذين قد يستخدمون منطقة الأوزان في الوقت نفسه. قد يحتاج فندق إلى ترتيب سهل الفهم وتشغيل هادئ ومظهر منظم، بينما يحتاج استوديو التدريب الشخصي إلى انتقال سريع بين الأوزان وخطوات صغيرة في المقاومة. أما النادي التجاري فيراجع تكرار استخدام الأوزان المتوسطة والحاجة إلى أزواج إضافية. إذا كان عدة مستخدمين يطلبون وزن خمسة أو ستة كيلوغرامات في الحصة نفسها، فقد تكون إضافة زوج آخر أكثر فائدة من توسيع النطاق إلى وزن نادر الاستخدام. تتحول هذه المعلومات إلى قائمة كميات فعلية تربط الشراء بالبرنامج التدريبي، بدلا من نسخ الترتيب المتناسق الظاهر في الصورة دون التحقق من حاجة المنشأة.",
    "يجب حساب المساحة والرف محمل بالكامل. لا تكفي أبعاد القاعدة الفارغة، لأن أطراف الدمبل البارزة، ومساحة دخول اليد، وحركة رفع الزوج، وخطوة المستخدم إلى الخلف كلها تؤثر في الموقع الآمن. يوضع في المخطط اتجاه فتح الأبواب، والمسافة عن المرايا والمقاعد وأجهزة الكارديو، وحواف الأرضيات المطاطية ومسارات التنظيف. عند التركيب يفحص الفريق استواء الأرضية، وتلامس الأرجل، وشد الوصلات، وثبات الهيكل عندما تزال عدة أزواج من جانب واحد. كما يجرب مستخدمون بأطوال مختلفة الوصول إلى المواضع العليا والسفلى، مع التأكد من عدم انحشار الأصابع بين الأوزان. تسجل نتيجة الاستلام بالقياسات والصور وحالة التجميع. يفيد هذا السجل عند إضافة وحدات لاحقة أو تكرار التصميم في فرع آخر أو مناقشة أي اختلاف مع المورد.",
    "تقييم المصنع يشمل قدرته على إنتاج دفعة متسقة وتسليمها، وليس جمال العينة فقط. يجب أن يفصل العرض بين زمن العينة، وزمن الإنتاج، ومدة تجهيز الشحنة، وأن يوضح الموافقات التي يبدأ بعدها كل جزء. تشمل وثيقة الاعتماد المادة، والأبعاد، وسماحية الوزن، وطريقة تثبيت الرؤوس، وتشطيب السطح، ووضوح العلامات، وملاءمة كل دمبل لموضعه في الرف. أثناء الإنتاج تراجع المواد الخام، والتشغيل، والوصلات، والكتلة، والسطح، والتجميع. وفي الطلبات المتكررة يستخدم رقم مراجعة للرسم والعينة حتى لا يتغير المقبض أو النقش أو نقطة الارتكاز أو التغليف دون موافقة. تتضمن بيانات الشحن الوزن الصافي والإجمالي، وأبعاد الصناديق، وعدد الطرود، وترتيب المنصة، وحدود التكديس، والحماية من الرطوبة والاحتكاك. ومن المهم الاتفاق على قطع الغيار، وإمكانية توريد وزن منفرد، وطريقة تقديم المطالبة، ووقت الرد عند وجود نقص أو ضرر. يراجع المستورد كذلك متطلبات العلامات والتعليمات والوثائق في سوق الوصول مع جهة محلية مختصة. بهذه البيانات يمكن مقارنة السعر الكلي، ومخاطر النقل، واستمرارية التوريد وخدمة ما بعد البيع على أساس واضح.",
    "بعد الاستلام يحتفظ فريق التشغيل بحالة مرجعية لكل زوج وللرف. يفحص العلامات، والسطح، وثبات الرؤوس، وملمس المقبض، وتسوية القاعدة، وشد المسامير. في الفحص اليومي يتأكد الموظف من عودة كل وزن إلى موضعه وعدم وجود حافة حادة أو تشوه في نقطة الحمل. تستخدم مواد تنظيف متوافقة وبكمية محدودة، ثم تجفف الأسطح والوصلات حتى لا تبقى الرطوبة. إذا ظهر ارتخاء أو ضرر يعزل المنتج عن الاستخدام ويسجل رقم الوزن والموقع ووصف الحالة وصورها قبل التواصل مع المورد. يساعد سجل بسيط للصيانة على معرفة ما إذا كانت المشكلة منفردة أو متكررة، ويجعل طلب القطعة البديلة أكثر دقة. كما توضح للمستخدمين طريقة إعادة الأوزان وعدم إسقاطها. هذه الإجراءات تحافظ على التنظيم وسلامة الاستخدام والعمر التشغيلي دون الاعتماد على ادعاءات غير قابلة للتحقق."
  ]
};
