import { isPublishedVersion, type ContentEntity, type ContentManifest, type LocalizedContentVersion, type LocalizedImage } from "../../lib/content/types";
import { indonesianExcludedContentIds } from "./indonesian-manifest";
import { dutchEditorialAuthor, dutchTechnicalReviewer, nlAnswer, nlChecklist, nlDefinition, nlTable, nlText } from "./nl-content-helpers";

const publishedAt = "2026-07-22T12:00:00.000Z";
const excludedIds = new Set(indonesianExcludedContentIds);

type Profile = { path: string; title: string; h1: string; description: string; keyword: string; intent: string; focus: string };
const core: Record<string, Profile> = {
  home: { path: "/nl", title: "Fabrikant van professionele fitnessapparatuur en OEM | PowerBaseFit", h1: "Professionele fitnessapparatuur voor importeurs, distributeurs en fitnessprojecten", description: "Productie van halters, halterschijven, racks, banken en accessoires voor Nederlandse en Belgische importeurs, distributeurs, private labels en commerciële sportscholen.", keyword: "fabrikant van fitnessapparatuur", intent: "fabrikant beoordelen en offerte aanvragen", focus: "Deze pagina verbindt het productassortiment met aantoonbare productie, OEM-ondersteuning en de gegevens die nodig zijn voor een vergelijkbare B2B-offerte." },
  "products-hub": { path: "/nl/producten", title: "Fitnessapparatuur groothandel voor commerciële sportscholen", h1: "Fitnessapparatuur voor commerciële sportscholen en distributie", description: "Halters, halterschijven, bumper plates, racks, banken en accessoires voor B2B-inkoop, sportschoolprojecten en private labels.", keyword: "fitnessapparatuur groothandel", intent: "categorie kiezen en RFQ voorbereiden", focus: "Het productcentrum helpt inkopers een SKU-lijst op te bouwen op basis van toepassing, materiaal, ruimte, kwaliteitscontrole, verpakking en logistiek." },
  "dumbbells-category": { path: "/nl/producten/halters", title: "Halters groothandel voor professionele sportscholen | OEM", h1: "Professionele halters voor sportscholen, distributeurs en private labels", description: "Hex-, ronde, verstelbare, rubberen, PU-, TPU-, CPU-, stalen en gietijzeren halters voor groothandel en commerciële projecten.", keyword: "halters groothandel", intent: "constructies en gewichtreeksen vergelijken", focus: "Vergelijk kopvorm, coating, greep, gewichtsbereik, rekindeling, geur, uitstraling en herhaalbaarheid van de serie." },
  "weight-plates-category": { path: "/nl/producten/halterschijven", title: "Olympische halterschijven en bumper plates | B2B leverancier", h1: "Olympische halterschijven en bumper plates voor commercieel gebruik", description: "Gietijzeren, stalen, rubberen, PU-, TPU- en CPU-schijven met specificatie, QC, exportverpakking en OEM-opties.", keyword: "halterschijven groothandel", intent: "schijven en compatibiliteit beoordelen", focus: "De inkoper vergelijkt boring, diameter, dikte, materiaal, gewichtstolerantie, insert, markering en gedrag in de beoogde trainingsomgeving." },
  "racks-benches-category": { path: "/nl/producten/racks-banken", title: "Fitness racks, banken en kabelstations voor sportscholen", h1: "Racks, fitnessbanken en kabelstations voor sportschoolprojecten", description: "Power racks, Smith machines, functional trainers, kabelstations en verstelbare banken voor projecten, distributeurs en OEM-programma's.", keyword: "fitness racks en banken", intent: "ruimte en montage plannen", focus: "Beoordeel toestelmaat, bewegingszone, plafondhoogte, servicebereik, montage, verankering, kabelroute en samenwerking met banken en opslag." },
  "gym-accessories-category": { path: "/nl/producten/fitnessaccessoires", title: "Fitnessaccessoires groothandel | B2B leverancier", h1: "Fitnessaccessoires voor distributeurs en professionele faciliteiten", description: "Kettlebells, kabelgrepen en accessoires voor distributie, sportschoolprojecten en private-labelverpakkingen.", keyword: "fitnessaccessoires groothandel", intent: "assortiment en aanvulorders bouwen", focus: "Selecteer accessoires op functie, materiaal, aansluiting, greep, opslag, verkoopeenheid, verpakking en omloopsnelheid." },
  factory: { path: "/nl/fabriek", title: "Fabriek voor fitnessapparatuur in China | Productie en QC", h1: "Productie en kwaliteitscontrole van PowerBaseFit fitnessapparatuur", description: "Van specificatie en monster tot productie, inspectie, exportverpakking en voorbereiding van een B2B-order.", keyword: "fitnessapparatuur fabriek China", intent: "productieproces verifiëren", focus: "Bekijk hoe een goedgekeurde specificatie wordt vertaald naar een monster, werkinstructie, procescontrole, eindinspectie, paklijst en partij-identificatie." },
  "oem-private-label": { path: "/nl/oem-private-label", title: "OEM en private-label fitnessapparatuur | PowerBaseFit", h1: "OEM, ODM en private label voor fitnessapparatuur", description: "Logo, kleur, productmarkering en verpakking via haalbaarheid, MOQ, monsters, goedkeuring, QC en serieproductie.", keyword: "private-label fitnessapparatuur", intent: "OEM-programma ontwikkelen", focus: "Logo, kleur, label, doos, constructie en gereedschap worden afzonderlijk beoordeeld omdat elk niveau andere MOQ's, kosten, monsters en risico's heeft." },
  projects: { path: "/nl/projecten", title: "Planning van sportschoolinrichting en vrije-gewichtzones", h1: "Leveringsplanning voor commerciële sportschoolprojecten", description: "Productselectie, indeling, opslag, personalisatie, verpakking en levering op basis van echte PowerBaseFit-producten en beelden.", keyword: "commercieel sportschoolproject", intent: "assortiment en indeling plannen", focus: "De methode koppelt producten, ruimte, gebruikersstromen, opslag, montage en levering zonder fictieve klantresultaten te presenteren." },
  "blog-index": { path: "/nl/blog", title: "Inkoopgidsen voor professionele fitnessapparatuur", h1: "Technische inkoopgidsen voor fitnessapparatuur", description: "Praktische informatie voor importeurs, distributeurs, merken en sportscholen over leveranciers, OEM, QC, verpakking, import en totale kosten.", keyword: "fitnessapparatuur inkoopgids", intent: "B2B-inkoop ondersteunen", focus: "Het kenniscentrum zet inkoopvragen om in criteria, tabellen, checklists en gegevens voor RFQ's, monsterbeoordeling en ordercontrole." },
  contact: { path: "/nl/contact", title: "B2B-offerte voor fitnessapparatuur aanvragen | PowerBaseFit", h1: "Vraag een offerte aan voor uw fitnessapparatuurproject", description: "Stuur producten, aantallen, personalisatie, bestemming en planning voor een vergelijkbare B2B-offerte van PowerBaseFit.", keyword: "offerte fitnessapparatuur", intent: "offertegegevens verzamelen", focus: "Het formulier verzamelt SKU's, aantallen per variant, logo, verpakking, bestemmingsplaats, Incoterm en gewenste planning." },
  "rubber-hex-dumbbell-manufacturer": { path: "/nl/fabrikant/rubberen-hex-halters", title: "Fabrikant van rubberen hex-halters | OEM en groothandel", h1: "Rubberen hex-halters rechtstreeks van een B2B-fabrikant", description: "Professionele hex-halters met opties voor gewichten, grepen, logo, exportverpakking en private label.", keyword: "fabrikant rubberen hex-halters", intent: "directe fabrikant kwalificeren", focus: "De pagina richt zich op één reproduceerbare serie: kopconstructie, stabiliteit, greep, geur, gewichtsaanduiding, doos, pallet en vervolgorders." }
};

type Guide = { slug: string; title: string; h1: string; keyword: string; intent: string; angle: string };
const guideSeed: Record<string, [string, string, string]> = {
  "factory-guide": ["een-fitnessapparatuur-fabriek-in-china-beoordelen", "Een fabriek voor fitnessapparatuur in China beoordelen", "Volg één echte SKU van inkomend materiaal tot exportdoos en scheid eigen processen, uitbesteding, capaciteit en afwijkingsbeheer."],
  "dumbbells-guide": ["halters-kiezen-voor-een-commerciele-sportschool", "Halters kiezen voor een commerciële sportschool", "Begin met gewichtsbereik, stapgrootte, dubbele paren, rekruimte en gebruikersprofiel; vergelijk daarna vorm, coating, greep en prijs."],
  "plates-guide": ["halterschijven-of-bumper-plates-kiezen", "Halterschijven of bumper plates kiezen", "Koppel boring, diameter, dikte, insert, gewicht en valgedrag aan halterstang, platform, huisregels en toepassing."],
  "import-guide": ["fitnessapparatuur-uit-china-importeren-naar-nederland", "Fitnessapparatuur uit China importeren naar Nederland", "Scheid leverancierselectie, specificatie, tariefindeling, documenten, Incoterm, transport, inspectie en landed cost; verifieer actuele verplichtingen via Access2Markets, TARIC en de Nederlandse Douane."],
  "import-cost-guide": ["kosten-van-import-fitnessapparatuur-berekenen", "Importkosten van fitnessapparatuur berekenen", "Bereken product, verpakking, pallets, inspectie, vracht, verzekering, invoer, btw, afhandeling, opslag, schade en kapitaal per SKU."],
  "moq-guide": ["moq-voor-fitnessapparatuur", "MOQ bij de inkoop van fitnessapparatuur", "Scheid MOQ voor product, kleur, logo, matrijs, doos en grondstof; totale orderwaarde vervangt niet altijd het minimum van een proces."],
  "oem-vs-odm-guide": ["oem-of-odm-voor-fitnessapparatuur", "OEM of ODM voor een fitnessmerk", "Bepaal of alleen identiteit, een standaardconfiguratie of ook functie en gereedschap veranderen; eigendom, testen, kosten en tijd verschillen."],
  "private-label-guide": ["private-label-fitnessapparatuur-opbouwen", "Een private-label lijn fitnessapparatuur opbouwen", "Start met positionering, SKU-architectuur, basisproducten, huisstijl, verpakking, monster, QC, productdata en herhaalorders."],
  "hex-vs-round-guide": ["hex-halters-of-ronde-halters", "Hex-halters of ronde halters voor professioneel gebruik", "Vergelijk rollen, opslag, vloerstabiliteit, greeptoegang, kopbreedte, setuitstraling en oefeningen waarbij de halter steunpunt is."],
  "materials-guide": ["rubber-pu-of-tpu-halters", "Rubberen, PU- of TPU-halters vergelijken", "Vergelijk complete constructie, geur, textuur, uitstraling, oppervlaktesterkte, kleur, reiniging, kosten en reproduceerbaarheid."],
  "olympic-vs-standard-guide": ["olympische-of-standaard-halterschijven", "Olympische en standaard halterschijven vergelijken", "Meet boring en halterhuls en controleer machines, schijfdikte, opslag, assortiment en beschikbaarheid van vervanging."],
  "professional-gym-list-guide": ["apparatuurlijst-voor-een-professionele-sportschool", "Een apparatuurlijst voor een professionele sportschool maken", "Bouw de lijst vanuit gebruikersprofiel, piekbelasting, zones, budget, ruimte, service en openingsfasen, niet vanuit catalogusaantallen."],
  "free-weight-area-guide": ["vrije-gewichtzone-plannen", "Een vrije-gewichtzone voor de sportschool plannen", "Plaats racks, banken, halters, schijven, stangen, opslag, platforms en looproutes op één schaal met werk- en spotterruimte."],
  "bumper-manufacturing-guide": ["hoe-bumper-plates-worden-gemaakt", "Hoe bumper plates worden geproduceerd en gecontroleerd", "Onderscheid compound, insertvoorbereiding, vorming, koeling, gewichtscorrectie, afwerking, maatcontrole en relevante tests."],
  "dumbbell-weighing-guide": ["gewicht-van-halters-controleren-in-de-fabriek", "Gewicht en balans van halters in de fabriek controleren", "Leg eenheid, tolerantie, resolutie en kalibratiestatus vast, plus sampling, meetmoment en balanscontrole voor lichte en zware SKU's."],
  "plate-materials-b2b": ["gietijzeren-rubberen-of-urethaan-halterschijven", "Materialen van halterschijven vergelijken voor B2B-inkoop", "Vergelijk kern, coating, insert, diameter, dikte, grepen, reiniging en reproduceerbaarheid bij hetzelfde gewicht en gebruik."],
  "commercial-free-weight-rfq": ["rfq-checklist-voor-halters-en-halterschijven", "RFQ-checklist voor commerciële halters en halterschijven", "Gebruik één regel per SKU en aparte kolommen voor eisen, alternatieven, aantallen, eenmalige kosten, monster, QC, doos, pallet en levering."],
  "custom-logo-free-weights": ["logo-op-halters-en-halterschijven", "Een logomethode voor private-label vrije gewichten kiezen", "Kies de methode na bevestiging van materiaal en geometrie; controleer vectorbestand, maat, positie, kleur, duurzaamheid, gewichtsaanduiding en verpakking."],
  "export-packaging-free-weights": ["exportverpakking-voor-halters-en-halterschijven", "Exportverpakking voor zware vrije gewichten ontwerpen", "Ontwerp doos en pallet op basis van massa, zwaartepunt, tillen, stapelen, vocht, etiketten en uitpakvolgorde."],
  "free-weight-reorder-batch-consistency": ["partijconsistentie-bij-herhaalorders", "Consistentie tussen eerste order en herhaalorder bewaken", "Archiveer monster, revisie, kleur, artwork, maten, gewicht, QC-beelden en verpakkingsinstructie; vraag vooraf naar proceswijzigingen."],
  "landed-cost-free-weights": ["landed-cost-van-halters-en-halterschijven", "Landed cost van halters en halterschijven berekenen", "Bereken vaste en variabele kosten per SKU en test scenario's voor volume, containervulling, koers, schade, opslag en omloopsnelheid."],
  "oem-sample-approval-free-weights": ["oem-monster-goedkeuren-voor-serieproductie", "Een OEM-monster goedkeuren vóór serieproductie", "Schrijf op wat het monster moet bewijzen, markeer de revisie, meet resultaten en onderscheid uiterlijk-, functie- en productiemonsters."],
  "commercial-dumbbell-set-planning": ["halterset-voor-een-commerciele-sportschool-plannen", "Gewichtsbereik en aantallen voor een commerciële halterset bepalen", "Gebruik vraag per gewicht, ledenprofiel, piekuren, dubbele paren, rekruimte, vervanging en budget."],
  "pre-shipment-inspection-free-weights": ["inspectie-voor-verzending-van-vrije-gewichten", "Checklist voor inspectie van vrije gewichten vóór verzending", "Leg voltooiingsniveau, sampling, referentiemonster, defectklassen, meetgereedschap, bewijs en afhandeling van afwijkingen vast."],
  "training-vs-competition-bumper-plates": ["training-of-competition-bumper-plates", "Training en competition bumper plates vergelijken", "Vergelijk gewicht, diameter, dikte, insert, uiterlijk, tolerantie en testmethode; een productlabel vervangt geen constructiegegevens."]
};

const guides: Record<string, Guide> = Object.fromEntries(Object.entries(guideSeed).map(([id, [slug, h1, angle]]) => [id, { slug, h1, title: `${h1} | PowerBaseFit`, keyword: h1.toLowerCase(), intent: "technische B2B-inkoopbeslissing", angle }]));

function slugify(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function sourceSlug(entity: ContentEntity) { return entity.versions.en?.publicPath?.split("/").filter(Boolean).pop() ?? entity.id; }
function family(entity: ContentEntity) {
  const path = entity.versions.en?.publicPath ?? "";
  if (path.includes("/dumbbells/")) return { slug: "halters", label: "Halters", categoryId: "dumbbells-category" };
  if (path.includes("/weight-plates/")) return { slug: "halterschijven", label: "Halterschijven", categoryId: "weight-plates-category" };
  if (path.includes("/racks-benches/")) return { slug: "racks-banken", label: "Racks en banken", categoryId: "racks-benches-category" };
  return { slug: "fitnessaccessoires", label: "Fitnessaccessoires", categoryId: "gym-accessories-category" };
}

const exactNames: Record<string, string> = {
  "hex-dumbbell-kg": "Rubberen hex-halter", "chrome-dumbbell": "Verchroomde halter", "rubber-bumper-plate": "Rubberen bumper plate", "classic-rubber-round-dumbbell": "Klassieke ronde rubber halter", "pu-dumbbell-kg": "PU-halter", "rubber-olympic-plate": "Rubberen olympische halterschijf", "cast-iron-dumbbell": "Gietijzeren halter", "cpu-dumbbell-kg": "CPU-halter", "tpu-dumbbell-kg": "TPU-halter", "cpu-bumper-plate": "CPU bumper plate", "cast-iron-weight-plate": "Gietijzeren halterschijf", "cpu-grip-plate": "CPU-halterschijf met grepen", "rubber-barbell-plate": "Rubberen halterstangschijf"
};

const productImageFallback: Record<string, string> = {
  "cast-iron-dumbbell": "/assets/products/dumbbells/cast-iron/cast-iron-dumbbell-main.webp",
  "chrome-dumbbell": "/assets/products/dumbbells/chrome/chrome-dumbbell-main.avif",
  "classic-rubber-round-dumbbell": "/assets/products/dumbbells/classic-rubber-round/classic-rubber-round-dumbbell-main.avif",
  "cpu-dumbbell-kg": "/assets/products/dumbbells/catalog-v2/cpu-dumbbell-kg.webp",
  "hex-dumbbell-kg": "/assets/products/dumbbells/catalog-v2/hex-dumbbell-kg.webp",
  "pu-dumbbell-kg": "/assets/products/dumbbells/catalog-v2/pu-dumbbell-kg.webp",
  "tpu-dumbbell-kg": "/assets/products/dumbbells/catalog-v2/tpu-dumbbell-kg.webp",
  "cpu-bumper-plate": "/assets/products/weight-plates/catalog/cpu-bumper-plate.webp",
  "cast-iron-weight-plate": "/assets/products/weight-plates/cast-iron/cast-iron-weight-plate-main.avif",
  "cpu-grip-plate": "/assets/products/weight-plates/catalog/cpu-grip-plate.webp",
  "rubber-olympic-plate": "/assets/products/weight-plates/catalog/rubber-olympic-plate.webp",
  "rubber-bumper-plate": "/assets/products/weight-plates/catalog/rubber-bumper-plate.webp"
};

function productName(entity: ContentEntity) {
  const source = sourceSlug(entity);
  if (exactNames[source]) return exactNames[source];
  if (source.includes("cpu-hexagonal-dumbbell-wide")) return "Brede CPU hex-halter";
  const title = entity.versions.en?.h1 ?? source;
  return title
    .replace(/^12-sided /i, "Twaalfzijdige ").replace(/Twelve-sided/gi, "twaalfzijdige").replace(/Hexagonal/gi, "hexagonale")
    .replace(/Cast Iron/gi, "gietijzeren").replace(/Solid Steel/gi, "massief stalen").replace(/Steel/gi, "stalen")
    .replace(/Rubber Coated/gi, "rubber beklede").replace(/Rubber/gi, "rubberen").replace(/Adjustable/gi, "verstelbare")
    .replace(/Competition/gi, "competition").replace(/Olympic/gi, "olympische").replace(/Color/gi, "gekleurde")
    .replace(/Heavy Duty/gi, "heavy-duty").replace(/Heavy/gi, "zware").replace(/Compact/gi, "compacte").replace(/Custom/gi, "maatwerk")
    .replace(/Wall Mounted/gi, "wandgemonteerde").replace(/Wall Folding/gi, "opklapbare wand-").replace(/Private Home Gym/gi, "privéfitness-")
    .replace(/Dumbbell/gi, "halter").replace(/Weight Plate/gi, "halterschijf").replace(/Barbell Plate/gi, "halterschijf").replace(/Plate Set/gi, "schijvenset").replace(/Plate/gi, "schijf")
    .replace(/Weight Bench/gi, "fitnessbank").replace(/Bench/gi, "fitnessbank").replace(/Functional Trainer/gi, "functional trainer")
    .replace(/Gym Handle Sets/gi, "fitnessgreepsets").replace(/Gym Handles/gi, "fitnessgrepen").replace(/Handles/gi, "grepen").replace(/Attachments/gi, "accessoireset")
    .replace(/Machine/gi, "machine").replace(/Rack System/gi, "racksysteem").replace(/Rack/gi, "rack").replace(/Kettlebell/gi, "kettlebell")
    .replace(/Full Range/gi, "volledige gewichtsreeks").replace(/Full Rubber/gi, "volledig rubberen").replace(/Full Frame/gi, "volledig frame").replace(/Half Frame/gi, "half-frame")
    .replace(/Four-Grip/gi, "viergreps").replace(/Seven-Hole/gi, "zevengats").replace(/Three-in-One/gi, "3-in-1").replace(/Three Station/gi, "drie-stations").replace(/Five Station/gi, "vijf-stations").replace(/Single Station/gi, "één-stations").replace(/Six-Column/gi, "zeskoloms").replace(/Eight-Column/gi, "achtkoloms")
    .replace(/Floor Plate/gi, "vloerplaat").replace(/Storage/gi, "met opslag").replace(/Home Gym/gi, "thuisfitness").replace(/Round/gi, "ronde").replace(/Square/gi, "vierkante").replace(/Small/gi, "kleine").replace(/Mini/gi, "mini").replace(/Black/gi, "zwarte").replace(/Gold/gi, "goudkleurige").replace(/Star/gi, "stervormige").replace(/Spray/gi, "gespoten").replace(/Vinyl/gi, "vinyl").replace(/Aluminum/gi, "aluminium").replace(/Selectorized/gi, "selecteerbare").replace(/Commercial/gi, "commerciële").trim();
}

function base(version: Omit<LocalizedContentVersion, "locale" | "translationStatus" | "reviewStatus" | "publishStatus" | "canonicalData" | "hreflangData" | "updatedAt" | "publishedAt" | "version">): LocalizedContentVersion {
  return { ...version, locale: "nl", translationStatus: "localized", reviewStatus: "approved", publishStatus: "published", canonicalData: { mode: "self" }, hreflangData: { include: true }, updatedAt: publishedAt, publishedAt, version: 1 };
}

function imagesFor(entity: ContentEntity, label: string): LocalizedImage[] {
  const productFallback = entity.type === "product" ? productImageFallback[sourceSlug(entity)] : undefined;
  const sources = [...new Set([...(entity.versions.en?.images.map((image) => image.src) ?? []), ...(productFallback ? [productFallback] : []), "/assets/dumbbell-production.webp", "/assets/factory-cases/packaging-area-pbf.webp"])].slice(0, 3);
  return sources.map((src, index) => ({ id: `beeld-${index + 1}`, src, alt: index === 0 ? `${label} — echt PowerBaseFit-product of projectbeeld` : index === 1 ? `Productie en kwaliteitscontrole voor ${label}` : `Exportverpakking en ordercontrole voor ${label}`, caption: "Echt PowerBaseFit-beeld ter ondersteuning van de inkoopbeslissing." }));
}

function faq(keyword: string) { return [
  { id: "faq-1", question: `Waar begint de beoordeling van ${keyword}?`, answer: "Leg eerst toepassing, gebruiker, variant, hoeveelheid en commerciële beslissing vast. Vergelijk daarna monster, leverancier en prijs op dezelfde scope." },
  { id: "faq-2", question: "Is een monster nodig vóór de bestelling?", answer: "Een monster is raadzaam wanneer materiaal, maat, functie, afwerking, logo of verpakking het resultaat beïnvloedt. Leg vooraf vast wat het monster moet bewijzen." },
  { id: "faq-3", question: "Hoe vergelijk ik twee leveranciers?", answer: "Stuur dezelfde RFQ en vergelijk dezelfde productspecificatie, aantallen, personalisatie, QC, verpakking, Incoterm en uitsluitingen." },
  { id: "faq-4", question: "Is private label mogelijk?", answer: "Ja, voor geschikte producten en volumes. Logomethode, artwork, MOQ, monster, controle en verpakking worden vóór serieproductie bevestigd." },
  { id: "faq-5", question: "Wie is verantwoordelijk voor importvereisten?", answer: "De importeur en zijn adviseurs verifiëren de actuele classificatie, documenten, heffingen, btw en productverplichtingen voor de concrete transactie via officiële EU- en nationale bronnen." }
]; }

function decisionBlocks(keyword: string, focus: string, seed: string) {
  const blocks = [
    nlAnswer(`kern-${seed}`, `Kernbeslissing — ${keyword}`, `${focus} Het resultaat moet een benoemde variant, offertescope, open vragen, verantwoordelijke en volgende stap zijn.`),
    nlDefinition(`definitie-${seed}`, keyword, `${keyword} betekent hier een concrete inkoopvraag die is gekoppeld aan product, specificatie, bewijs, kwaliteitscontrole en een B2B-beslissing; niet alleen een marketingterm.`),
    nlText(`input-${seed}`, `Benodigde input voor ${keyword}`, "Scheid verplichte eisen, voorkeuren en punten die nog bevestigd moeten worden. Noteer per regel product, variant, aantal, toepassing, eenheid, deadline en goedkeurder.", "Ontbrekende informatie is geen automatische toestemming. De leverancier markeert ieder punt als conform, afwijkend of nog te verduidelijken zodat aannames zichtbaar blijven."),
    nlText(`specificatie-${seed}`, `Specificatie en monster — ${keyword}`, "Koppel de SKU aan tekening, materiaal, afmetingen, gewicht, functie, afwerking, markering en verpakkingsinhoud. Een monster krijgt een revisienummer en formele goedkeuringsstatus.", "Controleer lichte, middelzware en zware varianten of de configuraties met het hoogste risico. Eén representatief stuk bevestigt niet automatisch de hele reeks, gereedschappen en verpakking."),
    nlTable(`matrix-${seed}`, `Beslismatrix — ${keyword}`, ["Onderdeel", "Minimale informatie", "Bewijs vóór bestelling"], [["Product", "SKU, variant en aantal", "Tekening en monster"], ["Kwaliteit", "Methode, tolerantie en sampling", "QC-plan"], ["Merk", "Logo, kleur en etiket", "Artwork en monster"], ["Logistiek", "Doos, pallet en Incoterm", "Paklijst"], ["Herhaalorder", "Revisie en referenties", "Goedkeuringsarchief"]]),
    nlText(`qc-${seed}`, `Kwaliteitscontrole — ${keyword}`, "Een criterium benoemt methode, gereedschap, meetpunt, eenheid, steekproef en limiet. Voor uiterlijk worden lichtconditie en referentiemonster vastgelegd; voor functie de testcondities.", "Scheid procescontrole van eindinspectie. De eerste beperkt afwijkingen tijdens productie, de tweede beoordeelt een gereedstaande partij en vervangt geen controle van eerdere stappen."),
    nlText(`oem-${seed}`, `OEM en private label — ${keyword}`, "Logo, kleur, markering, etiket, doos en constructiewijziging hebben verschillende MOQ's, kosten en doorlooptijden. Noteer elke wijziging met methode, bestand, positie en acceptatiecriterium.", "Eenmalige kosten, monsters, gereedschap en procesminimum worden apart gehouden van de prijs van het standaardproduct. Zo blijven haalbaarheid en vervolgorders inzichtelijk."),
    nlText(`verpakking-${seed}`, `Verpakking en levering — ${keyword}`, "Stem doos, inzetstukken en pallet af op massa, zwaartepunt, tillen, stapelen, vocht, etiketten en uitpakvolgorde. Bescherm oppervlakken en uitstekende onderdelen gericht.", "De paklijst laat magazijn en expediteur SKU, aantal, netto- en brutogewicht, afmetingen en partij herkennen. Deze gegevens beïnvloeden vracht, afhandeling en landed cost."),
    nlText(`import-${seed}`, `Context voor Nederlandse en Belgische importeurs`, "De importeur verifieert CN/TARIC-classificatie, douanewaarde, oorsprong, documenten, btw en productvereisten voor de echte transactie. PowerBaseFit levert productie- en exportgegevens, maar vervangt de importeur of autoriteit niet.", "Controleer actuele informatie in Access2Markets, TARIC en bij de Nederlandse Douane, Belgische douane of bevoegde adviseur. Pas geen tarief of eis uit een algemeen artikel toe zonder code en datum te bevestigen."),
    nlText(`kosten-${seed}`, `Totale kosten van ${keyword}`, "Vergelijk product, verpakking, pallets, inspectie, vracht, verzekering, inklaring, heffingen, btw, afhandeling, opslag, schade en kapitaal. Splits eenmalige en terugkerende kosten.", "Gebruik een laag, basis- en hoog scenario voor volume, wisselkoers, transport, schade en omloopsnelheid. De fabrieksprijs is niet de kostprijs van een SKU in het magazijn."),
    nlText(`leverancier-${seed}`, `Leveranciersbeoordeling — ${keyword}`, "Laat de leverancier het proces voor de gekozen SKU uitleggen: materiaal, vorming of bewerking, onderaannemers, monster, productie, inspectie, verpakking en wijzigingsbeheer.", "Algemene fabriekscapaciteit bewijst geen capaciteit voor de concrete configuratie en deadline. De offerte benoemt scope, uitsluitingen, geldigheid, valuta en named place van de Incoterm."),
    nlText(`herhaalorder-${seed}`, `Herhaalbaarheid van de volgende partij`, "Archiveer specificatie, monster, artwork, kleur, gecontroleerde foto's, QC-rapport, verpakkingsinstructie en paklijst. Koppel klachten aan SKU en partijnummer.", "Vraag vóór een herhaalorder naar wijzigingen in materiaal, matrijs, gereedschap, onderaannemer of verpakking. Vergelijk first article met de goedgekeurde revisie en eerdere partijdata."),
    nlChecklist(`checklist-${seed}`, `Inkoopchecklist — ${keyword}`, ["Definieer toepassing en gebruiker", "Noteer SKU en aantal per variant", "Leg materiaal, maat, functie en tolerantie vast", "Vraag een schriftelijke afwijkingenlijst", "Bevestig MOQ en eenmalige kosten", "Keur monster en artwork per revisie goed", "Leg sampling en reactie op afwijkingen vast", "Controleer doos, pallet en paklijst", "Vergelijk dezelfde Incoterm en named place", "Bewaar gegevens voor klachten en herhaalorders"]),
    nlText(`actie-${seed}`, `Volgende stap voor ${keyword}`, "Zet de checklist om in een korte RFQ met SKU's, aantallen, markt, personalisatie, bestemming en planning. De leverancier benoemt de gevolgen voor MOQ, monster, controle en logistiek.", "Wanneer kritieke eisen nog onbekend zijn, is een technische bespreking of monsterplan de juiste stap; niet een vroege prijs op basis van onvergelijkbare aannames.")
  ];
  const middle = blocks.slice(2, -2); const offset = [...seed].reduce((sum, char) => sum + char.charCodeAt(0), 0) % middle.length;
  return [...blocks.slice(0, 2), ...middle.slice(offset), ...middle.slice(0, offset), ...blocks.slice(-2)];
}

function productExtra(name: string, group: ReturnType<typeof family>, source: string) { return [
  nlText(`configuratie-${source}`, `Configuratie van ${name}`, `${name} krijgt één revisiecode voor materiaal, geometrie, bereik, markering, aansluiting en verpakking. Monster, offerte, order en inspectierapport verwijzen daarmee naar dezelfde uitvoering.`, `Elke gewichts-, kleur-, maat- of uitrustingsvariant krijgt een eigen SKU, aantal, prijs, verzendgewicht en goedkeuringsstatus. Dit voorkomt dat verschillen binnen de categorie ${group.label.toLowerCase()} verborgen blijven.`),
  nlText(`gebruik-${source}`, `${name} in de beoogde gebruiksomgeving`, `Beoordeel ${name} op ledenprofiel, piekbelasting, gebruiksfrequentie, reiniging en beschikbare opslag. De monstertest bootst die omstandigheden na en kijkt verder dan het uiterlijk van een nieuw product.`, "Controleer voor commerciële series ook de samenhang tussen aangrenzende varianten, zodat gebruiker, exploitant en distributeur een voorspelbare greep, markering, bediening en vervanging krijgen."),
  nlTable(`vergelijk-${source}`, `Offertes voor ${name} vergelijken`, ["Vergelijkpunt", "Vraag", "Bewijs"], [["Constructie", "Welke waarde en tolerantie geldt?", "Tekening of SKU-blad"], ["Partijcontrole", "Hoe wordt het resultaat gecontroleerd?", "Meetfoto en QC-plan"], ["Monsterstatus", "Komt het monster overeen met serieproductie?", "Revisienummer"], ["Verpakking", "Hoe wordt het product beschermd?", "Doos- en palletspecificatie"]]),
  nlText(`assortiment-${source}`, `Rol van ${name} in het assortiment`, `${name} moet een benoemde rol hebben: kernproduct, premiumvariant, projectartikel of aanvulling. Dat bepaalt SKU-aantal, vervangingsvoorraad, retailverpakking, presentatie en herbestelfrequentie.`, `Beoordeel marge en omloopsnelheid per variant. Massa, volume en schaderisico kunnen ervoor zorgen dat twee vergelijkbaar geprijsde artikelen een andere landed cost en magazijnbehoefte hebben.`)
]; }

function guideExtra(profile: Guide, id: string) { return [
  nlText(`scope-${id}`, `Beslisscope: ${profile.keyword}`, `${profile.angle} Noteer eerst welke beslissing moet worden genomen, wie verantwoordelijk is en wanneer. Scheid invoerdata van aannames en markeer informatie die fabrikant, importeur of specialist moet bevestigen.`, "Een bruikbare analyse noemt alternatieven, beperkingen, afwijscriteria en het bewijs dat nodig is vóór monster, productie of verzending."),
  nlText(`data-${id}`, "Gegevens voor de analyse", `Verzamel voor ${profile.keyword} SKU's, aantallen, toepassing, markt, personalisatie, afleverpunt en planning. Voeg voor bestaande faciliteiten maten, foto's, gebruik, opslag en ervaring met eerdere partijen toe.`, "Noteer iedere waarde met eenheid en bron. Catalogusdata, monstermeetresultaat, leveranciersverklaring en inkoopvereiste hebben een andere bewijswaarde."),
  nlText(`scenario-${id}`, "Scenario's en afwegingen", `${profile.angle} Vergelijk minstens een basis-, besparings- en risicobeperkend scenario en toon per scenario de gevolgen voor prijs, MOQ, tijd, controle, verpakking, transport, voorraad en herhaalbaarheid.`, "De laagste fabrieksprijs hoeft na levering niet de laagste keuze te zijn. Materiaal, massa, doosvolume en containervulling verplaatsen kosten naar inspectie, vracht, opslag, schade en service."),
  nlTable(`bewijs-${id}`, `Bewijsplan voor ${profile.keyword}`, ["Fase", "Vraag", "Vastlegging"], [["RFQ", "Is de scope eenduidig?", "SKU-tabel en afwijkingen"], ["Monster", "Wat wordt goedgekeurd?", "Revisie, metingen en foto's"], ["Productie", "Wat wordt in het proces gecontroleerd?", "Instructie en QC-plan"], ["Verzending", "Is de partij compleet en conform?", "Rapport, paklijst en partij-ID"]]),
  nlText(`fouten-${id}`, `Veelgemaakte fouten bij ${profile.keyword}`, "Veelgemaakte fouten zijn offertes met verschillende scope, geen benoemde productrevisie, onduidelijke eenheden, vergeten verpakking, een uiterlijkmonster als productiemonster behandelen en algemene leveranciersclaims zonder meetbaar criterium.", "Neem ook geen tarief, procedure of producteis uit algemene informatie over voor een concrete transactie. Verifieer code, product, oorsprong en datum in officiële bronnen."),
  nlText(`vragen-${id}`, "Vragen voor de leverancier", `Laat de leverancier voor één benoemde SKU materiaal, proces, uitbesteding, gereedschappen, toleranties, sampling, verpakking en wijzigingsbeheer uitleggen. Voor ${profile.keyword} moet het antwoord over uw variant gaan, niet alleen over algemene fabriekscapaciteit.`, "Leg iedere afwijking vast en bepaal het effect op prijs, MOQ, termijn, monster en inspectiecriterium. Voeg de samenvatting toe aan RFQ en order."),
  nlText(`uitvoering-${id}`, "Resultaat invoeren in het orderproces", `${profile.angle} Vertaal conclusies naar eigenaar, datum, document en status. Open punten worden niet stilzwijgend geaccepteerd omdat de besteltermijn nadert.`, "Bewaar na goedkeuring specificatie, referentiemonster, artwork, rapporten, verpakkingsfoto's en verzenddocumenten als basis voor klachten en vervolgorders."),
  nlText(`verantwoordelijkheid-${id}`, "Verantwoordelijkheid en officiële bronnen", "PowerBaseFit kan product-, proces-, verpakkings- en exportgegevens leveren. De importeur beoordeelt verplichtingen voor product en transactie. Gebruik voor classificatie, heffingen en procedures actuele informatie van Access2Markets, TARIC en de bevoegde douane.", `Deze gids over ${profile.keyword} is een inkoopmethode en geen belofte over een tarief, certificering of geschiktheid. Leg definitieve eisen vóór de order vast.`)
]; }

function coreVersion(entity: ContentEntity, p: Profile) {
  const body = decisionBlocks(p.keyword, p.focus, entity.id); if (entity.type === "contact") body.push({ id: "inquiry-form", type: "custom", heading: "Beschrijf uw aanvraag", data: { component: "inquiry-form" } });
  return base({ slug: p.path.split("/").pop() || "nl", publicPath: p.path, title: p.title, description: p.description, h1: p.h1, body, faq: faq(p.keyword), author: dutchEditorialAuthor, reviewedBy: dutchTechnicalReviewer, schemaData: { brand: "PowerBaseFit", manufacturer: "PowerBaseFit", category: p.keyword, breadcrumbs: [{ name: "Home", path: "/nl" }, ...(p.path === "/nl" ? [] : [{ name: p.h1, path: p.path }])], extra: { primaryKeyword: p.keyword, searchIntent: p.intent } }, images: imagesFor(entity, p.h1), internalLinks: [{ targetContentId: "products-hub", label: "Bekijk alle producten" }, { targetContentId: "factory", label: "Bekijk productie en kwaliteitscontrole" }, { targetContentId: "oem-private-label", label: "Ontdek OEM en private label" }, { targetContentId: "contact", label: "Stuur een B2B-aanvraag" }] });
}

function productVersion(entity: ContentEntity) {
  const source = sourceSlug(entity), name = productName(entity), group = family(entity), slug = slugify(name), path = `/nl/producten/${group.slug}/${slug}`, keyword = `${name.toLowerCase()} voor sportscholen`;
  const focus = `${name} moet als benoemde serieconfiguratie worden beoordeeld: materiaal, geometrie, bereik, markeringen, aansluitingen, verpakking en reproduceerbaarheid. Koppel die gegevens aan toepassing, verkoopmodel en vervolgorders.`;
  return base({ slug, publicPath: path, title: `${name} voor sportscholen | OEM-fabrikant PowerBaseFit`, description: `${name} voor distributeurs en commerciële sportscholen: specificatie, monster, productie, QC, exportverpakking, OEM en B2B-offerte.`, h1: `${name} voor professionele sportscholen en B2B-inkoop`, body: [...decisionBlocks(keyword, focus, slug), ...productExtra(name, group, source)], faq: faq(keyword), author: dutchEditorialAuthor, reviewedBy: dutchTechnicalReviewer, schemaData: { sku: `PBF-${source.toUpperCase()}`, brand: "PowerBaseFit", manufacturer: "PowerBaseFit", material: entity.versions.en?.schemaData.material, category: group.label, specifications: [{ name: "Product", value: name }, { name: "Bereik", value: "Volgens goedgekeurde SKU en offerte" }, { name: "Doelgroep", value: "Sportscholen, distributeurs, importeurs en fitnessmerken" }], breadcrumbs: [{ name: "Home", path: "/nl" }, { name: "Producten", path: "/nl/producten" }, { name: group.label, path: `/nl/producten/${group.slug}` }, { name, path }], extra: { primaryKeyword: keyword, searchIntent: "product beoordelen en B2B-offerte aanvragen" } }, images: imagesFor(entity, name), internalLinks: [{ targetContentId: group.categoryId, label: `Bekijk categorie ${group.label}` }, { targetContentId: "factory", label: "Productie en kwaliteitscontrole" }, { targetContentId: "oem-private-label", label: "OEM en private label" }, { targetContentId: "contact", label: "Vraag een B2B-offerte aan" }] });
}

function guideVersion(entity: ContentEntity, p: Guide) {
  const path = `/nl/blog/${p.slug}`, focus = `${p.angle} De gids ondersteunt een ${p.intent} en vervangt geen productspecificatie, actuele overheidsinformatie of individueel importadvies.`;
  return base({ slug: p.slug, publicPath: path, title: p.title, description: `Nederlandstalige B2B-gids over ${p.keyword}: vergelijkingsmethode, beslismatrix, checklist, monster, QC, verpakking en leveranciersvragen.`, h1: p.h1, body: [...decisionBlocks(p.keyword, focus, entity.id), ...guideExtra(p, entity.id)], faq: faq(p.keyword), author: dutchEditorialAuthor, reviewedBy: dutchTechnicalReviewer, schemaData: { brand: "PowerBaseFit", manufacturer: "PowerBaseFit", category: "B2B-inkoopgids", specifications: [{ name: "Onderwerp", value: p.keyword }, { name: "Intentie", value: p.intent }], breadcrumbs: [{ name: "Home", path: "/nl" }, { name: "Inkoopgidsen", path: "/nl/blog" }, { name: p.h1, path }], extra: { primaryKeyword: p.keyword, searchIntent: p.intent } }, images: imagesFor(entity, p.h1), internalLinks: [{ targetContentId: "products-hub", label: "Bekijk de productcatalogus" }, { targetContentId: "factory", label: "Bekijk het productieproces" }, { targetContentId: "oem-private-label", label: "Ontdek OEM en private label" }, { targetContentId: "contact", label: "Stuur een B2B-aanvraag" }] });
}

function versionFor(entity: ContentEntity): LocalizedContentVersion {
  if (core[entity.id]) return coreVersion(entity, core[entity.id]);
  if (guides[entity.id]) return guideVersion(entity, guides[entity.id]);
  if (entity.type === "product") return productVersion(entity);
  throw new Error(`Dutch localization missing for ${entity.id} (${entity.type})`);
}

export function withDutchLocalization(manifest: ContentManifest): ContentManifest {
  return { ...manifest, entities: manifest.entities.map((entity) => {
    if (!isPublishedVersion(entity.versions.id) || excludedIds.has(entity.id)) return entity;
    if (entity.versions.nl) throw new Error(`Dutch localization duplicates ${entity.id}`);
    return { ...entity, versions: { ...entity.versions, nl: versionFor(entity) } };
  }) };
}
