import type { LocalizedContentVersion, LocalizedImage } from "../../lib/content/types";
import { answerBlock, checklistBlock, definitionBlock, germanEditorialAuthor, germanImagePath, germanTechnicalReviewer, specTable, textBlock } from "./de-content-helpers";

export type GermanGuideProfile = {
  id: string;
  enPath: string;
  dePath: string;
  title: string;
  description: string;
  h1: string;
  keyword: string;
  intent: string;
  direct: string;
  definition: string;
  decision: string;
  comparison: string[][];
  process: string;
  quality: string;
  practical: string;
  risks: string;
  checklist: string[];
  faq: Array<[string, string]>;
  links: Array<[string, string]>;
};

const commonImages: LocalizedImage[] = [
  { id: "fertigung", src: "/assets/dumbbell-production.webp", alt: "Reale Fertigung von Kurzhanteln und freien Gewichten bei PowerBaseFit", caption: "Realer Fertigungsprozess als Grundlage technischer Einkaufsentscheidungen." },
  { id: "bearbeitung", src: "/assets/resource-cnc-machining.webp", alt: "CNC-Bearbeitung von Metallbauteilen für Fitnessgeräte", caption: "Reale Bearbeitung von Komponenten für Fitnessgeräte." },
  { id: "oberflaeche", src: "/assets/resource-plate-finishing.webp", alt: "Oberflächenkontrolle bei Gewichtsscheiben und Fitnessgeräten", caption: "Reale Oberflächen- und Finishprüfung im Produktionsumfeld." }
];

export const germanGuideProfiles: GermanGuideProfile[] = [
  {
    id: "factory-guide", enPath: "/resources/evaluate-oem-gym-equipment-factory-china", dePath: "/de/blog/fitnessgeraete-fabrik-china-pruefen",
    title: "Fitnessgeräte-Fabrik in China prüfen: B2B-Leitfaden | PowerBaseFit", description: "So prüfen Importeure eine Fitnessgeräte-Fabrik in China: Produktkompetenz, Muster, QC, OEM, Kapazität, Verpackung, Dokumentation und Audit.", h1: "So prüfen Sie eine Fitnessgeräte-Fabrik in China", keyword: "Fitnessgeräte Hersteller China prüfen", intent: "Lieferantenprüfung vor B2B-Bestellung",
    direct: "Prüfen Sie nicht zuerst den niedrigsten Preis, sondern ob die Fabrik Ihr konkretes Produkt reproduzierbar fertigen, messen, dokumentieren und verpacken kann. Verlangen Sie Modell- und Prozessnachweise, ein freigegebenes Muster, messbare Abnahmekriterien, realistische Kapazitäts- und Lieferangaben sowie eine klare Verantwortlichkeit für Abweichungen.",
    definition: "Eine Fabrikprüfung ist die strukturierte Bewertung von Unternehmen, Produktionsort, Produktkompetenz, Prozessen, Qualitätssicherung, Kapazität, Kommunikation und Exportvorbereitung. Sie kann Dokumentenprüfung, Video- oder Vor-Ort-Audit, Musterbewertung und unabhängige Inspektion kombinieren.",
    decision: "Beginnen Sie mit einem Produkt, das für Ihren Auftrag repräsentativ ist. Eine Fabrik kann gute Racks fertigen und trotzdem wenig Erfahrung mit Gewichtstoleranzen von Bumper Plates haben. Fragen Sie nach realen Fertigungsschritten, Werkzeugen, kritischen Merkmalen und Prüfmitteln. Vergleichen Sie Antworten mit Muster, Datenblatt und Angebot. Widersprüche sind wichtiger als eine perfekte Präsentation.",
    comparison: [["Handelsunternehmen", "breites Sortiment und Koordination", "Transparenz über tatsächliche Produktionsstellen"], ["Spezialisierte Fabrik", "tiefe Prozesskenntnis einer Produktgruppe", "begrenzte Breite und Kapazitätsabhängigkeit"], ["Integrierter Lieferant", "mehrere Prozesse und Projektkoordination", "klare Verantwortlichkeit je Prozess"], ["Auditbericht", "strukturierte Momentaufnahme", "Aktualität und Bezug zum bestellten Produkt"]],
    process: "Die Prüfung läuft in Stufen: Unternehmensidentität und Standort, Produkt- und Prozessabgleich, Dokumentenliste, Videotermin oder Audit, Musterauftrag, technische Freigabe, Pilot- oder Serienauftrag und Vorversandinspektion. Offene Punkte werden mit Verantwortlichem und Termin dokumentiert. Bei einem neuen Material, Werkzeug oder Unterlieferanten wird die Bewertung aktualisiert.",
    quality: "Fordern Sie Beispiele für Prüfplan, Messmittel, Kalibrierstatus, Wareneingang, Zwischenkontrollen, Endprüfung und Umgang mit nichtkonformer Ware. Bei freien Gewichten gehören Gewicht, Maße, Verbindung, Oberfläche, Kennzeichnung und Verpackung dazu; bei Racks zusätzlich Geometrie, Schweißnähte, Beschichtung, Funktion, Hardware und Montage.",
    practical: "Ein professioneller Einkäufer stellt dieselbe technische Frage an mehrere Anbieter und bewertet Vollständigkeit, Nachweise und Reaktionsqualität. Er trennt verifizierte Fakten von Versprechen. Videoaufnahmen sollten Datum, Produktcode und Prozesskontext zeigen. Bei hohem Risiko wird ein unabhängiger Auditor oder Inspektor beauftragt.",
    risks: "Warnsignale sind wechselnde Firmennamen oder Bankdaten, unklare Produktionsadresse, ausschließlich fremde Katalogbilder, unmögliche Lieferzeiten, pauschale Zertifikatsversprechen, fehlende Messkriterien und Widerstand gegen Muster oder Inspektion. Ein einzelnes Warnsignal beweist keinen Betrug, verlangt aber Klärung vor Zahlung oder Werkzeugfreigabe.",
    checklist: ["Unternehmensname, Adresse und Ansprechpartner verifizieren", "Produktkompetenz am konkreten Modell prüfen", "Reale Prozesse und Maschinen ansehen", "Material- und Unterlieferantenkontrolle verstehen", "Messmittel und Prüfaufzeichnungen bewerten", "Muster mit Spezifikation vergleichen", "Kapazität und Lieferplan plausibilisieren", "OEM- und Änderungsfreigabe dokumentieren", "Verpackungs- und Exportprozess prüfen", "Unabhängige Inspektion nach Risiko planen"],
    faq: [["Reicht ein Video-Call für die Fabrikprüfung?", "Er ist ein guter erster Schritt, ersetzt bei hohem Auftragsrisiko aber nicht Muster, Dokumente oder gegebenenfalls ein unabhängiges Audit."], ["Welche Unterlagen sollte eine Fabrik vorlegen?", "Projektbezogen Unternehmensdaten, Produktdaten, Prozess- und Prüfinformationen, Musterfreigabe und Packdaten. Zertifikate werden nur nach Relevanz und Gültigkeit bewertet."], ["Wann ist eine Vor-Ort-Prüfung sinnvoll?", "Bei hohem Auftragswert, neuem Werkzeug, komplexer Fertigung, wiederholten Widersprüchen oder besonders kritischen Zielmarktanforderungen."], ["Wie vermeidet man gefälschte Referenzen?", "Verlassen Sie sich nicht auf Logos oder Namen in Präsentationen. Prüfen Sie reale Produkte, Prozesse und unabhängig bestätigbare Fakten."]],
    links: [["factory", "PowerBaseFit-Fertigung"], ["pre-shipment-inspection-free-weights", "Vorversandinspektion"], ["oem-sample-approval-free-weights", "Musterfreigabe"], ["contact", "Fabrikfrage stellen"]]
  },
  {
    id: "dumbbells-guide", enPath: "/resources/how-to-choose-commercial-dumbbells", dePath: "/de/blog/kurzhanteln-fitnessstudio-auswaehlen",
    title: "Kurzhanteln für Fitnessstudios auswählen: B2B-Leitfaden", description: "Gummi, PU, TPU, CPU, Stahl oder verstellbar? Kurzhanteln für Studios nach Nutzung, Gewichtsbereich, Rack, Material, QC, OEM und Kosten auswählen.", h1: "Kurzhanteln für ein professionelles Fitnessstudio auswählen", keyword: "Kurzhanteln Fitnessstudio auswählen", intent: "Kommerzielle Produkt- und Sortimentsentscheidung",
    direct: "Wählen Sie Kurzhanteln nach Studiotyp, Nutzerzahl, Gewichtsabstufung, Rack, Oberfläche, Wartung und Nachbestellung. Gummi-Hex-Modelle sind vielseitig, Rundhanteln bilden ein geschlossenes Rack-Sortiment, PU/TPU/CPU eignen sich für differenzierte Markenpositionierung, Metallhanteln sind kompakt und verstellbare Systeme sparen Platz.",
    definition: "Kommerzielle Kurzhanteln sind Freigewichte, deren Konstruktion und Sortiment für wiederholte Nutzung, geordnete Lagerung und planbare Ersatzbeschaffung ausgelegt werden. Die Eignung ergibt sich aus Modell, Intensität, Umgebung und Prüfkriterien, nicht aus einem einzelnen Materialnamen.",
    decision: "Ermitteln Sie zuerst, welche Nutzer gleichzeitig trainieren und welche Gewichte am häufigsten gebraucht werden. Planen Sie mehr Paare im Kernbereich und prüfen Sie, ob schwere Endgewichte wirtschaftlich genutzt werden. Ordnen Sie das Sortiment einem Rack zu. Berücksichtigen Sie Griffweite, Kopfmaße, Boden, Reinigung, Geruch, Markenbild und den Aufwand einer späteren Ergänzung.",
    comparison: [["Gummi-Hex", "Functional und allgemeines Studiotraining", "Geruch, Verbindung, Kopfmaße"], ["Gummi-Rund", "durchgehende Racklinie und hohe Gewichte", "Racksicherheit, Durchmesser, Oberfläche"], ["PU/TPU/CPU", "hochwertige oder markenspezifische Programme", "Rezeptur, Farbe, Haftung, Chargenkonsistenz"], ["Stahl/Chrom", "kompakte Premiumbereiche", "Oberfläche, Kanten, Korrosionsschutz"], ["Verstellbar", "begrenzte Fläche", "Verriegelung, Wechselgeschwindigkeit, Ersatzteile"]],
    process: "Aus einer Flächen- und Nutzeranalyse entsteht eine Gewichtsmatrix. Danach folgen Material- und Modellvergleich, Rackabgleich, Angebotsanfrage, Musterprüfung und Pilotfreigabe. Bei Eigenmarken werden Logo, Farbe und Verpackung ergänzt. Vor Serie werden Gewichtstoleranz, Griff, Kopf, Verbindung, Oberfläche und Packweise dokumentiert.",
    quality: "Wiegen Sie mehrere Stücke aus leichten, mittleren und schweren Bereichen. Messen Sie Griff und Kopf, prüfen Sie Ausrichtung und Verbindung und vergleichen Sie Oberfläche sowie Kennzeichnung. Bei beschichteten Modellen sind Farbunterschiede, Blasen, Abrieb und Geruch relevant. Das Rack darf keine unzulässigen Druckstellen erzeugen.",
    practical: "Ein Studio mit vielen Einsteigern benötigt andere Stückzahlen als ein Kraftsportzentrum. Hotels und kleine Studios können einen engeren Bereich wählen. Fachhändler sollten Verpackung und Einzelverkauf beachten. Für alle gilt: Der mittlere Gewichtsbereich darf nicht nur deshalb knapp geplant werden, weil ein Komplettset optisch ausgewogen aussieht.",
    risks: "Häufige Fehler sind ein zu großer Bereich mit zu wenigen Paaren, ein unpassendes Rack, unklare Toleranzen, Materialentscheidung nur nach Preis, fehlende Ersatzstrategie und Logo-Freigabe an nur einem Gewicht. Auch ein schweres Endgewicht kann unnötig sein, wenn Zielgruppe und Fläche es nicht nutzen.",
    checklist: ["Studiotyp und gleichzeitige Nutzer", "Gewichte und Paare je Gewicht", "Kopfgeometrie und Rack", "Material und Oberfläche", "Griffdurchmesser und Rändelung", "Gewichtstoleranz und Stichprobe", "Boden, Reinigung und Wartung", "Logo und Kennzeichnung", "Verpackung und Wareneingang", "Nachbestellbarkeit"],
    faq: [["Welche Kurzhantelform eignet sich für Bodentraining?", "Hexagonale Köpfe reduzieren Wegrollen. Geeigneter Boden und sachgerechte Nutzung bleiben erforderlich."], ["Wie viele Paare braucht ein Fitnessstudio?", "Das hängt von Nutzerzahl und Trainingsprofil ab. Häufig genutzte Gewichte sollten mehrfach vorhanden sein."], ["Sind teurere Materialien automatisch langlebiger?", "Nein. Rezeptur, Konstruktion, Nutzung, Rack, Reinigung und Qualitätskontrolle beeinflussen die Leistung gemeinsam."], ["Sollte man KG- oder LB-Hanteln für Deutschland bestellen?", "Für DACH ist KG in der Regel die natürliche Hauptkennzeichnung. Ein abweichendes System muss zum Vertriebskanal passen."]],
    links: [["dumbbells-category", "Kurzhanteln ansehen"], ["commercial-dumbbell-set-planning", "Kurzhantelsatz planen"], ["dumbbell-weighing-guide", "Gewichtskontrolle"], ["contact", "Sortiment anfragen"]]
  },
  {
    id: "plates-guide", enPath: "/resources/weight-plates-vs-bumper-plates-b2b-guide", dePath: "/de/blog/gewichtsscheiben-vs-bumper-plates",
    title: "Gewichtsscheiben vs. Bumper Plates: B2B-Vergleich", description: "Gewichtsscheiben oder Bumper Plates? Vergleich für Studios und Einkäufer nach Training, 50-mm-Aufnahme, Dicke, Material, Boden, QC, Verpackung und Kosten.", h1: "Gewichtsscheiben oder Bumper Plates für Fitnessstudios?", keyword: "Gewichtsscheiben oder Bumper Plates", intent: "Produktvergleich für Studio- und Handelsbeschaffung",
    direct: "Bumper Plates sind die richtige Wahl, wenn olympische Hebeübungen und kontrolliertes Absetzen auf geeignetem Boden vorgesehen sind. Klassische Guss-, Stahl-, Gummi- oder Griffscheiben sind für Maschinen, Racks und allgemeines Krafttraining oft platz- oder kosteneffizienter. Viele Studios benötigen beide Gruppen.",
    definition: "Gewichtsscheiben ist der Oberbegriff für auf Stangen oder Maschinen geladene Gewichte. Bumper Plates sind elastomere Scheiben mit weitgehend einheitlichem Außendurchmesser für bestimmte dynamische Hebe- und Absetzvorgänge. Nicht jede gummierte Scheibe ist eine Bumper Plate.",
    decision: "Ordnen Sie jede Station einer Trainingsart zu. Prüfen Sie Stangenaufnahme, Hülsenlänge, erforderliche Gesamtlast, Scheibendicke, Boden und Geräusch. Griffscheiben erleichtern Wechsel an Maschinen; dünne Stahl- oder Gussvarianten ermöglichen hohe Lasten. Bumper Plates schützen nicht vor unsachgemäßem Boden oder falschem Fallenlassen.",
    comparison: [["Bumper Plate", "Gewichtheben und Functional Training", "Dicke, Einsatz, Material, Boden"], ["Gummi-Griffscheibe", "Racks und plate-loaded Maschinen", "Griffe, Mittelloch, Oberfläche"], ["Gusseisen", "klassische Kraftbereiche", "Gussbild, Gewicht, Beschichtung"], ["Stahl", "hohe Last bei geringer Dicke", "Maß, Kante, Korrosionsschutz"], ["Competition-Ausführung", "definierte Präzision und Optik", "Normbezug, Kalibrierung, Dokumentation"]],
    process: "Erfassen Sie Stangen und Maschinen, teilen Sie Trainingszonen ein und berechnen Sie Last pro Station. Legen Sie danach Gewichte und Stückzahlen fest. Vergleichen Sie Datenblätter und Muster. Bei gemischten Scheiben prüfen Sie Lagerung und Kennzeichnung, damit Nutzer die richtige Ausführung finden.",
    quality: "Kontrolliert werden Gewicht, Außendurchmesser, Dicke, Mittelloch, Planlage, Einsatzverbindung, Oberfläche und Kennzeichnung. Bei Bumper Plates sind dünne leichte Scheiben besonders zu betrachten. Bei Griffscheiben werden Griffbereiche und Materialübergänge geprüft.",
    practical: "Ein Studio kann Bumper Plates an Plattformen einsetzen und Griffscheiben an Maschinen oder allgemeinen Racks. So wird nicht jeder Arbeitsplatz mit der teuersten oder dicksten Scheibe ausgestattet. Fachhändler sollten Produktbezeichnungen klar trennen, damit Kunden keine gummierte Griffscheibe mit einer für Drops vorgesehenen Bumper Plate verwechseln.",
    risks: "Fehler entstehen durch unbestätigte 50-mm-Kompatibilität, zu dicke Scheiben für die gewünschte Last, ungeeigneten Boden, fehlende Paarzahlen, unklare Gewichtstoleranz und die Annahme, jede schwarze Scheibe sei technisch gleich. Ein reiner Kilopreis blendet Einsatz, Haltbarkeit, Platz und Verpackung aus.",
    checklist: ["Trainingsart je Zone", "Stangen- und Maschinenaufnahme", "Last und Hülsenlänge", "Durchmesser und Dicke", "Material und Einsatz", "Boden und Geräusch", "Gewichtstoleranz", "Griffe und Handhabung", "Verpackung und Lagerung", "Nachbestellstrategie"],
    faq: [["Kann man Bumper Plates an jeder Langhantel verwenden?", "Nur wenn Aufnahme, Hülse, Belastung und vorgesehene Nutzung kompatibel sind."], ["Sind Bumper Plates besser für alle Fitnessstudios?", "Nein. Sie sind für bestimmte Trainingsarten sinnvoll; für Maschinen und platzkritische hohe Lasten können andere Scheiben besser passen."], ["Warum sind leichte Bumper Plates oft dicker oder empfindlicher?", "Material und Geometrie müssen bei geringer Masse den gleichen Außendurchmesser bilden. Konstruktion und Nutzung sind deshalb besonders wichtig."], ["Können beide Scheibenarten dieselbe Marke tragen?", "Ja, wenn Logo, Farbe und Kennzeichnung je Konstruktion bemustert und konsistent geplant werden."]],
    links: [["weight-plates-category", "Gewichtsscheiben ansehen"], ["training-vs-competition-bumper-plates", "Training vs. Competition"], ["plate-materials-b2b", "Materialvergleich"], ["contact", "Scheiben anfragen"]]
  },
  {
    id: "bumper-manufacturing-guide", enPath: "/resources/how-are-bumper-plates-made", dePath: "/de/blog/wie-werden-bumper-plates-hergestellt",
    title: "Wie werden Bumper Plates hergestellt? Materialien & QC", description: "Herstellung von Bumper Plates: Material, Stahleinsatz, Formgebung, Gewicht, Maße, Qualitätskontrolle, Logo, Verpackung und Lieferantenprüfung.", h1: "Wie werden Bumper Plates hergestellt?", keyword: "Bumper Plates Herstellung", intent: "Fertigungswissen und Lieferantenbewertung",
    direct: "Bumper Plates entstehen aus einer Elastomer- oder Gummimischung, einem metallischen Mitteleinsatz und einem definierten Form- und Aushärtungsprozess. Nach dem Entformen folgen Finish, Kennzeichnung, Gewichtskorrektur oder -prüfung, Maßkontrolle, Funktionsprüfung und Verpackung. Rezeptur, Einsatzverbindung und Prozessstabilität bestimmen die Qualität wesentlich.",
    definition: "Eine Bumper Plate ist eine Gewichtsscheibe mit elastomerem Körper und 50-mm-Mittelaufnahme, die für bestimmte dynamische Langhantelübungen ausgelegt wird. Einheitlicher Außendurchmesser bedeutet nicht identische Dicke oder Konstruktion bei allen Gewichten.",
    decision: "Fragen Sie den Lieferanten nach Materialart, Neu- oder Recyclinganteil soweit relevant, Härte, Einsatzkonstruktion, Werkzeug, Aushärtung, Gewichtstoleranz und Prüfung. Ein Foto zeigt weder Verbindung noch Prozessstabilität. Muster verschiedener Gewichte sind wichtiger als nur eine 20-kg-Referenz.",
    comparison: [["Virgin Rubber", "kontrollierbare Rezeptur und Oberfläche", "Deklaration, Geruch, Härte"], ["Recycling-/Granulatanteil", "andere Kosten- und Materialcharakteristik", "Konsistenz, Bindung, Oberfläche"], ["PU/CPU/TPU", "alternative Elastomer- und Finishsysteme", "Rezeptur, Werkzeug, Verbindung"], ["Stahleinsatz", "Kraftübertragung zur Hülse", "Maß, Ausrichtung, Haftung"], ["Farbkennzeichnung", "schnelle Gewichtserkennung", "Referenz, Chargenkonsistenz, Abrieb"]],
    process: "Der Ablauf umfasst Rohstoffdosierung und Mischung, Vorbereitung des Stahleinsatzes, Einlegen in das Werkzeug, Formgebung unter Temperatur und Druck, Aushärten, Entformen, Entfernen von Graten, Oberflächenfinish, Markierung, Verwiegung und Verpackung. Prozessparameter unterscheiden sich nach Material und Werkzeug und dürfen nicht pauschal gleichgesetzt werden.",
    quality: "Kontrolliert werden Gewicht, Durchmesser, Dicke, Mittelloch, Planlage, Einsatzposition, Oberfläche, Härte beziehungsweise materialbezogene Merkmale, Kennzeichnung und Geruch. Funktionsprüfungen müssen ein definiertes Verfahren verwenden. Eine hohe Anzahl beliebiger Drops ist ohne Boden, Höhe, Last und Akzeptanzkriterium nicht vergleichbar.",
    practical: "Einkäufer sollten leichte, mittlere und schwere Scheiben bemustern. Leichte Scheiben sind dünner und können andere Risiken zeigen; schwere Scheiben beanspruchen Verpackung und Handling stärker. Speichern Sie Muster, Materialangabe, Werkzeugstand, Farbreferenz und Prüfplan für Nachbestellungen.",
    risks: "Risiken sind schlecht vorbereitete Einsätze, ungleichmäßige Mischung, Luftstellen, unvollständige Aushärtung, falsches Gewicht, verzogene Scheiben, abweichende Mittellöcher, unleserliche Markierung und schwache Kartons. Eine pauschale Materialbezeichnung verhindert diese Fehler nicht.",
    checklist: ["Material und Rezeptur deklarieren", "Einsatzkonstruktion und Mittelloch bestätigen", "Werkzeug und Gewichte festlegen", "Muster mehrerer Gewichte prüfen", "Gewichts- und Maßtoleranzen vereinbaren", "Oberfläche, Farbe und Geruch definieren", "Funktionsprüfung beschreiben", "Logo und Kennzeichnung freigeben", "Karton und Palette testen", "Nachbestellstand dokumentieren"],
    faq: [["Aus welchem Material bestehen Bumper Plates?", "Je nach Produkt aus Gummi oder anderen Elastomersystemen mit metallischem Mitteleinsatz. Die genaue Rezeptur muss am Modell bestätigt werden."], ["Warum haben verschiedene Gewichte unterschiedliche Dicke?", "Bei gleichem Außendurchmesser wird die Masse unter anderem über Materialvolumen und Konstruktion erreicht."], ["Wie wird die Haltbarkeit getestet?", "Mit einem definierten Verfahren aus Last, Höhe, Untergrund, Wiederholungen und Akzeptanzkriterium. Unvollständige Drop-Zahlen sind nicht vergleichbar."], ["Kann ein eigenes Logo in die Scheibe integriert werden?", "Ja, abhängig von Werkzeug, Kennzeichnungsverfahren, Design und Menge. Mehrere Gewichte sollten freigegeben werden."]],
    links: [["cpu-bumper-plate", "CPU Bumper Plate"], ["rubber-bumper-plate", "Gummi Bumper Plate"], ["factory", "Fertigung"], ["contact", "Bumper-Plate-Anfrage"]]
  },
  {
    id: "dumbbell-weighing-guide", enPath: "/resources/how-are-dumbbells-weighed", dePath: "/de/blog/kurzhanteln-gewichtstoleranz-pruefen",
    title: "Kurzhantel-Gewicht prüfen: Toleranz & Fabrik-QC", description: "Wie werden Kurzhanteln gewogen? Messmittel, Stichprobe, Toleranz, leichte und schwere Gewichte, Paarabgleich, Kalibrierung, Dokumentation und Abnahme.", h1: "Wie wird das Gewicht von Kurzhanteln in der Fabrik geprüft?", keyword: "Kurzhanteln Gewichtstoleranz", intent: "Qualitätskontrolle und Vorversandprüfung",
    direct: "Kurzhanteln werden auf einer zum Gewichtsbereich passenden, geprüften Waage gemessen und mit Sollgewicht sowie vereinbarter Toleranz verglichen. Der Prüfplan umfasst mehrere Gewichte, Paare und Positionen der Charge. Ergebnis, Messmittel, Datum und Entscheidung werden dokumentiert.",
    definition: "Gewichtstoleranz ist die zulässige Abweichung zwischen Nenngewicht und gemessenem Gewicht. Sie kann absolut oder prozentual angegeben werden. Ohne Messmethode, Waagenbereich, Auflösung und Stichprobe ist eine Toleranzangabe unvollständig.",
    decision: "Definieren Sie, ob einzelne Hanteln oder Paare bewertet werden, wie Rundung erfolgt und welche Gewichte kritisch sind. Eine Waage für schwere Hanteln kann für sehr leichte Modelle zu grob auflösen. Prüfen Sie nicht nur bequem erreichbare Kartons, sondern verteilen Sie die Stichprobe über Charge und Gewichtsbereich.",
    comparison: [["100-%-Prüfung", "jedes Stück wird gewogen", "höherer Aufwand, klare Kennzeichnung"], ["Stichprobe", "definierte Auswahl pro Gewicht", "repräsentative Verteilung erforderlich"], ["Absolute Toleranz", "fester kg- oder g-Wert", "Auswirkung auf leichte/schwere Gewichte"], ["Prozentuale Toleranz", "Abweichung relativ zum Soll", "Rundung und Grenzwerte"], ["Paarabgleich", "Differenz innerhalb eines Paars", "zusätzlich zur Einzelabweichung"]],
    process: "Waage aufstellen und prüfen, Referenzgewicht verwenden, Modell und Nenngewicht identifizieren, Oberfläche reinigen, Hantel zentriert auflegen, Wert nach festgelegter Stabilisierung ablesen, Ergebnis erfassen und Grenzwert anwenden. Abweichende Stücke werden getrennt, nachgemessen und entsprechend dem vereinbarten Verfahren bewertet.",
    quality: "Messmittel müssen zum Bereich passen und einen nachvollziehbaren Prüf- oder Kalibrierstatus besitzen. Die Aufzeichnung nennt Waage, Auflösung, Soll, Ist, Abweichung, Modell, Charge und Prüfer. Bei auffälligem Trend wird nicht nur das Einzelstück, sondern der Prozess untersucht.",
    practical: "Für ein Set sollten leichte, mittlere und schwere Gewichte separat ausgewertet werden. Paarweise Verpackung braucht einen Paarabgleich. Bei Einzelverkauf ist die Identität jeder Einheit wichtig. Eine unabhängige Inspektion kann denselben Prüfplan verwenden, damit Fabrik- und Drittdaten vergleichbar sind.",
    risks: "Typische Fehler sind ungeeignete Waagen, fehlende Nullkontrolle, Rundung ohne Regel, Verwechslung von KG und LB, zu kleine Stichprobe, nur ein Gewicht pro Sortiment und das Wiegen verpackter Ware ohne Tara. Auch ein korrektes Durchschnittsgewicht kann einzelne unzulässige Ausreißer verdecken.",
    checklist: ["Nenngewichte und Einheiten", "Toleranz je Gewichtsbereich", "Waagenbereich und Auflösung", "Prüf- oder Kalibrierstatus", "Null- und Referenzkontrolle", "Stichprobe je Gewicht", "Paarabgleich", "Charge und Kartonposition", "Umgang mit Abweichungen", "Messprotokoll archivieren"],
    faq: [["Welche Toleranz ist bei Kurzhanteln normal?", "Es gibt keine universelle Zahl für alle Produkte. Toleranz, Messmethode und Stichprobe werden vor der Bestellung vereinbart."], ["Muss jede Kurzhantel gewogen werden?", "Das hängt von Risiko, Prozess und Vereinbarung ab. Eine definierte Stichprobe kann ausreichend sein; kritische Programme können 100-%-Prüfung verlangen."], ["Warum ist der Paarabgleich wichtig?", "Zwei Hanteln können einzeln innerhalb der Toleranz liegen, aber spürbar unterschiedlich sein. Ein Paargrenzwert kann dies begrenzen."], ["Kann ein Inspektor das Gewicht vor Versand prüfen?", "Ja, wenn Modelle, Stichprobe, Waage, Toleranz und Entscheidungsregel im Inspektionsauftrag stehen."]],
    links: [["dumbbells-category", "Kurzhanteln"], ["pre-shipment-inspection-free-weights", "Vorversandinspektion"], ["free-weight-reorder-batch-consistency", "Chargenkonsistenz"], ["contact", "QC-Anfrage"]]
  },
  {
    id: "plate-materials-b2b", enPath: "/resources/cast-iron-rubber-urethane-weight-plates", dePath: "/de/blog/gusseisen-gummi-pu-gewichtsscheiben-vergleich",
    title: "Gusseisen, Gummi oder PU Gewichtsscheiben: Vergleich", description: "Gewichtsscheiben aus Gusseisen, Gummi, PU, TPU und CPU im B2B-Vergleich: Einsatz, Dicke, Oberfläche, Geruch, Handling, QC und Kosten.", h1: "Gusseisen-, Gummi- und PU-Gewichtsscheiben vergleichen", keyword: "Gewichtsscheiben Gusseisen Gummi PU Vergleich", intent: "Materialvergleich vor Beschaffung",
    direct: "Gusseisen ist kompakt und klassisch, gummierte Scheiben verbessern Oberflächenschutz und Handhabung, PU/TPU/CPU können ein anderes Finish und Markenbild bieten. Keine Materialgruppe ist pauschal die beste: Anwendung, Hülsenplatz, Griff, Geruch, Reinigung, Budget und Nachbestellung entscheiden.",
    definition: "Die Materialbezeichnung beschreibt nur einen Teil der Scheibe. Kern, Beschichtung, Einsatz, Härte, Dicke, Griffgeometrie und Herstellungsprozess bestimmen gemeinsam die tatsächliche Ausführung.",
    decision: "Vergleichen Sie pro Modell Datenblatt und Muster. Messen Sie Dicke, Mittelloch und Gewicht. Beurteilen Sie Griff, Kanten, Oberfläche, Farbe und Geruch. Fragen Sie nach Material- und Prozesskonstanz für Nachbestellungen. Für hohe Lasten kann Scheibendicke wichtiger sein als eine weichere Oberfläche.",
    comparison: [["Gusseisen", "kompakt und klassisch", "Gussbild, Beschichtung, Korrosion"], ["Gummibeschichtet", "breite Studioanwendung", "Geruch, Haftung, Oberfläche"], ["PU", "hochwertiges Finish", "Rezeptur, Farbe, Kontaktspuren"], ["TPU", "thermoplastische Oberfläche", "Formbild, Materialcharge, Verbindung"], ["CPU", "gegossenes Elastomersystem", "Aushärtung, Haftung, Kennzeichnung"]],
    process: "Gusseisen wird gegossen, entgratet, bearbeitet und beschichtet. Beschichtete Varianten kombinieren Kern oder Grundkörper mit Gummi oder Elastomer, gefolgt von Aushärtung, Finish und Kennzeichnung. Einsätze und Mittellöcher werden ausgerichtet und geprüft. Der genaue Ablauf wird am Produkt bestätigt.",
    quality: "Prüfen Sie Gewicht, Planlage, Mittelloch, Dicke, Griffbereiche, Beschichtungsübergänge, Blasen, Farbdifferenz und Kennzeichnung. Bei Metall sind Kanten und Korrosionsschutz relevant; bei Elastomeren Geruch, Härte und Haftung. Muster sollten mehrere Gewichte abdecken.",
    practical: "Maschinenbereiche profitieren oft von Griffscheiben, schwere freie Lasten von dünneren Konstruktionen. Premiumstudios können einheitliche PU- oder CPU-Linien wählen, müssen aber Ersatz und Chargenfarbe planen. Ein Fachhändler sollte Materialien korrekt beschreiben und keine universellen Haltbarkeitsversprechen machen.",
    risks: "Risiken sind Materialnamen ohne Rezeptur- oder Konstruktionsbezug, ungeprüfte Geruchsversprechen, zu dicke Scheiben, schwache Beschichtung, korrodierende Kanten, unpassende Griffe und Farbabweichungen bei Nachbestellung. Ein höherer Preis garantiert keine bessere Prozesskontrolle.",
    checklist: ["Anwendung und Station", "Gesamtlast und Hülsenplatz", "Kern und Beschichtung", "Mittelloch und Einsatz", "Gewicht und Toleranz", "Dicke und Planlage", "Griffe und Kanten", "Geruch, Farbe und Reinigung", "Muster und Nachbestellung", "Verpackung"],
    faq: [["Sind PU-Scheiben geruchsfrei?", "Pauschale Aussagen sind nicht belastbar. Material, Produktion, Lagerung und Verpackung beeinflussen den Geruch; ein Muster ist erforderlich."], ["Welche Scheiben sind am dünnsten?", "Stahl- und manche Gusseisenkonstruktionen sind oft kompakter, aber die tatsächliche Dicke muss je Gewicht bestätigt werden."], ["Sind gummierte Scheiben Bumper Plates?", "Nicht automatisch. Eine gummierte Griffscheibe kann für Racks und Maschinen gedacht sein und ist nicht zwingend für Drops ausgelegt."], ["Wie bleibt die Farbe bei Nachbestellungen konsistent?", "Farbreferenz, Material, Prozess und Musterstand werden gespeichert und vor der Wiederholungscharge bestätigt."]],
    links: [["weight-plates-category", "Gewichtsscheiben"], ["plates-guide", "Scheibenarten"], ["free-weight-reorder-batch-consistency", "Nachbestellungen"], ["contact", "Material anfragen"]]
  },
  {
    id: "commercial-free-weight-rfq", enPath: "/resources/commercial-free-weight-rfq-checklist", dePath: "/de/blog/rfq-freie-gewichte-anfrage-checkliste",
    title: "RFQ für Kurzhanteln & Gewichtsscheiben: Checkliste", description: "Welche Angaben gehören in eine RFQ für freie Gewichte? Modelle, Gewichte, Mengen, Material, Toleranzen, Logo, Verpackung, QC, Incoterm und Lieferort.", h1: "RFQ-Checkliste für Kurzhanteln und Gewichtsscheiben", keyword: "RFQ Fitnessgeräte Checkliste", intent: "Angebotsanfrage vorbereiten",
    direct: "Eine gute RFQ nennt Unternehmen und Zielmarkt, Produktcode oder klare Produktbeschreibung, Varianten und Mengen, Material und technische Daten, Toleranzen, Logo und Verpackung, Qualitäts- und Inspektionsanforderungen, Lieferort, Incoterm und Termin. So vergleichen Sie Angebote auf derselben Grundlage.",
    definition: "RFQ steht für Request for Quotation. Sie ist eine strukturierte Angebotsanfrage, die technische, qualitative, logistische und kaufmännische Angaben zusammenführt. Eine RFQ ist genauer als die Frage nach einem allgemeinen Stück- oder Kilopreis.",
    decision: "Vergeben Sie jeder Position einen Code. Trennen Sie Gewichte und Varianten in einzelnen Zeilen. Markieren Sie Pflicht- und Wunschmerkmale. Fordern Sie Anbieter auf, Abweichungen und Annahmen sichtbar zu nennen. Vergleichen Sie Preis, MOQ, Muster, Produktionszeit, Verpackung und Incoterm erst, wenn die technische Basis gleich ist.",
    comparison: [["Allgemeine Anfrage", "Produktname und Gesamtmenge", "schnell, aber kaum vergleichbar"], ["Technische RFQ", "SKU, Daten, Toleranzen, QC", "belastbarer Angebotsvergleich"], ["OEM-RFQ", "zusätzlich Logo, Farbe, Verpackung", "Muster und Freigabe erforderlich"], ["Projekt-RFQ", "Raum, Nutzer, Produktmix, Lieferung", "Koordination mehrerer Gruppen"], ["Nachbestell-RFQ", "bestehender Modell- und Versionsstand", "Fokus auf Konsistenz und Änderungen"]],
    process: "Sammeln Sie Bedarf und Zielmarkt, erstellen Sie SKU-Liste, ergänzen Sie Spezifikation, definieren Sie Abnahmekriterien, fügen Sie Grafik und Verpackung hinzu und nennen Sie Lieferbedingung. Nach Anbieterfragen aktualisieren Sie die RFQ versioniert. Das finale Angebot verweist auf denselben Stand.",
    quality: "QC-Anforderungen gehören in die RFQ, nicht erst in die Inspektion. Nennen Sie Gewicht oder Maß, Oberfläche, Funktion, Kennzeichnung, Stichprobe und erforderliche Nachweise. Vermeiden Sie unmessbare Begriffe. Bei kritischen Merkmalen ist ein Muster oder eine Zeichnung Teil der Referenz.",
    practical: "Eine Tabelle mit einer Zeile pro SKU ist meist wirksamer als lange E-Mails. Dokumentieren Sie offene Punkte separat. Bitten Sie jeden Anbieter, nicht angebotene oder geänderte Merkmale zu markieren. Verwenden Sie für Kosten einen Vergleich bis zum Zielort, nicht nur den Ex-Works-Preis.",
    risks: "Fehlende Mengen je Gewicht, unklare KG/LB-Kennzeichnung, kein Mittellochmaß, pauschales OEM, unbekannte Kartons, kein Lieferort und unterschiedliche Incoterms machen Angebote unbrauchbar. Auch versteckte Werkzeug-, Muster- oder Palettenkosten müssen erfragt werden.",
    checklist: ["Unternehmen und Zielland", "SKU und Produktbeschreibung", "Gewichte, Größen und Mengen", "Material und Konstruktion", "Maße und Toleranzen", "Funktion und Nutzung", "Logo, Farbe und Kennzeichnung", "Karton, Etikett und Palette", "QC, Stichprobe und Inspektion", "MOQ, Muster und Lieferzeit", "Incoterm und Lieferort", "Gültigkeit und Zahlungsbedingungen"],
    faq: [["Kann eine RFQ mehrere Produktgruppen enthalten?", "Ja. Trennen Sie Positionen und ergänzen Sie eine gemeinsame Verpackungs- und Lieferplanung."], ["Muss eine Zeichnung vorhanden sein?", "Nicht immer. Bei kritischen Maßen, Sonderkonstruktionen oder OEM-Entwicklung ist sie jedoch sinnvoll."], ["Sollte man einen Zielpreis nennen?", "Ein Ziel kann helfen, darf aber technische Mindestanforderungen nicht ersetzen. Anbieter sollen Annahmen offenlegen."], ["Wie vergleicht man unterschiedliche Incoterms?", "Rechnen Sie jede Option auf denselben Zielpunkt und denselben Kostenumfang um."]],
    links: [["products-hub", "Produkte"], ["oem-private-label", "OEM-Briefing"], ["landed-cost-free-weights", "Landed Cost"], ["contact", "RFQ senden"]]
  },
  {
    id: "custom-logo-free-weights", enPath: "/resources/custom-logo-options-dumbbells-weight-plates", dePath: "/de/blog/logo-kurzhanteln-gewichtsscheiben-private-label",
    title: "Logo auf Kurzhanteln & Gewichtsscheiben: OEM-Optionen", description: "Logo- und Private-Label-Optionen für Kurzhanteln und Gewichtsscheiben: Prägung, Einlage, Druck, Laser, Farbe, Muster, MOQ, Verpackung und QC.", h1: "Logo-Optionen für Kurzhanteln und Gewichtsscheiben", keyword: "Kurzhanteln mit Logo Private Label", intent: "OEM-Branding und Musterfreigabe",
    direct: "Logos können je nach Material und Werkzeug geprägt, vertieft, eingelegt, gedruckt, gelasert, auf einer Platte angebracht oder über Etikett und Verpackung umgesetzt werden. Die beste Methode hängt von Oberfläche, Gewichtsspanne, Design, Menge, Haltbarkeit und Budget ab.",
    definition: "Logoanpassung ist die kontrollierte Übertragung einer Marke auf Produkt oder Verpackung. Sie umfasst Verfahren, Position, Größe, Farbe, Kontrast, Mindestlinien, Freigabedatei und Qualitätskriterien. Ein Logo-Wunsch ohne diese Angaben ist kein fertiges OEM-Briefing.",
    decision: "Prüfen Sie zuerst die verfügbare Fläche bei kleinen und großen Gewichten. Ein identisches Logo kann auf mehreren Größen unleserlich oder unproportional wirken. Wählen Sie ein Verfahren, das zum Material und zur erwarteten Nutzung passt. Bei kleinen Mengen kann Verpackungs- oder Etikettenbranding wirtschaftlicher sein.",
    comparison: [["Formprägung", "dauerhafte Integration", "Werkzeug, MOQ, Proportion"], ["Farbige Einlage", "hoher Kontrast", "Haftung, Farbe, Kanten"], ["Druck", "flexible Grafik", "Abrieb, Vorbehandlung, Schutz"], ["Laser", "Metallgriffe und Platten", "Kontrast, Position, Material"], ["Logo-Platte / Etikett", "flexible Markenkennzeichnung", "Befestigung, Lesbarkeit, Verpackung"]],
    process: "Der Käufer liefert Vektordatei und Markenrichtlinien. PowerBaseFit prüft Produktfläche, Verfahren und MOQ. Es folgen Layout, digitale Ansicht, physisches Muster, Freigabe, Serienreferenz und QC. Änderungen an Grafik oder Position werden versioniert.",
    quality: "Kontrolliert werden richtige Datei, Position, Ausrichtung, Farbe, Kontrast, Schärfe, Haftung und Lesbarkeit. Bei einem Sortiment werden mehrere Gewichte bemustert. Kartonetikett, Barcode und Produktlogo müssen denselben Modell- und Gewichtsangaben entsprechen.",
    practical: "Reduzieren Sie komplexe Details für kleine Flächen und legen Sie Mindestgrößen fest. Dokumentieren Sie Farbreferenzen physisch oder mit eindeutigem System. Planen Sie Ersatz- und Nachbestellungen mit derselben Grafikversion. Berücksichtigen Sie, dass Griffe, Racks und Scheiben unterschiedliche Brandingverfahren brauchen.",
    risks: "Fehler entstehen durch ungeeignete Rasterdateien, zu feine Linien, fehlenden Kontrast, unbestätigte Farben, nur ein freigegebenes Gewicht und widersprüchliche Kartontexte. Markenrechte und Zielmarktangaben müssen vom Käufer geprüft werden.",
    checklist: ["Vektordatei und Markenfreigabe", "Produkt und Gewichtsbereich", "Position und Größe je Variante", "Verfahren und Materialverträglichkeit", "Farb- und Kontrastreferenz", "Muster mehrerer Größen", "Abrieb- oder Haftungsprüfung", "KG-Kennzeichnung und Barcode", "Verpackungsdesign", "Dateiversion für Nachbestellung"],
    faq: [["Welches Dateiformat wird für ein Logo benötigt?", "Eine editierbare Vektordatei ist in der Regel am besten. Schriften und Farben sollten eindeutig definiert sein."], ["Kann dasselbe Logo auf allen Gewichten gleich groß sein?", "Nicht immer. Fläche und Proportionen ändern sich; mehrere Gewichte sollten geprüft werden."], ["Ist eine Logoprägung bei kleinen Mengen möglich?", "Werkzeuggebundene Verfahren haben oft höhere Mindestmengen. Etikett, Verpackung oder vorhandene Logoflächen können Alternativen sein."], ["Wer prüft die Markenrechte?", "Der Käufer muss sicherstellen, dass er die Marke und Inhalte im Zielmarkt verwenden darf."]],
    links: [["oem-private-label", "OEM-Prozess"], ["oem-sample-approval-free-weights", "Muster freigeben"], ["dumbbells-category", "Kurzhanteln"], ["weight-plates-category", "Gewichtsscheiben"]]
  },
  {
    id: "export-packaging-free-weights", enPath: "/resources/export-packaging-dumbbells-weight-plates", dePath: "/de/blog/exportverpackung-kurzhanteln-gewichtsscheiben",
    title: "Exportverpackung für Kurzhanteln & Gewichtsscheiben", description: "Schwere Fitnessgeräte sicher verpacken: Karton, Trennlagen, Palette, Umreifung, Etikett, Gewicht, Containerladung, Wareneingang und Verpackungsprüfung.", h1: "Exportverpackung für Kurzhanteln und Gewichtsscheiben", keyword: "Exportverpackung Kurzhanteln Gewichtsscheiben", intent: "Logistik- und Schadensprävention",
    direct: "Schwere freie Gewichte brauchen begrenzte Kartongewichte, feste Innenlagen, Schutz zwischen Metall und Beschichtung, belastbare Paletten, Umreifung und eindeutige Etiketten. Die Verpackung wird mit realem Produktgewicht geprüft und auf Umschlag, Seetransport, Lagerung und Entladung abgestimmt.",
    definition: "Exportverpackung ist das System aus Produktschutz, Innenverpackung, Karton oder Kiste, Palette, Ladungssicherung, Kennzeichnung und Packdokumentation. Sie soll Produkt und Lieferkette schützen und eine kontrollierte Identifikation beim Wareneingang ermöglichen.",
    decision: "Teilen Sie schwere Produkte in handhabbare Einheiten. Vermeiden Sie direkten Kontakt zwischen beschichteten Flächen, scharfen Kanten und Metalleinsätzen. Prüfen Sie Kartonfestigkeit nicht leer, sondern mit Gewicht und realer Stapelung. Planen Sie Palette und Container so, dass Last verteilt und Bewegung begrenzt wird.",
    comparison: [["Einzelkarton", "kleine oder schwere Einheit", "Gewichtslimit und Innenverstärkung"], ["Mehrfachkarton", "leichte Varianten oder Sets", "Trennung und Gesamtgewicht"], ["Holzkiste", "empfindliche oder sperrige Teile", "Materialanforderung und Volumen"], ["Palette", "Bündelung und Umschlag", "Tragfähigkeit, Umreifung, Stapelung"], ["Retail-Verpackung", "Marken- und Verkaufsfunktion", "Schutz, Text, Barcode, Umkarton"]],
    process: "Bestimmen Sie Produktmaß und Gewicht, definieren Sie Kontakt- und Stoßrisiken, entwickeln Sie Innenverpackung und Karton, erstellen Sie Etikett, bauen Sie Palette und testen Sie Muster. Nach Serienverpackung werden Packliste, Gewichte, Abmessungen und Fotos mit der Bestellung abgeglichen.",
    quality: "Kontrolliert werden Kartonmaterial, Klebung oder Heftung, Innenlagen, Trennung, Produktorientierung, Verschluss, Etikett, Palettenzustand, Umreifung und Folie. Ein Verpackungstest kann Fall-, Stapel- oder Handhabungsszenarien nach vereinbartem Verfahren abbilden.",
    practical: "Kennzeichnen Sie Kartons mit SKU, Produkt, Gewicht, Menge, Netto- und Bruttogewicht sowie Zielmarktdaten. Bei Studioprojekten kann eine Kennzeichnung nach Raum oder Zone die Entladung erleichtern. Dokumentieren Sie Paletten vor Containerbeladung und bei Ankunft.",
    risks: "Zu schwere Kartons reißen, lockere Produkte schlagen gegeneinander, Metallringe zerkratzen Beschichtungen, falsch verteilte Palettenlast beschädigt Unterlagen und unklare Etiketten verursachen Fehlbestände. Feuchtigkeit und lange Lagerung müssen ebenfalls berücksichtigt werden.",
    checklist: ["Produktmaß und Einzelgewicht", "Einheiten pro Karton", "Netto- und Bruttogewicht", "Kontakt- und Kantenschutz", "Kartonmaterial und Verschluss", "Etikett und Barcode", "Palettentyp und Lastverteilung", "Umreifung und Folie", "Packliste und Fotos", "Wareneingangsprüfung"],
    faq: [["Wie schwer darf ein Karton mit Hanteln sein?", "Es gibt keine universelle Zahl. Produkt, Karton, Umschlag, Arbeitsschutz und Zielort bestimmen das sinnvolle Limit."], ["Brauchen Gewichtsscheiben Trennlagen?", "Wenn Oberflächen oder Einsätze sich beschädigen können, sind geeignete Trennungen erforderlich."], ["Kann Retail-Verpackung direkt exportiert werden?", "Oft braucht sie einen schützenden Umkarton und eine Palettenplanung. Verkaufsoptik ersetzt keinen Transportschutz."], ["Was wird beim Wareneingang dokumentiert?", "Paletten, Kartons, Mengen, Etiketten, sichtbare Schäden und Stichproben verschiedener Produkte."]],
    links: [["factory", "Fertigung und Verpackung"], ["pre-shipment-inspection-free-weights", "Vorversandprüfung"], ["landed-cost-free-weights", "Logistikkosten"], ["contact", "Verpackung anfragen"]]
  },
  {
    id: "free-weight-reorder-batch-consistency", enPath: "/resources/free-weight-reorder-batch-consistency", dePath: "/de/blog/nachbestellung-freie-gewichte-chargenkonsistenz",
    title: "Nachbestellung freier Gewichte: Chargenkonsistenz sichern", description: "Kurzhanteln und Gewichtsscheiben nachbestellen: Modellstand, Material, Farbe, Logo, Gewicht, Maße, Muster, QC, Verpackung und Änderungskontrolle.", h1: "Chargenkonsistenz bei Nachbestellungen freier Gewichte", keyword: "Kurzhanteln Nachbestellung Chargenkonsistenz", intent: "Wiederholungsbestellung und Qualitätssicherung",
    direct: "Eine Nachbestellung ist nur dann mit der ersten Charge vergleichbar, wenn Modellcode, Zeichnung, Material, Werkzeug, Farbe, Logo, Gewichtstoleranz, Verpackung und Prüfplan unverändert oder dokumentiert geändert sind. Bestätigen Sie den Versionsstand vor jeder Wiederholungsproduktion.",
    definition: "Chargenkonsistenz beschreibt die Übereinstimmung kritischer Produkt- und Verpackungsmerkmale zwischen verschiedenen Produktionslosen. Sie bedeutet nicht, dass jedes sichtbare Detail absolut identisch ist, sondern dass vereinbarte Grenzen eingehalten und Änderungen kontrolliert werden.",
    decision: "Führen Sie eine Golden Sample oder eindeutige Referenz, Datenblatt, Farbmuster, Grafik und Packstandard. Fragen Sie vor Nachbestellung nach Änderungen an Rohstoff, Unterlieferant, Werkzeug, Prozess oder Verpackung. Bemustern Sie neu, wenn ein kritisches Element geändert wurde oder die letzte Charge lange zurückliegt.",
    comparison: [["Identische Nachbestellung", "gleicher freigegebener Stand", "Bestätigung und Stichprobe"], ["Materialänderung", "mögliche Wirkung auf Farbe/Funktion", "Neubewertung und Muster"], ["Werkzeugwartung", "Geometrie oder Oberfläche kann variieren", "Maß- und Sichtprüfung"], ["Grafikänderung", "Logo oder Kennzeichnung neu", "Dateiversion und Freigabe"], ["Verpackungsänderung", "Schutz und Logistik betroffen", "Packtest und Etikettabgleich"]],
    process: "Vergleichen Sie neue Bestellung mit dem letzten freigegebenen Stand, erstellen Sie eine Änderungsliste, bestätigen Sie Material und Werkzeug, prüfen Sie Grafik und Verpackung und entscheiden Sie über neues Muster. In der Serie werden erste Teile und Endstichprobe gegen Referenz und Toleranzen bewertet.",
    quality: "Prüfen Sie dieselben Merkmale wie bei der ersten Charge, damit Trends sichtbar werden. Bei Hanteln sind Gewicht, Kopf, Griff, Verbindung, Farbe und Logo relevant; bei Scheiben Gewicht, Dicke, Mittelloch, Einsatz und Oberfläche. Fotografien sollten unter vergleichbaren Bedingungen erstellt werden.",
    practical: "Archivieren Sie nicht nur ein schönes Produkt, sondern auch Verpackung, Etikett und Messdaten. Lagern Sie Referenzmuster so, dass Alterung oder Licht die Bewertung nicht verfälschen. Ein Lieferant sollte Abweichungen vor Serienstart melden, nicht erst wenn neue Ware im Lager steht.",
    risks: "Stille Rohstoffwechsel, neue Farbrezeptur, Werkzeugverschleiß, andere Logo-Datei, neue Kartongröße und geänderte Unterlieferanten können eine Linie sichtbar oder funktional verändern. Die Formulierung „wie zuvor“ reicht ohne Referenznummer nicht.",
    checklist: ["Vorherige Auftrags- und Modellnummer", "Freigegebene Zeichnung und Datenblatt", "Golden Sample", "Material und Lieferant", "Werkzeug- und Prozessstand", "Farb- und Grafikversion", "Gewichts- und Maßtoleranz", "Verpackungsstandard", "Änderungsliste", "Erstmuster und Endstichprobe"],
    faq: [["Ist bei jeder Nachbestellung ein neues Muster nötig?", "Nicht zwingend. Bei kritischen Änderungen, langer Pause oder fehlender Referenz ist es jedoch sinnvoll."], ["Was ist ein Golden Sample?", "Ein dokumentiertes, freigegebenes Referenzprodukt für wesentliche Merkmale. Es wird zusammen mit Daten und Toleranzen verwendet."], ["Wie werden Farbunterschiede bewertet?", "Mit definierter Referenz, Licht- und Bewertungsbedingungen sowie vereinbarter Toleranz oder visueller Freigabe."], ["Was tun, wenn ein Material nicht mehr verfügbar ist?", "Alternative offenlegen, technische Wirkung bewerten, Muster und gegebenenfalls Prüfplan neu freigeben."]],
    links: [["oem-sample-approval-free-weights", "Musterfreigabe"], ["pre-shipment-inspection-free-weights", "Inspektion"], ["custom-logo-free-weights", "Grafikstand"], ["contact", "Nachbestellung besprechen"]]
  },
  {
    id: "commercial-dumbbell-set-planning", enPath: "/resources/plan-commercial-dumbbell-set", dePath: "/de/blog/kurzhantel-set-fitnessstudio-planen",
    title: "Kurzhantel-Set für Fitnessstudios planen: Gewichte & Mengen", description: "Kurzhantel-Sortiment für Studios planen: Nutzer, KG-Abstufung, Paarzahlen, schwere Gewichte, Rack, Fläche, Material, Budget, OEM und Nachbestellung.", h1: "Ein kommerzielles Kurzhantel-Set für das Fitnessstudio planen", keyword: "Kurzhantel Set Fitnessstudio planen", intent: "Sortiments- und Flächenplanung",
    direct: "Planen Sie ein Kurzhantel-Set vom Nutzerprofil aus. Definieren Sie unteren und oberen Gewichtsbereich, Abstufung und mehrfache Paare in stark genutzten Gewichten. Stimmen Sie Kopfmaße und Gesamtzahl auf Racklänge, Gangbreite und Fläche ab. Reservieren Sie Budget für Ersatz und Nachbestellung.",
    definition: "Ein kommerzielles Kurzhantel-Set ist eine nach Gewicht und Stückzahl geplante Produktlinie für gleichzeitige Nutzer. Es besteht nicht zwingend aus genau einem Paar jedes Gewichts. Die Mengenmatrix ist Teil der Studiokapazität.",
    decision: "Analysieren Sie Mitglieder, Trainingsschwerpunkt und Spitzenzeiten. Ein allgemeines Studio braucht viele mittlere Gewichte; ein Kraftsportbereich erweitert den oberen Bereich; Hotel- oder Firmenfitness kann enger planen. Berücksichtigen Sie, dass Paarzahl und Rackkapazität zusammen wachsen. Testen Sie Greifhöhe und Zugänglichkeit.",
    comparison: [["Ein Paar je Gewicht", "kleine oder wenig frequentierte Fläche", "Engpässe im Kernbereich"], ["Mehrfachpaare", "hohe gleichzeitige Nutzung", "mehr Rack- und Budgetbedarf"], ["Große Abstufungen", "weniger SKUs", "größere Trainingssprünge"], ["Kleine Abstufungen", "feinere Progression", "mehr Positionen und Lager"], ["Verstellbare Systeme", "begrenzte Fläche", "Mechanik und Wechselzeit"]],
    process: "Erstellen Sie eine Nutzer- und Übungsmatrix, bestimmen Sie Mindest- und Höchstgewicht, wählen Sie Abstufung, legen Sie Paare je Gewicht fest, prüfen Sie Rackmaße und berechnen Sie Gesamtstückzahl und Masse. Danach vergleichen Sie Materialien, Muster, Verpackung und Nachbestellweg.",
    quality: "Eine Setprüfung umfasst nicht nur einzelne Hanteln. Gewichtssystem, Kennzeichnung, Farb- und Oberflächenkonsistenz, Griff und Rackkontakt werden über die Linie bewertet. Leichte, mittlere und schwere Referenzen kommen in die Stichprobe.",
    practical: "Markieren Sie Gewichte, die in Kursen oder beliebten Übungen gleichzeitig gebraucht werden. Planen Sie dort Reserven. Sehr schwere Gewichte sollten nur aufgenommen werden, wenn Nutzer und Rack dies rechtfertigen. Bei mehreren Standorten kann ein Kernsortiment mit standortspezifischen Ergänzungen wirtschaftlicher sein.",
    risks: "Ein optisch lückenloses Set kann betrieblich schlecht sein, wenn Kerngewichte fehlen. Zu viele schwere Hanteln binden Kapital und Fläche; zu wenige Paare erzeugen Wartezeiten. Unpassende Kopfmaße können ein vorhandenes Rack unbrauchbar machen.",
    checklist: ["Studiotyp und Mitgliederprofil", "Spitzenzeit und gleichzeitige Nutzer", "Mindest- und Höchstgewicht", "Abstufung", "Paare je Gewicht", "Kopfmaße und Rack", "Gang- und Trainingsfläche", "Material und Wartung", "Budget und Ersatzreserve", "Nachbestellplan"],
    faq: [["Braucht ein Studio von jedem Gewicht nur ein Paar?", "Nein. Häufig genutzte Gewichte sollten nach Nutzerzahl mehrfach vorhanden sein."], ["Welche Abstufung ist sinnvoll?", "Sie hängt von Zielgruppe und Gewichtsbereich ab. Feinere Abstufungen erleichtern Progression, benötigen aber mehr SKUs."], ["Wie wird die Racklänge berechnet?", "Aus Kopfbreite, Ablageabstand, Anzahl der Positionen und Bedienraum. Herstellerdaten des konkreten Modells sind erforderlich."], ["Sollten Reservehanteln mitbestellt werden?", "Bei kritischen Kerngewichten oder langen Nachlieferzeiten kann eine Reserve wirtschaftlich sein."]],
    links: [["dumbbells-category", "Kurzhanteltypen"], ["dumbbells-guide", "Material auswählen"], ["projects", "Flächenplanung"], ["contact", "Set kalkulieren"]]
  },
  {
    id: "landed-cost-free-weights", enPath: "/resources/landed-cost-wholesale-free-weights", dePath: "/de/blog/landed-cost-kurzhanteln-gewichtsscheiben-import",
    title: "Landed Cost für Kurzhanteln & Scheiben berechnen", description: "Gesamtkosten beim Import freier Gewichte: Fabrikpreis, Verpackung, Inlandstransport, Fracht, Versicherung, Zoll, Einfuhrumsatzsteuer, Terminal, Lager und Schaden.", h1: "Landed Cost von Kurzhanteln und Gewichtsscheiben berechnen", keyword: "Fitnessgeräte Import Kosten China", intent: "Importkosten und Angebotsvergleich",
    direct: "Landed Cost ist der Fabrikpreis plus alle Kosten bis zum definierten Zielpunkt: Verpackung, Inlandstransport, Exportabwicklung, Fracht, Versicherung, Terminal, Zoll, Einfuhrumsatzsteuer je Behandlung, Broker, Inlandslieferung, Lager, Finanzierung und erwartete Schäden. Vergleichen Sie Angebote immer auf demselben Incoterm und Zielort.",
    definition: "Landed Cost bezeichnet die vollständigen Einstandskosten einer Ware am gewählten Zielpunkt. Sie ist nicht identisch mit dem Zollwert oder dem reinen Einkaufspreis. Welche Positionen enthalten sind, hängt von Lieferbedingung und interner Kalkulationsmethode ab.",
    decision: "Erstellen Sie eine Kostenzeile pro Auftrag und verteilen Sie gemeinsame Kosten nachvollziehbar auf SKU, Kilogramm, Kubikmeter oder Verkaufseinheit. Freie Gewichte sind massereich; Racks sind volumenreich. Ein gemischter Container braucht deshalb mehr als eine einzige Verteilungsmethode.",
    comparison: [["EXW", "Abholung ab Fabrik", "viele Kosten beim Käufer"], ["FOB", "bis benannter Verschiffungshafen", "Seefracht und Zielkosten offen"], ["CIF/CFR", "Fracht bis Zielhafen teilweise enthalten", "lokale Zielkosten nicht automatisch enthalten"], ["DAP", "Lieferung bis benannter Ort", "Zoll/Steuern und Entladung prüfen"], ["DDP", "weitreichende Lieferleistung", "Importeurrolle, Steuern und Compliance exakt prüfen"]],
    process: "Sammeln Sie Produkt- und Verpackungsdaten, bestätigen Sie Incoterm, holen Sie Fracht- und Zielkosten ein, bestimmen Sie Zolltarif mit Fachberatung, erfassen Sie Steuern und Gebühren und ergänzen Sie Inlandstransport, Lager und Finanzierung. Führen Sie Best-, Basis- und Risikoszenario.",
    quality: "Qualität beeinflusst Kosten über Ausschuss, Nacharbeit, Ersatz, Reklamation und Markenrisiko. Eine Vorversandinspektion ist eine kalkulierbare Kostenposition und kann teure Zielmarktprobleme reduzieren. Verpackung darf nicht nur als Ausgabe, sondern als Schadensprävention bewertet werden.",
    practical: "Fordern Sie Netto- und Bruttogewicht, Kartonmaße, Paletten und Volumen. Prüfen Sie Freitage, Demurrage, Detention, Entladung und schwerlastgeeignete Zustellung. Ein niedriger Fabrikpreis kann durch schwache Packdichte oder hohe Zielgebühren aufgehoben werden.",
    risks: "Häufig fehlen lokale Terminalgebühren, Broker, Zölle, Einfuhrumsatzsteuerbehandlung, Inlandstransport, Entladung, Lager und Finanzierung. Veraltete Frachtraten und falsche Zolltarife verzerren die Kalkulation. Steuer- und Zollfragen müssen von qualifizierten Stellen geprüft werden.",
    checklist: ["Produktpreis und Währung", "Incoterm und benannter Ort", "Werkzeug und Muster", "Verpackung und Palette", "Bruttogewicht und Volumen", "Inlandstransport im Ursprung", "Fracht und Versicherung", "Terminal und Broker", "Zoll und Steuerbehandlung", "Inlandslieferung und Entladung", "Inspektion und Schadenreserve", "Finanzierung und Lager"],
    faq: [["Ist CIF gleichbedeutend mit allen Kosten bis ins Lager?", "Nein. CIF deckt nicht automatisch alle Zielhafen-, Zoll-, Steuer-, Broker- und Inlandskosten ab."], ["Wie verteilt man Fracht auf Hanteln und Racks?", "Je nach Kostenursache über Gewicht, Volumen, Paletten oder Einheiten. Eine gemischte Methode ist oft genauer."], ["Gehört die Einfuhrumsatzsteuer zur Landed Cost?", "Das hängt von Buchhaltung und Erstattungsfähigkeit ab. Steuerberater oder Importfachleute sollten die Behandlung klären."], ["Warum braucht man ein Risikoszenario?", "Frachtraten, Wechselkurse, Verzögerungen und Schäden können die reale Einstandskosten verändern."]],
    links: [["commercial-free-weight-rfq", "RFQ vorbereiten"], ["export-packaging-free-weights", "Verpackung"], ["pre-shipment-inspection-free-weights", "Inspektion"], ["contact", "Angebot anfragen"]]
  },
  {
    id: "oem-sample-approval-free-weights", enPath: "/resources/oem-free-weight-sample-approval-process", dePath: "/de/blog/oem-muster-kurzhanteln-gewichtsscheiben-freigeben",
    title: "OEM-Muster für Kurzhanteln & Scheiben freigeben", description: "OEM-Musterprüfung für freie Gewichte: Produktidentität, Material, Gewicht, Maße, Logo, Farbe, Funktion, Verpackung, Abweichungen und Serienfreigabe.", h1: "OEM-Muster für freie Gewichte richtig freigeben", keyword: "OEM Fitnessgeräte Muster freigeben", intent: "Musterprüfung vor Serienproduktion",
    direct: "Ein OEM-Muster wird gegen eine schriftliche Spezifikation geprüft. Bewerten Sie Modell, Material, Gewicht, Maße, Funktion, Oberfläche, Logo, Farbe, Kennzeichnung und Verpackung. Dokumentieren Sie akzeptiert, abzulehnen oder zu ändern. Die Serie darf erst auf einem eindeutig versionierten Stand beginnen.",
    definition: "Eine Musterfreigabe ist die formelle Zustimmung zu einem definierten Referenzprodukt und den dazugehörigen Unterlagen. Sie ist keine pauschale Erlaubnis, beliebige Abweichungen in der Serie zu akzeptieren. Toleranzen und kritische Merkmale bleiben verbindlich.",
    decision: "Prüfen Sie nicht nur die Vorderseite. Wiegen und messen Sie das Muster, nutzen Sie es in der vorgesehenen Funktion, betrachten Sie Kontaktflächen und Verpackung. Bei Sortimentsprodukten werden mehrere Gewichte oder Größen benötigt. Trennen Sie kosmetische von funktionalen und sicherheitsrelevanten Abweichungen.",
    comparison: [["Referenzmuster", "freigegebener Serienstandard", "Lagerung und Identifikation"], ["Vorserienmuster", "Produkt aus geplantem Prozess", "höhere Aussagekraft"], ["Farbmuster", "Farbe und Oberfläche", "Licht und Materialbezug"], ["Verpackungsmuster", "Schutz und Markeninformation", "Gewicht und Transporttest"], ["Digitales Rendering", "Layoutabstimmung", "ersetzt keine physische Funktion"]],
    process: "Versionieren Sie Spezifikation und Grafik, empfangen und identifizieren Sie das Muster, prüfen Sie technische Daten und Nutzung, dokumentieren Sie Fotos und Messwerte, erstellen Sie eine Abweichungsliste und fordern Sie Korrektur. Nach erneuter Prüfung unterschreiben oder bestätigen beide Seiten den finalen Stand.",
    quality: "Messungen verwenden passende Prüfmittel. Gewicht, Maß, Farbe, Logo und Verpackung erhalten klare Kriterien. Bei Hanteln werden Griff und Verbindung, bei Scheiben Mittelloch und Einsatz, bei Racks Geometrie und Funktion ergänzt. Der Serienprüfplan verweist auf Muster und Daten.",
    practical: "Bewahren Sie ein Muster beim Käufer und möglichst eine identifizierte Gegenreferenz beim Lieferanten auf. Fotos zeigen Etikett und eindeutige Seriennummer oder Muster-ID. Wenn ein genehmigtes Detail in der Produktion nicht umsetzbar ist, muss die Änderung vor Serie neu freigegeben werden.",
    risks: "Eine Freigabe per kurzer Nachricht ohne Versionsnummer, nur Fotos, ungeprüfte Verpackung, falsche KG/LB-Kennzeichnung, fehlende Farbreferenz und ein einziges Muster für viele Größen sind häufige Risiken. Auch ein handgefertigtes Muster kann besser aussehen als die reale Serie; ein Vorserienmuster reduziert dieses Risiko.",
    checklist: ["Muster-ID und Spezifikationsversion", "Modell und Material", "Gewicht und Toleranz", "Maße und Funktion", "Oberfläche und Farbe", "Logo und Kennzeichnung", "Karton, Etikett und Palette", "Fotos und Messdaten", "Abweichungsliste", "Freigabe durch Verantwortliche", "Serienprüfplan", "Referenzlagerung"],
    faq: [["Reicht eine Foto-Freigabe?", "Für Layoutdetails kann sie helfen, aber Gewicht, Haptik, Farbe, Funktion und Verpackung erfordern oft ein physisches Muster."], ["Wie viele Muster sind erforderlich?", "Abhängig von Produktfamilie und Risiko. Mehrere Gewichte oder Größen können notwendig sein."], ["Was passiert nach einer Musterabweichung?", "Abweichung dokumentieren, Ursache und Korrektur abstimmen, geändertes Muster oder Nachweis prüfen und erst danach freigeben."], ["Ist das Muster automatisch die Serientoleranz?", "Nein. Das Muster ist Referenz; messbare Toleranzen müssen zusätzlich schriftlich festgelegt werden."]],
    links: [["oem-private-label", "OEM-Ablauf"], ["custom-logo-free-weights", "Logo-Optionen"], ["pre-shipment-inspection-free-weights", "Serieninspektion"], ["contact", "Musterprojekt starten"]]
  },
  {
    id: "pre-shipment-inspection-free-weights", enPath: "/resources/pre-shipment-inspection-dumbbells-weight-plates", dePath: "/de/blog/vorversandinspektion-kurzhanteln-gewichtsscheiben",
    title: "Vorversandinspektion für Kurzhanteln & Scheiben", description: "Pre-Shipment Inspection für freie Gewichte: Stichprobe, AQL, Produktidentität, Gewicht, Maße, Oberfläche, Logo, Verpackung, Dokumentation und Freigabe.", h1: "Vorversandinspektion für Kurzhanteln und Gewichtsscheiben", keyword: "Vorversandinspektion Fitnessgeräte", intent: "Qualitätskontrolle vor Restzahlung und Versand",
    direct: "Eine Vorversandinspektion prüft fertige, verpackungsbereite Ware gegen Bestellung, Spezifikation und Muster. Sie umfasst Menge und Verpackungsstatus, zufällige Stichprobe, Produktidentität, Gewicht, Maße, Funktion, Oberfläche, Logo, Etikett und Karton. Pass/Fail-Regeln müssen vor dem Termin feststehen.",
    definition: "Pre-Shipment Inspection ist eine unabhängige oder interne Kontrolle nach weitgehend abgeschlossener Produktion und vor Versand. Sie reduziert Risiken, ersetzt aber weder Prozesskontrolle noch eine klare Spezifikation und garantiert nicht, dass jedes ungezogene Stück fehlerfrei ist.",
    decision: "Wählen Sie Inspektionszeitpunkt, Losdefinition, Stichprobenverfahren und kritische Merkmale. Der Inspektor braucht Bestellliste, Datenblatt, Musterfotos, Toleranzen, Grafik und Packstandard. Kritische Tests werden vorab auf Durchführbarkeit, Zeit und Ausrüstung geprüft.",
    comparison: [["Produktionskontrolle", "während der Fertigung", "frühe Prozessabweichungen"], ["Vorversandinspektion", "fertige Ware", "Endstatus und Verpackung"], ["100-%-Prüfung", "jedes Stück", "hoher Aufwand, kritische Programme"], ["AQL-Stichprobe", "statistische Losstichprobe", "Fehlerklassen und Grenzwerte"], ["Container Loading Check", "Beladung", "Menge, Zustand, Sicherung"]],
    process: "Bestätigen Sie Produktionsfortschritt, definieren Sie Los und Stichprobe, ziehen Sie Kartons aus unterschiedlichen Positionen, prüfen Sie Verpackung und Produkte, erfassen Sie Fehler nach Klasse, führen Sie Messungen durch, dokumentieren Sie Fotos und erstellen Sie Bericht mit Ergebnis und offenen Punkten.",
    quality: "Bei Kurzhanteln werden Gewicht, Paarung, Griff, Verbindung, Kopf und Kennzeichnung geprüft. Bei Scheiben Gewicht, Dicke, Mittelloch, Einsatz, Planlage und Oberfläche. Verpackung umfasst Menge, Etikett, Schutz, Karton, Palette und Markierung. Messmittel und Methode werden im Bericht genannt.",
    practical: "Schreiben Sie nicht nur „Qualität prüfen“. Geben Sie Sollwerte und Referenzen an. Bitten Sie um Fotos der Stichprobenauswahl, nicht nur der besten Produkte. Bei Nichtbestehen werden Ursache, Sortierung oder Nacharbeit und eine erneute Prüfung abgestimmt, bevor Versand freigegeben wird.",
    risks: "Inspektionen scheitern an zu frühem Termin, nicht fertiger Ware, unzugänglichen Kartons, fehlenden Kriterien, ungeeigneten Messmitteln und uneindeutiger Fehlerklassifizierung. Ein bestandenes Ergebnis darf nicht verwendet werden, um spätere Produktänderungen zu rechtfertigen.",
    checklist: ["Bestellung und Spezifikation", "Losgröße und Produktionsstatus", "Stichprobe und Fehlerklassen", "Produktidentität", "Gewicht und Maße", "Funktion und Verbindung", "Oberfläche, Farbe und Logo", "Menge und Verpackung", "Messmittel", "Foto- und Datenbericht", "Pass/Fail-Regel", "Nacharbeit und Re-Inspection"] ,
    faq: [["Wann sollte die Vorversandinspektion stattfinden?", "Wenn die Ware weitgehend fertig und repräsentativ verpackt ist, aber noch Zeit für Korrekturen vor Versand bleibt."], ["Was bedeutet AQL?", "Ein statistisches Stichprobenkonzept mit Losgröße, Prüfniveau, Fehlerklassen und Annahmegrenzen. Es muss zum Risiko passen."], ["Kann der Käufer einen eigenen Inspektor beauftragen?", "Ja. Termin, Zugang, Unterlagen und Prüfumfang werden mit der Fabrik abgestimmt."], ["Was passiert bei einem Fail?", "Versand nicht automatisch freigeben. Ursache, Umfang, Sortierung oder Nacharbeit klären und erforderlichenfalls erneut prüfen."]],
    links: [["factory", "Qualitätssystem"], ["dumbbell-weighing-guide", "Gewicht messen"], ["export-packaging-free-weights", "Verpackung"], ["contact", "Inspektion abstimmen"]]
  },
  {
    id: "training-vs-competition-bumper-plates", enPath: "/resources/training-vs-competition-bumper-plates", dePath: "/de/blog/training-vs-competition-bumper-plates",
    title: "Training vs. Competition Bumper Plates: B2B-Vergleich", description: "Training oder Competition Bumper Plates? Vergleich nach Präzision, Dicke, Einsatz, Farbe, Nutzung, Studioziel, QC, Preis und Beschaffungsrisiko.", h1: "Training und Competition Bumper Plates vergleichen", keyword: "Training vs Competition Bumper Plates", intent: "Produktauswahl für Studio und Handel",
    direct: "Training Bumper Plates sind für den regulären Studio- und Trainingsbetrieb ausgelegt und meist wirtschaftlicher. Competition-Ausführungen zielen auf engere Spezifikationen, definierte Farb- und Konstruktionsmerkmale und ein hochwertigeres Präsentationsniveau. Ein Studio braucht Competition Plates nur, wenn Nutzer, Positionierung und Budget den Mehrwert rechtfertigen.",
    definition: "Training und Competition sind Markt- und Spezifikationskategorien für Bumper Plates. Der Name allein garantiert keine Normkonformität. Gewichtstoleranz, Abmessungen, Einsatz, Material und Prüfung müssen im Datenblatt des konkreten Modells stehen.",
    decision: "Bewerten Sie Trainingstyp, Nutzererwartung, Plattformen, Hülsenplatz, Farbsystem und erforderliche Präzision. Ein Functional-Bereich mit hohem Durchsatz kann robuste Trainingsscheiben priorisieren. Ein spezialisiertes Gewichthebezentrum oder Premiumangebot kann Competition-Modelle wählen. Mischungen müssen klar gekennzeichnet werden.",
    comparison: [["Training Bumper", "tägliches Studio- und Techniktraining", "Material, Einsatz, Dicke, Wirtschaftlichkeit"], ["Competition Bumper", "präzisions- und präsentationsorientiert", "Toleranz, Maße, Farbe, Dokumentation"], ["Schwarze Scheibe", "einheitliche Optik", "Kennzeichnung und Gewichtserkennung"], ["Farbcodiert", "schnelle Identifikation", "Farbreferenz und Konsistenz"], ["Kalibrierte Stahlscheibe", "Powerlifting und hohe Last", "andere Nutzung, keine Bumper Plate"]],
    process: "Definieren Sie Anwendung und Spezifikation, vergleichen Sie Datenblätter, prüfen Sie Muster mehrerer Gewichte, testen Sie Aufnahme und Plattform, berechnen Sie benötigte Paare und Hülsenplatz und legen Sie QC sowie Kennzeichnung fest. Angebote werden auf gleicher Spezifikation verglichen.",
    quality: "Competition-Produkte erfordern nachvollziehbare Gewicht- und Maßprüfung. Training Plates brauchen ebenfalls kontrollierte Gewichte, Einsätze, Oberflächen und Verbindung. Drop- oder Funktionsprüfungen werden nur mit definiertem Verfahren verglichen. Farbe und Logo gehören in die Musterfreigabe.",
    practical: "Viele kommerzielle Studios erhalten den besten Nutzen aus guten Training Plates und investieren das restliche Budget in ausreichende Paarzahlen, Plattformen und Lagerung. Competition Plates können für spezielle Bereiche oder Events reserviert werden. Fachhändler sollten beide Kategorien mit klaren Daten statt nur mit Prestige-Begriffen beschreiben.",
    risks: "Competition als Marketingwort ohne Spezifikation, unklare Toleranz, zu dicke Scheiben, ungeeignete Stangen, fehlender Boden und unnötig hohe Kosten sind typische Risiken. Umgekehrt darf eine Trainingsscheibe nicht als für jede professionelle oder wettkampfnähere Anforderung ausreichend dargestellt werden.",
    checklist: ["Trainingsart und Nutzer", "Gewichtstoleranz", "Außendurchmesser und Dicke", "Mittelloch und Einsatz", "Material und Oberfläche", "Farb- und Kennzeichnungssystem", "Plattform und Stange", "Paare je Gewicht", "Funktionsprüfung", "Budget und Nachbestellung"],
    faq: [["Sind Competition Bumper Plates langlebiger?", "Nicht automatisch. Konstruktion, Material, Nutzung, Boden und Pflege bestimmen die Leistung. Competition beschreibt andere Ziel- und Präzisionsmerkmale."], ["Braucht ein normales Fitnessstudio Competition Plates?", "Meist nicht für alle Stationen. Sie können für spezialisierte Bereiche sinnvoll sein."], ["Dürfen Training und Competition Plates gemischt werden?", "Wenn Stange, Durchmesser und Nutzung kompatibel sind, ist es technisch möglich; Kennzeichnung und Gewichtsgenauigkeit sollten klar bleiben."], ["Wie erkennt man echte Spezifikationsunterschiede?", "Datenblatt, Toleranzen, Maße, Material, Einsatz, Prüfung und Muster vergleichen statt nur Produktnamen."]],
    links: [["weight-plates-category", "Bumper Plates"], ["bumper-manufacturing-guide", "Herstellung"], ["plates-guide", "Scheibenarten"], ["contact", "Bumper Plates anfragen"]]
  }
];

function guideDecisionWorkbook(profile: GermanGuideProfile) {
  const optionReview = profile.comparison.map(([option, use, check], index) =>
    `${index + 1}. ${option}: Diese Option wird nur dann in die engere Auswahl aufgenommen, wenn der vorgesehene Einsatz „${use}“ tatsächlich zum Projekt passt. Im Angebotsvergleich ist „${check}“ als eigener Prüfpunkt zu führen. Der Einkäufer hält dazu Sollzustand, Lieferantenaussage, verfügbaren Nachweis und offene Abweichung in getrennten Spalten fest. Dadurch bleibt sichtbar, ob zwei Preise dieselbe Leistung beschreiben oder ob eine scheinbar günstigere Position wichtige Anforderungen auslässt.`
  );
  const checklistReview = profile.checklist.map((item, index) =>
    `${index + 1}. ${item}: Legen Sie hierfür einen überprüfbaren Sollwert, eine zuständige Person und den Zeitpunkt der Kontrolle fest. Wenn noch keine Zahl oder Referenz möglich ist, wird die Annahme ausdrücklich als offen markiert. Vor Serienfreigabe muss daraus entweder ein bestätigtes Kriterium, eine bewusst akzeptierte Abweichung oder ein gestrichener Leistungsbestandteil werden.`
  );

  return [
    textBlock(
      "entscheidungsarbeitsblatt",
      "Entscheidungsarbeitsblatt für den Angebotsvergleich",
      `Für die Suche nach „${profile.keyword}“ reicht eine Sammlung von Produktlinks nicht aus. Das Arbeitsblatt beginnt mit dem konkreten Geschäftsziel: ${profile.intent}. Ergänzen Sie Absatzkanal, Zielgruppe, geplante Nutzung, Bestellmenge, gewünschte Lieferform und den Zeitpunkt, zu dem Ware tatsächlich verfügbar sein muss. Danach werden technische, kaufmännische und logistische Anforderungen getrennt. Diese Trennung verhindert, dass ein attraktiver Stückpreis unbemerkt durch andere Materialausführung, fehlendes Branding, schwächere Verpackung oder eine unpassende Lieferbedingung entsteht.`,
      "Erstellen Sie je Lieferant eine Zeile pro Variante und verwenden Sie identische Einheiten. KG und LB, Stück und Paar, Nettogewicht und Bruttogewicht sowie EXW, FOB und andere Lieferbedingungen dürfen nicht vermischt werden. Hinterlegen Sie die Version von Zeichnung, Datenblatt, Grafik und Angebot. Ändert sich ein Merkmal, wird nicht die alte Zeile überschrieben; eine neue Version zeigt, welche Auswirkung die Änderung auf Preis, MOQ, Muster, Werkzeug, Prüfaufwand, Verpackung und Termin hat.",
      "Die Entscheidung wird erst getroffen, wenn Muss-Kriterien erfüllt oder bewusst neu bewertet wurden. Wunschmerkmale können nach Nutzen und Mehrkosten priorisiert werden. Offene Annahmen erhalten eine Frist. Diese einfache Disziplin ist besonders bei internationalen Projekten wichtig, weil Vertrieb, Einkauf, Hersteller, Spedition und Qualitätsprüfung sonst mit unterschiedlichen Ständen arbeiten können."
    ),
    textBlock(
      "optionen-einordnen",
      "Optionen anhand des Einsatzes einordnen",
      ...optionReview
    ),
    textBlock(
      "checkliste-umsetzen",
      "Die Checkliste in prüfbare Anforderungen übersetzen",
      ...checklistReview
    ),
    textBlock(
      "kosten-und-folgeentscheidungen",
      "Kosten, Risiken und Folgeentscheidungen zusammenführen",
      "Vergleichen Sie nicht nur den Nettopreis der ersten Bestellung. Relevante Folgekosten können Muster und Versand, Werkzeug oder Druckvorbereitung, zusätzliche Prüfungen, verstärkte Kartons, Paletten, Fracht, Einfuhrabwicklung, Lagerfläche, Montage, Ersatzteile und eine spätere Nachbestellung umfassen. Nicht jeder Punkt trifft auf jedes Produkt zu; genau deshalb wird er projektbezogen geprüft. Eine Kostenposition ohne bestätigte Grundlage bleibt eine Bandbreite und wird nicht als sichere Zahl dargestellt.",
      "Für ein Basisszenario verwenden Sie bestätigte Mengen, Verpackungsdaten und Lieferbedingungen. Ein Risikoszenario berücksichtigt mögliche Abweichungen bei Fracht, Wechselkurs, Nacharbeit oder Termin. Ein Alternativszenario zeigt, welche Anforderung vereinfacht werden könnte, ohne die vorgesehene Nutzung zu gefährden. So lässt sich erkennen, ob eine teurere Ausführung einen nachvollziehbaren betrieblichen Nutzen bietet oder nur eine unbewiesene Marketingbezeichnung trägt.",
      "Vor der Bestellung hält der Käufer außerdem fest, wie mit Abweichungen umgegangen wird: Wer entscheidet, welche Nachweise benötigt werden, ob sortiert oder nachgearbeitet werden kann und wann eine erneute Inspektion erforderlich ist. Diese Vereinbarung ersetzt keine rechtliche Vertragsprüfung, macht die technische und operative Erwartung aber wesentlich klarer."
    ),
    textBlock(
      "dokumentation-und-uebergabe",
      "Dokumentation vom Muster bis zum Wareneingang",
      "Ein belastbarer Projektordner enthält Anfrage, Stückliste, freigegebenes Datenblatt, Zeichnungen oder Maße, Materialangaben, Grafikdateien, Farbreferenz, Musterprotokoll, Verpackungsvorgabe, Auftragsbestätigung, Prüfplan und Versanddaten. Dateien erhalten Datum und Versionsnummer. Fotos werden dem Produktcode und der Variante zugeordnet; Nahaufnahmen ohne Kontext reichen als Identitätsnachweis nicht aus.",
      "Bei der Übergabe an Qualitätsprüfung oder Logistik werden kritische Merkmale hervorgehoben. Der Prüfer muss wissen, welche Abweichung sicherheits- oder funktionsrelevant, welche wesentlich und welche rein kosmetisch ist. Der Spediteur benötigt bestätigte Packmaße, Gewichte, Anzahl der Packstücke und Ladeanforderungen. Der Wareneingang braucht dieselbe Identifikation, damit Kartons, Etiketten und Produkte gegen Bestellung und Packliste geprüft werden können.",
      "Nach Ankunft werden Schäden, Fehlmengen und Abweichungen zeitnah mit Fotos, Mengen und Chargenbezug dokumentiert. Gute Ergebnisse werden ebenfalls gespeichert: Sie bilden zusammen mit dem Referenzmuster die Grundlage einer Nachbestellung. Erkenntnisse aus Reklamation, Montage, Reinigung oder tatsächlicher Nutzung fließen als konkrete Änderung in die nächste Spezifikationsversion ein."
    )
  ];
}

export function germanGuideVersion(profile: GermanGuideProfile): LocalizedContentVersion {
  return {
    locale: "de", translationStatus: "localized", reviewStatus: "approved", publishStatus: "published",
    slug: profile.dePath.split("/").at(-1) ?? profile.id, publicPath: profile.dePath, title: profile.title, description: profile.description, h1: profile.h1,
    body: [
      answerBlock("direkte-antwort", "Direkte Antwort", profile.direct),
      definitionBlock("definition", profile.h1, profile.definition),
      textBlock("kaufberatung", "Kaufberatung und Entscheidungslogik", profile.decision, "Eine belastbare B2B-Entscheidung trennt Muss-Kriterien, wünschenswerte Merkmale und offene Annahmen. Produktdaten, Muster, Angebot und Prüfplan müssen dieselbe Ausführung beschreiben. Wo ein Lieferant von der Anfrage abweicht, wird dies vor Preisvergleich und Freigabe sichtbar dokumentiert."),
      specTable("vergleich", "Vergleichstabelle", ["Option", "Geeigneter Einsatz", "Zu prüfen"], profile.comparison),
      textBlock("vorgehen", "Vorgehen in der Beschaffung", profile.process, "Jeder Schritt erhält einen Verantwortlichen und einen Versionsstand. So bleiben Einkaufsentscheidung, technische Freigabe, Qualitätssicherung und Logistik miteinander verbunden. Mündliche Zusagen werden in Datenblatt, Freigabe oder Auftragsunterlage überführt."),
      textBlock("qualitaet", "Qualitätskontrolle", profile.quality, "Prüfkriterien werden vor Serienbeginn definiert. Messmittel, Stichprobe, Fehlerklassen und Entscheidungsregel müssen zum Produktrisiko passen. Eine Endkontrolle kann keine unklare Spezifikation reparieren, sondern nur gegen einen festgelegten Standard prüfen."),
      textBlock("praxiswissen", "Praxiswissen aus der Fertigung", profile.practical, "Aus Herstellersicht entstehen viele Probleme nicht durch einen einzelnen großen Fehler, sondern durch unklare Varianten, fehlende Referenzen und späte Änderungen. Ein vollständiges Briefing und eine konsequente Musterfreigabe reduzieren Rückfragen, Nacharbeit und unterschiedliche Erwartungen."),
      textBlock("risiken", "Risiken und typische Fehler", profile.risks, "Risiken werden nach Auswirkung und Wahrscheinlichkeit priorisiert. Kritische Punkte erhalten vor Produktion einen Nachweis oder eine Freigabe. Kaufmännischer Zeitdruck darf nicht dazu führen, dass Produktidentität, Qualität, Verpackung oder Importverantwortung ungeklärt bleiben."),
      ...guideDecisionWorkbook(profile),
      checklistBlock("checkliste", "Einkaufs-Checkliste", profile.checklist),
      textBlock("herstellererfahrung", "Herstellererfahrung richtig einordnen", "PowerBaseFit nutzt Produkt-, Fertigungs- und Qualitätswissen, um offene Spezifikationen sichtbar zu machen und einen prüfbaren Auftragsstand aufzubauen. Dabei werden keine deutschen Kunden, Zertifizierungen, Verkaufszahlen oder Marktpositionen erfunden. Aussagen beziehen sich auf den beschriebenen Prozess und müssen für das konkrete Produkt bestätigt werden.", "Ein Hersteller ist besonders hilfreich, wenn er Grenzen benennt: nicht jede Logo-Methode passt zu jedem Material, nicht jede MOQ gilt für jedes Sortiment und nicht jede Prüfung ist ohne definiertes Verfahren aussagekräftig. Diese Einschränkungen machen eine Beschaffungsentscheidung belastbarer."),
      textBlock("anfrage", "Nächster Schritt für Einkäufer", "Übertragen Sie die Checkliste in Ihre eigene Produkt- oder Projektanfrage. Nennen Sie Unternehmen, Zielland, Produkt, Varianten, Mengen, technische Anforderungen, Eigenmarkenwünsche, Verpackung und Lieferort. PowerBaseFit kann dann Machbarkeit und offene Punkte prüfen.", "Preis, MOQ und Lieferzeit werden erst nach dem technischen Abgleich bestätigt. Zoll, Steuern, Zielmarktpflichten, Installation und Betreiberanforderungen müssen durch die jeweils verantwortlichen Fachstellen und den Käufer geprüft werden.")
    ],
    faq: profile.faq.map(([question, answer], index) => ({ id: `faq-${index + 1}`, question, answer })),
    author: germanEditorialAuthor, reviewedBy: germanTechnicalReviewer,
    schemaData: { category: profile.intent, breadcrumbs: [{ name: "Startseite", path: "/de" }, { name: "Ratgeber", path: "/de/blog" }, { name: profile.h1, path: profile.dePath }], extra: { primaryKeyword: profile.keyword, searchIntent: profile.intent, targetBuyer: "Importeure, Fachhändler, Studioausstatter und Eigenmarken" } },
    images: commonImages.map((item, index) => ({ ...item, id: `${profile.id}-bild-${index + 1}`, src: germanImagePath(item.src, profile.dePath.split("/").at(-1) ?? profile.id, index), alt: `${item.alt} – ${profile.h1}`, caption: `${item.caption} Bezug: ${profile.h1}.` })),
    internalLinks: profile.links.map(([targetContentId, label]) => ({ targetContentId, label })),
    canonicalData: { mode: "self" }, hreflangData: { include: true }, updatedAt: "2026-07-19T08:00:00.000Z", publishedAt: "2026-07-19T08:00:00.000Z", version: 1
  };
}
