import { isPublishedVersion, type ContentEntity, type ContentManifest, type LocalizedContentVersion, type LocalizedImage } from "../../lib/content/types";
import { indonesianExcludedContentIds } from "./indonesian-manifest";
import { plAnswer, plChecklist, plDefinition, polishEditorialAuthor, polishTechnicalReviewer, plTable, plText } from "./pl-content-helpers";

const publishedAt = "2026-07-22T08:00:00.000Z";
const excludedIds = new Set(indonesianExcludedContentIds);

type Profile = { path: string; title: string; h1: string; description: string; keyword: string; intent: string; focus: string };

const core: Record<string, Profile> = {
  home: { path: "/pl", title: "Producent profesjonalnego sprzętu fitness i OEM | PowerBaseFit", h1: "Profesjonalny sprzęt fitness dla dystrybutorów, importerów i siłowni", description: "Produkcja hantli, obciążeń, stojaków, ławek i akcesoriów dla polskich importerów, dystrybutorów, marek własnych oraz projektów komercyjnych.", keyword: "producent sprzętu fitness", intent: "ocena producenta i zapytanie ofertowe", focus: "Strona łączy katalog produktów z dowodami produkcyjnymi, obsługą OEM i informacjami potrzebnymi do przygotowania porównywalnej oferty B2B." },
  "products-hub": { path: "/pl/produkty", title: "Hurtowy sprzęt do siłowni komercyjnych | PowerBaseFit", h1: "Sprzęt fitness do siłowni komercyjnych i dystrybucji", description: "Hantle, obciążenia, talerze bumper, stojaki, ławki i akcesoria do zakupów B2B, projektów siłowni oraz programów marki własnej.", keyword: "sprzęt do siłowni hurtowo", intent: "wybór kategorii i przygotowanie RFQ", focus: "Centrum produktów pomaga zbudować listę SKU według zastosowania, materiału, przestrzeni, sposobu sprzedaży, kontroli jakości i wymagań logistycznych." },
  "dumbbells-category": { path: "/pl/produkty/hantle", title: "Hantle hurtowo do profesjonalnych siłowni | Producent OEM", h1: "Hantle profesjonalne dla siłowni, dystrybutorów i marek własnych", description: "Hantle sześciokątne, okrągłe, regulowane, gumowe, PU, TPU, CPU, stalowe i żeliwne do sprzedaży hurtowej oraz projektów siłowni.", keyword: "hantle hurtowo", intent: "porównanie konstrukcji i serii wagowych", focus: "Kategoria rozróżnia kształt głowic, materiał powłoki, uchwyt, zakres wag, stojak, zapach, wygląd oraz możliwość odtworzenia tej samej serii w kolejnych zamówieniach." },
  "weight-plates-category": { path: "/pl/produkty/obciazenia", title: "Obciążenia olimpijskie i talerze bumper | Dostawca B2B", h1: "Obciążenia olimpijskie i talerze bumper do zastosowań komercyjnych", description: "Obciążenia żeliwne, stalowe, gumowane, PU, TPU i CPU ze specyfikacją, kontrolą jakości, opakowaniem eksportowym i opcjami OEM.", keyword: "obciążenia do siłowni", intent: "dobór obciążeń i zgodności z gryfem", focus: "Buyer porównuje średnicę otworu, grubość, materiał, tolerancję masy, insert, oznaczenia i zachowanie produktu w rzeczywistym sposobie użytkowania." },
  "racks-benches-category": { path: "/pl/produkty/stojaki-lawki", title: "Stojaki, ławki i bramy treningowe do siłowni", h1: "Stojaki, ławki i maszyny linowe do projektów siłowni", description: "Power rack, Smith machine, bramy funkcjonalne, wyciągi i ławki regulowane dla projektów, dystrybutorów i programów OEM.", keyword: "stojaki i ławki do siłowni", intent: "planowanie przestrzeni i montażu", focus: "Ocena obejmuje nie tylko wymiar urządzenia, lecz także strefę ruchu, wysokość pomieszczenia, dostęp serwisowy, montaż, punkty kotwienia, prowadzenie linek i współpracę z ławką." },
  "gym-accessories-category": { path: "/pl/produkty/akcesoria-fitness", title: "Akcesoria fitness hurtowo | Dostawca B2B", h1: "Akcesoria fitness dla dystrybutorów i obiektów profesjonalnych", description: "Kettlebells, uchwyty i akcesoria do wyciągów uzupełniające ofertę dystrybutora, projekt siłowni oraz program opakowań marki własnej.", keyword: "akcesoria fitness hurtowo", intent: "budowa asortymentu i zamówień uzupełniających", focus: "Akcesoria dobiera się według funkcji, materiału, interfejsu, chwytu, przechowywania, jednostki sprzedaży, opakowania i tempa rotacji, a nie liczby modeli w katalogu." },
  factory: { path: "/pl/fabryka", title: "Fabryka sprzętu fitness w Chinach | Produkcja i kontrola jakości", h1: "Produkcja i kontrola jakości sprzętu fitness PowerBaseFit", description: "Proces od specyfikacji i próbki przez produkcję, kontrolę, pakowanie eksportowe oraz przygotowanie zamówienia B2B.", keyword: "fabryka sprzętu fitness w Chinach", intent: "weryfikacja procesu produkcyjnego", focus: "Strona pokazuje, jak zatwierdzona specyfikacja przechodzi w próbkę, instrukcję roboczą, kontrolę procesu, inspekcję końcową, packing list i identyfikację partii." },
  "oem-private-label": { path: "/pl/oem-marka-wlasna", title: "OEM i marka własna sprzętu fitness | PowerBaseFit", h1: "OEM, ODM i marka własna dla sprzętu fitness", description: "Logo, kolor, oznakowanie i opakowanie poprzez ocenę wykonalności, MOQ, próbkę, zatwierdzenie, kontrolę jakości oraz produkcję seryjną.", keyword: "sprzęt fitness marka własna", intent: "rozwój programu OEM", focus: "Program rozdziela zmianę logo, koloru, etykiety, kartonu, konstrukcji i oprzyrządowania, ponieważ każdy poziom ma inne MOQ, koszt, próbkę i ryzyko." },
  projects: { path: "/pl/projekty", title: "Planowanie wyposażenia siłowni i strefy wolnych ciężarów", h1: "Planowanie dostaw dla komercyjnych projektów siłowni", description: "Dobór produktów, układ, przechowywanie, personalizacja, pakowanie i dostawa oparte na rzeczywistych produktach oraz zdjęciach PowerBaseFit.", keyword: "projekt siłowni komercyjnej", intent: "planowanie asortymentu i układu", focus: "Metoda łączy listę produktów, przestrzeń, przepływ użytkowników, przechowywanie, montaż i dostawę bez tworzenia fikcyjnych realizacji lub wyników klientów." },
  "blog-index": { path: "/pl/blog", title: "Poradniki zakupu sprzętu fitness dla buyerów B2B", h1: "Poradniki techniczne dotyczące zakupu sprzętu fitness", description: "Materiały dla importerów, dystrybutorów, marek i właścicieli siłowni o dostawcach, produktach, OEM, QC, opakowaniu, imporcie i kosztach całkowitych.", keyword: "poradniki zakupu sprzętu fitness", intent: "edukacja zakupowa B2B", focus: "Centrum wiedzy zmienia pytania zakupowe w kryteria, tabele, checklisty i dane, które można wykorzystać w RFQ, ocenie próbki oraz kontroli zamówienia." },
  contact: { path: "/pl/kontakt", title: "Zapytanie ofertowe B2B na sprzęt fitness | PowerBaseFit", h1: "Poproś o wycenę projektu wyposażenia siłowni", description: "Prześlij produkty, ilości, personalizację, miejsce dostawy i termin, aby otrzymać porównywalną ofertę B2B od PowerBaseFit.", keyword: "wycena sprzętu do siłowni", intent: "zebranie danych do oferty", focus: "Formularz zbiera SKU, ilość każdego wariantu, logo, opakowanie, miasto lub port docelowy, Incoterm i oczekiwany termin." },
  "rubber-hex-dumbbell-manufacturer": { path: "/pl/producent/hantle-hex-gumowane", title: "Producent gumowanych hantli hex | OEM i hurt", h1: "Gumowane hantle hex bezpośrednio od producenta B2B", description: "Profesjonalne hantle sześciokątne z opcjami wag, uchwytu, logo, opakowania eksportowego i marki własnej.", keyword: "producent hantli hex", intent: "kwalifikacja bezpośredniego producenta", focus: "Landing page koncentruje się na jednej powtarzalnej serii: konstrukcji głowicy, stabilności, chwycie, zapachu, oznaczeniu masy, kartonie, palecie i kolejnych partiach." }
};

type Guide = { slug: string; title: string; h1: string; keyword: string; intent: string; angle: string };
const guides: Record<string, Guide> = {
  "factory-guide": { slug: "jak-ocenic-fabryke-oem-sprzetu-fitness-w-chinach", title: "Jak ocenić fabrykę OEM sprzętu fitness w Chinach", h1: "Jak zweryfikować fabrykę sprzętu do siłowni przed zakupem", keyword: "fabryka sprzętu fitness w Chinach", intent: "kwalifikacja dostawcy", angle: "Prześledź jeden rzeczywisty SKU od materiału wejściowego do kartonu i oddziel procesy własne, podwykonawstwo, dostępną zdolność produkcyjną oraz obsługę niezgodności." },
  "dumbbells-guide": { slug: "jak-wybrac-hantle-do-silowni-komercyjnej", title: "Jak wybrać hantle do siłowni komercyjnej", h1: "Przewodnik wyboru hantli do profesjonalnej siłowni", keyword: "hantle do siłowni komercyjnej", intent: "wybór produktu", angle: "Najpierw ustal zakres wag, skok, liczbę podwójnych par, miejsce na stojak i profil użytkowników; dopiero potem porównuj kształt, powłokę, chwyt i cenę." },
  "plates-guide": { slug: "obciazenia-czy-talerze-bumper", title: "Obciążenia czy talerze bumper do siłowni", h1: "Różnice między obciążeniami a talerzami bumper dla buyerów B2B", keyword: "obciążenia a talerze bumper", intent: "porównanie produktów", angle: "Połącz otwór, średnicę, grubość, insert, masę i zachowanie przy upadku z gryfem, platformą, zasadami obiektu oraz rzeczywistym zastosowaniem." },
  "import-guide": { slug: "jak-importowac-sprzet-fitness-z-chin-do-polski", title: "Jak importować sprzęt fitness z Chin do Polski", h1: "Import sprzętu do siłowni z Chin — przewodnik dla polskiego buyera", keyword: "import sprzętu fitness z Chin", intent: "planowanie importu", angle: "Oddziel wybór dostawcy, specyfikację, klasyfikację taryfową, dokumenty, Incoterm, transport, kontrolę i koszty docelowe; aktualne obowiązki sprawdzaj w Access2Markets, TARIC i PUESC." },
  "import-cost-guide": { slug: "koszt-importu-sprzetu-do-silowni", title: "Jak obliczyć koszt importu sprzętu do siłowni", h1: "Obliczanie landed cost sprzętu fitness do Polski", keyword: "koszt importu sprzętu fitness", intent: "analiza kosztów", angle: "Licz produkt, opakowanie, palety, kontrolę, fracht, ubezpieczenie, należności, VAT, obsługę, magazynowanie, uszkodzenia i kapitał na poziomie SKU." },
  "moq-guide": { slug: "moq-sprzetu-fitness", title: "MOQ sprzętu fitness dla dystrybutora i marki", h1: "Jak działa MOQ przy zakupie sprzętu fitness", keyword: "MOQ sprzętu fitness", intent: "negocjacja ilości", angle: "Rozdziel MOQ produktu, koloru, logo, formy, kartonu i surowca, ponieważ całkowita wartość zamówienia nie zawsze spełnia minimum konkretnego procesu." },
  "oem-vs-odm-guide": { slug: "oem-czy-odm-sprzetu-fitness", title: "OEM czy ODM dla sprzętu fitness", h1: "Jak wybrać OEM lub ODM dla marki sprzętu fitness", keyword: "OEM a ODM sprzętu fitness", intent: "wybór modelu produkcji", angle: "Ustal, czy zmieniasz tylko identyfikację, konfigurację standardową czy funkcję i oprzyrządowanie; własność plików, testy, koszt i czas różnią się w każdym wariancie." },
  "private-label-guide": { slug: "jak-stworzyc-marke-wlasna-sprzetu-fitness", title: "Jak stworzyć markę własną sprzętu fitness", h1: "Budowa linii sprzętu fitness pod marką własną", keyword: "marka własna sprzętu fitness", intent: "rozwój marki", angle: "Zacznij od pozycji rynkowej, architektury SKU, produktów bazowych, identyfikacji, opakowania, próbki, QC, danych produktowych i planu ponownych zamówień." },
  "hex-vs-round-guide": { slug: "hantle-hex-czy-okragle", title: "Hantle hex czy okrągłe do siłowni", h1: "Hantle sześciokątne i okrągłe — porównanie dla obiektu profesjonalnego", keyword: "hantle hex a okrągłe", intent: "porównanie kształtu", angle: "Porównaj toczenie, stojak, stabilność na podłodze, dostęp do chwytu, szerokość głowicy, wygląd zestawu i ćwiczenia, w których hantla jest punktem podparcia." },
  "materials-guide": { slug: "hantle-gumowe-pu-czy-tpu", title: "Hantle gumowe, PU czy TPU", h1: "Porównanie materiałów hantli: guma, PU i TPU", keyword: "hantle gumowe a PU a TPU", intent: "porównanie materiałów", angle: "Porównuj kompletną konstrukcję, zapach, teksturę, wygląd, odporność powierzchni, kolor, czyszczenie, koszt i powtarzalność, a nie samą nazwę polimeru." },
  "olympic-vs-standard-guide": { slug: "obciazenia-olimpijskie-a-standardowe", title: "Obciążenia olimpijskie a standardowe", h1: "Różnice między obciążeniami olimpijskimi i standardowymi", keyword: "obciążenia olimpijskie a standardowe", intent: "weryfikacja kompatybilności", angle: "Zmierz otwór i tuleję gryfu, a następnie sprawdź maszyny, grubość, przechowywanie, asortyment i dostępność zamienników przed wyborem standardu obiektu." },
  "professional-gym-list-guide": { slug: "lista-sprzetu-do-profesjonalnej-silowni", title: "Lista sprzętu do profesjonalnej siłowni", h1: "Jak przygotować listę wyposażenia siłowni komercyjnej", keyword: "lista sprzętu do siłowni", intent: "planowanie asortymentu", angle: "Buduj listę z profilu użytkowników, obciążenia w godzinach szczytu, stref, budżetu, przestrzeni, serwisu i etapów otwarcia, nie z liczby pozycji w katalogu." },
  "free-weight-area-guide": { slug: "planowanie-strefy-wolnych-ciezarow", title: "Planowanie profesjonalnej strefy wolnych ciężarów", h1: "Jak zaprojektować strefę wolnych ciężarów w siłowni", keyword: "strefa wolnych ciężarów", intent: "planowanie układu", angle: "Umieść na jednej skali stojaki, ławki, hantle, obciążenia, gryfy, storage, platformy, ciągi komunikacyjne, spottera i przestrzeń ruchu użytkownika." },
  "bumper-manufacturing-guide": { slug: "jak-powstaja-talerze-bumper", title: "Jak produkowane są talerze bumper", h1: "Proces produkcji talerzy bumper i kontrola jakości", keyword: "produkcja talerzy bumper", intent: "zrozumienie produkcji", angle: "Rozróżnij mieszankę, przygotowanie insertu, formowanie, chłodzenie, korektę masy, wykończenie, kontrolę wymiarów i testy odpowiednie dla kupowanej konstrukcji." },
  "dumbbell-weighing-guide": { slug: "kontrola-masy-hantli-w-fabryce", title: "Jak kontrolowana jest masa hantli", h1: "Ważenie i weryfikacja hantli podczas produkcji", keyword: "tolerancja masy hantli", intent: "kontrola masy", angle: "Ustal jednostkę, tolerancję, rozdzielczość i status wzorcowania wagi, sampling, moment pomiaru oraz sprawdzenie wyważenia dla lekkich i ciężkich SKU." },
  "plate-materials-b2b": { slug: "obciazenia-zeliwne-gumowe-czy-uretanowe", title: "Obciążenia żeliwne, gumowe czy uretanowe", h1: "Porównanie materiałów obciążeń w zakupie B2B", keyword: "obciążenia żeliwne gumowe uretanowe", intent: "wybór materiału", angle: "Porównaj rdzeń, powłokę, insert, średnicę, grubość, uchwyty, czyszczenie i powtarzalność przy tej samej masie oraz sposobie użytkowania." },
  "commercial-free-weight-rfq": { slug: "checklista-rfq-wolne-ciezary", title: "Checklista RFQ na hantle i obciążenia", h1: "Dane wymagane w RFQ na komercyjne wolne ciężary", keyword: "RFQ sprzętu fitness", intent: "przygotowanie zapytania", angle: "Użyj jednego wiersza na SKU i osobnych kolumn dla wymagań, alternatyw, ilości, kosztów jednorazowych, próbki, QC, kartonu, palety i dostawy." },
  "custom-logo-free-weights": { slug: "logo-na-hantlach-i-obciazeniach", title: "Metody logo na hantlach i obciążeniach", h1: "Jak wybrać metodę logo dla sprzętu marki własnej", keyword: "logo na hantlach", intent: "personalizacja produktu", angle: "Wybierz metodę dopiero po potwierdzeniu materiału i geometrii; sprawdź plik wektorowy, rozmiar, pozycję, kolor, trwałość, oznaczenie masy, etykietę i karton." },
  "export-packaging-free-weights": { slug: "opakowanie-eksportowe-hantli-i-obciazen", title: "Opakowanie eksportowe hantli i obciążeń", h1: "Projektowanie opakowania eksportowego wolnych ciężarów", keyword: "opakowanie eksportowe sprzętu fitness", intent: "ograniczenie szkód transportowych", angle: "Projektuj karton i paletę według masy, środka ciężkości, sposobu podnoszenia, piętrowania, wilgoci, etykiet i kolejności rozpakowania." },
  "free-weight-reorder-batch-consistency": { slug: "powtarzalnosc-partii-przy-ponownym-zamowieniu", title: "Powtarzalność partii przy ponownym zamówieniu", h1: "Kontrola zgodności produktu między pierwszą i kolejną partią", keyword: "powtarzalność partii hantli", intent: "zarządzanie repeat order", angle: "Archiwizuj próbkę, rewizję, kolor, artwork, wymiary, masę, zdjęcia QC i instrukcję pakowania oraz wymagaj informacji o zmianach materiału, formy lub poddostawcy." },
  "landed-cost-free-weights": { slug: "landed-cost-hantli-i-obciazen-hurtowo", title: "Landed cost hantli i obciążeń hurtowo", h1: "Jak obliczyć całkowity koszt importu wolnych ciężarów", keyword: "landed cost sprzętu fitness", intent: "analiza kosztu docelowego", angle: "Policz koszty stałe i zmienne na SKU, a następnie sprawdź scenariusze wolumenu, wykorzystania kontenera, kursu, szkód, magazynowania i rotacji." },
  "oem-sample-approval-free-weights": { slug: "zatwierdzanie-probki-oem-wolnych-ciezarow", title: "Zatwierdzanie próbki OEM wolnych ciężarów", h1: "Jak zatwierdzić próbkę OEM przed produkcją seryjną", keyword: "próbka OEM sprzętu fitness", intent: "kontrola przedprodukcyjna", angle: "Napisz, co próbka ma udowodnić, oznacz rewizję, zmierz wynik, zapisz odchylenia i rozróżnij próbkę wyglądu, funkcji oraz produkcyjną." },
  "commercial-dumbbell-set-planning": { slug: "planowanie-zestawu-hantli-do-silowni", title: "Planowanie zestawu hantli do siłowni", h1: "Jak określić zakres i liczbę hantli komercyjnych", keyword: "zestaw hantli do siłowni", intent: "planowanie serii wagowej", angle: "Wykorzystaj popyt według zakresu wag, profil członków, godziny szczytu, dodatkowe pary, miejsce na stojak, wymiany i budżet." },
  "pre-shipment-inspection-free-weights": { slug: "inspekcja-przedwysylkowa-hantli-i-obciazen", title: "Inspekcja przedwysyłkowa hantli i obciążeń", h1: "Checklista inspekcji wolnych ciężarów przed wysyłką", keyword: "inspekcja sprzętu fitness przed wysyłką", intent: "kontrola zamówienia", angle: "Ustal poziom ukończenia, sampling, próbkę referencyjną, klasy wad, narzędzia pomiarowe, dowody i sposób obsługi niezgodności przed przyjazdem inspektora." },
  "training-vs-competition-bumper-plates": { slug: "talerze-bumper-training-a-competition", title: "Talerze bumper training a competition", h1: "Porównanie talerzy bumper treningowych i competition", keyword: "bumper training a competition", intent: "porównanie osiągów", angle: "Porównaj masę, średnicę, grubość, insert, wygląd, tolerancję i metodę testu; etykieta training lub competition nie zastępuje danych konstrukcyjnych." }
};

const productNames: Record<string, string> = {
  "hex-dumbbell-kg":"Hantla sześciokątna gumowana","chrome-dumbbell":"Hantla chromowana","rubber-bumper-plate":"Gumowy talerz bumper","classic-rubber-round-dumbbell":"Okrągła hantla gumowana","pu-dumbbell-kg":"Hantla PU","rubber-olympic-plate":"Gumowane obciążenie olimpijskie","cast-iron-dumbbell":"Hantla żeliwna","cpu-dumbbell-kg":"Hantla CPU","tpu-dumbbell-kg":"Hantla TPU","cpu-bumper-plate":"Talerz bumper CPU","cast-iron-weight-plate":"Obciążenie żeliwne","cpu-grip-plate":"Obciążenie CPU z uchwytami",
  "twelve-sided-steel-dumbbell":"Dwunastokątna hantla stalowa","cpu-square-dumbbell-kg":"Kwadratowa hantla CPU","adjustable-dumbbell-kg":"Hantla regulowana","cpu-heavy-dumbbell-kg":"Ciężka hantla CPU","neoprene-dumbbell-kg":"Hantla neoprenowa","sus304-dumbbell-kg":"Hantla ze stali nierdzewnej SUS304","tpu-round-dumbbell-kg":"Okrągła hantla TPU","tpu-small-dumbbell-kg":"Kompaktowa hantla TPU","selectorized-adjustable-dumbbell-kg":"Hantla regulowana selektorowa","cpu-hexagonal-dumbbell-kg":"Sześciokątna hantla CPU","cpu-compact-dumbbell":"Kompaktowa hantla CPU","cpu-twelve-sided-dumbbell":"Dwunastokątna hantla CPU","cpu-hexagonal-dumbbell-wide":"Szeroka sześciokątna hantla CPU","cpu-dumbbell-full-range":"Pełny zestaw hantli CPU",
  "cpu-color-bumper-plate":"Kolorowy talerz bumper CPU","rubber-weight-plate":"Gumowane obciążenie","rubber-barbell-plate":"Gumowany talerz do sztangi","full-rubber-barbell-plate":"Talerz całkowicie pokryty gumą","black-competition-plate":"Czarny talerz bumper competition","solid-steel-barbell-plate":"Pełny talerz stalowy","custom-solid-steel-barbell-plate":"Personalizowany talerz stalowy","heavy-solid-steel-plate":"Ciężki pełny talerz stalowy","gold-steel-barbell-plate":"Złoty talerz stalowy","rubber-competition-bumper-plate":"Gumowy talerz bumper competition","seven-hole-cast-iron-plate":"Siedmiochwytowe obciążenie żeliwne","spray-weight-plate":"Obciążenie malowane natryskowo","tpu-olympic-plate":"Obciążenie olimpijskie TPU","star-tpu-plate":"Obciążenie TPU w kształcie gwiazdy","pu-grip-plate":"Obciążenie PU z uchwytami","pu-color-plate":"Kolorowe obciążenie PU","cpu-mini-bumper-plate":"Mini talerz bumper CPU","pu-plate-set":"Zestaw obciążeń PU","four-grip-cpu-plate":"Obciążenie CPU z czterema uchwytami",
  "private-home-gym-rack-system":"System stojaka do prywatnej siłowni","power-rack-functional-trainer":"Power rack z bramą funkcjonalną","home-gym-functional-trainer":"Brama funkcjonalna do domowej siłowni","compact-cable-power-rack":"Kompaktowy power rack z wyciągiem","dual-pulley-smith-rack":"Stojak Smitha z podwójnym wyciągiem","custom-home-gym-rack":"Personalizowany stojak do domowej siłowni","storage-functional-trainer":"Brama funkcjonalna ze storage","cable-crossover-functional-trainer":"Brama funkcjonalna cable crossover","adjustable-weight-bench":"Regulowana ławka treningowa","smith-squat-frame":"Rama Smitha do przysiadów","half-frame-squat-rack":"Half rack do przysiadów","cable-cross-functional-trainer":"Brama funkcjonalna cable cross","six-column-functional-trainer":"Sześciokolumnowa brama funkcjonalna","cable-crossover-machine":"Maszyna cable crossover","full-frame-squat-rack":"Pełny stojak do przysiadów","eight-column-training-rack":"Ośmiokolumnowy system treningowy","wall-mounted-functional-trainer":"Ścienna brama funkcjonalna","smith-cable-crossover-machine":"Maszyna Smitha z cable crossover","floor-plate-cable-crossover":"Cable crossover z płytą podłogową","smith-machine":"Maszyna Smitha","wall-folding-functional-trainer":"Składana ścienna brama funkcjonalna","incline-flat-decline-bench":"Ławka incline flat decline","commercial-adjustable-bench":"Komercyjna ławka regulowana","heavy-duty-adjustable-bench":"Wzmocniona ławka regulowana","compact-adjustable-bench":"Kompaktowa ławka regulowana","three-in-one-smith-functional-trainer":"Smith functional trainer 3 w 1","smith-dual-pulley-trainer":"Smith trainer z podwójnym wyciągiem","olympic-bench-plate-storage":"Ławka olimpijska ze storage na obciążenia","multi-jungle-functional-trainer":"Wielostanowiskowa brama multi jungle","single-station-functional-trainer":"Jednostanowiskowa brama funkcjonalna","three-station-functional-trainer":"Trzystanowiskowa brama funkcjonalna","five-station-functional-trainer":"Pięciostanowiskowa brama funkcjonalna",
  "vinyl-kettlebell":"Kettlebell winylowy","cast-iron-kettlebell":"Kettlebell żeliwny","competition-kettlebell":"Kettlebell competition","rubber-coated-gym-handle-sets":"Zestaw gumowanych uchwytów do wyciągu","aluminum-gym-handles":"Aluminiowe uchwyty do wyciągu","solid-steel-gym-handles":"Pełne stalowe uchwyty do wyciągu","lat-pulldown-handles":"Uchwyty do lat pulldown","cable-machine-attachments":"Zestaw akcesoriów do wyciągu"
};

function slugify(value: string) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ł/g, "l").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function sourceSlug(entity: ContentEntity) {
  return entity.versions.en?.publicPath?.split("/").filter(Boolean).pop() ?? entity.id;
}

function family(entity: ContentEntity) {
  const path = entity.versions.en?.publicPath ?? "";
  if (path.includes("/dumbbells/")) return { slug: "hantle", label: "Hantle", categoryId: "dumbbells-category" };
  if (path.includes("/weight-plates/")) return { slug: "obciazenia", label: "Obciążenia", categoryId: "weight-plates-category" };
  if (path.includes("/racks-benches/")) return { slug: "stojaki-lawki", label: "Stojaki i ławki", categoryId: "racks-benches-category" };
  return { slug: "akcesoria-fitness", label: "Akcesoria fitness", categoryId: "gym-accessories-category" };
}

function base(version: Omit<LocalizedContentVersion, "locale" | "translationStatus" | "reviewStatus" | "publishStatus" | "canonicalData" | "hreflangData" | "updatedAt" | "publishedAt" | "version">): LocalizedContentVersion {
  return { ...version, locale: "pl", translationStatus: "localized", reviewStatus: "approved", publishStatus: "published", canonicalData: { mode: "self" }, hreflangData: { include: true }, updatedAt: publishedAt, publishedAt, version: 1 };
}

function imagesFor(entity: ContentEntity, label: string): LocalizedImage[] {
  const sources = [...new Set([
    ...(entity.versions.en?.images.map((image) => image.src) ?? []),
    ...(entity.versions.id?.images.map((image) => image.src).filter((src) => src.startsWith("/assets/")) ?? []),
    "/assets/dumbbell-production.webp",
    "/assets/factory-cases/packaging-area-pbf.webp"
  ])].slice(0, 3);
  return sources.map((src, index) => ({ id: `zdjecie-${index + 1}`, src, alt: index === 0 ? `${label} — rzeczywisty produkt lub realizacja PowerBaseFit` : index === 1 ? `Proces produkcji związany z tematem: ${label}` : `Pakowanie eksportowe i kontrola zamówienia: ${label}`, caption: "Rzeczywisty materiał PowerBaseFit użyty do wyjaśnienia decyzji zakupowej." }));
}

function commonFaq(keyword: string) {
  return [
    { id: "faq-1", question: `Od czego zacząć ocenę: ${keyword}?`, answer: "Najpierw określ zastosowanie, użytkownika, wariant produktu, ilość i decyzję biznesową. Dopiero później porównuj próbkę, dostawcę i cenę." },
    { id: "faq-2", question: "Czy przed zamówieniem potrzebna jest próbka?", answer: "Próbka jest zalecana, gdy materiał, wymiar, funkcja, wykończenie, logo lub opakowanie wpływają na wynik. Należy zapisać, co dokładnie ma potwierdzić." },
    { id: "faq-3", question: "Jak porównać dwóch dostawców?", answer: "Wyślij ten sam RFQ i porównuj ten sam zakres: produkt, ilość, personalizację, kontrolę jakości, opakowanie, Incoterm i koszty wyłączone." },
    { id: "faq-4", question: "Czy możliwa jest marka własna?", answer: "Tak dla odpowiednich produktów i wolumenów. Metodę logo, artwork, MOQ, próbkę, kontrolę i opakowanie potwierdza się przed produkcją seryjną." },
    { id: "faq-5", question: "Kto odpowiada za wymagania importowe w Polsce?", answer: "Importer i jego doradcy weryfikują aktualną klasyfikację, dokumenty, należności, VAT i obowiązki produktu w oficjalnych źródłach UE oraz Polski dla konkretnej transakcji." }
  ];
}

function decisionBlocks(keyword: string, focus: string, seed: string) {
  const blocks = [
    plAnswer(`fokus-${seed}`, `Najważniejsza decyzja — ${keyword}`, `${focus} Rezultatem powinien być zapisany wariant, zakres oferty, otwarte pytania, odpowiedzialność i następny krok.`),
    plDefinition(`definicja-${seed}`, keyword, `${keyword} oznacza w tym serwisie konkretny problem zakupowy powiązany z rzeczywistym produktem, specyfikacją, dowodem, kontrolą jakości i decyzją B2B, a nie ogólne hasło marketingowe.`),
    plText(`wymagania-${seed}`, `Wymagania wejściowe — ${keyword}`, "Rozdziel wymagania obowiązkowe, preferencje i kwestie do potwierdzenia. W każdym wierszu podaj produkt, wariant, ilość, zastosowanie, jednostkę, termin i osobę zatwierdzającą.", "Brak danych nie oznacza zgody. Dostawca powinien oznaczyć pozycję jako zgodną, odmienną albo wymagającą wyjaśnienia, aby oferta nie ukrywała założeń."),
    plText(`specyfikacja-${seed}`, `Specyfikacja i próbka — ${keyword}`, "Połącz kod SKU z rysunkiem, materiałem, wymiarem, masą, funkcją, wykończeniem, oznaczeniem oraz zawartością opakowania. Próbka musi mieć numer rewizji i status zatwierdzenia.", "Sprawdź wariant lekki, średni i ciężki albo najbardziej ryzykowne konfiguracje. Jedna reprezentacyjna sztuka nie zawsze potwierdza całą serię, narzędzia i sposób pakowania."),
    plTable(`macierz-${seed}`, `Macierz decyzji — ${keyword}`, ["Obszar", "Dane minimalne", "Dowód przed zamówieniem"], [["Produkt", "SKU, wariant, ilość", "Rysunek i próbka"], ["Jakość", "Metoda, tolerancja, sampling", "Plan QC"], ["Marka", "Logo, kolor, etykieta", "Artwork i próbka"], ["Logistyka", "Karton, paleta, Incoterm", "Packing list"], ["Kolejna partia", "Rewizja i referencje", "Archiwum zatwierdzeń"]]),
    plText(`qc-${seed}`, `Kontrola jakości — ${keyword}`, "Kryterium powinno określać metodę, narzędzie, punkt pomiaru, jednostkę, próbę i limit. Dla wyglądu ustal oświetlenie oraz próbkę odniesienia; dla funkcji opisz warunki testu.", "Oddziel kontrolę procesu od inspekcji końcowej. Pierwsza ogranicza powstawanie odchyleń, druga ocenia partię gotową do wysyłki i nie zastępuje nadzoru wcześniejszych etapów."),
    plText(`oem-${seed}`, `OEM i marka własna — ${keyword}`, "Logo, kolor, oznaczenia, etykieta, karton i zmiana konstrukcji mają różne MOQ, koszt oraz czas. Każdą modyfikację wpisz osobno wraz z metodą, plikiem, pozycją i kryterium akceptacji.", "Koszty jednorazowe, próbka, oprzyrządowanie i minimalna ilość procesu powinny być oddzielone od ceny standardowego produktu. Ułatwia to ocenę wykonalności i plan kolejnych zamówień."),
    plText(`opakowanie-${seed}`, `Opakowanie i dostawa — ${keyword}`, "Dobierz karton, wkładki i paletę do masy, środka ciężkości, sposobu podnoszenia, piętrowania, wilgoci, etykiety i kolejności rozpakowania. Sprawdź ochronę powierzchni i elementów wystających.", "Packing list musi pozwalać magazynowi rozpoznać SKU, ilość, masę netto i brutto, wymiary oraz numer partii. Dane te wpływają na fracht, obsługę i landed cost."),
    plText(`polska-${seed}`, `Kontekst polskiego importera — ${keyword}`, "Importer w Polsce weryfikuje klasyfikację CN/TARIC, wartość celną, pochodzenie, dokumenty, VAT i wymagania produktu dla rzeczywistej transakcji. PowerBaseFit dostarcza dane produkcyjne i eksportowe, ale nie zastępuje importera ani organu.", "Aktualne informacje należy sprawdzać w Access2Markets, TARIC, polskim PUESC oraz u właściwego agenta celnego lub doradcy. Nie stosuj stawki ani wymogu z ogólnego artykułu bez potwierdzenia kodu i daty."),
    plText(`koszt-${seed}`, `Koszt całkowity — ${keyword}`, "Porównuj produkt, opakowanie, palety, kontrolę, fracht, ubezpieczenie, odprawę, należności, VAT, obsługę, magazynowanie, szkody i kapitał. Oddziel koszty jednorazowe od powtarzalnych.", "Użyj scenariusza niskiego, bazowego i wysokiego dla wolumenu, kursu, transportu, uszkodzeń i rotacji. Cena fabryczna nie jest kosztem produktu dostarczonego do magazynu."),
    plText(`dostawca-${seed}`, `Ocena dostawcy — ${keyword}`, "Poproś o wyjaśnienie procesu dla wskazanego SKU: materiału, formy lub obróbki, poddostawców, próbki, produkcji, kontroli, pakowania i zarządzania zmianą.", "Zdolność ogólna fabryki nie dowodzi zdolności dla konkretnej konfiguracji i terminu. Oferta powinna wskazywać zakres, wyłączenia, ważność, walutę i nazwane miejsce Incoterm."),
    plText(`repeat-${seed}`, `Powtarzalność kolejnej partii — ${keyword}`, "Archiwizuj specyfikację, próbkę, artwork, kolor, zdjęcia kontrolowane, raport QC, instrukcję pakowania i packing list. Reklamacje łącz z kodem SKU oraz numerem partii.", "Przed ponownym zamówieniem zapytaj o zmianę materiału, formy, narzędzia, poddostawcy lub opakowania. Porównaj first article z zatwierdzoną rewizją i danymi poprzedniej partii."),
    plChecklist(`checklista-${seed}`, `Checklista buyera — ${keyword}`, ["Określ zastosowanie i użytkownika", "Wypisz SKU oraz ilość każdego wariantu", "Zapisz materiał, wymiar, funkcję i tolerancję", "Zażądaj pisemnej listy odstępstw", "Potwierdź MOQ i koszty jednorazowe", "Zatwierdź próbkę oraz artwork z rewizją", "Ustal sampling i reakcję na wady", "Sprawdź karton, paletę i packing list", "Porównaj ten sam Incoterm i named place", "Zachowaj dane dla reklamacji i repeat order"]),
    plText(`dzialanie-${seed}`, `Następny krok — ${keyword}`, "Przekształć checklistę w krótki RFQ. Dołącz SKU, ilości, rynek, personalizację, miejsce dostawy i oczekiwany termin, a dostawca powinien wskazać wpływ na MOQ, próbkę, kontrolę oraz logistykę.", "Jeżeli krytyczne wymagania nie są jeszcze znane, właściwym krokiem jest rozmowa techniczna lub plan próbki, a nie przedwczesna cena oparta na nieporównywalnych założeniach.")
  ];
  const middle = blocks.slice(2, -2);
  const offset = [...seed].reduce((sum, character) => sum + character.charCodeAt(0), 0) % middle.length;
  return [...blocks.slice(0, 2), ...middle.slice(offset), ...middle.slice(0, offset), ...blocks.slice(-2)];
}

function productDecisionBlocks(name: string, group: ReturnType<typeof family>, source: string) {
  const familyAdvice: Record<string, string[]> = {
    hantle: ["zakres mas i skok między kolejnymi parami", "geometrię głowicy oraz współpracę ze stojakiem", "średnicę, fakturę i długość części chwytnej", "czytelność oznaczenia masy z pozycji użytkownika"],
    obciazenia: ["średnicę otworu i współpracę z tuleją gryfu", "grubość talerza oraz liczbę sztuk na rękawie", "konstrukcję insertu i sposób jego osadzenia", "tolerancję masy dla lekkich i ciężkich wariantów"],
    "stojaki-lawki": ["gabaryt urządzenia oraz bezpieczną strefę pracy", "zakres regulacji, punkty blokowania i ergonomię", "dostęp montażowy, serwisowy i sposób kotwienia", "zgodność elementów współpracujących z układem sali"],
    "akcesoria-fitness": ["interfejs z urządzeniem i rzeczywisty sposób chwytu", "materiał części roboczej oraz powierzchni kontaktowej", "jednostkę sprzedaży, kompletność zestawu i oznaczenia", "przechowywanie, ekspozycję i pakowanie pojedynczego SKU"]
  };
  const checks = familyAdvice[group.slug];
  return [
    plText(`konfiguracja-${source}`, `Konfiguracja modelu ${name}`, `${name} należy opisać jednym kodem rewizji obejmującym ${checks[0]}, ${checks[1]}, ${checks[2]} i ${checks[3]}. Dzięki temu próbka, oferta, zamówienie oraz raport kontroli odnoszą się do dokładnie tej samej konfiguracji.`, `Wariantów modelu ${name} nie należy łączyć w jednym ogólnym wierszu. Każda masa, kolor, rozmiar lub opcja wyposażenia otrzymuje osobny SKU, ilość, cenę, masę wysyłkową i status zatwierdzenia.`),
    plText(`uzytkowanie-${source}`, `${name} w rzeczywistym zastosowaniu`, `Ocena modelu ${name} zaczyna się od miejsca użytkowania: profilu członków, natężenia ruchu, częstotliwości odkładania, sposobu czyszczenia oraz dostępnego storage. Kryteria próbki powinny odtwarzać te warunki, zamiast ograniczać się do wyglądu nowego produktu.`, `Dla serii komercyjnej sprawdza się również spójność sąsiednich wariantów. Użytkownik powinien otrzymać przewidywalny chwyt, oznaczenie i sposób obsługi, a operator obiektu — jasną procedurę kontroli, konserwacji i wymiany.`),
    plTable(`porownanie-${source}`, `Co porównać w ofertach na ${name}`, ["Punkt porównania", "Pytanie do dostawcy", "Dowód"], [[checks[0], "Jaka wartość i tolerancja obowiązuje?", "Rysunek lub karta SKU"], [checks[1], "Jak wynik jest sprawdzany w partii?", "Zdjęcie pomiaru i plan QC"], [checks[2], "Czy próbka odpowiada produkcji seryjnej?", "Numer rewizji próbki"], [checks[3], "Jak zabezpiecza to opakowanie?", "Specyfikacja kartonu i palety"]]),
    plText(`asortyment-${source}`, `Rola ${name} w asortymencie`, `${name} powinien mieć jasno określoną rolę: produkt podstawowy, wariant premium, pozycję projektową albo uzupełnienie oferty. Ta decyzja wpływa na liczbę SKU, zapas części lub sztuk zamiennych, opakowanie detaliczne, ekspozycję oraz częstotliwość ponownego zamówienia.`, `Importer powinien oceniać marżę i rotację na poziomie wariantu, nie tylko całej kategorii ${group.label.toLowerCase()}. Ciężar, objętość i ryzyko uszkodzeń powodują, że dwa podobnie wycenione produkty mogą mieć inny landed cost i inne wymagania magazynowe.`)
  ];
}

function guideDecisionBlocks(profile: Guide, entityId: string) {
  const angle = profile.angle;
  return [
    plText(`zakres-${entityId}`, `Zakres decyzji: ${profile.keyword}`, `${angle} Najpierw zapisz decyzję, którą materiał ma wesprzeć, osobę odpowiedzialną i termin. Następnie oddziel dane wejściowe od założeń oraz zaznacz informacje wymagające potwierdzenia przez producenta, importera lub właściwego specjalistę.`, `Dobra analiza nie kończy się listą zalet. Powinna wskazać alternatywy, ograniczenia, kryteria odrzucenia i dowód potrzebny przed przejściem do próbki, produkcji albo wysyłki.`),
    plText(`dane-${entityId}`, `Dane wejściowe do analizy`, `Dla tematu „${profile.keyword}” zbierz listę SKU, ilości, zastosowanie, rynek, oczekiwany poziom personalizacji, punkt dostawy i termin. Jeżeli decyzja dotyczy istniejącego obiektu, dodaj wymiary, zdjęcia, sposób użytkowania, storage i doświadczenia z poprzednią partią.`, `Wszystkie liczby zapisuj z jednostką i źródłem. Informacja z katalogu, wynik pomiaru próbki, deklaracja dostawcy i wymaganie kupującego mają różną wagę, dlatego nie powinny znaleźć się w jednej kolumnie bez oznaczenia.`),
    plText(`scenariusze-${entityId}`, `Scenariusze i kompromisy`, `${angle} Porównaj co najmniej wariant bazowy, oszczędnościowy i ograniczający ryzyko. Dla każdego pokaż wpływ na cenę produktu, MOQ, czas, kontrolę, opakowanie, transport, zapas oraz możliwość powtórzenia zamówienia.`, `Najtańszy wariant fabryczny nie musi być najtańszy po dostawie. Zmiana materiału, masy, liczby kartonów albo wykorzystania kontenera może przesunąć koszt do kontroli, frachtu, magazynu, szkód i obsługi posprzedażowej.`),
    plTable(`dowody-${entityId}`, `Plan dowodów dla: ${profile.keyword}`, ["Etap", "Pytanie", "Wymagany zapis"], [["RFQ", "Czy zakres jest jednoznaczny?", "Tabela SKU i odstępstw"], ["Próbka", "Co dokładnie zatwierdzamy?", "Rewizja, pomiary i zdjęcia"], ["Produkcja", "Które cechy są kontrolowane w procesie?", "Instrukcja i plan kontroli"], ["Wysyłka", "Czy partia jest kompletna i zgodna?", "Raport, packing list i identyfikacja partii"]]),
    plText(`bledy-${entityId}`, `Najczęstsze błędy przy temacie ${profile.keyword}`, `Pierwszym błędem jest porównanie ofert o innym zakresie. Kolejne to brak nazwanej wersji produktu, niejasna jednostka, pominięcie opakowania, traktowanie próbki wyglądu jak próbki produkcyjnej oraz przyjęcie, że ogólna deklaracja dostawcy zastępuje mierzalne kryterium.`, `Błędem jest też przenoszenie stawki, procedury lub wymagania z ogólnego artykułu na konkretną transakcję. Aktualne informacje importowe trzeba sprawdzić dla kodu, produktu, pochodzenia i daty w oficjalnych źródłach UE oraz Polski.`),
    plText(`spotkanie-${entityId}`, `Pytania na spotkanie z dostawcą`, `Poproś dostawcę, aby na przykładzie wskazanego SKU wyjaśnił materiał, proces, podwykonawstwo, narzędzia, tolerancje, sampling, pakowanie i obsługę zmiany. Przy temacie „${profile.keyword}” odpowiedź powinna odnosić się do Twojego wariantu, a nie jedynie do ogólnej zdolności fabryki.`, `Zapisz każde odstępstwo i ustal, czy zmienia ono cenę, MOQ, termin, próbkę lub kryterium kontroli. Podsumowanie spotkania warto dołączyć do RFQ i późniejszego zamówienia, aby decyzje nie pozostały wyłącznie w korespondencji.`),
    plText(`wdrozenie-${entityId}`, `Jak wdrożyć wynik`, `${angle} Zamień wnioski na właściciela zadania, datę, dokument i status. Pozycje otwarte nie mogą automatycznie stać się zaakceptowanymi wymaganiami tylko dlatego, że zbliża się termin zamówienia.`, `Po zatwierdzeniu zachowaj wersję specyfikacji, próbkę referencyjną, artwork, raporty, zdjęcia pakowania i dokumenty wysyłkowe. Ten pakiet stanowi punkt odniesienia dla reklamacji oraz kolejnego zamówienia i ogranicza ryzyko cichej zmiany.`),
    plText(`granice-${entityId}`, `Odpowiedzialność i źródła`, `PowerBaseFit może dostarczyć dane produktu, procesu, opakowania i eksportu. Importer odpowiada za ocenę obowiązków dla konkretnego produktu i transakcji. W przypadku klasyfikacji, należności i procedur należy korzystać z aktualnych informacji Access2Markets, TARIC i PUESC oraz właściwego doradcy.`, `Materiał o „${profile.keyword}” jest metodą przygotowania zakupu, a nie obietnicą stawki celnej, certyfikacji ani przydatności produktu. Ostateczne wymagania muszą zostać zapisane i zweryfikowane przed zamówieniem.`)
  ];
}

function coreVersion(entity: ContentEntity, profile: Profile): LocalizedContentVersion {
  const body = decisionBlocks(profile.keyword, profile.focus, entity.id);
  if (entity.type === "contact") body.push({ id: "inquiry-form", type: "custom", heading: "Opisz swoje zapotrzebowanie", data: { component: "inquiry-form" } });
  return base({ slug: profile.path.split("/").pop() || "pl", publicPath: profile.path, title: profile.title, description: profile.description, h1: profile.h1, body, faq: commonFaq(profile.keyword), author: polishEditorialAuthor, reviewedBy: polishTechnicalReviewer, schemaData: { brand: "PowerBaseFit", manufacturer: "PowerBaseFit", category: profile.keyword, breadcrumbs: [{ name: "Strona główna", path: "/pl" }, ...(profile.path === "/pl" ? [] : [{ name: profile.h1, path: profile.path }])], extra: { primaryKeyword: profile.keyword, searchIntent: profile.intent } }, images: imagesFor(entity, profile.h1), internalLinks: [{ targetContentId: "products-hub", label: "Zobacz wszystkie produkty" }, { targetContentId: "factory", label: "Sprawdź produkcję i kontrolę jakości" }, { targetContentId: "oem-private-label", label: "Poznaj program OEM i marki własnej" }, { targetContentId: "contact", label: "Wyślij zapytanie B2B" }] });
}

function productVersion(entity: ContentEntity): LocalizedContentVersion {
  const source = sourceSlug(entity);
  const name = productNames[source];
  if (!name) throw new Error(`Polish product name missing: ${entity.id} (${source})`);
  const group = family(entity);
  const slug = slugify(name);
  const path = `/pl/produkty/${group.slug}/${slug}`;
  const keyword = `${name.toLowerCase()} do siłowni`;
  const focus = `${name} należy oceniać jako konkretną konfigurację serii: materiał, geometrię, zakres, oznaczenia, interfejsy, opakowanie i powtarzalność. Buyer powinien powiązać te dane z zastosowaniem, sposobem sprzedaży i obsługą kolejnych partii.`;
  return base({ slug, publicPath: path, title: `${name} do siłowni | Producent OEM PowerBaseFit`, description: `${name} dla dystrybutorów i siłowni komercyjnych: specyfikacja, próbka, produkcja, QC, pakowanie eksportowe, OEM i zapytanie B2B.`, h1: `${name} do profesjonalnych siłowni i zakupów B2B`, body: [...decisionBlocks(keyword, focus, slug), ...productDecisionBlocks(name, group, source)], faq: commonFaq(keyword), author: polishEditorialAuthor, reviewedBy: polishTechnicalReviewer, schemaData: { sku: `PBF-${source.toUpperCase()}`, brand: "PowerBaseFit", manufacturer: "PowerBaseFit", material: entity.versions.en?.schemaData.material, category: group.label, specifications: [{ name: "Produkt", value: name }, { name: "Zakres", value: "Według zatwierdzonego SKU i oferty" }, { name: "Odbiorca", value: "Siłownie, dystrybutorzy, importerzy i marki fitness" }], breadcrumbs: [{ name: "Strona główna", path: "/pl" }, { name: "Produkty", path: "/pl/produkty" }, { name: group.label, path: `/pl/produkty/${group.slug}` }, { name, path }], extra: { primaryKeyword: keyword, searchIntent: "ocena produktu i zapytanie ofertowe B2B" } }, images: imagesFor(entity, name), internalLinks: [{ targetContentId: group.categoryId, label: `Zobacz kategorię: ${group.label}` }, { targetContentId: "factory", label: "Produkcja i kontrola jakości" }, { targetContentId: "oem-private-label", label: "OEM i marka własna" }, { targetContentId: "contact", label: "Poproś o wycenę B2B" }] });
}

function guideVersion(entity: ContentEntity, profile: Guide): LocalizedContentVersion {
  const path = `/pl/blog/${profile.slug}`;
  const focus = `${profile.angle} Artykuł prowadzi do decyzji w obszarze „${profile.intent}” i nie zastępuje specyfikacji produktu, aktualnej informacji urzędowej ani indywidualnej porady importowej.`;
  return base({ slug: profile.slug, publicPath: path, title: `${profile.title} | PowerBaseFit`, description: `Polski poradnik B2B: ${profile.keyword}, metoda porównania, tabela decyzji, checklista, próbka, QC, opakowanie i pytania do dostawcy.`, h1: profile.h1, body: [...decisionBlocks(profile.keyword, focus, entity.id), ...guideDecisionBlocks(profile, entity.id)], faq: commonFaq(profile.keyword), author: polishEditorialAuthor, reviewedBy: polishTechnicalReviewer, schemaData: { brand: "PowerBaseFit", manufacturer: "PowerBaseFit", category: "Poradnik zakupowy B2B", specifications: [{ name: "Temat", value: profile.keyword }, { name: "Intencja", value: profile.intent }], breadcrumbs: [{ name: "Strona główna", path: "/pl" }, { name: "Poradniki", path: "/pl/blog" }, { name: profile.h1, path }], extra: { primaryKeyword: profile.keyword, searchIntent: profile.intent } }, images: imagesFor(entity, profile.h1), internalLinks: [{ targetContentId: "products-hub", label: "Przejdź do katalogu produktów" }, { targetContentId: "factory", label: "Sprawdź proces produkcji" }, { targetContentId: "oem-private-label", label: "Poznaj OEM i markę własną" }, { targetContentId: "contact", label: "Wyślij zapytanie B2B" }] });
}

function versionFor(entity: ContentEntity): LocalizedContentVersion {
  if (core[entity.id]) return coreVersion(entity, core[entity.id]);
  if (guides[entity.id]) return guideVersion(entity, guides[entity.id]);
  if (entity.type === "product") return productVersion(entity);
  throw new Error(`Polish localization missing for ${entity.id} (${entity.type})`);
}

export function withPolishLocalization(manifest: ContentManifest): ContentManifest {
  const entities = manifest.entities.map((entity) => {
    if (!isPublishedVersion(entity.versions.id) || excludedIds.has(entity.id)) return entity;
    if (entity.versions.pl) throw new Error(`Polish localization duplicates ${entity.id}`);
    return { ...entity, versions: { ...entity.versions, pl: versionFor(entity) } };
  });
  return { ...manifest, entities };
}
