import type { SpanishPage } from "./es-types";
import { checklist, definition, quick, rich, spanishEditorialAuthor, spanishTechnicalReviewer, table } from "./es-content-helpers";

const releaseDate = "2026-07-17T12:00:00.000Z";
const common = { author: spanishEditorialAuthor, reviewedBy: spanishTechnicalReviewer, updatedAt: releaseDate, publishedAt: releaseDate };

type ProductInput = {
  id: string;
  esPath: string;
  sku: string;
  title: string;
  description: string;
  h1: string;
  image: [string, string];
  productName: string;
  definition: string;
  range: string;
  material: string;
  positioning: string;
  applications: string;
  construction: string;
  process: string;
  qcFocus: string;
  handling: string;
  comparison: string;
  specifications: Array<{ name: string; value: string }>;
  links: Array<[string, string]>;
};

function productPage(input: ProductInput): SpanishPage {
  return {
    id: input.id,
    type: "product",
    esPath: input.esPath,
    title: input.title,
    description: input.description,
    h1: input.h1,
    sku: input.sku,
    image: input.image,
    material: input.material,
    category: "Equipamiento profesional de peso libre",
    specifications: input.specifications,
    blocks: [
      quick("respuesta-rapida", `${input.productName} está dirigido a gimnasios, importadores, distribuidores y marcas que necesitan una referencia verificable y suministro B2B. ${input.range}. La oferta final confirma pesos, cantidades, material, logotipo, embalaje, MOQ y control; una imagen no sustituye la ficha ni la muestra aprobada.`),
      definition("definicion", input.productName, input.definition),
      table("especificaciones", "Tabla de especificaciones para cotizar", ["Elemento", "Referencia disponible", "Confirmación del comprador"], [
        ["Producto", input.productName, "Código, versión y fotografía"],
        ["Gama", input.range, "Pesos y unidades por peso"],
        ["Material", input.material, "Construcción, superficie y acabado"],
        ["Identificación", "kg o lb y logo sujetos a viabilidad", "Método, posición, color y muestra"],
        ["Control", "Peso, medidas, superficie y montaje", "Tolerancia y plan de muestreo"],
        ["Embalaje", "Caja y palé según composición", "Protección, peso bruto y etiquetas"]
      ]),
      rich("posicionamiento", "Producto y valor para una compra profesional", input.positioning, `La selección debe relacionar producto, canal y coste durante la vida útil. ${input.comparison} Un distribuidor necesita rotación, presentación y reposición; un gimnasio necesita capacidad para hora punta, almacenamiento, limpieza y un procedimiento para retirar unidades dañadas.`),
      rich("aplicaciones", "Aplicaciones comerciales y planificación", input.applications, "Prepare una lista por referencia y no solo un peso total. Los pesos de mayor demanda pueden necesitar unidades repetidas; los extremos dependen del público y del espacio. Confirme rack, barra o estación antes de aprobar el pedido. Para España o América Latina, incluya sistema kg/lb, idioma de etiqueta y requisitos del destino sin asumir que son idénticos entre países."),
      rich("materiales", "Materiales y construcción", input.construction, `El nombre “${input.material}” no describe por sí solo formulación, espesor, dureza, unión, inserto o acabado. Dos ofertas con la misma denominación pueden ser distintas. Compare muestras, escriba criterios de aceptación y pida confirmación si la materia prima, herramienta o método cambia después de aprobar.`),
      rich("fabricacion", "Proceso de fabricación", input.process, "PowerBaseFit inicia el proyecto con modelo, gama, unidades, identidad y embalaje definidos. Los componentes pasan por preparación, formación, mecanizado o recubrimiento aplicable, unión, acabado, marcado, limpieza y control. El orden exacto corresponde al producto cotizado; no se presenta un único proceso como válido para todas las mancuernas o discos."),
      checklist("control", "Puntos de control del pedido", ["Código, peso y cantidad", "Medidas y compatibilidad", "Material, superficie y color", "Unión, inserto o empuñadura", "Logo, kg/lb y legibilidad", "Comparación con muestra", "Caja, protección, etiqueta y palé"]),
      rich("qc", "Inspección y aceptación", input.qcFocus, "Los límites se acuerdan antes de producir. El plan puede combinar registros internos, fotografías, pesaje por muestreo e inspección independiente según el riesgo. En marca propia también se revisan archivo, posición, color, texto y consistencia entre pesos. Una no conformidad debe evaluarse contra la especificación, no contra expresiones ambiguas como “calidad superior”."),
      rich("oem", "OEM, marca propia y personalización", "Se pueden evaluar logotipo, colores, marcado kg/lb, etiquetas y embalaje. La viabilidad depende de superficie, método, cantidad y construcción. Aplicar identidad sobre un producto existente no es lo mismo que cambiar forma, material o molde; el segundo caso puede exigir desarrollo, muestra y un MOQ distinto.", "Envíe archivo vectorial, país, pesos, unidades, color, embalaje y destino. PowerBaseFit confirma método, muestra y plazo después de revisar el conjunto. Verifique el logo en referencias pequeñas y grandes para que proporción y legibilidad sean coherentes."),
      rich("embalaje", "Embalaje, transporte y recepción", input.handling, "El peso libre concentra mucha masa: las cajas pueden romperse y las superficies marcarse por movimiento. Defina unidades, peso neto y bruto, separadores, palés y etiqueta. En destino, compare bultos, daños, cantidades, marcado y muestras de distintos pesos antes de vender o instalar."),
      checklist("comprador", "Checklist para el comprador B2B", ["Empresa, país y canal", "Modelo y aplicación", "Pesos y unidades", "Material y construcción", "Logo, color y kg/lb", "Muestra y criterios de control", "Cajas, palés y destino", "MOQ, plazo e Incoterm", "Reposición futura"])
    ],
    faq: [
      ["¿Es adecuado para un gimnasio profesional?", "Puede serlo cuando modelo, gama, almacenamiento, mantenimiento y especificación correspondan a la intensidad prevista."],
      ["¿Puedo aplicar mi marca?", "Sí, según superficie, método, cantidad, muestra y MOQ. Logo, marcado y embalaje se aprueban antes de producir."],
      ["¿Cuál es el pedido mínimo?", "No hay una cifra única. Depende de modelo, combinación por peso y personalización."],
      ["¿Cómo se verifica la calidad?", "Peso, medidas, superficie, construcción, marcado, cantidades y embalaje se comparan con criterios aprobados."],
      ["¿El precio incluye la importación?", "Depende del Incoterm. Transporte, seguro, despacho, impuestos, almacenaje y entrega se calculan para cada destino."],
      ["¿Cómo se gestiona una reposición?", "Conserve código, ficha, muestra, arte y datos de caja; confirme cambios antes de repetir el pedido."]
    ],
    links: input.links,
    ...common
  };
}

export const productLocalizationBatch1Spanish: SpanishPage[] = [
  productPage({
    id: "rubber-round-dumbbell", esPath: "/es/productos/mancuernas/mancuerna-redonda-de-goma", sku: "ROUND-RUBBER-DB", title: "Mancuerna redonda de goma 2,5–100 kg | PowerBaseFit", description: "Mancuerna redonda de goma de 2,5 a 100 kg para gimnasios y distribuidores, con kg/lb, logo, marca propia, control y embalaje OEM.", h1: "Mancuerna redonda de goma para uso comercial",
    image: ["/assets/products/dumbbells/classic-rubber-round/classic-rubber-round-dumbbell-main.jpg", "Mancuerna redonda de goma para gimnasio profesional"], productName: "Mancuerna redonda de goma", definition: "Es una mancuerna con cabezas circulares recubiertas de goma y empuñadura metálica. Su formato favorece una gama continua en un soporte compatible y permite pesos altos, pero requiere almacenamiento estable para evitar rodamiento y contacto inadecuado.", range: "Gama publicada de 2,5 a 100 kg, con incrementos de 2,5 kg", material: "Cabeza redonda recubierta de goma y empuñadura metálica",
    positioning: "La gama hasta 100 kg permite equipar zonas completas de fuerza para gimnasios comerciales y distribuidores. Puede dividirse en colecciones de entrada, musculación general y entrenamiento pesado. Su valor no es comprar todos los pesos por igual, sino construir una progresión coherente y repetible.", applications: "Se utiliza en salas de musculación, centros de rendimiento y catálogos profesionales. Hoteles o estudios suelen elegir una parte de la gama; instalaciones de fuerza pueden necesitar referencias pesadas. El soporte debe mantener cada cabeza estable y permitir retirar la pieza sin riesgo.", construction: "La cabeza redonda combina núcleo y goma según el modelo con empuñadura metálica. Confirme diámetro por peso, superficie, olor, unión, moleteado y marcado. El recubrimiento no autoriza golpes ni sustituye mantenimiento de suelo y soporte.", process: "El flujo incluye preparación del núcleo y la empuñadura, formación de la cabeza, aplicación del recubrimiento, unión, acabado, marcado y pesaje. La galería inglesa existente muestra producto, detalle, rack, embalaje y uso, y debe conservarse sin alterar el aspecto.", qcFocus: "Muestree pesos ligeros, medios y pesados. Revise masa, diámetro, alineación, unión, empuñadura, superficie y correspondencia entre pares. En la gama pesada, compruebe también caja y forma de manipulación.", handling: "Cada mancuerna necesita separación para que goma y metal no se rocen. Los pesos altos requieren cajas reforzadas y un plan de descarga. Identifique cada bulto para montar la gama sin mover repetidamente todas las piezas.", comparison: "Frente a la forma hexagonal, la redonda presenta una línea continua en rack, pero puede rodar fuera de un soporte; frente a PU o TPU, compare superficie, mantenimiento y coste.", specifications: [{ name: "Gama", value: "2,5–100 kg" }, { name: "Incremento", value: "2,5 kg" }, { name: "Sistemas", value: "kg/lb según proyecto" }], links: [["dumbbells-category", "Mancuernas profesionales"], ["pu-dumbbell", "Mancuerna de PU"], ["cast-iron-dumbbell", "Mancuerna de hierro fundido"], ["dumbbell-weighing-guide", "Control del peso"], ["contact", "Solicitar cotización"]]
  }),
  productPage({
    id: "pu-dumbbell", esPath: "/es/productos/mancuernas/mancuerna-pu", sku: "PU-DB-KG", title: "Mancuerna de PU 2,5–50 kg para gimnasios | PowerBaseFit", description: "Mancuerna de PU de 2,5 a 50 kg para gimnasios premium, distribuidores y marca propia, con logo, control y embalaje OEM.", h1: "Mancuerna de PU para gimnasios y distribuidores",
    image: ["/assets/products/dumbbells/catalog-v2/pu-dumbbell-kg.jpg", "Mancuerna de PU profesional para gimnasio"], productName: "Mancuerna de PU", definition: "Es una mancuerna cuya cabeza utiliza un recubrimiento exterior de poliuretano sobre la estructura definida. PU identifica una familia de material; formulación, dureza, superficie y construcción deben verificarse en la referencia y muestra reales.", range: "Gama publicada de 2,5 a 50 kg, con incrementos de 2,5 kg", material: "Recubrimiento de poliuretano y empuñadura metálica",
    positioning: "Está orientada a clubes, hoteles, gimnasios premium, showrooms y distribuidores que valoran acabado uniforme e identidad visual. Una línea de gama alta también necesita reposición y coherencia: la apariencia inicial no compensa pesos populares agotados o diferencias entre lotes.", applications: "Funciona en zonas de mancuernas con soporte adecuado y en programas de marca propia. España y varios mercados latinoamericanos pueden tener posiciones de precio distintas, por lo que el importador debe definir canal, presentación, unidades y servicio de reposición antes de seleccionar la gama.", construction: "El recubrimiento de PU se combina con núcleo y empuñadura según el modelo. Compare espesor, textura, brillo, olor, transición y resistencia al contacto con el rack. No atribuya prestaciones universales a la sigla PU.", process: "La fabricación prepara componentes, forma o aplica el PU, une la empuñadura, estabiliza el recubrimiento, termina la superficie, marca, pesa y embala. Logo y color se aprueban antes del lote y deben revisarse en más de un tamaño.", qcFocus: "Observe uniformidad, burbujas, marcas, diferencia de color, alineación, unión, empuñadura y legibilidad. Verifique peso con la tolerancia acordada y compare piezas de distintas partes de la gama.", handling: "La superficie premium requiere separadores limpios y protección contra presión y metal. Confirme límite por caja y palé. En recepción, retire embalaje con cuidado para no provocar las mismas marcas que se pretende detectar.", comparison: "PU puede competir con goma, TPU o CPU, pero la elección debe basarse en producto real, mantenimiento, presentación y coste total, no en una jerarquía automática de materiales.", specifications: [{ name: "Gama", value: "2,5–50 kg" }, { name: "Incremento", value: "2,5 kg" }, { name: "Recubrimiento", value: "PU" }], links: [["dumbbells-category", "Ver mancuernas"], ["rubber-round-dumbbell", "Mancuerna redonda de goma"], ["tpu-dumbbell", "Mancuerna TPU"], ["materials-guide", "Comparar goma, PU y TPU"], ["contact", "Cotizar mancuernas PU"]]
  }),
  productPage({
    id: "cast-iron-dumbbell", esPath: "/es/productos/mancuernas/mancuerna-hierro-fundido", sku: "CAST-IRON-DB", title: "Mancuerna de hierro fundido 2,5–100 kg | PowerBaseFit", description: "Mancuerna de hierro fundido de 2,5 a 100 kg para gimnasios y mayoristas, con marca propia, control, embalaje OEM y suministro B2B.", h1: "Mancuerna de hierro fundido para gimnasios y distribución",
    image: ["/assets/products/dumbbells/cast-iron/cast-iron-dumbbell-main.webp", "Mancuerna de hierro fundido profesional para gimnasio"], productName: "Mancuerna de hierro fundido", definition: "Es una mancuerna con cuerpo principal producido por fundición y empuñadura unida conforme al modelo. La gama publicada llega a pesos altos, por lo que soporte, manipulación, acabado y embalaje forman parte de la especificación comercial.", range: "Gama publicada de 2,5 a 100 kg, en incrementos de 2,5 kg", material: "Hierro fundido y empuñadura metálica",
    positioning: "Permite montar una zona completa desde pesos ligeros hasta trabajo de fuerza avanzada. Distribuidores pueden ofrecer tramos de gama y gimnasios pueden duplicar pesos de alta rotación. El hierro fundido aporta una construcción tradicional, pero no evita planificar ruido, suelo y mantenimiento.", applications: "Se utiliza en gimnasios comerciales, centros de rendimiento y programas mayoristas. Los pesos extremos solo tienen sentido si el público, el rack y la logística pueden manejarlos. Una instalación pequeña puede comprar una selección sin perder la continuidad del modelo.", construction: "El cuerpo fundido debe revisarse por geometría, bordes, poros visibles, acabado, empuñadura, unión y marcado. La robustez percibida no reemplaza límites para defectos y tolerancia de peso.", process: "Incluye preparación del molde, fundición, limpieza, eliminación de rebabas, acabado, preparación y unión del mango, marcado, pesaje y formación de pares. Las imágenes reales disponibles cubren producto, detalle, soporte, embalaje y aplicación.", qcFocus: "Distribuya la muestra entre pesos ligeros, medios y pesados. Verifique masa, dimensiones, estabilidad, mango, unión, superficie y pares. Para pesos altos, revise caja, palé y método de descarga.", handling: "Piezas de hierro pueden rozarse o dañar cajas. Use separación y refuerzo y defina un peso bruto manipulable. La entrega de una referencia de 100 kg requiere medios y responsabilidad claros.", comparison: "Frente a modelos recubiertos, el hierro fundido prioriza construcción y gama amplia; frente a mancuernas ajustables, ocupa más espacio, pero evita mecanismos y permite uso simultáneo.", specifications: [{ name: "Gama", value: "2,5–100 kg" }, { name: "Incremento", value: "2,5 kg" }, { name: "Construcción", value: "Hierro fundido" }], links: [["dumbbells-category", "Línea de mancuernas"], ["cpu-dumbbell", "Mancuerna CPU"], ["tpu-dumbbell", "Mancuerna TPU"], ["dumbbell-weighing-guide", "Cómo comprobar el peso"], ["contact", "Pedir cotización"]]
  }),
  productPage({
    id: "cpu-dumbbell", esPath: "/es/productos/mancuernas/mancuerna-cpu", sku: "CPU-DB-KG", title: "Mancuerna CPU 2,5–50 kg para gimnasio | PowerBaseFit", description: "Mancuerna CPU de 2,5 a 50 kg para gimnasios, distribuidores y marca propia, con logo, control y embalaje de exportación.", h1: "Mancuerna CPU profesional para compradores B2B",
    image: ["/assets/products/dumbbells/catalog-v2/cpu-dumbbell-kg.webp", "Mancuerna CPU profesional de 2,5 a 50 kg"], productName: "Mancuerna CPU", definition: "Es una mancuerna con cabeza protegida por material CPU según la construcción del modelo y empuñadura metálica. La sigla identifica la superficie comercial, pero composición, dureza, unión y acabado se confirman en ficha y muestra.", range: "Gama publicada de 2,5 a 50 kg, en incrementos de 2,5 kg", material: "Superficie CPU y empuñadura metálica",
    positioning: "La línea CPU ofrece una alternativa para gimnasios y distribuidores que quieren diferenciar superficie, color y marca sin limitarse a una construcción metálica. Puede organizarse como colección kg para uso comercial y programa privado.", applications: "Es apta para salas de musculación, cadenas, hoteles y catálogos de importación. Revise contacto con soporte, limpieza, olor inicial y disponibilidad de reposición. En cadenas, la referencia debe mantener aspecto y agarre entre compras.", construction: "Confirme núcleo, capa CPU, transición, textura, diámetro y método de unión. Dos formulaciones CPU pueden comportarse de manera distinta; no compare únicamente nombres o fotografías.", process: "Los componentes se preparan, la cabeza se forma con el material previsto, el mango se mecaniza y el conjunto pasa por unión, acabado, marcado y pesaje. Color y logo se revisan antes de liberar la producción.", qcFocus: "Controle superficie, burbujas, rebabas, color, alineación, textura del mango, peso y legibilidad. Pruebe la muestra en el soporte que usará el cliente y documente cualquier marca o inestabilidad.", handling: "La capa necesita protección frente a metal y fricción. Las cajas deben separar unidades y respetar peso bruto. En contenedor, evite que racks u otros equipos presionen las cabezas.", comparison: "Compare CPU con goma, PU o TPU por formulación, mantenimiento, acabado, precio, canal y reposición; ninguna sigla garantiza por sí sola un resultado superior.", specifications: [{ name: "Gama", value: "2,5–50 kg" }, { name: "Incremento", value: "2,5 kg" }, { name: "Superficie", value: "CPU" }], links: [["dumbbells-category", "Mancuernas profesionales"], ["cast-iron-dumbbell", "Hierro fundido"], ["tpu-dumbbell", "TPU"], ["dumbbell-weighing-guide", "Control del peso"], ["contact", "Cotizar CPU"]]
  }),
  productPage({
    id: "tpu-dumbbell", esPath: "/es/productos/mancuernas/mancuerna-tpu", sku: "TPU-DB-KG", title: "Mancuerna TPU 2,5–70 kg para gimnasios | PowerBaseFit", description: "Mancuerna TPU de 2,5 a 70 kg para gimnasios, cadenas y distribuidores, con logo, marca propia, control y embalaje OEM.", h1: "Mancuerna TPU para gimnasios y líneas premium",
    image: ["/assets/products/dumbbells/catalog-v2/tpu-dumbbell-kg.webp", "Mancuerna TPU profesional para gimnasio"], productName: "Mancuerna TPU", definition: "Es una mancuerna con recubrimiento exterior de poliuretano termoplástico conforme al modelo. TPU puede apoyar una línea comercial de superficie uniforme y personalización, pero sus propiedades dependen de formulación y construcción verificadas.", range: "Gama publicada de 2,5 a 70 kg, con incrementos de 2,5 kg", material: "Recubrimiento TPU y empuñadura metálica",
    positioning: "La amplitud hasta 70 kg sirve a gimnasios premium que no quieren detener la colección en pesos medios. Para un distribuidor, permite construir una línea con mayor valor percibido, colores y marca, siempre que la reposición mantenga la misma especificación.", applications: "Puede usarse en clubes, hoteles, cadenas, estudios y showrooms. Evalúe demanda de pesos altos, longitud del soporte y espacio de circulación. La identidad debe conservar proporción y legibilidad entre cabezas pequeñas y grandes.", construction: "La construcción combina núcleo, TPU y empuñadura. Confirme espesor, dureza, textura, transición, unión y logo. El nombre no permite asumir olor, brillo, resistencia a rayas o limpieza.", process: "Se preparan núcleo y mango, se forma o aplica el TPU, se realiza unión, estabilización, acabado, marcado y pesaje. Arte y color se aprueban en muestra y un cambio de material requiere nueva confirmación.", qcFocus: "Revise uniformidad, rayas, burbujas, diferencias de color, logo, alineación y peso. Compruebe piezas de varios tamaños y registre mantenimiento recomendado.", handling: "Proteja TPU de quinas, metal y fricción. Use separadores y cajas ajustadas. Durante recepción, no arrastre piezas y examine superficie antes de colocarlas en el rack.", comparison: "TPU debe compararse con PU, CPU y goma por muestra, mantenimiento, presentación, gama y coste puesto en almacén.", specifications: [{ name: "Gama", value: "2,5–70 kg" }, { name: "Incremento", value: "2,5 kg" }, { name: "Recubrimiento", value: "TPU" }], links: [["dumbbells-category", "Ver mancuernas"], ["pu-dumbbell", "Mancuerna PU"], ["cpu-dumbbell", "Mancuerna CPU"], ["materials-guide", "Goma, PU y TPU"], ["contact", "Solicitar propuesta"]]
  }),
  productPage({
    id: "cpu-bumper-plate", esPath: "/es/productos/discos/disco-bumper-cpu", sku: "CPU-BUMPER", title: "Disco bumper CPU para gimnasio y marca propia | PowerBaseFit", description: "Disco bumper CPU para barras olímpicas, gimnasios y distribuidores, con colores, logo, kg/lb, control y embalaje OEM.", h1: "Disco bumper CPU para gimnasios y compradores B2B",
    image: ["/assets/products/weight-plates/catalog/cpu-bumper-plate.webp", "Disco bumper CPU profesional para gimnasio"], productName: "Disco bumper CPU", definition: "Es un disco con cuerpo de material CPU, diámetro exterior uniforme dentro de su línea e inserto central para una barra compatible. Está destinado a aplicaciones definidas, pero necesita plataforma, técnica, supervisión y mantenimiento.", range: "Programas en kg o lb disponibles según el conjunto cotizado", material: "Material CPU con inserto central de acero",
    positioning: "Es una opción para zonas funcionales y de halterofilia que buscan identificación por color y un programa de marca propia. El distribuidor puede organizar juegos; el gimnasio debe calcular unidades por plataforma y demanda.", applications: "Puede atender boxes, centros de fuerza y salas comerciales. Confirme barra, centro, espesor y uso permitido. La palabra bumper no autoriza soltar una barra sobre cualquier superficie.", construction: "El cuerpo CPU incorpora un inserto metálico. Confirme dureza aplicable, espesor por peso, concentricidad, planitud, marcado y comportamiento previsto. Examine pesos ligeros y pesados porque no tienen la misma geometría.", process: "Incluye preparación del material, moldeo, posición del inserto, estabilización, acabado, marcado, pesaje e inspección. Colores y logo siguen la muestra aprobada.", qcFocus: "Mida masa, diámetro, espesor, centro, planitud, superficie y marcado. Si se acuerda prueba funcional, documente barra, plataforma, altura, ciclos y aceptación; “probado” sin condiciones no es un dato suficiente.", handling: "Separe bordes e insertos, limite peso por caja y estabilice palés. Al recibir, compruebe ajuste en barra y daños antes de autorizar el uso.", comparison: "Frente a un disco convencional, cambia construcción y aplicación; frente a otros bumper, compare material, espesor, inserto, dureza y coste.", specifications: [{ name: "Sistema", value: "kg/lb según proyecto" }, { name: "Material", value: "CPU" }, { name: "Centro", value: "Inserto de acero" }], links: [["weight-plates-category", "Discos profesionales"], ["cast-iron-weight-plate", "Disco de hierro fundido"], ["cpu-grip-plate", "Disco CPU con agarres"], ["bumper-manufacturing-guide", "Cómo se fabrican"], ["contact", "Cotizar bumper CPU"]]
  }),
  productPage({
    id: "cast-iron-weight-plate", esPath: "/es/productos/discos/disco-hierro-fundido", sku: "CAST-IRON-PLATE", title: "Disco de hierro fundido al por mayor | PowerBaseFit", description: "Disco de hierro fundido para gimnasios y distribuidores, con kg/lb, logo, acabado, control y embalaje OEM para compras B2B.", h1: "Disco de hierro fundido para gimnasios y distribución",
    image: ["/assets/products/weight-plates/cast-iron/cast-iron-weight-plate-main.avif", "Disco de hierro fundido con agarres para gimnasio"], productName: "Disco de hierro fundido", definition: "Es un disco con cuerpo fundido, marcado elevado y aberturas de agarre según el modelo. Se utiliza en barras y estaciones compatibles para musculación y no equivale a un bumper diseñado para otra aplicación.", range: "Juegos en kg o lb definidos en la cotización", material: "Hierro fundido con superficie negra texturizada",
    positioning: "Ofrece construcción tradicional, manipulación mediante agarres y una opción de coste práctico para gimnasios, distribuidores y proyectos de fuerza. El valor depende de compatibilidad, acabado, marcado y suministro continuo.", applications: "Puede instalarse en barras, racks y máquinas plate-loaded compatibles. Separe el uso sin caída del entrenamiento que exige bumpers y plataforma. El centro y el diámetro deben verificarse con el equipo real.", construction: "El cuerpo fundido pasa por limpieza y tratamiento superficial. Confirme bordes, agarres, centro, planitud y números. La textura no debe ocultar rebabas o dificultar el manejo.", process: "Incluye molde, fundición, limpieza, acabado de bordes y centro, tratamiento superficial, inspección del marcado, pesaje y embalaje. Un logo moldeado necesita herramienta y arte aprobados.", qcFocus: "Compruebe masa, centro, espesor, planitud, agarres, bordes y superficie. Ensaye el encaje en barra o máquina. Evite mezclar kg y lb en producto, caja o lista de bultos.", handling: "El hierro puede sufrir golpes o rozamiento. Use separación, caja resistente y palés equilibrados. En recepción, revise centro, bordes, humedad y cantidad.", comparison: "Frente a discos recubiertos, prioriza una construcción directa; ruido, suelo, corrosión, estética y coste deben entrar en la comparación.", specifications: [{ name: "Material", value: "Hierro fundido" }, { name: "Marcado", value: "kg/lb según juego" }, { name: "Formato", value: "Agarres y números elevados" }], links: [["weight-plates-category", "Ver discos"], ["cpu-bumper-plate", "Bumper CPU"], ["cpu-grip-plate", "CPU con agarres"], ["bumper-manufacturing-guide", "Fabricación de bumper"], ["contact", "Pedir cotización"]]
  }),
  productPage({
    id: "cpu-grip-plate", esPath: "/es/productos/discos/disco-cpu-con-agarres", sku: "CPU-GRIP-PLATE", title: "Disco CPU con agarres para gimnasio | PowerBaseFit", description: "Disco CPU con aberturas de agarre para gimnasios y cadenas, con kg/lb, logo, colores, control y embalaje de marca propia.", h1: "Disco CPU con agarres para uso comercial",
    image: ["/assets/products/weight-plates/catalog/cpu-grip-plate.webp", "Disco CPU con agarres para gimnasio profesional"], productName: "Disco CPU con agarres", definition: "Es un disco recubierto con material CPU y formado con aberturas para facilitar retirada, transporte y carga. El centro reforzado conecta con una barra o estación compatible; forma y número de agarres dependen del modelo.", range: "Programas en kg o lb definidos para la línea cotizada", material: "Recubrimiento CPU, agarres moldeados e inserto central reforzado",
    positioning: "Su valor está en la manipulación frecuente de salas comerciales. Los agarres ayudan en racks y máquinas, mientras la superficie CPU permite una presentación diferenciada y opciones de marca.", applications: "Está dirigido a gimnasios, cadenas, estaciones plate-loaded y catálogos de fuerza. Confirme que los agarres funcionan en cada peso y que diámetro y espesor son compatibles. Evalúe ergonomía con manos y movimientos reales.", construction: "El cuerpo combina CPU, aberturas y centro reforzado. Revise bordes, espesor alrededor de cada hueco, inserto, dureza y equilibrio. Logo y peso deben conservar legibilidad.", process: "Se posiciona el centro, se forma el cuerpo y los agarres, se termina la superficie, se marca, pesa e inspecciona. Color y arte se controlan antes del lote.", qcFocus: "Además de masa y centro, compruebe cada agarre por simetría, bordes y comodidad. Pruebe la carga en barra o máquina y estabilidad en almacenamiento.", handling: "Los agarres ayudan con unidades, pero no con palés completos. Limite peso por caja, separe superficies y planifique descarga. Inspeccione aberturas después del transporte.", comparison: "Frente a un disco sin agarres, facilita ciertas rutinas; frente a bumper, responde a otra construcción y no comparte automáticamente el uso con caída.", specifications: [{ name: "Material", value: "CPU" }, { name: "Manipulación", value: "Aberturas de agarre" }, { name: "Centro", value: "Inserto reforzado" }], links: [["weight-plates-category", "Línea de discos"], ["cpu-bumper-plate", "Bumper CPU"], ["cast-iron-weight-plate", "Hierro fundido"], ["bumper-manufacturing-guide", "Proceso bumper"], ["contact", "Cotizar discos CPU"]]
  }),
  {
    id: "bumper-manufacturing-guide", type: "blog", esPath: "/es/blog/como-se-fabrican-discos-bumper", title: "Cómo se fabrican los discos bumper: materiales y control | PowerBaseFit", description: "Conozca material, inserto, moldeado, acabado, peso, pruebas, OEM y embalaje en la fabricación de discos bumper para compras B2B.", h1: "Cómo se fabrican los discos bumper",
    image: ["/assets/factory-process/plate-raw-material.webp", "Materia prima para fabricar discos bumper"],
    blocks: [
      quick("respuesta-rapida", "Un disco bumper se fabrica con un material definido para el cuerpo, un inserto central metálico y una especificación de peso, diámetro, espesor, dureza o comportamiento aplicable, color y marcado. El flujo incluye preparación de material, posición del inserto, moldeo, estabilización, acabado, pesaje, inspección y embalaje. Fórmula y pruebas cambian por modelo; el comprador debe evaluar la referencia cotizada y no una descripción genérica."),
      definition("definicion", "Disco bumper", "Es un disco con cuerpo predominantemente de goma, caucho, CPU u otro material declarado, diámetro exterior uniforme dentro de la línea e inserto para una barra compatible. Está pensado para aplicaciones de levantamiento definidas, pero depende de plataforma, técnica, mantenimiento y límites de uso."),
      table("componentes", "Componentes que debe documentar el proveedor", ["Elemento", "Función", "Dato de compra"], [["Cuerpo", "Forma y respuesta al contacto", "Material, dureza, olor y color"], ["Inserto", "Ajuste y transmisión de carga", "Material, diámetro, fijación y tolerancia"], ["Geometría", "Compatibilidad y capacidad de manga", "Diámetro y espesor por peso"], ["Marcado", "Identificación", "kg/lb, logo, contraste y método"], ["Embalaje", "Protección logística", "Unidades, caja, palé y peso bruto"]]),
      rich("especificacion", "1. Definir el producto antes de moldear", "La fábrica necesita modelo, pesos, cantidades, kg/lb, inserto, color, logo, tolerancia, embalaje y uso. “Bumper olímpico” no define material, centro, espesor o dureza. Para comparar proveedores, envíe la misma tabla y exija que cada respuesta indique qué está incluido.", "Marca propia añade archivos, colores y método. Cambiar un gráfico es distinto de cambiar molde o construcción. Conserve ficha, arte y muestra para producción y reposición."),
      rich("material", "2. Preparación de la materia prima", "La materia prima se selecciona y mezcla según el modelo. Goma virgen, reciclada, CPU y otras composiciones no son equivalentes. Fórmula, almacenamiento, temperatura y tiempo pueden influir en superficie, olor, dureza y estabilidad.", "PowerBaseFit no presenta una receta universal. El comprador debe pedir material declarado, referencia de dureza cuando corresponda, uso y límites. Un cambio posterior a la muestra requiere revisión."),
      rich("inserto", "3. Inserto y molde", "El inserto se dimensiona para la barra y se coloca concéntrico. Su superficie, fijación y tolerancia influyen en ajuste y vida útil. El molde define diámetro, espesor y elementos de identificación.", "Mida el centro y revise holgura, alineación y acabado. Un disco atractivo puede fallar en compatibilidad si solo se inspecciona visualmente."),
      rich("moldado", "4. Moldeado, estabilización y acabado", "Material e inserto entran en el proceso correspondiente con presión, temperatura y tiempo definidos. Después, la pieza se estabiliza o cura, se retira, recorta, limpia y termina.", "Se observan llenado, burbujas, rebabas, manchas, deformación, planitud y zona del inserto. Colores y logos se comparan entre pesos, pero la pieza todavía debe medirse y pesarse."),
      table("flujo", "Flujo de fabricación y control", ["Etapa", "Evidencia", "Riesgo"], [["Especificación", "Ficha, arte, muestra", "Modelo incorrecto"], ["Material", "Lote y parámetros", "Variación"], ["Inserto", "Medida y posición", "Desalineación"], ["Moldeo", "Parámetros", "Formación incompleta"], ["Acabado", "Criterios visuales", "Rebaba o deformación"], ["Pesaje", "Registro y tolerancia", "Masa fuera de límite"], ["Embalaje", "Plan de cajas", "Daño en transporte"]]),
      rich("peso", "5. Peso, espesor y marcado", "Cada referencia tiene peso nominal y tolerancia acordada. El muestreo debe incluir unidades ligeras y pesadas. También se comprueban diámetro, centro, espesor, planitud y texto. El espesor define cuánto cabe en la manga.", "kg/lb, logo y color deben coincidir con caja y lista de bultos. Registrar lote, equipo y resultado facilita investigar una diferencia."),
      rich("pruebas", "6. Verificación funcional y control", "Puede haber inspección visual, masa, medidas, inserto y una prueba funcional definida. Si se habla de impacto, documente barra, plataforma, altura, ciclos y criterio. No acepte una afirmación de prueba sin condiciones.", "Ningún bumper convierte cualquier suelo en plataforma. El operador del gimnasio debe establecer reglas, revisar insertos y retirar piezas con rotura o deformación relevante."),
      checklist("auditoria", "Checklist de fábrica y muestra", ["Modelo y material", "Pesos y espesores", "Centro y barra", "Dureza o referencia", "Tolerancia y muestra", "Logo y colores", "Prueba documentada", "Defectos y acciones", "Cajas y trazabilidad"]),
      rich("oem", "7. OEM, logística y reposición", "Logo, colores, kg/lb y caja se personalizan según proceso y cantidad. Apruebe varios pesos cuando cambie espacio o espesor. El MOQ se confirma con la combinación cerrada.", "Bordes e insertos necesitan separación y el palé debe impedir desplazamiento. Para una reposición, conserve código, material, arte y muestra y confirme cambios."),
      rich("recepcion", "8. Recepción y seguimiento en el gimnasio", "Prepare la recepción antes de la llegada: lista de bultos, zona de descarga, medios para mover palés y una muestra distribuida entre cajas. Revise humedad, golpes, desplazamiento, bordes e insertos. Seleccione discos ligeros, medios y pesados de distintos palés y repita masa, centro, espesor, planitud y marcado. Inspeccionar solo el disco más pesado puede ocultar diferencias en referencias finas.", "Una vez instalados, registre ajuste en barra, estado del inserto, ruido, marcas y comportamiento sobre la plataforma definida. Vincule cualquier incidencia con lote, peso y condiciones de uso. Un vídeo sin información de barra, altura o suelo no permite atribuir una causa.", "Para distribuidores, la rotación por peso orienta la reposición y evita repetir juegos que dejan inventario inmóvil. Para gimnasios, el número de barras y plataformas, junto con la demanda en hora punta, ayuda a decidir unidades adicionales. Conserve ficha, muestra, fotografías, informe, arte y datos de caja para comprobar que el siguiente lote sigue siendo equivalente."),
      rich("proveedor", "9. Cómo comparar dos ofertas", "Use una tabla común con material, dureza o referencia, pesos, tolerancia, espesor, inserto, colores, logo, ensayo, cajas e Incoterm. Un precio por kilogramo no permite comparar cuando una oferta omite molde, muestra, control o palés. Pida que cada proveedor marque qué datos están confirmados y cuáles dependen de desarrollo.", "Compare también comunicación técnica y tratamiento de no conformidades. El proveedor debe poder relacionar fotografías y registros con el modelo cotizado. No se deben aceptar certificaciones, clientes o resultados que no puedan demostrarse. El objetivo es escoger una especificación reproducible, no la descripción comercial más extensa."),
      rich("decision", "10. Convertir la información en una decisión de compra", "Resuma cada alternativa en una hoja con aplicación, material, peso, tolerancia, espesor, centro, prueba, personalización, embalaje, plazo y coste puesto en destino. Señale datos todavía pendientes y no conceda la misma confianza a un valor confirmado que a una estimación. Esta distinción ayuda a decidir si procede pedir muestra, ampliar el ensayo o cambiar el mix antes de emitir la orden.", "La mejor opción no es siempre el disco con menor precio o mayor rebote anunciado. Es la combinación que encaja con barra, plataforma, usuarios, logística, mantenimiento y canal comercial, y que puede reproducirse en una reposición. Documentar esa decisión también facilita explicar el producto al equipo de ventas o a los responsables del gimnasio."),
      rich("experiencia", "Información de primera parte de PowerBaseFit", "En la fábrica de Dezhou, la tabla por peso orienta material, unidades, color, marca, control, cajas y carga. Solicitudes que solo dicen “disco olímpico bumper” se aclaran antes de cotizar porque pueden representar productos diferentes.", "Las imágenes reales de materia prima, tratamiento, embalaje y contenedor ayudan a entender el flujo, pero cada evidencia debe vincularse al modelo. No se inventan certificados, composiciones ni resultados."),
      checklist("compra", "Checklist final de compra", ["Aplicación y plataforma", "Material y dureza", "Centro, diámetro y espesor", "Peso y tolerancia", "Logo, color y kg/lb", "Muestra y prueba", "Control y no conformidad", "Embalaje e Incoterm", "Reposición"])
    ],
    faq: [["¿De qué se fabrica un disco bumper?", "Puede usar goma, caucho, CPU u otra composición declarada con inserto metálico."], ["¿Todos pueden dejarse caer?", "No. Depende del modelo, plataforma, técnica y límites establecidos."], ["¿Cómo se controla el peso?", "Con balanza, tolerancia y muestreo definidos."], ["¿Por qué importa el espesor?", "Determina la carga posible en la manga y cambia entre pesos."], ["¿Se puede poner marca propia?", "Sí, según molde, método, cantidad y muestra."], ["¿Qué documentos pedir?", "Ficha, medidas, arte, muestra, control, embalaje y registros del pedido."]],
    links: [["weight-plates-category", "Discos profesionales"], ["cpu-bumper-plate", "Bumper CPU"], ["cast-iron-weight-plate", "Hierro fundido"], ["cpu-grip-plate", "CPU con agarres"], ["factory", "Conocer la fábrica"], ["contact", "Solicitar cotización"]], ...common
  },
  {
    id: "dumbbell-weighing-guide", type: "blog", esPath: "/es/blog/como-verificar-peso-mancuernas-fabrica", title: "Cómo verificar el peso de las mancuernas en fábrica | PowerBaseFit", description: "Guía B2B sobre peso nominal, tolerancia, balanzas, muestreo, control, registros y aceptación de mancuernas antes del envío.", h1: "Cómo se verifica el peso de las mancuernas en fábrica",
    image: ["/assets/factory-process/dumbbell-material.webp", "Componentes de mancuernas antes del montaje y pesaje"],
    blocks: [
      quick("respuesta-rapida", "Las mancuernas se verifican con balanzas adecuadas a la gama y con peso nominal, tolerancia y muestreo acordados antes de producir. El procedimiento identifica modelo, kg/lb, instrumento, frecuencia, redondeo, aceptación y acción ante desviaciones. Una lectura aislada no representa todo el lote; además del peso se revisan pares, marcado, construcción y embalaje."),
      definition("definicion", "Peso nominal de una mancuerna", "Es el valor declarado, por ejemplo 10 kg. El peso medido es la lectura obtenida en condiciones definidas. La diferencia se compara con la tolerancia contratada; no existe un porcentaje universal aplicable a cualquier modelo o mercado."),
      table("conceptos", "Conceptos del control de peso", ["Concepto", "Significado", "Qué acordar"], [["Nominal", "Valor marcado", "kg/lb y referencia"], ["Medido", "Lectura de balanza", "Método y redondeo"], ["Tolerancia", "Desviación permitida", "Límite superior e inferior"], ["Muestra", "Unidades verificadas", "Tamaño y distribución"], ["Instrumento", "Balanza identificada", "Capacidad y resolución"], ["No conformidad", "Resultado fuera del acuerdo", "Segregación y decisión"]]),
      rich("regla", "1. Acordar la regla antes de producir", "La orden debe indicar modelo, pesos, kg/lb, tolerancia, redondeo y si se acepta por unidad, par, media o muestra. Sin esa información, comprador y fábrica pueden interpretar una misma lectura de forma diferente.", "Una gama de 2,5 a 100 kg puede necesitar balanzas o resoluciones distintas. El equipo para una mancuerna ligera debe ser sensible; el de una pieza pesada debe soportar la carga y permitir manipulación segura."),
      rich("balanza", "2. Balanza, entorno y trazabilidad", "Compruebe ID del instrumento, capacidad, resolución, nivel, estado y verificación aplicable. La unidad mostrada debe coincidir con el producto. Vibración, apoyo parcial o contacto con otra superficie alteran la lectura.", "El operador registra modelo, lote y nominal. La zona debe permitir colocar la mancuerna sin riesgo. Las piezas pesadas requieren medios adecuados para no dañar a personas, producto o equipo."),
      rich("muestra", "3. Seleccionar una muestra representativa", "No mida solo las primeras cajas. Distribuya unidades entre momentos de producción, pesos, moldes, colores y palés. Incluya ligeras, medias y pesadas y aumente cobertura después de un cambio de material o herramienta.", "El tamaño depende del riesgo y del acuerdo. Un comprador puede pedir inspección más amplia o externa, pero el inspector debe recibir la misma ficha y tolerancia."),
      table("registro", "Campos de un registro de pesaje", ["Campo", "Información", "Objetivo"], [["Lote", "Código y fecha", "Trazabilidad"], ["Producto", "Modelo y nominal", "Evitar mezcla"], ["Balanza", "ID, capacidad, resolución", "Repetir método"], ["Lectura", "Valor y unidad", "Comparar límite"], ["Resultado", "Aceptado o segregado", "Acción"], ["Responsable", "Operador y revisión", "Control"]]),
      rich("variacion", "4. Por qué puede variar una mancuerna", "Hierro, acero, goma, PU, TPU, CPU, cromo y empuñaduras contribuyen al peso. Las variaciones pueden venir de fundición, mecanizado, recubrimiento, componente o unión. El control debe buscar la etapa pertinente al modelo.", "Una corrección no debe comprometer estructura, equilibrio o superficie. Evite ajustes improvisados que generen ruido, cavidades o diferencias visibles."),
      rich("pares", "5. Correspondencia entre pares", "Dos unidades con igual marcado deben formar un par coherente. Además de masa, compare tamaño, alineación, empuñadura, centro de gravedad, superficie y arte. Una pieza dentro de tolerancia todavía puede tener un defecto de unión.", "Compruebe que dimensiones funcionan en el soporte y que logo y color usan la misma versión. Registre diferencias que afecten uso o presentación."),
      checklist("inspeccion", "Checklist de inspección", ["Modelo y lote", "Nominal y unidad", "Balanza identificada", "Lectura y tolerancia", "Par", "Medidas y alineación", "Empuñadura y unión", "Superficie y logo", "Caja y etiqueta"]),
      rich("desvio", "6. Gestionar un resultado fuera del límite", "Identifique y separe la unidad. Evalúe alcance, causa y necesidad de ampliar la muestra. Retrabajo, sustitución o aceptación excepcional requieren decisión documentada.", "No cambie el marcado para acomodar una lectura sin revisar la referencia. Si se repite el problema, investigue material, molde, componente o ajuste y registre la liberación."),
      rich("embalaje", "7. Control en embalaje y recepción", "La masa de la unidad controla producto; peso neto y bruto de caja apoyan logística. Diferencias de caja pueden indicar una unidad faltante, pero no sustituyen el pesaje individual.", "El importador puede repetir una muestra al recibir. Compare lote, instrumento, unidad y redondeo antes de declarar discrepancia. Una fotografía del visor sin contexto no permite investigar."),
      rich("proveedores", "8. Comparar proveedores con el mismo método", "Envíe la misma tabla de modelos, pesos, cantidades, tolerancia, muestra, control y embalaje. Una oferta expresada únicamente como precio por kilogramo no explica cómo se forman pares, qué balanza se usa ni qué ocurre con una unidad fuera del límite. Pida un ejemplo de registro sin información confidencial y compruebe que incluya lote, instrumento, lectura, resultado y responsable.", "El coste de compra también incluye muestra, inspección, segregación, sustitución, embalaje y reposición. Una propuesta más barata puede resultar costosa si mezcla kg y lb, entrega pares visualmente distintos o no puede repetir la construcción. Evalúe la capacidad de mantener método y documentación en pedidos posteriores."),
      rich("recepcion", "9. Repetir la verificación en destino", "Antes de abrir los palés, fotografíe etiquetas y daños y compare lista de bultos. Seleccione cajas de diferentes zonas y pesos ligeros, medios y altos. Deje que producto e instrumento estén en condiciones estables y use la unidad y el redondeo acordados. Registre cada lectura con lote y referencia.", "Si aparece una diferencia, no extrapole inmediatamente a todo el lote. Confirme balanza, superficie, tara, marcado y posible mezcla; luego amplíe la muestra según el procedimiento. Comparta datos reproducibles con la fábrica. Un proceso ordenado permite distinguir una desviación real de una diferencia de método y facilita acordar sustitución o reposición cuando corresponda."),
      rich("decision", "10. Usar los datos para planificar la siguiente compra", "Agrupe resultados por modelo, peso y lote. Observe si los desvíos se concentran en una referencia, etapa o momento de producción y relacione también devoluciones, daños de caja y demanda por peso. Un informe de recepción útil no termina con “aprobado”: conserva las tendencias que pueden mejorar el siguiente pedido.", "Para una cadena de gimnasios, compare necesidades entre sedes y duplique pesos con uso simultáneo. Para un distribuidor, combine rotación, consultas y reposición. Mantenga muestra, ficha, arte y registro de balanza como control de versión. Antes de repetir, confirme cualquier cambio de núcleo, recubrimiento, mango, marcado o caja; el mismo nombre comercial no garantiza que todos esos elementos permanezcan iguales."),
      rich("experiencia", "Información de primera parte de PowerBaseFit", "En Dezhou, una tabla por peso y unidades organiza producción, pares, pesaje, cajas y carga. Evita confundir kg y lb y distribuye el muestreo. La gama de hierro fundido publicada llega de 2,5 a 100 kg; otros modelos tienen rangos propios.", "PowerBaseFit recomienda fijar tolerancia e inspección antes del pedido. Identificar instrumento, muestra y registro ofrece más valor que afirmar simplemente que una mancuerna ha sido comprobada."),
      checklist("comprador", "Checklist del comprador", ["Gama y unidades", "kg/lb", "Tolerancia", "Método y redondeo", "Balanza", "Muestreo", "Pares", "Acción ante desvío", "Informe y recepción", "Reposición por lote"])
    ],
    faq: [["¿Toda mancuerna pesa exactamente lo marcado?", "Puede existir variación; se controla mediante tolerancia y método acordados."], ["¿Qué tolerancia utilizar?", "Depende de modelo, mercado y contrato; no debe inventarse una cifra universal."], ["¿Hay que pesar todas?", "Depende del riesgo: puede usarse control total o muestreo definido."], ["¿Cómo elegir balanza?", "Capacidad y resolución deben cubrir la gama y el instrumento debe estar identificado."], ["¿Peso correcto significa calidad completa?", "No. También se revisan unión, alineación, superficie, mango, marcado y caja."], ["¿El comprador puede repetir la prueba?", "Sí, usando método y condiciones comparables y registrando lote e instrumento."]],
    links: [["dumbbells-category", "Mancuernas profesionales"], ["cast-iron-dumbbell", "Hierro fundido"], ["cpu-dumbbell", "CPU"], ["tpu-dumbbell", "TPU"], ["factory", "Control de fábrica"], ["contact", "Enviar especificación"]], ...common
  }
];
