import type { PilotPage } from "./pt-br-types";
import { checklist, definition, quick, rich, table } from "./pt-br-content-helpers";
import { ptBrEditorialAuthor, ptBrTechnicalReviewer } from "./pt-br-existing-growth";

const releaseDate = "2026-07-17T12:00:00.000Z";

type ProductInput = {
  id: string;
  enPath: string;
  ptPath: string;
  enTitle: string;
  sku: string;
  title: string;
  description: string;
  h1: string;
  image: [string, string];
  productName: string;
  definition: string;
  range: string;
  material: string;
  positioning: string;
  applications: string;
  construction: string;
  process: string;
  qcFocus: string;
  handling: string;
  comparison: string;
  specifications: Array<{ name: string; value: string }>;
  links: Array<[string, string]>;
};

function productPage(input: ProductInput): PilotPage {
  return {
    id: input.id,
    type: "product",
    enPath: input.enPath,
    ptPath: input.ptPath,
    enTitle: input.enTitle,
    title: input.title,
    description: input.description,
    h1: input.h1,
    sku: input.sku,
    image: input.image,
    material: input.material,
    category: "Equipamentos profissionais de peso livre",
    specifications: input.specifications,
    blocks: [
      quick("resposta-rapida", `${input.productName} atende compradores B2B que precisam de uma referência documentada para academia, distribuição ou marca própria. ${input.range}. A proposta confirma pesos, quantidades, acabamento, logotipo, embalagem, MOQ e critérios de inspeção; nenhuma característica não documentada deve ser deduzida apenas da fotografia.`),
      definition("definicao", input.productName, input.definition),
      table("especificacoes", "Tabela de especificações para cotação", ["Item", "Referência disponível", "Confirmação necessária"], [
        ["Produto", input.productName, "Código, versão e imagem do modelo"],
        ["Faixa", input.range, "Pesos e unidades por peso"],
        ["Material", input.material, "Construção, superfície e acabamento"],
        ["Identificação", "kg ou lb e logo conforme viabilidade", "Método, posição, contraste e amostra"],
        ["Controle", "Peso, dimensões, superfície e montagem", "Tolerância e plano de amostragem"],
        ["Embalagem", "Caixa e pallet conforme composição", "Proteção, peso bruto e etiquetas"]
      ]),
      rich("posicionamento", "Produto, posicionamento e valor de compra", input.positioning, `O comprador deve relacionar o produto ao seu canal e ao custo durante a vida útil. ${input.comparison} Para atacado, a decisão inclui giro por peso, apresentação, estoque e reposição. Para uma academia, entram usuários simultâneos, armazenamento, limpeza e retirada de peças danificadas.`),
      rich("aplicacoes", "Aplicações comerciais e seleção", input.applications, "A lista de compra deve mostrar quantidade por referência, não apenas o peso total do pedido. Pesos de maior giro podem exigir pares adicionais, enquanto referências extremas dependem do perfil do público. O rack, a barra ou a estação compatível precisa ser considerado antes da aprovação para evitar uma linha correta no papel, mas inadequada ao espaço real."),
      rich("materiais", "Materiais e construção", input.construction, `A expressão comercial “${input.material}” não substitui uma ficha técnica. Formulação, espessura, dureza, método de união, insertos e acabamento podem variar entre fornecedores. Compare o produto real, registre o que será aceito e peça nova confirmação se material ou processo mudar depois da amostra.`),
      rich("fabricacao", "Fluxo de fabricação", input.process, "Na operação da PowerBaseFit, a ordem começa com modelo, faixa, quantidades, identidade visual e embalagem aprovados. Componentes são preparados conforme a construção, passam por formação, usinagem ou revestimento aplicável, união, acabamento, marcação e limpeza. A sequência exata pertence ao modelo cotado; ela não é apresentada como igual para todos os produtos."),
      checklist("controle", "Pontos de controle de qualidade", ["Código, peso e quantidade", "Dimensões e compatibilidade", "Material, superfície e cor", "União, inserto ou empunhadura", "Logo, kg/lb e legibilidade", "Comparação com amostra aprovada", "Caixa, proteção, etiqueta e pallet"]),
      rich("qc", "Inspeção e aceitação do lote", input.qcFocus, "Os critérios precisam ser mensuráveis e definidos antes da produção. O plano pode combinar registros internos, fotografias, pesagem por amostragem e inspeção independente conforme o risco. Em marca própria, confira também versão do arquivo, posição, cor, texto da embalagem e coerência visual entre pesos. Qualquer desvio deve ser relacionado à especificação aprovada, não a expressões genéricas como “qualidade premium”."),
      rich("oem", "OEM, logo e marca própria", "Podem ser avaliados logotipo, cores, marcação em kg ou lb, etiquetas e embalagem. A viabilidade depende da superfície, do método, da quantidade e do modelo. Aplicar uma identidade visual em uma construção existente é diferente de mudar forma, material ou ferramenta; alterações estruturais podem exigir nova amostra, MOQ e prazo.", "Para receber uma cotação comparável, envie arquivo vetorial, mercado, pesos, unidades por peso, referência de cor, embalagem e destino. A PowerBaseFit confirma o método possível e o que precisa de amostra. Não se presume que o mesmo tamanho de logo funcione em toda a faixa."),
      rich("embalagem", "Embalagem, transporte e recebimento", input.handling, "Produtos de peso livre concentram carga e podem sofrer atrito, deslocamento ou quebra de caixa. O plano precisa indicar unidades, peso líquido e bruto, separadores, identificação e distribuição no pallet. Na chegada, confira volumes, danos, quantidade por peso, marcação e amostras de diferentes caixas antes de colocar o lote em venda ou uso."),
      checklist("comprador", "Checklist do comprador B2B", ["Empresa, país e canal", "Modelo e aplicação", "Pesos e unidades por peso", "Material e construção", "Logo, cor e kg/lb", "Amostra e critérios de QC", "Caixas, pallets e destino", "MOQ, prazo e condição comercial", "Plano de reposição"])
    ],
    faq: [
      ["Este produto serve para academia profissional?", "Pode atender uso profissional quando modelo, faixa, armazenamento, manutenção e especificação forem compatíveis com a intensidade prevista."],
      ["É possível aplicar minha marca?", "Sim, conforme superfície, método, quantidade, amostra e MOQ. Logo, marcação e embalagem devem ser aprovados antes da produção."],
      ["Qual é o pedido mínimo?", "Não existe um MOQ único para toda a categoria. Ele depende do modelo, da composição por peso e da personalização solicitada."],
      ["Como a qualidade é verificada?", "Peso, dimensões, superfície, construção, marcação, quantidades e embalagem são comparados com critérios e amostra aprovados."],
      ["A cotação inclui importação para o Brasil?", "A condição comercial deve ser informada. Frete, seguro, despacho, tributos, armazenagem e entrega local são calculados para a operação real."],
      ["Como planejar reposição?", "Conserve código, ficha, amostra, arte e dados da caixa. Confirme mudanças de material ou processo antes de repetir o pedido."]
    ],
    links: input.links,
    author: ptBrEditorialAuthor,
    reviewedBy: ptBrTechnicalReviewer,
    updatedAt: releaseDate,
    publishedAt: releaseDate
  };
}

export const productLocalizationBatch1Portuguese: PilotPage[] = [
  productPage({
    id: "cast-iron-dumbbell", enPath: "/products/dumbbells/cast-iron-dumbbell", ptPath: "/pt/produtos/halteres/halter-ferro-fundido", enTitle: "Cast Iron Dumbbell", sku: "CAST-IRON-DB",
    title: "Halter de ferro fundido 2,5–100 kg no atacado | PowerBaseFit", description: "Halter de ferro fundido de 2,5 a 100 kg para academias e distribuidores, com marca própria, QC, embalagem OEM e fornecimento B2B.", h1: "Halter de ferro fundido para academias e distribuidores",
    image: ["/assets/products/dumbbells/cast-iron/cast-iron-dumbbell-main.webp", "Halter de ferro fundido profissional para academia"], productName: "Halter de ferro fundido", definition: "É um halter cuja cabeça e estrutura principal usam ferro fundido, dimensionado por peso e unido a uma empunhadura conforme o modelo. A linha cadastrada cobre pesos leves e muito pesados, por isso exige planejamento de rack, manuseio e proteção diferente de uma linha compacta.", range: "Faixa publicada de 2,5 a 100 kg, em incrementos de 2,5 kg", material: "Ferro fundido com empunhadura metálica",
    positioning: "A amplitude até 100 kg permite montar uma área completa de força para academias comerciais, centros de treinamento e distribuidores. O valor comercial está na continuidade da faixa e na possibilidade de organizar conjuntos para iniciantes, musculação geral e treino pesado sem misturar construções diferentes.", applications: "É indicado para zonas de halteres, projetos de peso livre e programas de estoque que precisam de pesos altos. Academias menores podem selecionar apenas parte da faixa; distribuidores podem separar conjuntos por perfil de cliente. Pesos acima do uso comum só devem entrar quando houver demanda, rack e equipe capazes de movimentá-los.", construction: "O corpo fundido oferece uma solução tradicional e robusta. O comprador deve confirmar geometria, acabamento, empunhadura, união e marcação. Pequenos vazios, bordas, variação superficial ou desalinhamento precisam de limites definidos; a resistência percebida do ferro não elimina a necessidade de inspeção.", process: "O fluxo inclui preparação do molde, fundição, limpeza de rebarbas, acabamento do corpo, preparação e união da empunhadura, marcação, pesagem e separação por pares. A superfície e o método de união são confirmados para a versão cotada. As cinco imagens existentes do modelo mostram produto, detalhe, rack, embalagem e aplicação.", qcFocus: "Como a faixa é ampla, a amostragem deve incluir pesos leves, intermediários e pesados. Verifique massa, dimensões, estabilidade, empunhadura, união, bordas e correspondência entre pares. Para referências pesadas, confira também manuseio, caixa e capacidade do pallet.", handling: "Peças fundidas podem marcar umas às outras e pesos altos sobrecarregam caixas. Separação, reforço e limite por volume precisam ser definidos. A descarga deve prever equipamentos e pessoas adequados; uma peça de 100 kg não deve ser tratada como uma caixa comum.", comparison: "Comparado a versões revestidas, o ferro fundido prioriza construção tradicional e faixa ampla; superfície, ruído, proteção do piso e apresentação devem ser avaliados para a aplicação.", specifications: [{ name: "Faixa", value: "2,5–100 kg" }, { name: "Incremento", value: "2,5 kg" }, { name: "Construção", value: "Ferro fundido" }], links: [["dumbbells-category", "Linha de halteres"], ["cpu-dumbbell", "Halter CPU"], ["tpu-dumbbell", "Halter TPU"], ["dumbbell-weighing-guide", "Como verificar o peso"], ["contact", "Solicitar cotação"]]
  }),
  productPage({
    id: "cpu-dumbbell", enPath: "/products/dumbbells/cpu-dumbbell-kg", ptPath: "/pt/produtos/halteres/halter-cpu", enTitle: "CPU Dumbbell", sku: "CPU-DB-KG",
    title: "Halter CPU 2,5–50 kg para academia e marca própria | PowerBaseFit", description: "Halter CPU de 2,5 a 50 kg para academias, distribuidores e marcas próprias, com logo, QC, embalagem e fornecimento direto de fábrica.", h1: "Halter CPU profissional para compradores B2B",
    image: ["/assets/products/dumbbells/catalog-v2/cpu-dumbbell-kg.webp", "Halter CPU profissional de 2,5 a 50 kg"], productName: "Halter CPU", definition: "É um halter com cabeça protegida por material CPU conforme a construção do modelo e empunhadura preparada para uso recorrente. CPU identifica a família de superfície; espessura, dureza, união e acabamento precisam constar na amostra ou ficha aprovada.", range: "Faixa publicada de 2,5 a 50 kg, em incrementos de 2,5 kg", material: "Revestimento CPU e empunhadura metálica",
    positioning: "A linha CPU ocupa uma posição comercial entre soluções tradicionais e linhas de apresentação premium. É adequada para distribuidores que querem diferenciar material e para academias que precisam de uma faixa em kg com identidade consistente, proteção de superfície e possibilidade de marca própria.", applications: "Atende áreas de musculação, redes de academia, clubes, hotéis e catálogos B2B. A seleção deve considerar contato com rack, piso, odor inicial, limpeza e reposição. Em redes, a mesma referência deve manter cor, marcação e empunhadura entre lotes para não fragmentar a experiência visual.", construction: "A cabeça recebe superfície CPU e é combinada com a empunhadura definida. Confirme núcleo, método de aplicação, transição, textura, diâmetro e identificação. CPU não deve ser descrito como desempenho universal: a avaliação deve usar o modelo real e comparar dureza, acabamento e resistência a marcas.", process: "Componentes são preparados, a cabeça é formada e recebe o material conforme a tecnologia do modelo, a empunhadura é usinada ou acabada e o conjunto passa por união, cura aplicável, limpeza, marcação e pesagem. Cor e logo entram na aprovação antes de liberar o lote.", qcFocus: "Confira uniformidade da superfície, bolhas, rebarbas, cor, alinhamento, textura da empunhadura e legibilidade. A pesagem deve seguir tolerância acordada e amostras distribuídas pela faixa. O contato com o rack pode ser testado na amostra para detectar marcas ou instabilidade.", handling: "A superfície precisa de separação contra atrito e pressão. Caixas densas devem respeitar limite de manuseio e ser identificadas por peso. A combinação com racks ou anilhas no contêiner precisa evitar contato direto com metal e movimento durante o transporte.", comparison: "Em relação à borracha, PU ou TPU, CPU deve ser comparado por formulação, toque, acabamento, manutenção, custo e posicionamento, não apenas pela sigla.", specifications: [{ name: "Faixa", value: "2,5–50 kg" }, { name: "Incremento", value: "2,5 kg" }, { name: "Superfície", value: "CPU" }], links: [["dumbbells-category", "Halteres profissionais"], ["cast-iron-dumbbell", "Halter de ferro fundido"], ["tpu-dumbbell", "Halter TPU"], ["dumbbell-weighing-guide", "Controle de peso na fábrica"], ["contact", "Cotar halteres CPU"]]
  }),
  productPage({
    id: "tpu-dumbbell", enPath: "/products/dumbbells/tpu-dumbbell-kg", ptPath: "/pt/produtos/halteres/halter-tpu", enTitle: "TPU Dumbbell", sku: "TPU-DB-KG",
    title: "Halter TPU 2,5–70 kg para academias | PowerBaseFit", description: "Halter TPU de 2,5 a 70 kg para academias, redes e distribuidores, com logo, marca própria, QC e embalagem de exportação OEM.", h1: "Halter TPU para academias e linhas premium",
    image: ["/assets/products/dumbbells/catalog-v2/tpu-dumbbell-kg.webp", "Halter TPU profissional para academia e marca própria"], productName: "Halter TPU", definition: "É um halter cuja cabeça usa revestimento externo de poliuretano termoplástico conforme a configuração do modelo. O material oferece uma alternativa para linhas comerciais que valorizam superfície e personalização, mas suas propriedades precisam ser comprovadas na amostra específica.", range: "Faixa publicada de 2,5 a 70 kg, em incrementos de 2,5 kg", material: "Revestimento TPU e empunhadura metálica",
    positioning: "A faixa até 70 kg permite atender academias premium e áreas de força que querem uma apresentação uniforme sem limitar o catálogo aos pesos intermediários. Para distribuidores, o TPU pode formar uma linha de maior valor percebido com cores, logo e embalagem coerentes.", applications: "É adequado para clubes, hotéis, redes, estúdios de alto padrão e revendedores. A compra deve verificar se a faixa pesada tem demanda e se o rack suporta diâmetro, comprimento e carga. Para projetos de marca própria, a consistência entre pesos pequenos e grandes é parte da apresentação.", construction: "A construção combina núcleo, revestimento TPU e empunhadura segundo o modelo. Confirme espessura, dureza, textura, transição, união e método de logo. O nome TPU não garante que duas formulações tenham o mesmo odor, brilho, resistência a riscos ou comportamento de limpeza.", process: "O processo parte da preparação do núcleo e da empunhadura, segue para formação ou aplicação do TPU, união, estabilização, acabamento, marcação e pesagem. Referência de cor e arte devem ser verificadas em amostra; mudanças de matéria-prima precisam ser comunicadas antes do lote.", qcFocus: "A inspeção deve observar uniformidade, riscos, bolhas, diferença de cor, marcação, alinhamento, empunhadura e peso. Se a linha usa logo aplicado ou moldado, confira proporção em mais de um tamanho. Registre produtos de limpeza compatíveis e critérios para reposição.", handling: "Superfícies de TPU precisam ser protegidas contra metal, quinas e atrito entre peças. Separadores, caixas dimensionadas e pallet estável reduzem marcas. Na recepção, não arraste os halteres e verifique danos antes de montar a linha no rack.", comparison: "Comparado ao PU, CPU ou borracha, TPU deve ser escolhido pela combinação real de superfície, manutenção, apresentação, faixa e custo total.", specifications: [{ name: "Faixa", value: "2,5–70 kg" }, { name: "Incremento", value: "2,5 kg" }, { name: "Revestimento", value: "TPU" }], links: [["dumbbells-category", "Ver halteres"], ["cpu-dumbbell", "Comparar com CPU"], ["cast-iron-dumbbell", "Comparar com ferro fundido"], ["materials-guide", "Borracha, PU e TPU"], ["contact", "Solicitar proposta TPU"]]
  }),
  productPage({
    id: "cpu-bumper-plate", enPath: "/products/weight-plates/cpu-bumper-plate", ptPath: "/pt/produtos/anilhas/anilha-bumper-cpu", enTitle: "CPU Bumper Plate", sku: "CPU-BUMPER",
    title: "Anilha bumper CPU para academia e marca própria | PowerBaseFit", description: "Anilha bumper CPU para barras olímpicas, academias e distribuidores, com cores, logo, kg/lb, QC e embalagem OEM de fábrica.", h1: "Anilha bumper CPU para academias e compradores B2B",
    image: ["/assets/products/weight-plates/catalog/cpu-bumper-plate.webp", "Anilha bumper CPU profissional para academia"], productName: "Anilha bumper CPU", definition: "É uma anilha de diâmetro externo uniforme dentro da linha, com corpo de material CPU e inserto central para carregamento em barra compatível. Destina-se a aplicações de levantamento definidas pelo modelo e não elimina a necessidade de plataforma, técnica e regras de uso.", range: "Planejamento em kg ou lb disponível conforme o conjunto cotado", material: "Superfície CPU com inserto central de aço",
    positioning: "A anilha bumper CPU é uma opção para áreas funcionais e de levantamento que procuram identificação por cor, apresentação consistente e programa de marca própria. Distribuidores podem organizá-la em jogos; academias precisam dimensionar quantidades por plataforma e frequência de uso.", applications: "Pode atender boxes, áreas de levantamento, academias comerciais e linhas de distribuição. Antes de comprar, confirme barra, centro, diâmetro, espessura e uso permitido. Não trate a palavra bumper como autorização para quedas em qualquer piso ou altura.", construction: "O corpo usa material CPU e inserto central metálico. Confirme dureza ou referência aplicável, espessura por peso, encaixe, planicidade, marcação e comportamento previsto. O inserto deve permanecer alinhado e sem folga indevida; a superfície precisa ser avaliada em diferentes pesos.", process: "A fabricação envolve preparação do material, moldagem do corpo, posicionamento do inserto, acabamento, marcação, verificação de peso e inspeção. Cores e logo seguem amostra aprovada. Parâmetros de uso e tolerância pertencem à especificação do modelo, não a uma promessa genérica da categoria.", qcFocus: "Inclua peso, diâmetro, espessura, centro, planicidade, superfície, cor e logo. Se houver ensaio funcional acordado, registre equipamento, altura, piso, número de ciclos e critério de aceitação. A inspeção deve abranger pesos leves e pesados porque a espessura e a rigidez podem variar.", handling: "Anilhas são densas e o inserto e as bordas precisam ficar separados durante o transporte. Informe unidades por caixa, peso bruto, pallet e proteção contra umidade e deslocamento. Na chegada, confira encaixe na barra e danos antes do uso.", comparison: "Em relação à anilha olímpica convencional, a bumper muda construção e aplicação; em relação a outras bumpers, compare material, espessura, inserto, dureza, marcação e custo.", specifications: [{ name: "Sistema", value: "kg ou lb conforme projeto" }, { name: "Material", value: "CPU" }, { name: "Centro", value: "Inserto de aço" }], links: [["weight-plates-category", "Linha de anilhas"], ["cast-iron-weight-plate", "Anilha de ferro fundido"], ["cpu-grip-plate", "Anilha CPU com pegada"], ["bumper-manufacturing-guide", "Como bumpers são fabricadas"], ["contact", "Cotar bumper CPU"]]
  }),
  productPage({
    id: "cast-iron-weight-plate", enPath: "/products/weight-plates/cast-iron-weight-plate", ptPath: "/pt/produtos/anilhas/anilha-ferro-fundido", enTitle: "Cast Iron Weight Plate", sku: "CAST-IRON-PLATE",
    title: "Anilha de ferro fundido no atacado e marca própria | PowerBaseFit", description: "Anilha de ferro fundido para academias, distribuidores e projetos de força, com kg/lb, logo, acabamento, QC e embalagem OEM.", h1: "Anilha de ferro fundido para academias e distribuição",
    image: ["/assets/products/weight-plates/cast-iron/cast-iron-weight-plate-main.avif", "Anilha de ferro fundido com pegadas para academia"], productName: "Anilha de ferro fundido", definition: "É uma anilha com corpo fundido em ferro, marcação elevada e aberturas de pegada conforme o modelo. É usada em barras e estações compatíveis para musculação; não deve ser confundida com uma bumper plate destinada a outra forma de contato com o piso.", range: "Conjuntos em kg ou lb definidos na cotação", material: "Corpo de ferro fundido com superfície preta texturizada",
    positioning: "A construção tradicional atende academias, distribuidores e projetos que valorizam manuseio pelas pegadas, marcação visível e custo controlado. É uma linha prática para barras e estações plate-loaded quando centro, diâmetro e capacidade são compatíveis.", applications: "Pode compor racks de anilhas, zonas de musculação, academias residenciais de alto nível e estoques de distribuidores. O comprador deve separar aplicação em barra, máquina e armazenamento. Se houver quedas planejadas, precisa avaliar produto e piso apropriados em vez de assumir que ferro fundido é intercambiável com bumper.", construction: "O corpo é produzido por fundição e recebe limpeza, tratamento superficial e marcação. Confirme bordas, pegadas, furo central, planicidade e acabamento. A superfície texturizada e os números elevados precisam ser legíveis sem criar rebarbas que dificultem o manuseio.", process: "O fluxo inclui preparação do molde, fundição, retirada e limpeza, acabamento de bordas e centro, tratamento de superfície, inspeção da marcação, pesagem e embalagem. Logo moldado ou outra personalização exige arte e ferramenta aprovadas antes da produção.", qcFocus: "Verifique massa, diâmetro interno, espessura, planicidade, pegadas, bordas, acabamento e legibilidade. Coloque amostras na barra ou estação informada pelo comprador. Para conjuntos kg/lb, confira que marcações, etiquetas e caixas não misturem sistemas.", handling: "Ferro fundido pode sofrer lascas e transferir atrito se as peças viajarem soltas. Use separação e caixa compatíveis com o peso. Pallets devem distribuir a carga; na recepção, inspecione bordas, centro, corrosão visível e quantidade por referência.", comparison: "Comparada a anilhas revestidas, a versão fundida oferece construção direta e aparência tradicional; ruído, proteção de piso, corrosão e acabamento precisam entrar na decisão.", specifications: [{ name: "Material", value: "Ferro fundido" }, { name: "Marcação", value: "kg/lb conforme conjunto" }, { name: "Formato", value: "Pegadas e marcação elevada conforme modelo" }], links: [["weight-plates-category", "Ver anilhas"], ["cpu-bumper-plate", "Anilha bumper CPU"], ["cpu-grip-plate", "Anilha CPU com pegada"], ["bumper-manufacturing-guide", "Processo de anilhas bumper"], ["contact", "Solicitar cotação"]]
  }),
  productPage({
    id: "cpu-grip-plate", enPath: "/products/weight-plates/cpu-grip-plate", ptPath: "/pt/produtos/anilhas/anilha-cpu-com-pegada", enTitle: "CPU Grip Plate", sku: "CPU-GRIP-PLATE",
    title: "Anilha CPU com pegada para academia | PowerBaseFit", description: "Anilha CPU com aberturas de pegada para academias e redes, com kg/lb, logo, cores, QC e embalagem para compras B2B e marca própria.", h1: "Anilha CPU com pegada para uso comercial",
    image: ["/assets/products/weight-plates/catalog/cpu-grip-plate.webp", "Anilha CPU com pegadas para academia profissional"], productName: "Anilha CPU com pegada", definition: "É uma anilha revestida com material CPU e formada com aberturas que facilitam retirar, transportar e carregar a peça. O centro reforçado conecta a anilha à barra ou estação compatível; número, forma e posição das pegadas pertencem ao modelo específico.", range: "Programas em kg ou lb definidos conforme a linha cotada", material: "Revestimento CPU, pegadas moldadas e inserto central reforçado",
    positioning: "O principal valor comercial é o manuseio em áreas de alta rotatividade. Pegadas podem facilitar a organização em racks e a troca em máquinas, enquanto a superfície CPU oferece uma apresentação diferenciada. Para redes e distribuidores, a linha também permite identidade visual e marcação coerentes.", applications: "É indicada para academias, estações de barras e máquinas plate-loaded compatíveis, clubes e catálogos de força. Confirme se as pegadas são acessíveis em todos os pesos e se o diâmetro externo não interfere na estação. A ergonomia deve ser avaliada com mãos e usos reais.", construction: "O corpo recebe superfície CPU, aberturas formadas e centro reforçado. Peça desenho ou amostra para confirmar bordas, espessura das pegadas, inserto, dureza e equilíbrio. As aberturas não devem reduzir a clareza do peso ou criar pontos ásperos.", process: "O processo inclui posicionamento do centro, formação do corpo e das pegadas, aplicação ou moldagem da superfície CPU, acabamento, marcação, pesagem e inspeção. Cor, logo e kg/lb são verificados antes de liberar o lote; o mesmo método pode ter proporções diferentes por peso.", qcFocus: "Além de peso, centro e superfície, inspecione cada pegada quanto a espessura, bordas, simetria e conforto. Teste carregamento em barra ou máquina compatível e estabilidade no rack. Confira logo e marcação nas áreas próximas às aberturas.", handling: "Apesar das pegadas, caixas densas ainda precisam de limite e reforço. Separe superfícies e insertos para evitar marcas. Na descarga, as aberturas ajudam o manuseio individual, mas não substituem planejamento para pallets e volumes pesados.", comparison: "Comparada a uma anilha sem pegadas, melhora a manipulação em certas rotinas; comparada a bumper, atende outra construção e deve ser escolhida pelo uso real.", specifications: [{ name: "Material", value: "CPU" }, { name: "Manuseio", value: "Aberturas de pegada" }, { name: "Centro", value: "Inserto reforçado" }], links: [["weight-plates-category", "Anilhas profissionais"], ["cpu-bumper-plate", "Bumper CPU"], ["cast-iron-weight-plate", "Ferro fundido"], ["bumper-manufacturing-guide", "Fabricação de bumpers"], ["contact", "Cotar anilhas CPU"]]
  }),
  {
    id: "bumper-manufacturing-guide", type: "blog", enPath: "/resources/how-are-bumper-plates-made", ptPath: "/pt/blog/como-sao-fabricadas-anilhas-bumper", enTitle: "How Are Bumper Plates Made?", title: "Como são fabricadas as anilhas bumper: materiais e QC | PowerBaseFit", description: "Entenda materiais, inserto, moldagem, acabamento, pesagem, testes, OEM e embalagem usados na fabricação de anilhas bumper para compras B2B.", h1: "Como são fabricadas as anilhas bumper",
    image: ["/assets/factory-process/plate-raw-material.webp", "Matéria-prima usada na fabricação de anilhas bumper"],
    blocks: [
      quick("resposta-rapida", "Uma anilha bumper é fabricada a partir de material elastomérico preparado para o corpo, um inserto central metálico e uma especificação de peso, diâmetro, espessura, dureza ou comportamento aplicável, marcação e acabamento. O fluxo normalmente inclui preparação do material, posicionamento do inserto, moldagem, estabilização, acabamento, pesagem, inspeção e embalagem. Fórmula, parâmetros e testes variam por modelo; a compra deve usar dados e amostra do produto cotado."),
      definition("definicao", "Anilha bumper", "É uma anilha de peso com corpo predominantemente de borracha, caucho, CPU ou outro material definido, diâmetro externo uniforme dentro da linha e inserto central para barra compatível. Ela é projetada para aplicações de levantamento especificadas pelo fabricante, mas continua dependente de plataforma, técnica, manutenção e limites de uso."),
      table("componentes", "Componentes e função", ["Componente", "Função", "O que o comprador confirma"], [["Material do corpo", "Forma, superfície e resposta ao contato", "Composição, dureza, odor e cor"], ["Inserto central", "Encaixe e transferência de carga", "Material, dimensão, fixação e tolerância"], ["Marcação", "Identificação do peso e da marca", "kg/lb, contraste, método e posição"], ["Geometria", "Compatibilidade e capacidade da barra", "Diâmetro, centro e espessura por peso"], ["Embalagem", "Proteção durante transporte", "Unidades, caixa, pallet e peso bruto"]]),
      rich("projeto", "1. O processo começa pela especificação", "Antes de preparar material, a fábrica precisa saber modelo, pesos, quantidades, sistema kg/lb, inserto, cor, logo, tolerância, embalagem e uso. A mesma palavra “bumper” pode representar construções, durezas e faixas diferentes. Uma cotação sem espessura, centro e aplicação não permite comparar produtos equivalentes.", "Para marca própria, arquivo vetorial, posição, cor e método entram na especificação. Mudanças de molde ou construção são diferentes de trocar uma impressão. O comprador deve conservar ficha, arte e amostra como referência para o lote e para futuras reposições."),
      rich("material", "2. Preparação do material", "A matéria-prima é selecionada e preparada conforme a formulação do modelo. Borracha virgem, material reciclado, CPU e outras composições não devem ser tratados como equivalentes. Proporção, mistura, temperatura, tempo e condições de armazenamento afetam superfície, odor, dureza e estabilidade.", "PowerBaseFit não publica uma fórmula universal porque ela depende do produto. Para compra, é mais útil confirmar material declarado, referência de dureza quando aplicável, aparência, cheiro inicial, uso recomendado e limites aceitos. Se a formulação mudar depois da amostra, o comprador deve ser informado."),
      rich("inserto", "3. Inserto central e preparação do molde", "O inserto é dimensionado para a manga da barra e precisa ser posicionado de forma concêntrica. Superfície, método de fixação e tolerância influenciam encaixe e durabilidade. O molde define diâmetro, espessura, grafismos e detalhes da anilha.", "Antes do lote, confirme centro, desenho, marcação e versão da ferramenta. Um inserto desalinhado pode causar rotação irregular; excesso de folga ou encaixe apertado dificulta o uso. A inspeção deve medir o produto, não apenas observar a aparência."),
      rich("moldagem", "4. Moldagem, estabilização e acabamento", "O material preparado é colocado ou injetado no processo correspondente com o inserto posicionado. Pressão, temperatura e tempo seguem a construção. Depois da formação, a peça passa por estabilização ou cura aplicável, retirada do molde, remoção de excesso, limpeza e acabamento.", "A equipe observa preenchimento, bolhas, rebarbas, manchas, deformação, planicidade e integridade ao redor do centro. Cores e logos precisam permanecer coerentes entre pesos. Uma peça visualmente limpa ainda deve ser pesada e medida."),
      table("processo", "Resumo do fluxo de fabricação", ["Etapa", "Registro útil", "Risco controlado"], [["Especificação", "Ficha, arte e amostra", "Produto incorreto"], ["Material", "Lote e parâmetros", "Variação de superfície"], ["Inserto", "Dimensão e posição", "Folga ou desalinhamento"], ["Moldagem", "Parâmetros do modelo", "Falha de formação"], ["Acabamento", "Critérios visuais", "Rebarba e deformação"], ["Pesagem", "Equipamento e tolerância", "Peso fora do acordo"], ["Embalagem", "Plano de caixas", "Dano no transporte"]]),
      rich("peso", "5. Pesagem, dimensões e identificação", "Cada referência deve ser relacionada a um peso nominal e a uma tolerância aprovada. O plano define equipamento, frequência e distribuição da amostra. Também mede diâmetro externo, centro, espessura, planicidade e legibilidade. Pesos leves e pesados não devem ser avaliados como se tivessem a mesma espessura e rigidez.", "A identificação em kg ou lb precisa corresponder à caixa e à lista de volumes. Em OEM, logo, cor e texto são comparados com a arte. O registro evita misturar versões e permite investigar uma divergência por lote."),
      rich("testes", "6. QC e verificação funcional", "O controle pode incluir inspeção visual, massa, dimensões, inserto, superfície e um ensaio funcional definido. Se houver teste de impacto ou queda, registre barra, plataforma, altura, número de ciclos, ambiente e critério de aceitação. Dizer apenas “testado” não informa o que ocorreu.", "O produto não torna qualquer piso seguro. O comprador deve validar plataforma, regras de uso e manutenção no destino. Inserto solto, borda rasgada, trinca ou deformação relevante exigem retirada e avaliação."),
      checklist("auditoria", "Checklist para avaliar fábrica e amostra", ["Modelo e material declarado", "Pesos, espessuras e quantidades", "Centro e compatibilidade", "Dureza ou referência funcional", "Amostra e tolerância", "Método de logo e cores", "Plano de teste documentado", "Critérios de defeito", "Caixas, pallets e rastreabilidade"]),
      rich("oem", "7. OEM, embalagem e reposição", "Logo, cores, kg/lb e embalagem podem ser personalizados conforme ferramenta, processo e quantidade. Aprove mais de um peso quando geometria ou espaço de marcação variar. O MOQ deve ser confirmado depois que a combinação estiver definida.", "Na embalagem, bordas e insertos precisam de separação. Caixas devem respeitar peso e o pallet deve impedir deslocamento. Para reposição, conserve código, ficha, fórmula ou material declarado, arte e amostra. Uma nova compra só é equivalente quando os pontos críticos permanecem confirmados."),
      rich("recebimento", "8. Recebimento e acompanhamento no uso", "Antes da carga chegar, prepare lista de volumes, área de descarga e amostra de recebimento. Confira caixas abertas, umidade, deslocamento, bordas e insertos. Selecione diferentes pesos e pallets para repetir massa, centro, espessura e marcação; verificar apenas a referência mais pesada pode ocultar problemas em peças finas ou leves.", "Depois da instalação, registre ajuste na barra, ruído, estado do piso, marcas superficiais e qualquer folga do inserto. Relacione ocorrências ao lote e à plataforma usada. Para distribuidores, a rotação por peso orienta reposição; para academias, o número de barras e plataformas ajuda a calcular unidades adicionais. Esses dados tornam a compra seguinte mais precisa do que repetir jogos completos sem observar o uso."),
      rich("experiencia", "Informação de primeira parte da PowerBaseFit", "Na fábrica da PowerBaseFit em Dezhou, a revisão de um pedido de anilhas começa pela tabela por peso: unidades, material, cor, logo, embalagem e destino. Essa tabela orienta amostra, produção, pesagem, caixas e carga. Pedidos descritos apenas como “bumper olímpica” exigem esclarecimento antes de uma proposta confiável.", "O comprador pode usar as fotos reais de matéria-prima, tratamento de superfície, embalagem e carga para compreender etapas, mas deve relacionar cada evidência ao modelo cotado. Não se presume certificação, resultado de teste ou composição que não esteja documentada."),
      checklist("compra", "Checklist final de compra", ["Aplicação e plataforma", "Material e dureza", "Centro, diâmetro e espessura", "Pesos e tolerâncias", "Logo, cor e kg/lb", "Amostra e ensaio", "QC e não conformidade", "Embalagem e custo total", "Reposição e controle de versão"])
    ],
    faq: [["De que material é feita uma anilha bumper?", "Depende do modelo: pode usar borracha, caucho, CPU ou outra composição declarada, combinada com inserto central metálico."], ["Toda bumper pode ser solta no chão?", "Não. Uso permitido depende do produto, da plataforma, da técnica e das regras do ambiente."], ["Como o peso é controlado?", "Por equipamento e plano de amostragem definidos, comparando peso nominal com tolerância acordada."], ["Por que a espessura importa?", "Ela determina quanto peso cabe na manga e varia entre materiais e pesos."], ["É possível aplicar marca própria?", "Sim, conforme molde, método, quantidade e amostra aprovada."], ["Que documentos pedir?", "Ficha, desenho ou medidas, arte, amostra, critérios de QC, plano de embalagem e registros aplicáveis ao pedido."]],
    links: [["weight-plates-category", "Linha de anilhas"], ["cpu-bumper-plate", "Anilha bumper CPU"], ["cast-iron-weight-plate", "Anilha de ferro fundido"], ["cpu-grip-plate", "Anilha CPU com pegada"], ["factory", "Conhecer a fábrica"], ["contact", "Solicitar cotação"]], author: ptBrEditorialAuthor, reviewedBy: ptBrTechnicalReviewer, updatedAt: releaseDate, publishedAt: releaseDate
  },
  {
    id: "dumbbell-weighing-guide", type: "blog", enPath: "/resources/how-are-dumbbells-weighed", ptPath: "/pt/blog/como-verificar-peso-de-halteres-na-fabrica", enTitle: "How Are Dumbbells Weighed?", title: "Como verificar o peso de halteres na fábrica | PowerBaseFit", description: "Guia B2B sobre peso nominal, tolerância, balanças, amostragem, QC, registros e aceitação de halteres antes do embarque.", h1: "Como o peso dos halteres é verificado na fábrica",
    image: ["/assets/factory-process/dumbbell-material.webp", "Componentes de halteres antes da pesagem e montagem"],
    blocks: [
      quick("resposta-rapida", "Halteres são verificados em balanças adequadas à faixa, seguindo peso nominal, tolerância e plano de amostragem definidos antes da produção. A fábrica precisa identificar modelo, unidade kg/lb, equipamento, frequência, arredondamento, critérios de aceitação e ação para desvios. Uma leitura isolada não representa o lote inteiro; o comprador deve combinar pesagem com inspeção de marcação, pares, construção e embalagem."),
      definition("definicao", "Peso nominal do halter", "É o valor declarado no produto, como 10 kg. O peso medido é a leitura obtida sob condições definidas. A diferença entre ambos deve ser comparada com a tolerância contratada; não existe uma margem universal que possa ser aplicada sem considerar produto, mercado, método e acordo comercial."),
      table("conceitos", "Termos usados no controle de peso", ["Termo", "Significado", "Decisão do comprador"], [["Peso nominal", "Valor marcado", "kg/lb e referência"], ["Peso medido", "Leitura da balança", "Método e arredondamento"], ["Tolerância", "Desvio permitido", "Limites superior e inferior"], ["Amostra", "Unidades verificadas", "Quantidade e distribuição"], ["Calibração", "Relação do instrumento com referência", "Validade e identificação"], ["Não conformidade", "Resultado fora do acordo", "Segregação, correção ou decisão"]]),
      rich("especificacao", "1. Defina a regra antes de produzir", "A ordem de compra deve registrar modelo, pesos, sistema kg ou lb, tolerância e critério de arredondamento. Também precisa dizer se a aceitação considera cada unidade, média, par ou amostragem. Sem essa definição, comprador e fábrica podem interpretar a mesma leitura de formas diferentes.", "Para uma linha de 2,5 a 100 kg, um único procedimento pode usar equipamentos ou resoluções diferentes. A balança adequada a um halter leve precisa ter sensibilidade suficiente; a usada em um peso alto precisa suportar a carga. O plano deve cobrir os extremos e os pesos de maior volume."),
      rich("equipamento", "2. Balança, ambiente e identificação", "Antes da medição, confira identificação do instrumento, capacidade, resolução, superfície nivelada, condição e verificação aplicável. A unidade exibida precisa corresponder ao produto. Poeira, vibração, apoio parcial ou peça encostada em outra superfície podem alterar a leitura.", "O operador identifica modelo, peso nominal e lote antes de registrar o valor. Balanças devem estar em uma área onde a peça possa ser colocada com segurança. Halteres muito pesados exigem método de movimentação que proteja pessoas, instrumento e produto."),
      rich("amostragem", "3. Monte uma amostra representativa", "Amostragem não significa escolher apenas as primeiras caixas. Distribua verificações entre momentos da produção, pesos, moldes, cores, embalagens e pallets. Inclua pesos leves, médios e pesados e aumente a atenção quando houver mudança de material, ferramenta ou ajuste.", "O tamanho da amostra e o critério de aceitação devem ser acordados conforme risco. Para um pedido pequeno ou crítico, o comprador pode solicitar maior cobertura. Uma inspeção externa pode ser usada, mas precisa receber a mesma especificação da fábrica."),
      table("registro", "Exemplo de registro de pesagem", ["Campo", "Exemplo de informação", "Por que registrar"], [["Lote", "Código e data", "Rastreabilidade"], ["Produto", "Modelo e nominal", "Evitar mistura"], ["Balança", "ID, capacidade e resolução", "Reproduzir método"], ["Leitura", "Valor e unidade", "Comparar tolerância"], ["Resultado", "Aceito ou segregado", "Tomar ação"], ["Operador/revisor", "Responsáveis", "Controle de versão"]]),
      rich("construcao", "4. Entenda por que o peso pode variar", "Halteres podem combinar ferro fundido, aço, borracha, PU, TPU, CPU, cromo e empunhaduras. Variação pode vir de fundição, usinagem, volume de revestimento, componentes, união ou acabamento. O controle deve identificar a etapa relevante ao modelo.", "Corrigir uma peça não deve comprometer construção, superfície ou equilíbrio. Qualquer método de ajuste precisa pertencer ao processo aprovado. O comprador deve evitar soluções improvisadas que criem cavidades, ruído ou diferença visual."),
      rich("pares", "5. Peso, equilíbrio e correspondência entre pares", "Dois halteres com a mesma marcação devem formar um par coerente, mas a verificação não termina na massa. Observe dimensões, alinhamento, empunhadura, centro de gravidade, superfície e identificação. Uma peça pode estar dentro da tolerância e ainda apresentar defeito de união ou acabamento.", "Para racks, confirme que cabeças e empunhaduras mantêm dimensões compatíveis. Em linhas coloridas ou com logo, o par deve usar a mesma versão de arte. Registre diferenças que afetem apresentação ou uso."),
      checklist("inspecao", "Checklist de inspeção de halteres", ["Modelo e lote", "Peso nominal e unidade", "Balança identificada", "Leitura e tolerância", "Par correspondente", "Dimensões e alinhamento", "Empunhadura e união", "Superfície, logo e marcação", "Caixa e etiqueta"]),
      rich("nao-conforme", "6. O que fazer com resultados fora do limite", "Uma unidade fora da tolerância deve ser identificada e separada. A equipe avalia extensão, possível causa e necessidade de ampliar a inspeção. Retrabalho, substituição ou aceitação excepcional só ocorre com decisão documentada pelas partes responsáveis.", "Não altere a marcação para coincidir com uma leitura sem verificar a referência comercial. Se o problema aparecer em várias unidades, investigue material, molde, componente ou método. O relatório deve indicar o que foi encontrado e como o lote foi liberado."),
      rich("embalagem", "7. Verificação antes e depois da embalagem", "A pesagem de produto controla a unidade; peso líquido e bruto da caixa apoiam logística e conferência. A caixa deve informar referência e quantidade. Diferenças no peso bruto podem indicar componente, etiqueta ou unidade faltante, mas não substituem a inspeção individual.", "Na recepção, o importador pode repetir uma amostra usando método documentado. Compare lote, balança, ambiente e arredondamento antes de concluir que há divergência. Fotos do visor sem identificação não bastam para investigar."),
      rich("fornecedor", "8. Como comparar propostas e relatórios", "Envie aos fornecedores a mesma tabela de pesos, unidades, tolerância, método de inspeção e embalagem. Uma proposta que informa apenas preço por quilograma não mostra como pares, marcação e desvios serão controlados. Peça um exemplo de registro sem dados confidenciais e verifique se instrumento, lote, leitura, resultado e responsável podem ser relacionados.", "Ao comparar o custo, inclua amostra, inspeção, segregação de não conformes, embalagem e reposição. Um lote aparentemente mais barato pode gerar custo adicional se pares chegarem misturados ou se a referência não puder ser repetida. A decisão deve considerar a capacidade do fornecedor de manter a mesma construção, faixa e método entre pedidos, além do valor inicial."),
      rich("experiencia", "Informação de primeira parte da PowerBaseFit", "Na fábrica de Dezhou, a tabela por peso e quantidade é a base para organizar produção, pesagem, pares, caixas e carga. Ela reduz erros entre kg e lb e permite distribuir a amostra. Para o halter de ferro fundido publicado, por exemplo, a faixa é 2,5–100 kg; outros modelos têm faixas diferentes e não devem herdar esse dado.", "PowerBaseFit recomenda que a solicitação indique tolerância e inspeção desejadas antes do pedido. Quando isso não ocorre, a equipe precisa confirmar os critérios antes de liberar o lote. A transparência sobre instrumento, amostra e registro é mais útil do que afirmar apenas que o produto foi “testado”."),
      checklist("comprador", "Checklist do comprador", ["Faixa e quantidades", "kg ou lb", "Tolerância escrita", "Método e arredondamento", "Balança e identificação", "Plano de amostragem", "Correspondência de pares", "Ação para desvios", "Relatório e recebimento", "Reposição por lote"])
    ],
    faq: [["Todo halter pesa exatamente o valor marcado?", "Produtos físicos podem ter variação. O importante é definir tolerância, método e aceitação antes da produção."], ["Qual tolerância deve ser usada?", "Depende do modelo, mercado e acordo. Não se deve inventar uma margem universal."], ["É necessário pesar todas as unidades?", "Depende do risco e do pedido. Pode haver inspeção total ou amostragem definida."], ["Como escolher a balança?", "Capacidade e resolução precisam cobrir a faixa, e o instrumento deve estar identificado e verificado conforme o procedimento aplicável."], ["Peso correto garante qualidade?", "Não. União, alinhamento, superfície, empunhadura, marcação e embalagem também precisam ser inspecionados."], ["O comprador pode repetir a pesagem?", "Sim. Use método, unidade, arredondamento e condições comparáveis e registre lote e instrumento."]],
    links: [["dumbbells-category", "Linha de halteres"], ["cast-iron-dumbbell", "Halter de ferro fundido"], ["cpu-dumbbell", "Halter CPU"], ["tpu-dumbbell", "Halter TPU"], ["factory", "Controle na fábrica"], ["contact", "Enviar especificação"]], author: ptBrEditorialAuthor, reviewedBy: ptBrTechnicalReviewer, updatedAt: releaseDate, publishedAt: releaseDate
  }
];
