import type { ContentBlock } from "../../lib/content/types";
import { checklist, rich, table } from "./pt-br-content-helpers";

export const contentSupplements: Record<string, ContentBlock[]> = {
  "dumbbells-category": [rich("decisao-comercial", "Decisão comercial e reposição", "Antes de fechar o pedido, compare a linha pelo custo instalado e pela continuidade. Registre código, material, faixa, marcação e versão de cada modelo. Defina quais pesos precisam de reposição rápida e como diferenças de lote serão tratadas. Para distribuidores, prepare informações claras sobre aplicação e manutenção; para academias, treine a equipe para inspeção e devolução ao rack.")],
  "weight-plates-category": [rich("recebimento", "Recebimento e rastreabilidade", "Na chegada, confira volumes, pesos, marcações e possíveis danos antes de distribuir as anilhas pelas estações. Mantenha código e lote associados à especificação e à amostra. Essa rastreabilidade ajuda a pedir reposição e a separar problema de fabricação, transporte, armazenamento ou uso inadequado.")],
  "products-hub": [rich("proximo-passo", "Do catálogo à proposta", "Escolha uma categoria e transforme interesse em lista. Uma proposta útil depende de modelos, quantidades, sistema de peso, personalização e destino. Se ainda não conhece a composição ideal, envie público, área e canal de venda; a equipe pode organizar as perguntas comerciais sem substituir o projeto técnico local.")],
  "rubber-round-dumbbell": [
    rich("recebimento", "Recebimento, instalação e reposição", "Ao receber a linha, confira quantidade e peso por referência antes de colocar os halteres no rack. Compare pares, marcação, logo, superfície e empunhadura com a especificação. Pesos de até 100 kg exigem plano de movimentação seguro; a equipe local deve usar recursos adequados e evitar arrastar peças.", "Mantenha códigos e fotos da versão instalada. Para reposição, informe peso, sistema, acabamento, logo e lote quando disponível. Uma substituição visualmente diferente pode prejudicar a linha, por isso não use apenas a expressão “halter redondo” em pedidos futuros."),
    checklist("operacao", "Checklist operacional", ["Rack com capacidade e posições confirmadas", "Equipe preparada para peças pesadas", "Pares e marcações conferidos", "Rotina de limpeza definida", "Inspeção de união e superfície", "Código e versão guardados para reposição"])
  ],
  "pu-dumbbell": [
    rich("amostra", "Como avaliar a amostra de PU", "Observe a peça sob iluminação semelhante à academia ou ao showroom. Compare uniformidade, textura, transição entre revestimento e outros componentes, clareza da marcação e posição do logo. Meça peso e dimensões relevantes. Fotografe a referência sem filtros e registre a versão da arte.", "Teste o contato com o rack e o método de limpeza proposto em uma área discreta, seguindo orientação aplicável. A amostra não deve ser submetida a testes improvisados que não representem uso real. O objetivo é aprovar critérios que também possam ser verificados no lote."),
    rich("reposicao", "Consistência e reposição", "Linhas premium tornam diferenças de lote mais visíveis. Guarde amostra, referência de cor, código e especificação. Planeje quantidades de reposição e pergunte como pequenos lotes serão tratados. Se a cor ou o logo mudar, avalie o impacto sobre peças já instaladas ou em estoque.")
  ],
  "rubber-olympic-plate": [
    rich("comparacao-compra", "Como comparar propostas", "Peça que cada proposta informe pesos, dimensão interna, espessura, construção, tipo de inserto, marcação e embalagem. Compare o mesmo conjunto. Uma anilha mais barata pode ter perfil ou centro diferente; uma mais cara só se justifica quando a especificação e o uso sustentam a diferença.", "Solicite fotos do centro e das bordas, além da vista frontal. Se houver pegadas, avalie espaço e acabamento. Confirme o número de unidades por caixa e o peso bruto para estimar manuseio."),
    rich("recebimento", "Recebimento e teste de compatibilidade", "Separe uma amostra de cada peso, confira marcação e teste em barras representativas sem forçar o encaixe. Observe rebarbas e estabilidade. Compare quantidade e embalagem. Registre qualquer divergência antes de distribuir o lote pela academia ou revenda.", "Depois da instalação, crie uma rotina para verificar inserto, bordas, superfície e legibilidade. Mantenha anilhas organizadas por peso e não permita que unidades danificadas permaneçam misturadas ao estoque disponível. Registre a data e o lote recebido.")
  ],
  "dumbbells-guide": [rich("projeto-piloto", "Quando usar um projeto piloto", "Se a academia ou distribuidor ainda não conhece o material, um lote ou conjunto piloto pode ajudar a avaliar aceitação, limpeza, rack e apresentação, desde que respeite o MOQ. Defina período e critérios antes de comprar. Registre uso, reclamações, desgaste e pesos mais procurados. Esses dados são mais úteis para o segundo pedido do que impressões gerais e permitem ajustar faixa, quantidades e embalagem.")],
  "plates-guide": [rich("recebimento-pratico", "Conferência prática no recebimento", "Ao receber anilhas, selecione unidades de cada peso, confira marcação, centro, espessura e superfície, e teste compatibilidade com barras representativas. Compare quantidades com a lista e registre caixas danificadas. Para bumper plates, se houver teste de uso, ele deve seguir ambiente, barra, plataforma e procedimento definidos; quedas improvisadas não substituem inspeção nem documentação."), rich("reposicao", "Reposição e consistência", "Guarde código do modelo, versão do logo, cor e especificação. Em pedidos futuros, confirme se material, centro ou molde mudou. A reposição deve manter compatibilidade e leitura, mesmo quando pequenas variações aceitáveis de lote existirem.", "Revise o inventário periodicamente para identificar pesos faltantes, unidades com centro danificado e diferenças de sistema. Um registro simples evita que a academia compre reposições incompatíveis ou mantenha uma linha incompleta por muito tempo.")],
  "import-guide": [rich("cronograma-risco", "Cronograma e registro de riscos", "Monte um cronograma com datas dependentes: especificação antes de amostra, amostra antes da produção, QC antes da liberação e documentos antes do desembaraço. Adicione responsáveis e folga. Mantenha um registro de riscos com probabilidade, impacto e ação: atraso de material, mudança de arte, espaço insuficiente no contêiner, documento divergente ou indisponibilidade de descarga. A lista não elimina imprevistos, mas evita que problemas conhecidos sejam descobertos tarde.")],
  "import-cost-guide": [
    rich("sensibilidade", "Faça análise de sensibilidade", "Crie pelo menos três cenários para câmbio, frete e quantidade. Identifique quais componentes mais alteram o custo por SKU. Em produtos densos, uma mudança de frete ou limite de carga pode ser mais importante que pequena redução no preço unitário. Em racks, volume e montagem podem dominar.", "Não use o cenário otimista como orçamento único. Registre limites de aprovação: quanto a margem suporta e em que ponto o pedido deve ser revisto. Atualize cotações antes do depósito e antes do embarque quando necessário."),
    table("controle-custos", "Controle de premissas", ["Premissa", "Data", "Responsável", "Gatilho de revisão"], [["Câmbio", "Data da simulação", "Financeiro", "Antes de cada pagamento"], ["Frete", "Validade da tarifa", "Agente", "Antes da reserva"], ["Tributos", "Data da análise", "Despachante/contador", "Mudança de produto ou regra"], ["Volumes", "Versão do packing", "Fábrica", "Mudança de mix"], ["Entrega", "Data da cotação", "Operador local", "Mudança de destino"]]),
    rich("auditoria-planilha", "Revise a planilha antes da decisão", "Peça que uma segunda pessoa confira fórmulas, unidades e duplicidades. Diferencie quilograma, peça, par, caixa e conjunto. Verifique se frete ou seguro já aparece em outro item e se os valores usam a mesma moeda. Guarde propostas e versões para explicar por que o custo mudou.")
  ],
  "moq-guide": [
    rich("decisao", "Use uma árvore de decisão", "Primeiro pergunte se o produto padrão atende. Se sim, teste logo e embalagem existentes. Se não, identifique se a mudança é visual ou técnica. Para mudança visual, compare custo de setup com lote maior. Para mudança técnica, avalie ferramenta, amostra, teste e propriedade antes de discutir unidade.", "Em seguida, compare demanda de seis a doze meses, capacidade de estoque e capital. Se o MOQ exceder a demanda, reduza variantes, concentre pesos ou procure outro processo. Não aceite estoque excessivo apenas para atingir um preço unitário atraente."),
    rich("reposicao", "MOQ de reposição", "O primeiro lote e a reposição podem ter mínimos diferentes. Pergunte como pares perdidos, pesos isolados ou peças de rack serão fornecidos. Uma marca deve planejar estoque de serviço ou consolidar reposições em janelas. Registre a resposta na estratégia comercial."),
    table("perguntas-moq", "Perguntas para obter um MOQ real", ["Pergunta", "Evita"], [["O mínimo é por modelo, peso, cor ou pedido?", "Interpretação errada"], ["Qual opção usa processo existente?", "Desenvolvimento desnecessário"], ["Embalagem tem mínimo separado?", "Caixas sobrando ou custo oculto"], ["O MOQ muda na reposição?", "Linha incompleta"], ["Há custo de setup para lote menor?", "Negociação sem alternativa"]]),
    rich("exemplo-halteres", "Exemplo de raciocínio para uma linha de halteres", "Um comprador pode desejar vinte pesos, duas cores e caixa impressa. Antes de aceitar o mínimo resultante, deve perguntar se todos os pesos têm a mesma procura, se as duas cores precisam entrar juntas e se a caixa pode começar neutra. Concentrar a primeira compra nos pesos de maior giro reduz SKUs sem desmontar a proposta.", "Depois do lançamento, dados de venda e reposição indicam quais pesos ampliar. O segundo pedido pode usar um mix diferente, desde que modelo e versão permaneçam controlados. Essa abordagem transforma MOQ em planejamento de portfólio, e não apenas em obstáculo de negociação.")
  ],
  "oem-vs-odm-guide": [
    rich("governanca", "Governança do projeto", "Nomeie um responsável por requisitos e aprovação em cada empresa. Use reuniões com decisões registradas, não apenas mensagens. Mantenha lista de pendências, versão dos arquivos e data de congelamento. Defina o que acontece quando uma aprovação atrasa e como mudanças afetam preço e prazo.", "Para projetos técnicos, crie marcos: conceito, desenho, protótipo, validação, lote piloto e produção. Não pule um marco apenas porque a data de lançamento está próxima; registre o risco e a decisão."),
    rich("saida", "Planeje continuidade e saída", "Antes de investir, pergunte como obter reposição, arquivos e ferramentas se o relacionamento terminar. Defina estoque de peças, manutenção e uso de propriedade intelectual. Uma estratégia de saída não demonstra desconfiança; ela protege a continuidade da marca e esclarece responsabilidades."),
    rich("briefing-modelo", "Como escrever o briefing", "Descreva problema, usuário, ambiente, dimensões obrigatórias, materiais permitidos, identidade, quantidade, preço-alvo como referência e data desejada. Separe requisito obrigatório de preferência. Anexe desenhos somente com versão e unidades.", "Peça ao fornecedor que responda ponto a ponto: existente, adaptável, novo desenvolvimento ou inviável. Essa resposta revela se o projeto é realmente OEM, ODM ou híbrido e cria uma base para custo, amostra e cronograma."),
    rich("decisao-final", "Decisão final", "Escolha o modelo que oferece controle proporcional ao valor da diferenciação. Se o mercado ainda não foi validado, um OEM sobre produto existente pode reduzir incerteza. Se design exclusivo é central e há orçamento, equipe e contrato adequados, desenvolvimento mais amplo pode ser justificável. Documente por que a escolha foi feita.")
  ],
  "private-label-guide": [
    rich("conteudo-vendas", "Conteúdo e capacitação comercial", "Prepare fichas, páginas e treinamento que expliquem aplicação, especificação, manutenção e compatibilidade. Distribuidores precisam saber responder perguntas sem inventar benefícios. Use fotos do produto real e indique quando uma configuração é opcional.", "Crie um processo para atualizar conteúdo quando material, molde ou embalagem mudar. Marketing, vendas e pós-venda devem usar a mesma versão. Isso aumenta confiança e reduz promessas que a fábrica não documentou."),
    rich("pos-venda", "Pós-venda e aprendizado", "Defina canal para registrar problema, lote, foto e uso. Classifique ocorrências por fabricação, transporte, instalação, manutenção ou expectativa. Use dados para ajustar QC e conteúdo. Planeje peças e reposição antes de lançar, principalmente para linhas que precisam manter aparência uniforme."),
    table("metricas", "Métricas do primeiro lote", ["Métrica", "Uso"], [["Giro por SKU", "Ajustar mix e MOQ"], ["Perguntas recorrentes", "Melhorar conteúdo"], ["Danos de transporte", "Revisar embalagem"], ["Reposições", "Planejar estoque"], ["Prazo real", "Aprimorar cronograma"], ["Margem por linha", "Validar posicionamento"]]),
    rich("governanca-marca", "Governança da marca e dos arquivos", "Mantenha uma biblioteca com logos, cores, artes, especificações, fotos aprovadas e histórico de mudanças. Dê acesso controlado e identifique quem pode liberar produção. O fornecedor deve receber apenas a versão vigente.", "Antes de cada reposição, compare o pedido com a biblioteca. Confirme se embalagem, contato, marcação ou requisito local mudou. Essa revisão reduz divergências entre lotes e impede que um arquivo antigo retorne à produção."),
    rich("criterio-sucesso", "Defina sucesso antes do lançamento", "Estabeleça metas realistas de giro, margem, reclamações, prazo e reposição. Uma marca não é validada apenas porque o primeiro lote foi vendido; ela precisa sustentar produto, informação e atendimento. Revise as metas após o ciclo inicial e ajuste o próximo pedido com dados.")
  ],
  "hex-vs-round-guide": [
    rich("teste", "Como fazer uma comparação piloto", "Selecione pesos representativos de cada formato e use o rack previsto. Observe retirada, devolução, estabilidade, marcação, limpeza e preferência da equipe durante um período definido. Registre ocorrências e não dependa apenas de opinião. O piloto deve usar produtos comparáveis em material e qualidade.", "Para distribuição, mostre amostras a compradores e pergunte sobre faixa, preço e embalagem. O resultado pode justificar manter duas linhas ou concentrar uma."),
    table("rfq-comparativa", "RFQ comparativa", ["Campo", "Sextavado", "Redondo"], [["Faixa e incremento", "Preencher", "Preencher"], ["Material", "Preencher", "Preencher"], ["Dimensões por peso", "Solicitar", "Solicitar"], ["Rack", "Modelo/capacidade", "Modelo/capacidade"], ["Logo", "Método", "Método"], ["Embalagem", "Peso/caixa", "Peso/caixa"], ["Reposição", "Condição", "Condição"]]),
    rich("decisao-distribuidor", "Decisão para distribuidores", "Se o mercado compra por preço e versatilidade, uma linha sextavada pode facilitar entrada. Se clientes montam áreas completas e valorizam peso alto ou identidade contínua, redondos podem ampliar a oferta. Use consultas, vendas históricas e amostras para decidir.", "Evite duas linhas quase iguais competindo pelo mesmo comprador sem diferença clara. Defina público, faixa, material, embalagem e argumento de cada uma. Isso reduz estoque duplicado e torna a página de produto mais objetiva."),
    rich("resumo-compra", "Resumo para a cotação", "Peça preços para faixas equivalentes, racks compatíveis e a mesma personalização. Compare peso total, caixas, MOQ e reposição. Uma comparação por unidade isolada não mostra o investimento da área completa nem o custo de manter a linha organizada.")
  ],
  "materials-guide": [
    rich("protocolo-amostra", "Protocolo de avaliação de amostra", "Identifique amostra, material declarado, peso e data. Fotografe sob luz consistente. Meça peso e dimensões, observe superfície e união, confira logo e teste no rack. Registre odor inicial e após ventilação sem usar conclusões absolutas. Limpe apenas com método recomendado e observe alteração.", "Compare borracha, PU e TPU no mesmo ambiente e em pesos semelhantes. Não realize quedas ou exposição química improvisadas. Se durabilidade for crítica, combine método de teste e critérios com o fornecedor ou laboratório adequado."),
    table("score-material", "Scorecard de material", ["Critério", "Peso sugerido", "Evidência"], [["Aplicação", "Alta", "Briefing"], ["Superfície", "Média", "Amostra"], ["União", "Alta", "Processo e inspeção"], ["Manutenção", "Alta", "Instrução"], ["Logo", "Média", "Prova"], ["Custo total", "Alta", "Proposta e logística"], ["Reposição", "Alta", "Código e condição"]]),
    rich("recebimento-material", "Controle do material no lote", "Na inspeção, selecione unidades de pesos leves, médios e pesados. Compare cor, textura, transições, marcação e empunhadura. Registre defeitos por tipo e frequência, em vez de dizer apenas que o lote está “bom” ou “ruim”.", "Confirme que caixas e etiquetas identificam o material e o modelo. No recebimento, mantenha ventilação e limpeza adequadas, sem remover proteções antes da conferência. Guarde uma referência do lote para futuras reposições."),
    rich("alegacoes", "Evite alegações sem evidência", "Não anuncie material como atóxico, sem odor, reciclável, resistente a químicos ou superior por anos sem documentação aplicável. Marketing deve usar fatos do produto e instruções de manutenção. Se um ensaio for necessário, defina norma, laboratório, amostra e escopo com especialistas."),
    rich("decisao-material", "Decisão final de material", "Classifique critérios por importância e pontue amostras. Se duas opções atendem tecnicamente, use custo total, posicionamento e reposição para decidir. Registre a escolha e os limites; isso facilita explicar ao time comercial por que a linha usa borracha, PU ou TPU.")
  ],
  "olympic-vs-standard-guide": [
    rich("inventario", "Faça inventário antes de padronizar", "Liste barras, máquinas, suportes e anilhas atuais. Registre diâmetros, comprimentos, capacidades, estado e localização. Identifique itens sem informação e confirme com fabricante ou medição responsável. Esse inventário evita comprar um novo padrão que não conversa com a operação.", "Se a academia migrar para olímpico, planeje a transição. Separe equipamentos e sinalize. Não descarte anilhas padrão utilizáveis sem avaliar destino e segurança."),
    rich("recebimento", "Inspeção no recebimento", "Teste amostras de cada peso em barras representativas. O encaixe deve ocorrer sem forçar e sem rebarbas. Confira espessura, marcação, centro e quantidade. Em produtos com inserto, observe fixação. Registre lote e mantenha peças não conformes separadas.", "Para distribuição, inclua medida e compatibilidade na embalagem e na página. Isso reduz devoluções e perguntas. Não anuncie apenas “universal” sem evidência."),
    table("decisao-padrao", "Decisão de padrão", ["Pergunta", "Olímpico", "Padrão"], [["Já existe na academia?", "Manter compatibilidade", "Manter compatibilidade"], ["Projeto profissional novo?", "Geralmente maior variedade", "Somente com justificativa de mercado"], ["Levantamento?", "Necessário para bumper compatível", "Normalmente inadequado"], ["Mercado de revenda?", "Analisar demanda", "Analisar demanda local"], ["Reposição?", "Ampla, mas por modelo", "Pode ser mais restrita"]]),
    rich("erro-catalogo", "Como evitar erros de catálogo", "Use medida, sistema e construção no nome do produto. Inclua fotografia do centro, pesos disponíveis, espessura e barras compatíveis. Não copie descrições entre anilha olímpica, padrão e bumper. Cada página deve responder o uso e os limites do modelo.", "Para marca própria, revise códigos e etiquetas antes de imprimir. Uma embalagem com padrão incorreto gera devolução mesmo quando o produto foi produzido conforme outra especificação."),
    rich("planejamento-transicao", "Transição entre padrões", "Se uma rede troca de padrão, escolha unidades piloto e identifique equipamentos antigos. Treine equipe, separe armazenamento e comunique reposição. Não use adaptações improvisadas para acelerar a mudança.", "Planeje o destino dos produtos anteriores e atualize inventário, manutenção e páginas comerciais. A transição termina quando operação e estoque usam a mesma referência, não apenas quando o primeiro pedido chega."),
    rich("resumo-especificacao", "Resumo de especificação", "Toda compra deve registrar sistema, medida, tolerância, material, pesos, espessura, marcação e uso. Essa linha de dados deve aparecer na cotação, na inspeção e no catálogo. Quando os três documentos divergem, pause a liberação e corrija a versão antes do embarque.")
  ],
  "professional-gym-list-guide": [
    rich("fases", "Implantação em fases", "Divida o projeto em abertura, estabilização e expansão. Na abertura, garanta zonas essenciais, armazenamento e capacidade mínima. Depois, use dados de ocupação, filas e manutenção para comprar duplicações ou novas categorias. Reserve infraestrutura para expansão sem comprometer circulação.", "Defina gatilhos objetivos: taxa de uso de bancos, falta de pesos, crescimento de alunos ou demanda por modalidade. Evite comprar equipamento apenas porque apareceu em uma feira ou concorrente."),
    rich("validacao", "Validação com equipe e usuários", "Instrutores podem mapear exercícios e gargalos. Manutenção pode avaliar acesso e peças. Comercial pode explicar posicionamento. Combine essas perspectivas com dados e responsabilidade técnica. Uma preferência individual não deve definir todo o mix.", "Antes de fechar, faça uma revisão em planta com dimensões dos modelos reais. Confirme portas, elevadores, descarga e montagem. Equipamento que não entra no local não é uma especificação válida."),
    table("prioridade", "Matriz de prioridade", ["Critério", "Pergunta", "Classificação"], [["Necessidade", "Atende exercício ou capacidade essencial?", "Obrigatório/importante/opcional"], ["Uso", "Qual frequência esperada?", "Alta/média/baixa"], ["Espaço", "Cabe com circulação?", "Validado/pendente"], ["Manutenção", "Há suporte e peças?", "Preparado/risco"], ["Custo", "Inclui instalação e operação?", "Completo/parcial"], ["Expansão", "Pode ser duplicado depois?", "Sim/não"]]),
    rich("documentacao", "Documentos para implantação", "Mantenha planta aprovada, lista de equipamentos, fichas, instruções, contatos, garantias aplicáveis, registros de montagem e inspeção. Identifique número de série ou lote quando existir. Centralize arquivos para que operação e manutenção não dependam de uma pessoa.", "Crie um termo de aceite por zona. Registre itens pendentes, danos de transporte e correções. A abertura deve ocorrer somente quando responsáveis locais confirmarem que espaço e equipamentos estão prontos para uso."),
    rich("primeiros-noventa-dias", "Primeiros 90 dias", "Acompanhe filas, utilização, limpeza, falhas, reposições e feedback da equipe. Compare com premissas do projeto. Se pesos intermediários faltam, ajuste quantidade; se bancos bloqueiam circulação, revise operação com responsável técnico.", "Não use apenas número de alunos. Observe horários e zonas. Esses dados orientam segunda compra e reduzem expansão baseada em percepção."),
    rich("revisao-orcamento", "Revisão final do orçamento", "Antes de aprovar, separe custos obrigatórios, expansão e itens opcionais. Confirme frete, descarga, montagem, piso, instalações, treinamento e manutenção. Uma lista que cabe no preço de compra pode ultrapassar o orçamento quando implantação e operação ficam fora.", "Registre reservas e responsáveis. Se for necessário cortar, preserve segurança, circulação, armazenamento e capacidade essencial. Adie itens de baixa utilização em vez de remover componentes que tornam a área operável.")
  ],
  "free-weight-area-guide": [
    rich("sequencia", "Sequência de implantação", "Congele layout e modelos antes de marcar piso ou pontos de ancoragem. Confirme medidas reais, acesso e descarga. Instale piso e estruturas conforme projeto, monte racks e bancos e só então distribua pesos. Faça inspeção final de estabilidade, ferragens, superfícies e circulação.", "Treine equipe para organizar pesos, verificar danos e registrar manutenção. Abra a área com regras claras. Observe as primeiras semanas e ajuste sinalização e distribuição sem bloquear rotas."),
    rich("dados-operacao", "Use dados da operação", "Conte quantas vezes pesos e estações ficam indisponíveis no pico. Registre peças deixadas no piso, congestionamento e tempo de devolução. Esses dados mostram se faltam pares, suportes ou instrução. Também ajudam a planejar expansão.", "Analise manutenção e limpeza. Se um material marca o rack ou exige rotina difícil, ajuste processo antes de substituir toda a linha. Diferencie problema de layout, produto e comportamento."),
    table("aceite", "Checklist de aceite da área", ["Tema", "Verificação"], [["Layout", "Rotas e zonas conforme projeto"], ["Racks", "Estáveis, identificados e compatíveis"], ["Pesos", "Quantidade, marcação e pares"], ["Piso", "Instalado conforme especificação local"], ["Montagem", "Ferragens e ajustes conferidos"], ["Sinalização", "Uso e devolução claros"], ["Manutenção", "Responsáveis e frequência definidos"], ["Documentação", "Modelos, lotes e contatos arquivados"]]),
    rich("limpeza", "Planejamento de limpeza", "Deixe acesso para limpar sob racks e ao redor de plataformas. Defina produtos compatíveis com borracha, PU, metal e piso. Evite borrifar diretamente sobre componentes e não misture produtos sem orientação.", "A frequência deve acompanhar uso e ambiente. Registre manchas, odor ou corrosão e investigue causa. Uma rotina agressiva pode danificar acabamento tanto quanto falta de limpeza."),
    rich("expansao-area", "Expansão sem perder circulação", "Reserve pontos para novos pares, bancos ou suportes, mas não deixe áreas indefinidas virarem depósito. Quando demanda crescer, atualize layout e capacidade. Duplicar pesos populares pode resolver gargalo com menos impacto que adicionar outra estação.", "Toda mudança deve ser validada com medidas reais e responsáveis locais. Mover rack ou plataforma pode alterar rota, piso e segurança. Atualize inventário e sinalização depois da expansão."),
    rich("responsaveis", "Defina responsáveis", "Nomeie responsáveis por abertura, inspeção diária, manutenção, limpeza e reposição. Documente como interditar um item e quem autoriza retorno ao uso. Sem essa rotina, até um layout bem planejado perde organização e segurança com o tempo.")
  ]
};
