import type { SpanishPage } from "./es-types";
import { checklist, definition, quick, rich, spanishEditorialAuthor, spanishTechnicalReviewer, table } from "./es-content-helpers";

const author = spanishEditorialAuthor;
const reviewer = spanishTechnicalReviewer;
const common = {
  author,
  reviewedBy: reviewer,
  updatedAt: "2026-07-17T08:00:00.000Z",
  publishedAt: "2026-07-17T08:00:00.000Z"
};

export const seoExpansionSpanishPages: SpanishPage[] = [
  {
    id: "racks-benches-category",
    type: "product_category",
    esPath: "/es/productos/racks-y-bancos",
    title: "Racks y bancos de gimnasio al por mayor y OEM | PowerBaseFit",
    description: "Racks, jaulas, máquinas Smith y bancos profesionales de fábrica, con OEM, marca propia, control de calidad y embalaje para importadores.",
    h1: "Racks y bancos profesionales para gimnasios y distribuidores",
    image: ["/assets/racks-benches.webp", "Rack y banco profesional para gimnasio comercial"],
    blocks: [
      quick("respuesta-rapida", "PowerBaseFit suministra racks, jaulas, estaciones funcionales, máquinas Smith y bancos para compradores B2B. La selección debe relacionar uso, espacio, carga prevista, ajustes, montaje, embalaje y soporte local. La oferta confirma las dimensiones, capacidades y componentes del modelo real; no se deben deducir especificaciones únicamente de una fotografía."),
      definition("definicion", "Racks y bancos de gimnasio", "Son estructuras y estaciones que soportan barras, organizan cargas o colocan al usuario para ejercicios de fuerza. En una compra profesional, estabilidad, geometría, ajustes, capacidad, acabado, montaje y compatibilidad forman parte de la especificación y de la inspección."),
      table("tipos", "Tipos de racks y bancos", ["Categoría", "Aplicación", "Qué confirmar"], [
        ["Power rack o jaula", "Sentadilla, press y peso libre", "Medidas, perforaciones, seguros y accesorios"],
        ["Máquina Smith", "Movimiento guiado y musculación", "Recorrido, guías, bloqueos, contrapeso y carga"],
        ["Entrenador funcional", "Trabajo con cables", "Relación de poleas, recorrido, placas y accesorios"],
        ["Banco ajustable", "Press plano e inclinado y mancuernas", "Ángulos, mecanismo, tapizado, ruedas y capacidad"],
        ["Banco fijo", "Estaciones dedicadas", "Altura, base, apoyo y uso"],
        ["Almacenamiento", "Barras, discos y mancuernas", "Compatibilidad, carga y circulación"]
      ]),
      rich("planificacion", "Planificación de una zona profesional", "Empiece con el plano, el número de usuarios y los ejercicios. Reserve circulación, espacio para cargar la barra y distancia entre estaciones. El área ocupada durante el entrenamiento es mayor que la huella del equipo: bancos, puertas, brazos, cables y discos se desplazan.", "El distribuidor debe diferenciar claramente la línea comercial y documentar piezas, herrajes y manuales. El gimnasio debe comprobar suelo, altura, acceso, montaje y requisitos locales. PowerBaseFit aporta información de producto; el diseño del recinto, la instalación, el anclaje y las revisiones de seguridad corresponden a profesionales responsables en destino."),
      rich("construccion", "Estructura, acabado y componentes", "Los modelos pueden combinar tubos y chapa de acero, piezas mecanizadas, cables, poleas, guías, rodamientos, tapizado, goma y fijaciones. Términos como “acero reforzado” no sustituyen sección, espesor, dimensiones, capacidad y método de montaje.", "Revise preparación de la superficie, pintura, soldaduras visibles, bordes y zonas de contacto. En bancos, compruebe base, holguras, mecanismo, densidad y revestimiento. En estaciones con cable, confirme terminales, alineación, relación de poleas y recorrido en la documentación o muestra."),
      checklist("qc", "Checklist de control de calidad", ["Modelo y dimensiones", "Geometría, alineación y estabilidad", "Soldaduras y pintura", "Bloqueos, pasadores y ajustes", "Cables, poleas y guías", "Tapizado, costuras y apoyo", "Herrajes, manual e identificación", "Volúmenes y protección de embalaje"]),
      rich("oem", "OEM, colores y marca propia", "La personalización puede incluir color, logotipo, etiquetas, tapizado y embalaje según modelo y cantidad. Archivo, referencia de color, posición y método se aprueban antes de producir. Cambiar dimensiones o estructura es un desarrollo distinto de aplicar una identidad visual y puede modificar MOQ, herramienta y plazo.", "Una solicitud útil incluye modelos, cantidades, mercado, colores, logotipo, embalaje, destino y requisitos eléctricos cuando sean aplicables. El MOQ se confirma después de revisar esa combinación; no existe una única cantidad mínima para toda la categoría."),
      rich("logistica", "Embalaje, montaje y transporte", "Racks y bancos consumen volumen. Pueden enviarse desmontados o parcialmente montados, por lo que piezas, herrajes y cajas deben estar identificados. Pintura, guías, tapizado y componentes móviles necesitan separación para evitar rozaduras.", "Compare volumen, peso bruto, número de bultos, palés y secuencia de descarga. Planifique acceso, herramientas, equipo de montaje y comprobación en destino. La condición comercial define el alcance del transporte; impuestos, instalación y requisitos locales se calculan para cada país."),
      checklist("cotizacion", "Datos para solicitar cotización", ["Empresa, país y canal", "Modelos y cantidades", "Plano y espacio", "Uso y usuarios", "Dimensiones y capacidad", "Color, logotipo y tapizado", "Embalaje, montaje y manual", "Destino, condición comercial y plazo"])
    ],
    faq: [["¿Cómo elegir un rack para gimnasio profesional?", "Relacione ejercicios, usuarios, espacio, barras y discos; después compare medidas, estructura, seguros, ajustes, accesorios, montaje e inspección."], ["¿Se pueden personalizar racks y bancos?", "Sí, según modelo y cantidad. Se pueden evaluar color, logotipo, etiquetas, tapizado y embalaje."], ["¿Cuál es el MOQ?", "Depende de modelos, configuración y personalización. Se confirma tras revisar la lista."], ["¿Llegan montados?", "Depende del producto y del embalaje. La oferta debe indicar bultos, nivel de montaje y herrajes."], ["¿Cómo se inspeccionan?", "Con criterios de medidas, alineación, superficie, ajustes, componentes, cantidades y embalaje definidos antes de producir."]],
    links: [["products-hub", "Ver todos los equipos"], ["dumbbells-category", "Mancuernas profesionales"], ["weight-plates-category", "Discos de peso"], ["factory", "Conocer la fábrica"], ["oem-private-label", "OEM y marca propia"], ["contact", "Solicitar cotización"]],
    ...common
  },
  {
    id: "gym-accessories-category",
    type: "product_category",
    esPath: "/es/productos/accesorios-de-gimnasio",
    title: "Accesorios de gimnasio al por mayor y marca propia | PowerBaseFit",
    description: "Accesorios de musculación y entrenamiento funcional para distribuidores, con selección B2B, OEM, QC, embalaje y suministro directo de fábrica.",
    h1: "Accesorios de gimnasio al por mayor para compradores B2B",
    image: ["/assets/gym-accessories.webp", "Accesorios profesionales de musculación y entrenamiento funcional"],
    blocks: [
      quick("respuesta-rapida", "La gama de PowerBaseFit incluye kettlebells, agarres para cable, cuerdas, barras, esterillas, balones y artículos funcionales según el catálogo vigente. Para mayoristas o marcas, el surtido debe organizarse por uso, material, pesos, compatibilidad, embalaje y rotación comercial; una lista amplia sin función definida aumenta inventario y errores."),
      definition("definicion", "Accesorios de gimnasio al por mayor", "Son artículos adquiridos en cantidad por distribuidores, importadores, tiendas o gimnasios para complementar musculación y entrenamiento funcional. Cada referencia necesita cantidad, material, medida, color, embalaje y criterio de calidad. “Accesorio fitness” describe un grupo, no una especificación."),
      table("surtido", "Cómo organizar el surtido", ["Grupo", "Ejemplos", "Decisión de compra"], [
        ["Kettlebells", "Hierro fundido, vinilo y competición", "Pesos, asa, base, superficie y marcado"],
        ["Agarres de cable", "Barras, manerales, cuerdas y juegos", "Conexión, ancho, giro, recubrimiento y carga"],
        ["Entrenamiento funcional", "Balones, tubos y plataformas", "Material, medida, uso, almacenamiento y caja"],
        ["Yoga y movilidad", "Esterillas y pelotas", "Espesor, textura, material y olor"],
        ["Venta complementaria", "Artículos asociados al equipo principal", "Margen, reposición, volumen y presentación"]
      ]),
      rich("seleccion", "Selección para gimnasios y distribución", "El gimnasio debe asociar cada accesorio con estaciones y clases reales. Los agarres deben coincidir con cables y mosquetones; los kettlebells requieren rango y almacenamiento; esterillas y balones necesitan limpieza y espacio. Un lote genérico puede dejar productos sin uso.", "El distribuidor debe evaluar nivel de precio, volumen, protección, etiquetado y reposición. Los artículos pequeños pueden completar una carga, pero aumentan referencias y control. La solicitud debe indicar cantidades por SKU, no solo un total estimado."),
      rich("materiales", "Materiales y datos técnicos", "La categoría combina hierro, acero, goma, vinilo, TPE, plásticos, espuma, tejidos y componentes de rotación. Confirme peso, dimensiones, tolerancia, dureza o espesor cuando proceda, acabado, uniones y compatibilidad.", "En agarres, revise soldaduras, ejes, giro, superficie y conexión. En kettlebells, peso, asa, base y recubrimiento. En esterillas y balones, material, medida, textura, válvula cuando exista y embalaje. La ficha y la muestra deben corresponder a la referencia cotizada."),
      checklist("qc", "Control por lote", ["Referencia, color y cantidad", "Peso y dimensiones", "Superficie, olor y acabado", "Uniones, costuras, válvulas o giro", "Compatibilidad", "Logotipo y etiqueta", "Unidades y peso por caja", "Protección contra deformación y roce"]),
      rich("oem", "Marca propia y presentación", "Se pueden evaluar logotipo, colores, etiquetas, manual y embalaje según producto, método y cantidad. El área disponible cambia entre una barra, un kettlebell y una esterilla; el arte debe comprobarse en el artículo real.", "El MOQ puede aplicarse por modelo, color, peso o proceso. Combinar referencias no elimina automáticamente cada mínimo. PowerBaseFit revisa el surtido y confirma muestra, personalización, producción y embalaje."),
      rich("coste", "Embalaje y coste total", "Los accesorios mezclan artículos densos, frágiles, flexibles y voluminosos. Kettlebells requieren cajas resistentes; metal y superficies pintadas necesitan separación; artículos flexibles no deben deformarse. El plan indica unidades, dimensiones y peso bruto.", "El coste de importación incluye producto, personalización, muestra, inspección, transporte, seguro cuando corresponda, despacho, impuestos, almacenaje y entrega. PowerBaseFit aporta datos del producto y carga; clasificación y cumplimiento deben validarse en España, México, Colombia, Chile, Argentina u otro destino."),
      rich("catalogo", "Gestión del catálogo y reposición", "Asigne un código estable a cada combinación de modelo, medida, peso y color. Conserve fotografía, ficha, arte y datos de caja aprobados para que ventas, almacén y proveedor hablen de la misma referencia. Antes de ampliar el surtido, revise rotación, devoluciones, piezas compatibles y disponibilidad de reposición.", "Para una marca propia, mantenga reglas comunes de nombre, etiqueta, advertencias e identidad visual sin ocultar diferencias técnicas. Una segunda compra debe confirmar si materiales, moldes, colores o embalajes han cambiado. Esta disciplina reduce mezclas de lote y permite explicar al cliente profesional exactamente qué está comprando."),
      checklist("rfq", "Checklist para cotizar", ["Canal y país", "Referencias y cantidades", "Pesos, medidas y compatibilidad", "Material y acabado", "Color, logo y embalaje", "Etiqueta e idioma", "Muestra e inspección", "Destino y condición comercial"])
    ],
    faq: [["¿Qué accesorios se pueden comprar al por mayor?", "El catálogo incluye kettlebells, agarres, artículos funcionales, esterillas, balones y otras referencias cuya disponibilidad se confirma al cotizar."], ["¿Puedo combinar productos?", "Sí, sujeto a MOQ y embalaje por referencia."], ["¿Se admite marca propia?", "Se pueden evaluar logotipo, color, etiqueta y embalaje según producto y cantidad."], ["¿Cómo se comprueba un agarre de cable?", "Confirme conexión, dimensiones, movimiento, equipo y carga; use muestra cuando la compatibilidad sea crítica."], ["¿El precio incluye importación?", "No necesariamente. Compare la condición comercial y calcule los costes en destino."]],
    links: [["products-hub", "Equipos profesionales"], ["dumbbells-category", "Mancuernas"], ["weight-plates-category", "Discos"], ["factory", "Proceso de fábrica"], ["oem-private-label", "Marca propia"], ["contact", "Cotizar accesorios"]],
    ...common
  },
  {
    id: "rubber-hex-dumbbell-manufacturer",
    type: "landing",
    esPath: "/es/fabricante/mancuernas-hexagonales-de-goma",
    title: "Fabricante de mancuernas hexagonales de goma OEM | PowerBaseFit",
    description: "Fabricante de mancuernas hexagonales de goma de 2,5 a 50 kg para mayoristas, importadores y marca propia, con OEM, QC y embalaje.",
    h1: "Fabricante de mancuernas hexagonales de goma para compradores B2B",
    image: ["/assets/products/dumbbells/catalog-v2/hex-dumbbell-kg.webp", "Fabricación de mancuerna hexagonal de goma con marca propia"],
    blocks: [
      quick("respuesta-rapida", "PowerBaseFit fabrica el modelo Rubber Hex Dumbbell en un rango publicado de 2,5 a 50 kg, con incrementos de 2,5 kg. Distribuidores, importadores y marcas pueden solicitar evaluación de logotipo, marcado, color y embalaje. La oferta final confirma construcción, pesos, unidades, tolerancias, muestra, MOQ, control y condición de entrega."),
      definition("definicion", "Fabricante de mancuernas hexagonales de goma", "Es la empresa que produce mancuernas con cabezas de seis lados recubiertas de goma y empuñadura metálica conforme a una especificación de peso, superficie, identificación y embalaje. Un fabricante B2B debe vincular muestra, documentación e inspección con el modelo cotizado."),
      table("especificacion", "Referencia técnica", ["Elemento", "Referencia publicada", "Qué confirmar"], [
        ["Producto", "Rubber Hex Dumbbell", "Código y versión"], ["Rango", "2,5–50 kg", "Pesos y unidades"], ["Incremento", "2,5 kg en el modelo kg", "Surtido del mercado"], ["Construcción", "Cabeza hexagonal recubierta y mango metálico", "Unión, textura y acabado"], ["Identificación", "Peso y logo sujetos a viabilidad", "kg/lb, posición y muestra"], ["Embalaje", "Según peso y carga", "Protección, caja y palé"]
      ]),
      rich("aplicacion", "Aplicación comercial", "La forma reduce el rodamiento al dejar la mancuerna en el suelo y se utiliza en gimnasios, estudios, hoteles, distribución y marca propia. Deben considerarse ejercicios, intensidad, rack, suelo, limpieza y reposición. La geometría no permite impactos incontrolados ni sustituye normas de uso.", "El mayorista planifica unidades por peso según rotación. El gimnasio considera usuarios en hora punta y repite pesos intermedios cuando sea necesario. La misma cantidad para todo el rango no siempre es la combinación más eficiente."),
      rich("fabricacion", "Proceso de fabricación", "El flujo comienza con modelo, materiales, empuñadura, pesos, marcado y embalaje aprobados. Se preparan componentes; las cabezas se forman según la construcción; la empuñadura se mecaniza y texturiza cuando corresponde; después se realizan unión, recubrimiento, acabado, limpieza e identificación.", "Los parámetros dependen del modelo. La muestra y la ficha aprobada son referencias del lote. Cambios posteriores en goma, dureza, color, mango, logo o embalaje pueden afectar producción e inspección."),
      checklist("qc", "Puntos de inspección", ["Modelo, peso y cantidad", "Tolerancia acordada", "Forma y estabilidad", "Unión cabeza-empuñadura", "Diámetro, textura y alineación", "Superficie, olor, color y acabado", "Marcado y logotipo", "Protección y peso por caja"]),
      rich("oem", "OEM, ODM y marca propia", "Se pueden evaluar logotipo, kg o lb, colores y embalaje. Una personalización visual sobre el modelo existente es distinta de cambiar forma, material o herramienta. La fábrica confirma viabilidad después de revisar archivos, cantidades y mercado.", "Envíe el logo vectorial, referencias de color, tamaño, pesos y unidades. La muestra verifica proporción en distintos tamaños. Un cambio estructural u ODM requiere evaluación técnica y no se promete sin revisión."),
      rich("moq", "MOQ, muestra y compra", "No existe un MOQ universal. Depende de pesos, método de marca, embalaje y programación; pueden existir mínimos por peso, color o proceso. Una solicitud clara incluye empresa, país, canal, rango, unidades, logo, destino y plazo.", "Compare propuestas con la misma especificación, muestra, control y condición comercial. Un precio unitario sin explicar construcción, tolerancia y embalaje no permite evaluar el coste ni el riesgo."),
      rich("exportacion", "Embalaje y exportación", "Las mancuernas concentran masa y pueden marcarse durante el movimiento. El embalaje separa superficies, limita peso por caja, identifica referencias y forma palés adecuados. La carga equilibra peso, volumen y descarga.", "PowerBaseFit aporta datos de producto y preparación de exportación. Transporte, seguro, clasificación, impuestos y despacho dependen de la ruta y deben validarse con profesionales del país de destino."),
      checklist("proveedor", "Checklist para evaluar al fabricante", ["Modelo identificado", "Rango disponible", "Muestra vinculada", "QC mensurable", "Logo y embalaje definidos", "MOQ explicado", "Datos de carga", "Condición comercial documentada"])
    ],
    faq: [["¿PowerBaseFit fabrica mancuernas hexagonales?", "Sí. Rubber Hex Dumbbell forma parte de su gama de peso libre para proyectos B2B."], ["¿Qué rango está disponible?", "El modelo kg publicado cubre de 2,5 a 50 kg en incrementos de 2,5 kg."], ["¿Puedo importarlas con mi marca?", "Sí, sujeto a revisión de logo, método, pesos, cantidades, muestra, MOQ y embalaje."], ["¿Cómo se controla el peso?", "Se acuerda una tolerancia y se aplica el plan de comprobación definido para el lote."], ["¿El MOQ es por peso?", "Puede depender del peso, color o proceso. Se confirma con la combinación completa."], ["¿Qué datos necesita la cotización?", "Pesos, unidades, mercado, logo, embalaje, destino y plazo."]],
    links: [["rubber-hex-dumbbell", "Ver la mancuerna hexagonal"], ["dumbbells-category", "Comparar mancuernas"], ["oem-private-label", "Marca propia"], ["factory", "Fabricación y QC"], ["factory-guide", "Evaluar una fábrica"], ["contact", "Solicitar cotización"]],
    ...common
  },
  {
    id: "dumbbells-guide",
    type: "blog",
    esPath: "/es/blog/como-elegir-mancuernas-para-gimnasio-profesional",
    title: "Cómo elegir mancuernas para un gimnasio profesional | Guía B2B",
    description: "Guía B2B para elegir mancuernas por forma, material, rango, agarre, rack, QC, OEM, embalaje y proveedor para un gimnasio profesional.",
    h1: "Cómo elegir mancuernas para un gimnasio profesional",
    image: ["/assets/hex-dumbbells.webp", "Mancuernas profesionales organizadas en un rack de gimnasio"],
    blocks: [
      quick("respuesta-rapida", "Para elegir mancuernas profesionales, defina primero usuarios, ejercicios, rango, pares repetidos, espacio y mantenimiento. Después compare forma, material, unión, empuñadura, tolerancia, identificación y rack. En una compra B2B, añada muestra, criterios de QC, reposición, marca propia, embalaje y coste total; el modelo más vistoso no siempre es el más adecuado."),
      definition("definicion", "Mancuerna profesional", "Es una pesa manual especificada para uso repetido en instalaciones o distribución comercial. Su idoneidad depende de construcción, unión, superficie, empuñadura, tolerancia, almacenamiento y mantenimiento. La palabra “profesional” por sí sola no demuestra capacidad ni durabilidad."),
      rich("necesidades", "1. Empiece por el gimnasio y sus usuarios", "Registre tipo de instalación, aforo, horas punta, experiencia de usuarios, ejercicios, suelo, limpieza y espacio. Un hotel puede priorizar presentación y pesos ligeros; una sala de fuerza necesita rango alto, reposición y circulación; un estudio puede requerir incrementos más próximos y menos pares pesados.", "Calcule cuántas personas usarán el mismo peso simultáneamente. Los pesos ligeros e intermedios suelen repetirse más; los pesados necesitan almacenamiento y manipulación. No copie una lista estándar sin relacionarla con el programa real."),
      table("comparacion", "Comparación de formatos y materiales", ["Opción", "Ventaja habitual", "Riesgo o verificación"], [
        ["Hexagonal de goma", "Reduce rodamiento y sirve en ejercicios de suelo", "Unión, olor, superficie, mango y rack"],
        ["Redonda de goma", "Gama continua y presentación en rack", "Rodamiento, diámetro, unión y pesos altos"],
        ["Cromada", "Formato compacto y apariencia metálica", "Humedad, limpieza, marcas y almacenamiento"],
        ["PU", "Acabado uniforme para posicionamiento premium", "Formulación real, color, dureza y coste"],
        ["TPU", "Alternativa técnica según construcción", "Muestra, composición, unión y reposición"],
        ["Ajustable", "Ahorra espacio en ciertos entornos", "Mecanismo, cambios, mantenimiento y uso intensivo"]
      ]),
      rich("rango", "2. Diseñe el rango de pesos", "Defina unidad kg o lb y no mezcle sistemas sin una razón comercial. Establezca peso mínimo, máximo e incremento. Para un gimnasio generalista, el rango debe cubrir calentamiento, fuerza básica y progresión; una instalación especializada tendrá otra distribución.", "Asigne más pares a pesos con mayor uso esperado. Relacione el número total con longitud y capacidad del rack. Añada margen para retirar una pieza dañada sin dejar un ejercicio sin alternativa y acuerde cómo comprar reposiciones compatibles."),
      rich("ergonomia", "3. Revise empuñadura, unión y dimensiones", "Compare diámetro, longitud, moleteado, transición y alineación. Una empuñadura demasiado agresiva puede resultar incómoda; una superficie insuficiente puede dificultar el agarre. El criterio depende de usuarios y aplicación, no de una frase comercial.", "Pregunte cómo se une la cabeza a la empuñadura y qué se comprobará. Observe holguras, giro, alineación y consistencia entre pesos. En cabezas redondas, revise diámetro y espacio; en hexagonales, estabilidad de las caras y contacto con el rack."),
      rich("material", "4. Evalúe material y mantenimiento", "Goma, PU, TPU y metal deben evaluarse en el producto real. Compare olor, textura, dureza, uniformidad, resistencia a marcas y método de limpieza. Dos proveedores pueden utilizar el mismo nombre con formulaciones y espesores diferentes.", "Defina productos de limpieza compatibles, ventilación inicial, inspección diaria y almacenamiento. El rack debe apoyar la mancuerna sin dañar superficie ni empuñadura. La instalación debe retirar piezas con unión suelta, grietas o daños que comprometan el uso."),
      checklist("muestra", "Checklist para evaluar una muestra", ["Peso y tolerancia", "Dimensiones y estabilidad", "Diámetro y textura del mango", "Unión y alineación", "Olor, superficie y color", "Marcado kg/lb", "Logotipo en pesos pequeños y grandes", "Contacto con rack y suelo", "Caja, protección y etiqueta"]),
      rich("proveedor", "5. Compare proveedores con la misma especificación", "Envíe una tabla idéntica a cada proveedor: modelo, construcción, pesos, cantidades, tolerancias, logo, muestra, inspección, caja y condición comercial. Pregunte qué fabrica, qué subcontrata y qué evidencia puede relacionar con el producto cotizado.", "No elija únicamente por precio. Una oferta puede omitir muestra, molde, embalaje, palés o controles. Confirme plazo desde la aprobación y el depósito, tratamiento de no conformidades y disponibilidad de reposición. La comunicación técnica antes del pedido es un indicador práctico de cómo se gestionarán cambios."),
      table("coste", "Componentes del coste total", ["Componente", "Pregunta", "Impacto"], [
        ["Producto", "¿Es la misma construcción y rango?", "Precio base"], ["Personalización", "¿Incluye logo, kg/lb y muestra?", "Herramienta y preparación"], ["QC", "¿Qué inspección está incluida?", "Riesgo de aceptación"], ["Embalaje", "¿Unidades y peso por caja?", "Daño y manipulación"], ["Transporte", "¿Qué Incoterm y destino?", "Comparación logística"], ["Importación", "¿Qué impuestos y gastos locales?", "Coste puesto en almacén"], ["Reposición", "¿Puede repetirse la especificación?", "Coste durante la vida útil"]
      ]),
      rich("oem", "6. Planifique OEM y marca propia", "Defina archivo vectorial, posición, color, kg/lb, etiqueta y embalaje. Compruebe el logo en referencias pequeñas y grandes. Una muestra de un solo peso no siempre demuestra la proporción en toda la gama.", "Diferencie personalización visual de cambio estructural. Si se modifica forma, material o herramienta, documente nueva muestra, coste, MOQ y calendario. No publique promesas de certificación o rendimiento que el proveedor no haya demostrado."),
      rich("implantacion", "7. Planifique recepción e implantación", "Antes de la llegada, cierre la distribución del rack, capacidad del suelo, pasillos y método de descarga. Prepare una lista de recepción con bultos, pares y pesos esperados. Las cajas densas requieren medios de manipulación y un orden que evite mover repetidamente toda la gama. No coloque las mancuernas en servicio hasta comprobar daños, identificación y estabilidad.", "Durante las primeras semanas, registre qué pesos se usan a la vez, qué piezas requieren limpieza adicional y si el rack genera marcas. Esa información permite ajustar duplicados y mantenimiento en la siguiente compra. Para distribución, registre consultas, devoluciones y demanda por peso; una reposición basada en datos suele ser más eficiente que repetir exactamente el primer pedido.", "Conserve muestra aprobada, ficha, fotografías, informe y arte. Si el proveedor cambia material, empuñadura, método de logo o caja, solicite confirmación antes de aceptar que la referencia sigue siendo equivalente. La consistencia del suministro es parte del valor B2B."),
      rich("experiencia", "Información de primera parte de PowerBaseFit", "PowerBaseFit trabaja con mancuernas y otros productos de peso libre desde su fábrica en Dezhou, Shandong. En las conversaciones de compra, la información que más reduce aclaraciones es una tabla por peso con unidades, mercado, logo, embalaje y destino. Sin esa tabla, el precio y el MOQ pueden interpretarse de forma distinta.", "Para el modelo hexagonal kg publicado, la gama es 2,5–50 kg en incrementos de 2,5 kg. Ese dato pertenece a ese modelo y no debe extrapolarse a toda mancuerna. La fábrica revisa configuración, muestra, producción, control y carga para el pedido concreto."),
      checklist("decision", "Checklist final del comprador", ["Uso, usuarios y hora punta", "Forma y material", "Rango, incrementos y pares", "Empuñadura y unión", "Rack, suelo y limpieza", "Muestra y tolerancias", "Logo y embalaje", "QC y no conformidades", "Coste total y reposición", "Documentación de la oferta"])
    ],
    faq: [["¿Qué tipo de mancuerna es mejor para un gimnasio?", "Depende de uso, usuarios, espacio y mantenimiento. La hexagonal de goma es versátil y estable; la redonda crea gamas continuas; PU, TPU y cromo responden a otros posicionamientos."], ["¿Cuántos pares necesita un gimnasio?", "Calcule usuarios simultáneos, rango, repetición de pesos populares, rack y reposición. No existe una cifra universal."], ["¿Goma o PU?", "Compare muestras por formulación, superficie, olor, construcción, mantenimiento, presentación y coste total."], ["¿Cómo se controla la precisión?", "Defina tolerancia y plan de muestreo antes de producir; registre equipos y criterios de aceptación."], ["¿Puedo usar mi marca?", "Sí, según modelo, método, cantidad y muestra. Verifique el diseño en varios pesos."], ["¿Qué información necesita el proveedor?", "Modelo, pesos, unidades, uso, logo, embalaje, inspección, destino y plazo."]],
    links: [["dumbbells-category", "Ver mancuernas profesionales"], ["rubber-hex-dumbbell", "Mancuerna hexagonal"], ["chrome-dumbbell", "Mancuerna cromada"], ["hex-vs-round-guide", "Comparar hexagonal y redonda"], ["materials-guide", "Comparar goma, PU y TPU"], ["oem-private-label", "Marca propia"], ["contact", "Solicitar cotización"]],
    ...common
  },
  {
    id: "plates-guide",
    type: "blog",
    esPath: "/es/blog/discos-de-peso-vs-discos-bumper",
    title: "Discos de peso vs discos bumper: guía para compradores B2B",
    description: "Compare discos olímpicos, discos de hierro y bumper por uso, material, espesor, suelo, tolerancia, OEM, embalaje y coste de importación.",
    h1: "Discos de peso o discos bumper: cómo elegir para un gimnasio",
    image: ["/assets/weight-plate.webp", "Discos de peso y discos bumper para gimnasio profesional"],
    blocks: [
      quick("respuesta-rapida", "Elija discos bumper cuando el entrenamiento incluya levantamientos con contacto planificado con una plataforma adecuada; elija discos convencionales cuando predominen musculación, máquinas o ejercicios sin caída. Confirme barra, diámetro interior, espesor, material, tolerancia, rebote, suelo, almacenamiento y coste logístico. “Olímpico” describe compatibilidad; no significa automáticamente “bumper”."),
      definition("definicion", "Disco bumper", "Es un disco de diámetro exterior uniforme y cuerpo predominantemente de goma o caucho, con inserto central, diseñado para levantamientos en los que puede existir contacto controlado con una plataforma apropiada. No elimina la necesidad de suelo, técnica, supervisión y límites de uso."),
      rich("diferencia", "1. La diferencia principal es la aplicación", "Los discos convencionales pueden ser de hierro, acero o construcciones recubiertas y se usan con barras, máquinas y estaciones de fuerza. Los bumper priorizan una construcción capaz de gestionar de otra forma el contacto con el suelo. La decisión debe partir del programa de entrenamiento, no de la tendencia visual.", "Si la barra nunca debe caer, un disco convencional puede ofrecer menor espesor y buen aprovechamiento de carga. Si se practican levantamientos olímpicos o movimientos con descenso controlado, un bumper compatible puede ser adecuado, siempre con plataforma, reglas y mantenimiento."),
      table("comparacion", "Comparación para compra profesional", ["Criterio", "Disco convencional", "Disco bumper"], [
        ["Uso", "Musculación, máquinas y fuerza sin caída", "Levantamiento y funcional con contacto planificado"],
        ["Material", "Metal o construcción recubierta", "Cuerpo de goma/caucho e inserto"],
        ["Diámetro", "Puede variar con peso y modelo", "Normalmente uniforme dentro de la línea"],
        ["Espesor", "Suele aprovechar mejor la manga", "Los pesos ligeros pueden ser más gruesos"],
        ["Ruido e impacto", "Depende del material y uso", "Gestiona mejor el contacto, no lo elimina"],
        ["Suelo", "Requiere protección y almacenamiento", "Requiere plataforma o suelo apropiado"],
        ["Coste", "Depende de material y acabado", "Depende de goma, inserto, dureza y tolerancia"]
      ]),
      rich("compatibilidad", "2. Confirme barra, centro y espesor", "Mida la manga y confirme el estándar del disco. Un producto anunciado como olímpico debe corresponder a la barra real. Revise diámetro interior, inserto, holgura y facilidad de carga sin asumir que todas las barras y discos etiquetados igual tienen el mismo ajuste.", "El espesor determina cuánto peso cabe. Los bumpers ligeros pueden ocupar más espacio, mientras discos metálicos o recubiertos pueden ser más finos. Prepare una tabla de espesores por peso y calcule la carga máxima práctica para los ejercicios previstos."),
      rich("material", "3. Material, dureza, rebote y superficie", "En bumper plates, pida material, dureza o referencia de rebote cuando sea pertinente, construcción del inserto y uso recomendado. Un rebote alto o bajo no es bueno por sí mismo: debe coincidir con plataforma, entorno y control del gimnasio.", "En discos convencionales, revise metal, recubrimiento, asas, bordes, inserto y resistencia del marcado. La superficie puede proteger el núcleo y mejorar la presentación, pero formulación, adherencia y espesor deben evaluarse en muestras y criterios de aceptación."),
      checklist("muestra", "Checklist de muestra", ["Peso y tolerancia", "Diámetro exterior e interior", "Espesor", "Inserto y ajuste en barra", "Planitud y estabilidad", "Superficie, olor y color", "Marcado kg/lb y logo", "Comportamiento en uso previsto", "Caja y protección"]),
      rich("seguridad", "4. Suelo, almacenamiento y normas de uso", "Ningún disco convierte un suelo inadecuado en una plataforma. Defina dónde se permiten levantamientos, altura y forma de descenso, inspección de insertos, limpieza y retirada de piezas dañadas. Señalice qué discos pertenecen a máquinas y cuáles a plataformas.", "Coloque almacenamiento cerca de las estaciones sin bloquear circulación. Los discos con asas facilitan manipulación en ciertos usos; los bumpers necesitan soportes que no dañen bordes ni inserto. La selección debe incluir el sistema de guardado."),
      rich("mix", "5. Calcule el mix de pesos", "Cuente barras, plataformas y estaciones. Los pesos ligeros sirven para progresión, pero pueden requerir más unidades; los pesados concentran carga. En distribución, analice rotación y reposición por mercado. En gimnasio, evite comprar juegos idénticos si las estaciones tienen demandas diferentes.", "Defina kg o lb, código de color y legibilidad. Si combina líneas, asegure que los usuarios puedan identificar qué disco usar. La coherencia visual no debe ocultar diferencias de aplicación."),
      table("coste", "Coste total del pedido", ["Factor", "Dato necesario", "Por qué importa"], [
        ["Precio", "Modelo, material y peso", "Comparar el mismo producto"], ["Espesor", "Tabla por peso", "Capacidad de la barra"], ["MOQ", "Por peso, color y línea", "Inventario"], ["QC", "Tolerancia y muestreo", "Aceptación"], ["Embalaje", "Peso por caja y palé", "Daño y manipulación"], ["Flete", "Peso total e Incoterm", "Los discos son densos"], ["Destino", "Impuestos, despacho y entrega", "Coste puesto en almacén"]
      ]),
      rich("oem", "6. OEM, marca propia y control", "Se pueden evaluar logo, colores, kg/lb y embalaje según modelo y cantidad. Confirme método, posición y contraste. Una apariencia aprobada no sustituye peso, inserto, espesor y superficie como criterios técnicos.", "El plan de QC puede comprobar peso, dimensiones, inserto, acabado, marcado, cantidad y caja. Registre cómo se tratará una desviación. Para reposición futura, conserve códigos, arte y muestra de referencia."),
      rich("recepcion", "7. Recepción, seguimiento y reposición", "Prepare la recepción antes de que llegue la carga. Compare lista de bultos, pesos, etiquetas y palés; inspeccione golpes, humedad, cajas abiertas y desplazamiento. Seleccione muestras de distintos pesos para comprobar masa, centro, superficie y marcado. Una revisión concentrada solo en el disco más pesado puede no detectar problemas de espesor o fragilidad en referencias ligeras.", "Después de instalar, observe qué pesos faltan en horas punta, qué estaciones acumulan discos y cómo responde el suelo. Registre daños de inserto, superficie o borde y relacione cada pieza con su lote. Para un distribuidor, la rotación por peso y tipo determina la reposición; para un gimnasio, el número de barras y plataformas ofrece una base mejor que repetir juegos completos.", "Conserve la ficha, la muestra, el arte y el plan de cajas. En pedidos futuros, confirme cualquier cambio de material, dureza, inserto, color o embalaje. Mantener códigos estables y criterios documentados reduce incompatibilidades y reclamaciones."),
      rich("experiencia", "Información de primera parte de PowerBaseFit", "PowerBaseFit fabrica y suministra productos de peso libre desde Dezhou, Shandong. En proyectos de discos, una de las decisiones más importantes es enviar una tabla por peso y aplicación. Decir únicamente “discos olímpicos” o “bumper” deja sin definir centro, espesor, material y uso.", "La fábrica revisa modelo, cantidad, logo, embalaje y carga. Como los discos concentran peso, el cálculo de cajas, palés y contenedor influye en coste y daños. La oferta debe indicar condición comercial para que el importador calcule el coste real en España o América Latina."),
      checklist("decision", "Checklist final", ["Barra y estándar", "Ejercicios y caídas previstas", "Material y construcción", "Diámetro, centro y espesor", "Pesos y cantidades", "Suelo y almacenamiento", "Tolerancia y muestra", "Logo y marcado", "QC y embalaje", "Coste total y reposición"])
    ],
    faq: [["¿Un disco olímpico es siempre bumper?", "No. Olímpico se refiere principalmente a compatibilidad; bumper describe construcción y aplicación."], ["¿Qué disco conviene para musculación?", "Para máquinas y fuerza sin caída suelen funcionar discos convencionales compatibles. Si hay levantamientos con contacto planificado, evalúe bumpers y plataforma."], ["¿Los bumpers protegen completamente el suelo?", "No. Reducen y gestionan el contacto de otra manera, pero necesitan plataforma adecuada, técnica y mantenimiento."], ["¿Por qué importa el espesor?", "Porque limita cuánto peso cabe en la manga y afecta almacenamiento y carga."], ["¿Puedo poner mi marca?", "Sí, según modelo, método, cantidad y muestra; también deben controlarse peso, centro y superficie."], ["¿Cómo se calcula el coste?", "Sume producto, personalización, inspección, embalaje, transporte, seguro, despacho, impuestos, almacenaje y entrega."]],
    links: [["weight-plates-category", "Ver discos profesionales"], ["rubber-bumper-plate", "Disco bumper de goma"], ["rubber-olympic-plate", "Disco olímpico recubierto"], ["oem-private-label", "Discos de marca propia"], ["factory", "Fábrica y control"], ["contact", "Solicitar cotización"]],
    ...common
  }
];
