import type { LocalizedContentVersion, LocalizedImage } from "../../lib/content/types";
import { svAnswer, svChecklist, svDefinition, swedishEditorialAuthor, swedishImagePath, swedishTechnicalReviewer, svTable, svText } from "./sv-content-helpers";

type GuideProfile={id:string;enPath:string;path:string;title:string;description:string;h1:string;keyword:string;image:string;answer:string;definition:string;decision:string;method:string;evidence:string;risk:string;comparison:string;links:Array<[string,string]>};

export const swedishGuideProfiles:GuideProfile[]=[
  {id:"factory-guide",enPath:"/resources/evaluate-oem-gym-equipment-factory-china",path:"/sv/blogg/utvardera-fabrik-gymutrustning-kina",title:"Utvärdera fabrik för gymutrustning i Kina | B2B-guide",description:"Kontrollera produktkompetens, prov, process, QC, kapacitet, exportpackning och leveranssäkerhet innan fabrik väljs.",h1:"Så utvärderar du en fabrik för gymutrustning i Kina",keyword:"gymutrustning fabrik Kina",image:"/assets/factory-production-line.webp",answer:"Utvärdera fabriken mot den produkt du faktiskt ska köpa. Kontrollera material- och processkompetens, märkta prov, mätbar QC, avvikelsehantering, packning och realistisk tidplan. Registreringar och generella fabriksbilder räcker inte som bevis för att just din artikel kan produceras jämnt.",definition:"En fabriksutvärdering är en riskbaserad kontroll av leverantörens förmåga att upprepa en godkänd produktspecifikation i rätt volym och dokumentera resultatet.",decision:"Beslutet gäller inte om fabriken ser stor ut, utan om den har rätt process, utrustning, fixturer, personal och kontroll för produktfamiljen.",method:"Följ en order genom fabriken: inkommande material, beredning, kritiskt tillverkningssteg, ytbehandling, montering, provning, karantän för avvikelser, packning och lastning. Intervjua den som faktiskt ansvarar för mätning och dokumentation.",evidence:"Begär exempel på arbetsinstruktion, kontrollrapport, kalibreringsstatus, avvikelserapport och packlista med känsliga kunduppgifter borttagna. Be sedan fabriken visa hur samma dokument skulle anpassas till din artikel.",risk:"Vanliga varningssignaler är oidentifierade prover, olika svar från säljare och teknik, mätutrustning utan status, godkännanden i chatt utan versionsnummer och en ledtid som inte delar upp prov, material, produktion och inspektion.",comparison:"Jämför fabriker på produktpassning, verifierbar process, ändringskontroll och förmåga till återbeställning. Lägsta pris är inte en egen kvalitetsindikator.",links:[["factory","Fabrik och kvalitet"],["commercial-free-weight-rfq","RFQ-checklista"],["pre-shipment-inspection-free-weights","Inspektion före leverans"],["contact","Diskutera fabriksval"]]},
  {id:"dumbbells-guide",enPath:"/resources/how-to-choose-commercial-dumbbells",path:"/sv/blogg/valja-hantlar-kommersiellt-gym",title:"Välja hantlar till kommersiellt gym | Inköpsguide",description:"Jämför hexagonala och runda hantlar, gummi, PU, TPU och CPU samt viktserie, ställ, QC och total inköpskostnad.",h1:"Så väljer du hantlar till ett kommersiellt gym",keyword:"hantlar kommersiellt gym",image:"/assets/dumbbells-collection.webp",answer:"Välj hantlar utifrån användarprofil, viktintervall, belastning, grepp, huvudform, ytmaterial, ställ och möjlighet att komplettera serien. Ett komplett gym behöver ofta tätare viktsteg och dubbletter i populära vikter, inte bara en högsta vikt.",definition:"En kommersiell hantelserie är en planerad uppsättning fasta eller justerbara hantlar som ska tåla frekvent användning och vara konsekvent i vikt, grepp, balans, märkning och lagring.",decision:"Bestäm först om serien ska optimera driftsäkerhet, premiumkänsla, kompakt yta, låg ljudnivå eller inköpsbudget. Materialvalet kommer därefter.",method:"Kartlägg övningar och användare, välj minsta och största vikt, ange steg och dubbletter, kontrollera ställets kapacitet och beställ referensprov från tre delar av serien. Simulera rengöring, flytt och placering på ställ.",evidence:"Mät faktisk vikt, greppdiameter, total längd, huvudbredd, balans och sammanfogning. Dokumentera lukt och ytreaktion med en definierad bedömningsmetod i stället för lösa omdömen.",risk:"En vanlig felinvestering är en estetiskt enhetlig serie som inte får plats på stället, har stora hopp i mellanvikter eller saknar möjlighet att ersätta enskilda par efter ett år.",comparison:"Hexhantlar minskar rullning och passar funktionell träning; runda hantlar ger klassiskt uttryck och tät lagring på rätt ställ. Gummi är prisorienterat, medan PU, TPU och CPU kan prioriteras för olika yt- och hållbarhetsmål.",links:[["dumbbells-category","Se hantelsortiment"],["commercial-dumbbell-set-planning","Planera komplett hantelset"],["dumbbell-weighing-guide","Kontrollera hantelvikt"],["contact","Begär offert"]]},
  {id:"plates-guide",enPath:"/resources/weight-plates-vs-bumper-plates-b2b-guide",path:"/sv/blogg/viktskivor-eller-bumpervikter",title:"Viktskivor eller bumpervikter för gym | B2B-guide",description:"Jämför konstruktion, användning, tjocklek, ljud, golv, lagring, viktserie och kostnad för professionella gym.",h1:"Viktskivor eller bumpervikter – vad passar gymmet?",keyword:"viktskivor eller bumper plates",image:"/assets/weight-plates-overview.webp",answer:"Välj bumpervikter när kontrollerade släpp ingår i träningen och golv samt plattform är avsedda för det. Välj tätare metall- eller greppskivor när stångkapacitet, kompakt lagring och maskinanvändning väger tyngre. Många gym behöver båda i separata zoner.",definition:"Bumpervikter har normalt full diameter och en elastomer konstruktion för relevant släpphantering. Vanliga viktskivor kan vara gjutjärn, stål eller belagda och är ofta tunnare men inte automatiskt avsedda att släppas.",decision:"Utgå från lyft, golv, ljudkrav, stångens hylslängd, lagring och användarregler. Marknadsnamnet ger inte rätt att anta en viss testnivå.",method:"Dela träningsytan i lyftar som kräver släpp, kontrollerad styrketräning, maskinlastning och lagring. Beräkna antal skivor per station och hur tjockleken påverkar maximal stånglast.",evidence:"Begär viktavvikelse, diameter, tjocklek, centrumhål, hårdhet eller återstuds när relevant, navkonstruktion och den testmetod som leverantören faktiskt använder.",risk:"Att placera bumpervikter på fel golv eller sälja träningsskivor som tävlingsklass kan skapa skador, missnöje och felaktiga förväntningar. Tydlig zon- och produktmärkning minskar risken.",comparison:"Bumpervikter prioriterar släpphantering och gemensam diameter; metallskivor prioriterar densitet. Greppskivor underlättar manuell hantering men öppningarna och beläggningen ska kontrolleras som strukturella detaljer.",links:[["weight-plates-category","Se viktskivor"],["training-vs-competition-bumper-plates","Träning eller tävling"],["plate-materials-b2b","Jämför material"],["contact","Begär projektoffert"]]},
  {id:"bumper-manufacturing-guide",enPath:"/resources/how-are-bumper-plates-made",path:"/sv/blogg/sa-tillverkas-bumperviktskivor",title:"Hur tillverkas bumperviktskivor? Process och QC",description:"Från gummiblandning och nav till formning, viktkontroll, efterbehandling, test, märkning och exportförpackning.",h1:"Så tillverkas bumperviktskivor",keyword:"hur tillverkas bumper plates",image:"/assets/resource-plate-finishing.webp",answer:"Bumperviktskivor tillverkas genom att elastomermaterial förbereds och formas kring en definierad navkonstruktion, varefter skivan efterbehandlas, vägs, mäts, märks och provas. Exakt metod skiljer sig mellan gummi, urethan och produktdesign.",definition:"En bumperviktskiva är en viktbärande skiva med elastomer kropp och centruminsats som är konstruerad för en angiven typ av lyft- och släpphantering.",decision:"Köparen ska frysa material, nav, diameter, tjocklek, hårdhet, viktavvikelse, färg och märkning innan processen godkänns.",method:"Processflödet omfattar materialmottagning, blandning eller beredning, vägning av sats, form och nav, pressning eller gjutning, härdning, avformning, trimning, vikt- och måttkontroll, märkning samt packning.",evidence:"Kontrollera satsidentitet, processparametrar, navets centrering, skivans planhet, vikt, diameter, tjocklek och visuella fel. Funktionstestet ska beskriva höjd, underlag, antal cykler och godkännandekriterium.",risk:"Felaktig materialmängd, dålig navinfästning, ojämn härdning eller okontrollerad trimning kan ge viktfel, skevhet, sprickor eller rörelse mellan nav och kropp.",comparison:"Gummiblandningar, återvunnet gummi, PU, TPU och CPU har olika processer och egenskaper. Jämför den faktiska sammansättningen och verifieringen, inte bara familjenamnet.",links:[["weight-plates-category","Se bumpervikter"],["training-vs-competition-bumper-plates","Tränings- och tävlingsskivor"],["factory","Fabrik och QC"],["contact","Diskutera specifikation"]]},
  {id:"dumbbell-weighing-guide",enPath:"/resources/how-are-dumbbells-weighed",path:"/sv/blogg/kontrollera-vikt-pa-hantlar",title:"Hur kontrolleras vikten på hantlar? Fabriksguide",description:"Lär dig definiera nominell vikt, tolerans, våg, stickprov, serievariation och kontrollrapport för B2B-hantlar.",h1:"Så vägs och kontrolleras hantlar i fabriken",keyword:"kontrollera vikt hantlar",image:"/assets/dumbbell-production.webp",answer:"Hantlar vägs på lämplig, kontrollerad våg efter att konstruktion och finish nått det steg som definieras i specifikationen. Resultatet jämförs med nominell vikt och avtalad tolerans. För en serie behöver urvalet täcka flera viktsteg och produktionspartier.",definition:"Vikttolerans är det tillåtna intervallet mellan produktens nominella märkning och det uppmätta värdet enligt avtalad metod.",decision:"Bestäm om toleransen anges absolut, procentuellt eller per viktgrupp och vid vilket produktionssteg mätningen ska ske.",method:"Verifiera vågens kapacitet, upplösning, nollning och status. Identifiera hanteln, väg den enligt instruktion, registrera mätvärde och bedöm mot rätt gräns. Isolera enheter utanför tolerans.",evidence:"Rapporten bör visa artikel, märkvikt, uppmätt vikt, avvikelse, enhet, våg, datum, operatör eller kontrollant och beslut. Fotografier kan stödja men inte ersätta mätvärden.",risk:"En våg med för grov upplösning eller ett urval från bara en lätt vikt kan ge en falsk bild av seriens noggrannhet. Märkning och mätmetod måste använda samma kg- eller lb-logik.",comparison:"Procentuell tolerans kan ge stort absolut intervall på tunga hantlar; fast tolerans kan vara oproportionerligt strikt på lätta. En viktgruppsbaserad modell kan vara tydligare om den dokumenteras.",links:[["dumbbells-category","Se hantlar"],["commercial-dumbbell-set-planning","Planera hantelserie"],["pre-shipment-inspection-free-weights","Inspektion före leverans"],["contact","Begär kontrollunderlag"]]},
  {id:"plate-materials-b2b",enPath:"/resources/cast-iron-rubber-urethane-weight-plates",path:"/sv/blogg/gjutjarn-gummi-pu-viktskivor",title:"Gjutjärn, gummi eller PU-viktskivor | Materialguide",description:"Jämför densitet, yta, ljud, rengöring, märkning, hållbarhet, QC och inköpskostnad för kommersiella gym.",h1:"Gjutjärn, gummi eller PU – välj material för viktskivor",keyword:"gjutjärn gummi PU viktskivor",image:"/assets/weight-plates-overview.webp",answer:"Gjutjärn ger hög densitet och traditionell känsla, gummibeläggning kan minska metallkontakt och ljud, medan PU och andra polymerer kan prioriteras för yta, färg och slitprofil. Rätt val beror på användning, budget, rengöring, märkning och leverantörens faktiska materialkontroll.",definition:"Materialval för viktskivor omfattar både den bärande kärnan och exponerad yta, nav, märkning och eventuella bindningar mellan materialen.",decision:"Välj inte på materialnamn ensamt. Specificera recept eller materialklass där det är affärskritiskt och definiera vilka egenskaper som ska verifieras.",method:"Skapa en matris med användningszon, släpphantering, ljud, kontakt med golv, rengöring, UV, lagring, färg och budget. Prova representativa skivor i den verkliga miljön.",evidence:"Begär materialbeskrivning, mått, vikt, ytreferens, luktbedömning när relevant, vidhäftning och dokumentation som den svenska importören behöver för sin egen bedömning.",risk:"Två leverantörer kan använda samma ord men olika kärna, beläggningstjocklek eller process. Prisskillnaden kan bero på konstruktion och kontroll, inte bara materialets handelsnamn.",comparison:"Gjutjärn är kompakt men exponerad metall kräver korrosions- och kantkontroll. Gummi, PU, TPU och CPU ger olika kompromisser i pris, ytkaraktär, färg och processbarhet.",links:[["weight-plates-category","Se viktskivor"],["plates-guide","Viktskivor eller bumper"],["factory","Tillverkning"],["contact","Jämför materialalternativ"]]},
  {id:"commercial-free-weight-rfq",enPath:"/resources/commercial-free-weight-rfq-checklist",path:"/sv/blogg/rfq-checklista-fria-vikter",title:"RFQ-checklista för hantlar och viktskivor | B2B",description:"Skapa en jämförbar offertförfrågan med SKU, material, tolerans, logo, emballage, QC, Incoterm och leveransplan.",h1:"RFQ-checklista för kommersiella fria vikter",keyword:"RFQ gymutrustning checklista",image:"/assets/products-overview.webp",answer:"En bra RFQ anger företag och marknad, användning, artikelnummer, viktserie, antal per variant, material, toleranser, märkning, emballage, prov, inspektion, destination och Incoterm. Leverantörer ska svara på samma omfattning.",definition:"RFQ, request for quotation, är en strukturerad offertförfrågan som gör kommersiella och tekniska antaganden synliga och jämförbara.",decision:"Bestäm vilka krav som är obligatoriska, önskvärda eller öppna för leverantörsförslag. Annars riskerar varje offert att avse en annan produkt.",method:"Bygg RFQ:n i fem delar: företags- och marknadskontext, artikelmatris, tekniska krav, kvalitet och dokumentation samt kommersiella villkor. Ge varje fråga ett svarsfält.",evidence:"Bifoga ritning eller referensbild med förklarande text, men låt inte bilden vara enda specifikation. Be leverantören markera avvikelse i stället för att tyst anta en ersättning.",risk:"Vanliga luckor är antal per vikt, kg/lb, logometod, kartongstyrka, bruttovikt, provkostnad, inspektionsfönster och exakt hamn eller leveranspunkt.",comparison:"Jämför offerter rad för rad och normalisera valuta, antal, förpackning och Incoterm. Ett totalsummetal utan omfattning är inte jämförbart.",links:[["products-hub","Välj produktfamiljer"],["factory-guide","Utvärdera fabrik"],["landed-cost-free-weights","Räkna total kostnad"],["contact","Skicka RFQ"]]},
  {id:"custom-logo-free-weights",enPath:"/resources/custom-logo-options-dumbbells-weight-plates",path:"/sv/blogg/logotyp-hantlar-viktskivor",title:"Logotyp på hantlar och viktskivor | OEM-guide",description:"Jämför gjuten, präglad, tryckt, graverad och etikettbaserad märkning för eget varumärke, prov och serieproduktion.",h1:"Alternativ för logotyp på hantlar och viktskivor",keyword:"logotyp gymutrustning eget varumärke",image:"/assets/custom-logo.webp",answer:"Rätt logometod beror på material, yta, färg, relief, antal och önskad hållbarhet. Gjutning och prägling påverkar form eller verktyg; tryck och laser kan vara flexiblare men måste provas på den verkliga ytan.",definition:"Produktmärkning är den kontrollerade kombinationen av varumärke, vikt, artikeldata och lagstadgad information på produkt, etikett och förpackning.",decision:"Välj metod efter var logotypen sitter, vilken nötning och rengöring den utsätts för och hur ofta artwork eller färg väntas ändras.",method:"Skicka vektorfil, färgreferens, minsta storlek, friyta och förbjudna användningar. Fabriken gör placeringsförslag, digital korrektur och vid behov fysiskt prov i rätt skala.",evidence:"Godkänn form, proportion, läsbarhet, färg, placering, kant, relief och vidhäftning. Fotografera referensprovet i kontrollerat ljus och spara fysisk master.",risk:"En skärmbild kan dölja tunn text, fel färgrymd eller proportion. Ändrad huvudstorlek mellan vikter kan kräva flera artwork-storlekar och separata godkännanden.",comparison:"Lasergravyr passar exponerad metall, medan tryck, ingjuten relief och applicerade märken har andra verktygs- och hållbarhetsprofiler. Kartong och produkt behöver inte använda samma metod.",links:[["oem-private-label","OEM och eget varumärke"],["oem-sample-approval-free-weights","Godkänn prov"],["dumbbells-category","Hantlar"],["contact","Skicka artwork"]]},
  {id:"export-packaging-free-weights",enPath:"/resources/export-packaging-dumbbells-weight-plates",path:"/sv/blogg/exportforpackning-hantlar-viktskivor",title:"Exportförpackning för hantlar och viktskivor",description:"Planera kartong, inlägg, bandning, pall, märkning, bruttovikt och mottagning för tung gymutrustning.",h1:"Så packas hantlar och viktskivor för export",keyword:"exportförpackning gymutrustning",image:"/assets/export-packaging.webp",answer:"Tunga fria vikter kräver förstärkt kartong, separation mellan hårda ytor, tät passform, kontrollerad kollivikt och pallfördelning som hindrar förskjutning. Förpackningen ska provas mot den produkt, transportkedja och mottagningsmetod som faktiskt används.",definition:"Exportförpackning är ett system av produktsskydd, inneremballage, ytterkartong, bandning, pall, märkning och dokumentation för hela logistikkedjan.",decision:"Utgå från produktskada, personhantering, pallstabilitet, fukt, omlastning och lager. Minimera inte material innan risk och test är kända.",method:"Kartlägg resa och hanteringspunkter, välj kollivikt, skydda ytor och hörn, separera delar, prova kartong, skapa pallmönster och genomför en dokumenterad packkontroll före lastning.",evidence:"Packlistan ska stämma mot fysiska kollin och visa artikel, antal, netto- och bruttovikt, mått och pallnummer. Bilder tas innan kartong stängs och efter att pall säkrats.",risk:"Överfyllda kartonger, obalanserade pallar, lösa metallkontakter och otydlig märkning kan orsaka skada även när själva produkten är korrekt tillverkad.",comparison:"Enhetskartong ger spårbarhet och återförsäljning men mer volym; bulkpackning kan minska volym men ökar krav på separation och lagerhantering. Beslutet ska vara avsiktligt.",links:[["factory","Packning i fabriken"],["landed-cost-free-weights","Total kostnad"],["pre-shipment-inspection-free-weights","Kontrollera packning"],["contact","Begär packplan"]]},
  {id:"free-weight-reorder-batch-consistency",enPath:"/resources/free-weight-reorder-batch-consistency",path:"/sv/blogg/jamn-kvalitet-aterbestallning-fria-vikter",title:"Jämn kvalitet vid återbeställning av fria vikter",description:"Styr referensprov, material, färg, mått, vikt, logo, artikelnummer och avvikelser mellan produktionspartier.",h1:"Så behåller du jämn kvalitet mellan återbeställningar",keyword:"återbeställning hantlar jämn kvalitet",image:"/assets/dumbbells-collection.webp",answer:"Jämn kvalitet kräver en fryst produktversion, märkt referensprov, materialspecifikation, färgreferens, mätdata och ändringskontroll. Nästa order ska jämföras med dessa underlag, inte med minnesbilder eller en gammal webblänk.",definition:"Partikonsistens är graden av överensstämmelse mellan godkänd referens och efterföljande produktionspartier för funktion, mått, vikt, material, yta och märkning.",decision:"Bestäm vilka egenskaper kunden märker direkt, vilka som påverkar kompatibilitet och vilka som är säkerhets- eller funktionskritiska. Sätt tolerans och åtgärd därefter.",method:"Arkivera prov och filer, skapa versionshistorik, bekräfta material och underleverantörer, mät första artikel i ny order och jämför stickprov med tidigare data före massproduktion.",evidence:"En återbeställningsrapport bör visa gammal och ny version, ändringar, mätvärden, fotografier under jämförbart ljus och beslut från behörig köpare.",risk:"Obemärkta prov, utbytt råvara, renoverat verktyg, ny färgleverantör eller ändrad kartong kan skapa synlig skillnad trots samma artikelbenämning.",comparison:"Full identitet är inte alltid realistisk, men kontrollerad variation är. Definiera vad som får variera och vad som måste matcha för att produkterna ska kunna säljas och användas tillsammans.",links:[["oem-private-label","OEM-styrning"],["oem-sample-approval-free-weights","Provprocess"],["pre-shipment-inspection-free-weights","Slutkontroll"],["contact","Planera återbeställning"]]},
  {id:"commercial-dumbbell-set-planning",enPath:"/resources/plan-commercial-dumbbell-set",path:"/sv/blogg/planera-hantelset-kommersiellt-gym",title:"Planera hantelset för kommersiellt gym",description:"Välj viktintervall, steg, dubbletter, material, ställ, golvyta, artikelantal och kompletteringsstrategi.",h1:"Planera ett komplett hantelset för gymmet",keyword:"hantelset kommersiellt gym planering",image:"/assets/project-dumbbell-zone.webp",answer:"Ett kommersiellt hantelset planeras efter medlemsprofil, träningsinriktning, toppbelastning, golvyta och budget. Välj minsta och största vikt, steg och dubbletter per vikt och kontrollera att ställ, passage och kompletteringsplan fungerar.",definition:"Hantelsetplanering är dimensioneringen av antal par, viktsteg, material, ställ och reservstrategi för en definierad träningsmiljö.",decision:"Utgå från sannolik samtidig användning och övningar, inte en standardlista. Populära mellanvikter kan behöva dubbletter medan yttervikter används mer sällan.",method:"Samla medlems- och tränardata, lista övningar, sätt viktspann, modellera toppbelastning, välj ställ, beräkna total styck- och fraktvikt och granska layouten i skala.",evidence:"Offerten ska visa varje vikt, antal stycken eller par, enhetsvikt, total vikt, kartong och ställposition. Det avslöjar luckor och dubbelräkning.",risk:"För stort viktsteg bromsar progression, men för många sällan använda par binder kapital och yta. Ett kort ställ kan skapa hantlar på golvet trots tillräckligt totalutrymme.",comparison:"Fasta hantlar ger snabb användning och hög genomströmning; justerbara sparar yta men har fler röreliga delar och långsammare byte. De kan fylla olika zoner snarare än ersätta varandra helt.",links:[["dumbbells-category","Välj hantelmodell"],["dumbbells-guide","Jämför material och form"],["projects","Planera gymyta"],["contact","Få setoffert"]]},
  {id:"landed-cost-free-weights",enPath:"/resources/landed-cost-wholesale-free-weights",path:"/sv/blogg/total-kostnad-import-gymutrustning",title:"Total kostnad vid import av gymutrustning",description:"Beräkna produkt, prov, QC, emballage, frakt, försäkring, tullvärde, avgifter, lager och skaderisk.",h1:"Beräkna total kostnad för importerade fria vikter",keyword:"importera gymutrustning från Kina kostnad",image:"/assets/export-packaging.webp",answer:"Total kostnad till lager är produktpriset plus kundanpassning, prov, inspektion, emballage, transport, försäkring, tullhantering, eventuell tull, lokal leverans och interna mottagningskostnader. Importmoms behandlas enligt företagets situation och ska bedömas med svensk expertis.",definition:"Landed cost är den sammanlagda kostnaden för att få en definierad vara från leverantör till avtalad mottagningspunkt, med tydliga antaganden om Incoterm och importansvar.",decision:"Jämför samma artikelmix, packning, transportform och ansvarspunkt. Ett FOB-pris kan inte direkt jämföras med DDP eller ett lokalt lagerpris.",method:"Bygg en kostnadsmodell per order och SKU: varuvärde, engångskostnader, QC, emballage, frakt, försäkring, tullvärde, avgifter, inrikestransport, lager och beräknad skaderisk.",evidence:"Använd faktisk packlista och fraktoffert när de finns. Dokumentera valutakurs, varukod, tullsats och antaganden med datum eftersom de kan förändras.",risk:"Tunga produkter kan se billiga ut per kilo men bli dyra per såld enhet när låg containerutnyttjande, specialpall, hamnavgifter eller skador läggs till.",comparison:"Jämför sjö, järnväg, lastbil och flyg efter volym, massa, ledtid, stabilitet och kostnad. Transportvalet beror på ordern och ska inte generaliseras.",links:[["export-packaging-free-weights","Exportförpackning"],["commercial-free-weight-rfq","RFQ-checklista"],["products-hub","Planera artikelmix"],["contact","Begär packdata"]]},
  {id:"oem-sample-approval-free-weights",enPath:"/resources/oem-free-weight-sample-approval-process",path:"/sv/blogg/godkanna-oem-prov-gymutrustning",title:"Godkänna OEM-prov för gymutrustning | Process",description:"Styr provversion, material, vikt, mått, funktion, logo, färg, emballage, avvikelse och serieproduktionsreferens.",h1:"Så godkänner du ett OEM-prov före serieproduktion",keyword:"OEM prov gymutrustning godkännande",image:"/assets/custom-logo.webp",answer:"Ett OEM-prov godkänns mot en checklista och ett versionsstyrt underlag, inte enbart med texten ser bra ut. Kontrollera produktidentitet, material, vikt, mått, funktion, yta, färg, logotyp, etikett och förpackning och registrera avvikelser.",definition:"Ett godkänt OEM-prov är en fysisk och dokumenterad referens som anger vad serieproduktionen ska motsvara inom överenskomna toleranser.",decision:"Bestäm om provet är visuellt, funktionellt, förproduktionsprov eller fullständig golden sample. Olika prov får inte användas som om de bevisar samma sak.",method:"Märk provet, kontrollera mot specifikationen, fotografera definierade vinklar, registrera mätvärden, lista avvikelser, besluta godkänd, villkorat godkänd eller ny provomgång och arkivera allt.",evidence:"Godkännandedokumentet visar artikel, version, datum, material, färg, vikt, mått, logo, förpackning, öppna punkter och namn på behörig beslutsfattare.",risk:"Ett säljprov kan vara handgjort, använda annat material eller sakna produktionsverktyg. Fråga vilka delar av provet som verkligen representerar massproduktion.",comparison:"Digital korrektur räcker för viss etiketttext men inte för grepp, lukt, färg på material, vikt, passning eller hållbarhet. Välj bevis efter risk.",links:[["oem-private-label","OEM-process"],["custom-logo-free-weights","Logotypalternativ"],["free-weight-reorder-batch-consistency","Återbeställning"],["contact","Planera prov"]]},
  {id:"pre-shipment-inspection-free-weights",enPath:"/resources/pre-shipment-inspection-dumbbells-weight-plates",path:"/sv/blogg/inspektion-hantlar-viktskivor-fore-leverans",title:"Inspektion av hantlar och viktskivor före leverans",description:"Planera urval, artikelkontroll, vikt, mått, yta, logo, antal, kartong, pall och rapport före slutbetalning.",h1:"Inspektera fria vikter före leverans",keyword:"inspektion gymutrustning före leverans",image:"/assets/resource-plate-finishing.webp",answer:"En inspektion före leverans verifierar att färdig order stämmer mot godkänd specifikation och packlista. Urvalet ska täcka produkter, viktsteg, kartonger och pallar som bär störst risk, och rapporten ska skilja kritiska, större och mindre avvikelser.",definition:"Pre-shipment inspection är en dokumenterad kontroll av färdiga och packade varor före avsändning enligt avtalat urval och godkännandekriterier.",decision:"Bestäm inspektionspunkt när tillräcklig andel är färdig men korrigering fortfarande är möjlig. Definiera om återinspektion krävs efter omarbete.",method:"Kontrollera orderstatus, slumpa urval, verifiera artikel och antal, mät vikt och kritiska mått, prova funktion, granska yta och logo, öppna kartonger och bedöm pall samt dokumentera avvikelser.",evidence:"Rapporten ska innehålla order, plats, datum, färdigställandegrad, urvalsmetod, mätvärden, bilder, avvikelselista och sammanfattande beslut mot köparens kriterier.",risk:"Förberett urval från fabriken, otydliga toleranser eller inspektion efter att containern stängts begränsar värdet. Inspektören behöver fri tillgång till relevant lager.",comparison:"Intern slutkontroll är en del av fabriksprocessen; tredjepartsinspektion är oberoende verifiering. Den ena gör inte den andra överflödig när risknivån motiverar båda.",links:[["factory-guide","Utvärdera fabrik"],["dumbbell-weighing-guide","Viktkontroll"],["export-packaging-free-weights","Packning"],["contact","Planera inspektion"]]},
  {id:"training-vs-competition-bumper-plates",enPath:"/resources/training-vs-competition-bumper-plates",path:"/sv/blogg/traningsvikter-eller-tavlingsvikter-bumper",title:"Tränings- eller tävlingsvikter | Bumper guide",description:"Jämför tolerans, nav, tjocklek, färg, återstuds, test, pris och användning för gym, klubbar och distributörer.",h1:"Träningsvikter eller tävlingsvikter – välj rätt bumper plate",keyword:"träningsvikter tävlingsvikter bumper",image:"/assets/weight-plates-overview.webp",answer:"Träningsvikter prioriterar vanligtvis hållbar kommersiell användning och kostnad, medan tävlingsinriktade skivor behöver mer definierad viktavvikelse, mått, nav, färg och verifiering. En gymkedja behöver inte tävlingsspecifikation i varje zon.",definition:"Tränings- och tävlingsbumpervikter är produktklasser som måste definieras genom tekniska krav och test, inte enbart genom namn eller färgsättning.",decision:"Koppla specifikationsnivån till verksamheten: allmän gymdrift, tyngdlyftningsklubb, tävlingsförberedelse, event eller detaljhandel.",method:"Lista krav på viktavvikelse, diameter, tjocklek, centrumhål, nav, hårdhet, återstuds, färg, märkning och provning. Jämför hur dessa krav påverkar pris och stångkapacitet.",evidence:"Begär mätdata från flera vikter och beskrivning av funktionstest. Om formell standard eller certifiering påstås måste giltigt underlag gälla den exakta modellen.",risk:"Att betala för visuell tävlingsstil utan verifierad precision ger liten funktionell nytta. Omvänt kan en för tjock billig skiva begränsa lasten på stången.",comparison:"Träningsskivor kan ge bättre budgetutnyttjande i högtrafikzoner; tävlingsskivor kan vara motiverade där precision och konsekvent geometri är centrala. Ett blandat gym kan zonindela.",links:[["weight-plates-category","Se bumpervikter"],["bumper-manufacturing-guide","Tillverkningsprocess"],["plates-guide","Viktskivor jämfört"],["contact","Jämför alternativ"]]}
];

const planningAngles=[
  "Svenska inköpare bör dokumentera vilka uppgifter som är leverantörsfakta och vilka som måste verifieras av importör, tullombud eller annan lokal expert.",
  "Låt ansvarig för inköp, drift och logistik läsa samma underlag. De upptäcker olika risker och bör godkänna innan ordern låses.",
  "Ett beslut som kan förklaras med data är lättare att återanvända vid nästa order och att försvara när kostnad, kvalitet eller leveranstid ändras.",
  "Planera kontrollpunkter tidigt. Att lägga till mätning, nytt prov eller specialpackning när ordern redan är färdig skapar försening och omarbete.",
  "Översätt kommersiella ord till mätbara krav. Hållbar, professionell och premium är mål; material, tolerans och test visar hur målet ska bedömas."
];

const verifiedGuideImage:Record<string,string>={
  "/assets/factory-production-line.webp":"/assets/factory.webp",
  "/assets/dumbbells-collection.webp":"/assets/hex-dumbbells.webp",
  "/assets/weight-plates-overview.webp":"/assets/weight-plate.webp",
  "/assets/products-overview.webp":"/assets/hero-poster.avif",
  "/assets/custom-logo.webp":"/assets/products/dumbbells/chrome/chrome-dumbbell-custom-logo.webp",
  "/assets/export-packaging.webp":"/assets/factory-cases/packaging-area-pbf.webp"
};

const guideSpecifics:Record<string,string[]>={
  "factory-guide":[
    "Spåra en utvald hantel eller viktskiva från råvara till packad pall och notera var identitet, mått, vikt och yta faktiskt kontrolleras.",
    "Jämför uppgiven kapacitet med maskintid, verktyg, bemanning, materialtillgång och andra order i planeringen; ett årsmaximum säger lite om ditt leveransfönster.",
    "Låt fabriken demonstrera hur en avvikande enhet märks, isoleras, utreds och frisläpps. En muntlig försäkran är inte en fungerande karantänprocess.",
    "Kontrollera att prov, ritning, materiallista, artwork och kartong har samma artikel- och versionsnummer hos sälj, teknik, produktion och QC.",
    "Avsluta utvärderingen med en risklista per produktfamilj, inte ett enda fabriksbetyg. Svetsade rack och formade bumpervikter kräver olika bevis."
  ],
  "dumbbells-guide":[
    "Modellera ett vardagsdygn: uppvärmning, gruppass, personlig träning och rusningstid. Det visar vilka mellanvikter som behöver dubbla eller tredubbla par.",
    "Mät ställets användbara bredd och varje hantelhuvud i serien. Nominellt antal platser räcker inte när huvudstorleken förändras mellan viktstegen.",
    "Bedöm gummi, PU, TPU och CPU på verklig rengöring, golvkontakt, lukt, färgstabilitet och möjlighet att ersätta ett skadat par.",
    "Provserien bör innehålla en lätt, en populär och en tung hantel. Jämför greppdiameter, balans och sammanfogning i stället för att bara granska finish.",
    "Räkna setkostnad inklusive ställ, dubbletter, fraktvikt och framtida komplettering. Ett lägre styckepris kan ge ett dyrare och sämre utnyttjat system."
  ],
  "plates-guide":[
    "Lista övningarna per zon och markera var kontrollerade släpp förekommer. Bumpervikter löser inte ett golv eller en plattform som är fel dimensionerad.",
    "Beräkna stånglast med skivans verkliga tjocklek, lås och marginal på hylsan. Två skivor med samma vikt kan ge helt olika maximal last.",
    "För maskinzoner väger enkel på- och avlastning, greppöppningar och kompakt lagring ofta tyngre än släppegenskaper.",
    "Kontrollera centrumhål på flera skivor och flera stänger. En enstaka passning avslöjar inte variation eller problem vid återbeställning.",
    "Separera inköpslistan i träningsskivor, teknikskivor, tävlingsinriktade skivor och kompakta viktskivor så att varje krav får rätt prov."
  ],
  "bumper-manufacturing-guide":[
    "Satsvägningen påverkar nominell vikt redan före formning. Dokumentera hur materialmängd, nav och eventuell efterjustering ingår i den färdiga vikten.",
    "Formtemperatur, tryck och härdningstid behöver styras för den valda blandningen. Ojämn process kan synas först som skevhet, sprickor eller varierande återstuds.",
    "Navet ska centreras och bindningen mot kroppen verifieras. Mät rörelse och planhet efter relevant provning, inte bara direkt efter avformning.",
    "Ett släpprov måste ange skivvikt, stång, höjd, underlag, antal cykler, temperatur och felkriterier. Utan metod går resultat inte att jämföra.",
    "Efter trimning kontrolleras vikt, diameter, tjocklek, yta, märkning och packning per variant. Färg får inte användas som enda identitetskontroll."
  ],
  "dumbbell-weighing-guide":[
    "Välj våg så att kapacitet och upplösning passar både seriens lättaste och tyngsta hantel; annars kan två mätstationer behövas.",
    "Nollställning, stabilt underlag och placeringsmetod påverkar resultatet. Instruktionen ska göra att två kontrollanter får samma avläsning.",
    "Urvalet ska täcka flera viktsteg, formar och tidpunkter i produktionen. Fem enheter från samma kartong säger lite om hela serien.",
    "Rapportera avvikelsen både i faktisk enhet och mot godkänd gräns. Avrundad viktmärkning får inte blandas ihop med mätvärdets precision.",
    "Bestäm på förhand vad som händer utanför tolerans: omvägning, sortering, omarbete eller kassation. En gräns utan åtgärd styr inte kvalitet."
  ],
  "plate-materials-b2b":[
    "Gjutjärnets densitet ger tunnare skivor men exponerade kanter och ytor behöver bedömas för stötar, fukt och korrosionsskydd.",
    "Gummibeläggning kan skydda och dämpa kontakt, men recept, lukt, vidhäftning, ytstruktur och märken mot golv måste provas på verklig variant.",
    "PU, TPU och CPU är inte utbytbara kvalitetsstämplar. Be leverantören beskriva konstruktion, process och den egenskap som materialvalet ska förbättra.",
    "Jämför rengöring med de medel och rutiner gymmet faktiskt använder. Yta, tryck och färg kan reagera annorlunda än i ett kort showroomtest.",
    "Materialbeslutet ska omfatta kärna, nav, beläggning och märkning. En enda rad med handelsnamn räcker inte för svensk importörs produktbedömning."
  ],
  "commercial-free-weight-rfq":[
    "Artikelmatrisen ska visa vikt, enhet, antal stycken eller par, färg, logo och förpackning per SKU så att totalen kan räknas om.",
    "Dela obligatoriska krav från leverantörsalternativ. Då kan fabriken föreslå en bättre process utan att tyst ersätta en kritisk egenskap.",
    "Be om netto- och bruttovikt, kartongmått och pallplan samtidigt med priset. Frakt och lager kan annars inte jämföras mellan offerter.",
    "Sätt sista datum för tekniska frågor, prov, artwork, produktionsstart, inspektion och avgång. Ett enda leveransdatum döljer beroenden.",
    "Låt varje leverantör lämna en avvikelselista och undertecknad omfattning. Tomma svar ska behandlas som öppna frågor, inte som automatiskt godkännande."
  ],
  "custom-logo-free-weights":[
    "Kartlägg logotypens underlag: exponerad metall, gummi, urethan, plast, tyg eller kartong. Samma metod fäster och åldras olika på varje yta.",
    "Skapa en placeringsritning med mått från fasta kanter, minsta fria yta och läsriktning. Centrerad är inte ett mätbart produktionskrav.",
    "Godkänn färg med fysisk referens när material och glans påverkar upplevelsen. Skärmfärg räcker bara som kommunikation, inte som slutlig tolerans.",
    "Prova märkningen efter rengöring, nötning och relevant hantering. Ett snyggt första prov visar inte hur tryck eller etikett beter sig i gymdrift.",
    "Versionsstyr produkt, artwork, viktmärkning, etikett och kartong tillsammans. Fel kombination kan vara kommersiellt obrukbar även om varje del är korrekt."
  ],
  "export-packaging-free-weights":[
    "Fastställ högsta kollivikt utifrån produkt, manuell hantering och mottagning. En stark kartong eliminerar inte riskerna med ett ohanterligt tungt kolli.",
    "Separera metall- och målade ytor med material som inte flyttar sig under vibration. Lösa delar kan skada finish utan att ytterkartongen ser skadad ut.",
    "Bygg pallmönster med tyngdpunkt, överhäng, höjd, bandning och lossningsmetod. Testa den verkliga artikelmixen, inte en idealiserad homogen pall.",
    "Märk kolli med artikel, variant, antal, netto- och bruttovikt samt pallnummer. Lagret ska kunna avstämma packlistan utan att öppna allt.",
    "Fotografera packningssteg och förseglad pall. Bilderna stödjer spårbarhet men ska kompletteras med kartongspecifikation och avtalat kontrollresultat."
  ],
  "free-weight-reorder-batch-consistency":[
    "Arkivera golden sample mörkt och kontrollerat samt märk datum, artikel och version. Ett slitet showroomprov är en dålig färg- och ytreferens.",
    "Begär förhandsmeddelande vid byte av råvara, pigment, verktyg, underleverantör eller processparameter som påverkar godkända egenskaper.",
    "Mät första artiklar från den nya ordern mot tidigare rapport, inte bara toleransgränsen. Trendförändring kan upptäckas innan den blir ett fel.",
    "Använd samma fotovinkel, ljus och bakgrund när färg och finish jämförs. Bilder från olika miljöer skapar falska skillnader och likheter.",
    "Koppla reklamationer och reservbeställningar till batch och artikelversion. Då kan orsaken avgränsas utan att hela produktlinjen ifrågasätts."
  ],
  "commercial-dumbbell-set-planning":[
    "Samla beläggningsdata eller tränarnas erfarenhet per viktzon. Populära mellanvikter behöver ofta fler par än de lättaste och tyngsta ändarna.",
    "Rita ställ och fria passager i skala. Ta med hantelns verkliga djup, användarens lyftzon och plats för rengöring och komplettering.",
    "Räkna antal enheter, inte bara antal viktsteg. Ett par per steg plus tre extra populära par förändrar både budget och fraktvikt tydligt.",
    "Planera en ersättningsstrategi: lagerför reservpar, avropa snabbt eller acceptera tillfälliga luckor. Färg och grepp bör kunna matchas vid återbeställning.",
    "Förankra högsta vikt i medlemsprofil och träningskoncept. Oanvända tunga par binder yta och kapital medan för få mellanvikter skapar kö."
  ],
  "landed-cost-free-weights":[
    "Bygg kostnaden från verklig artikelmix och packlista. Vikt per produkt räcker inte när volym, pallhöjd och containerutnyttjande styr frakten.",
    "Separera engångskostnader för prov, verktyg och artwork från återkommande styckkostnad. Annars blir första och följande order fel jämförda.",
    "Ange Incoterm med namngiven plats och version samt vem som bokar, försäkrar, deklarerar och tar risk i varje transportsteg.",
    "Dokumentera varukod, tullvärde, valutakurs och datum med svensk tullkompetens. Byt inte antagande i en offert utan att räkna om alla alternativ.",
    "Lägg till mottagning, kvalitetsavvikelse, skada, lager och kapitalbindning. Den billigaste leveransen är inte alltid lägst kostnad per säljbar enhet."
  ],
  "oem-sample-approval-free-weights":[
    "Definiera om provet visar utseende, funktion, produktionsprocess eller allt tillsammans. Ett handgjort färgprov bevisar inte massproduktionens toleranser.",
    "Märk provet permanent med artikel, version och datum och länka det till ritning, material, artwork, mätblad och öppna avvikelser.",
    "Kontrollera i en fast ordning: identitet, material, vikt, mått, funktion, yta, märkning, etikett och emballage. Registrera faktiska mätvärden.",
    "Villkorat godkännande ska lista vem som korrigerar vad och vilket nytt bevis som krävs. Det är inte samma sak som fri produktionsstart.",
    "Behåll en referens hos köparen och en hos fabriken när risken motiverar det. Båda ska förseglas eller märkas så att de inte byts ut."
  ],
  "pre-shipment-inspection-free-weights":[
    "Boka kontroll när ordern är tillräckligt färdig för representativt urval men det fortfarande finns tid för sortering, omarbete och återinspektion.",
    "Låt inspektören välja kartonger och pallar från hela partiet. Ett urval som fabriken förberett kan inte betraktas som slumpmässigt.",
    "Täck lätta, populära och tunga vikter samt varje logo- och färgvariant. Riskurval kompletterar den avtalade stickprovsmodellen.",
    "Rapportera mätvärden, inte bara godkänd eller underkänd. Fotografier ska visa identitet och instrument så att resultatet kan granskas.",
    "Koppla varje avvikelse till krav, omfattning, klassning och åtgärd. Slutbetalning och leveransbeslut följer köparens avtalade process."
  ],
  "training-vs-competition-bumper-plates":[
    "Placera tävlingskrav endast där precision, definierad geometri och evenemangsanvändning skapar verkligt värde; övriga zoner kan prioritera robust ekonomi.",
    "Jämför faktisk viktavvikelse, diameter, tjocklek, centrumhål och nav på flera skivor. Färgkodning eller ordet competition är inget mätresultat.",
    "Beräkna möjlig stånglast med skivtjocklek och lås. En exakt men tjock skiva kan begränsa ett träningsupplägg med mycket hög belastning.",
    "Definiera återstuds- och släpprov med underlag, höjd, cykler och felkriterier. Träningsmiljön måste samtidigt ha rätt golv och regler.",
    "Ett blandat inköp kan ha tävlingsinriktade skivor på plattformar och kostnadseffektiva träningsskivor i högtrafikzoner, med tydlig lagring och märkning."
  ]
};

function guideDeepDive(profile:GuideProfile){
  const specifics=guideSpecifics[profile.id];
  if(!specifics||specifics.length!==5)throw new Error(`Swedish guide specifics missing for ${profile.id}`);
  const headings=["Arbetsscenario i praktiken","Beräkning och dimensionering","Godkännandepunkter","Drift och återbeställning","Beslutsunderlag för ledningen"];
  const frames=[
    ["Beskriv scenariot med användare, plats, belastning och tidsperiod. Markera vad som händer normalt och vad som händer vid toppbelastning eller avvikelse. Då bedöms lösningen mot verklig drift i stället för en isolerad katalogegenskap.","Tilldela varje öppen fråga en ägare och ett sista beslutsdatum. Inköp, träningsdrift, lager och leverantör kan annars göra olika antaganden om samma punkt."],
    ["Räkna med angivna enheter och visa mellanled. Vikt, antal, mått, yta, volym, cykler eller kostnad ska kunna kontrolleras av en kollega utan muntlig förklaring.","Gör en känslighetskontroll för den faktor som varierar mest. Jämför minst ett realistiskt låg-, bas- och högscenario innan budget eller artikelmix låses."],
    ["En godkännandepunkt behöver krav, metod, urval, gräns, dokument och behörig beslutsfattare. Skriv också vad som händer när resultatet ligger utanför gränsen.","Separera kritiska funktionsfel från större kommersiella fel och mindre kosmetiska avvikelser. Klassningen ska bygga på användning och avtal, inte skapas först när felet hittas."],
    ["Planera hur samma artikel kan identifieras, kompletteras, rengöras, servas och reklameras efter leverans. Produktens liv i lager och gym är en del av inköpsbeslutet.","Spara artikelversion, godkänt prov, mätdata, artwork och packinstruktion. Vid återbeställning bekräftas ändringar före materialköp så att serien inte glider obemärkt."],
    ["Sammanfatta alternativen i en sida med rekommendation, viktiga antaganden, total kostnad, huvudrisker och återstående beslut. Ledningen behöver veta vad som är verifierat och vad som fortfarande kan ändra utfallet.","Rekommendationen ska ange varför ett alternativ passar den definierade verksamheten, inte bara varför produkten verkar bäst. Lägg till stoppvillkor om prov, kostnad eller dokumentation inte når beslutad nivå."]
  ];
  const evidenceFrames=[
    "Skriv observationer som data: datum, plats, artikelversion, antal och ansvarig. Komplettera med bilder där de förklarar sammanhanget, men låt mätvärden och godkända dokument bära beslutet. Ett tydligt underlag gör det möjligt att skilja ett enstaka fel från ett återkommande processproblem.",
    "Ange alltid datakällan och om siffran är uppmätt, offererad eller uppskattad. Uppdatera beräkningen när packlista, fraktoffert eller provresultat ersätter antagandet. På så sätt ser beslutsfattaren både aktuell prognos och vilka variabler som fortfarande kan påverka den totala affären.",
    "Provresultat ska gå att härleda till exakt enhet och metod. Notera instrument, förutsättningar och eventuell osäkerhet. Om leverantör och köpare mäter olika behöver metoden harmoniseras före produktion, annars kan båda följa sin instruktion och ändå komma fram till olika beslut.",
    "Driftdata efter mottagning ger återkoppling till nästa specifikation. Registrera skador, saknade delar, slitage, användarproblem och tid för montering eller hantering per artikel och batch. Återkommande mönster prioriteras i nästa RFQ, prov eller packningsinstruktion.",
    "Bifoga den korta rekommendationen till det fullständiga underlaget. Där finns mätningar, kostnadsmodell, avvikelser och godkännanden för den som behöver granska detaljerna. Den kombinationen gör beslutet snabbt att förstå men svårt att misstolka vid order eller senare uppföljning."
  ];
  return specifics.map((specific,index)=>svText(`fordjupning-${index+1}`,headings[index],specific,...frames[index],evidenceFrames[index]));
}

export function swedishGuideVersion(profile:GuideProfile):LocalizedContentVersion{
  const slug=profile.path.split("/").pop()!;
  const index=swedishGuideProfiles.indexOf(profile);
  const images:LocalizedImage[]=[verifiedGuideImage[profile.image]??profile.image,"/assets/dumbbell-production.webp","/assets/factory-cases/packaging-area-pbf.webp"].map((src,imageIndex)=>({id:`bild-${imageIndex+1}`,src:swedishImagePath(src,slug,imageIndex),alt:imageIndex===0?`${profile.h1} – verkligt underlag`:imageIndex===1?`Verklig tillverkningsprocess kopplad till ${profile.keyword}`:"Verklig exportförpackning för gymutrustning",caption:imageIndex===0?"Befintlig PowerBaseFit-bild som stödjer guidens beslutssituation.":imageIndex===1?"Produktion används som bevis först när processen kopplas till en specifikation.":"Förpackning och pallplan påverkar både skaderisk och total kostnad."}));
  const body=[
    svAnswer("snabbt-svar","Snabbt svar",profile.answer),
    svDefinition("definition",profile.h1,profile.definition),
    svText("beslutslage","Beslutet som guiden ska stödja",profile.decision,planningAngles[index%planningAngles.length],"Definiera först vilket beslut som ska fattas, vem som godkänner det och vilket bevis som krävs. Då blir sökningen efter leverantörer, prover och offerter betydligt mer fokuserad."),
    svText("arbetsmetod","Rekommenderad arbetsmetod",profile.method,"Arbeta från behov till specifikation och därefter till leverantörsbevis. Om ordningen vänds riskerar köparen att låta den första katalogen bestämma kraven. Varje öppet val skrivs som fråga med ägare och sista beslutsdatum.","Frys inte fler egenskaper än verksamheten behöver, men lämna inte kritiska gränssnitt öppna. Mått, vikt, material, kompatibilitet, märkning och packning påverkar ofta både funktion och kostnad."),
    svTable("beslutstabell","Beslutstabell",["Område","Fråga","Bevis före beslut"],[["Användning","Vem använder eller säljer?","Målgrupp, miljö och belastning"],["Produkt","Vad ska levereras?","Artikel, version, mått och material"],["Kvalitet","Vad får avvika?","Mätmetod, tolerans och urval"],["Varumärke","Vad ska kunden se?","Artwork, prov, etikett och kartong"],["Logistik","Hur når varan lagret?","Packlista, bruttovikt, volym och Incoterm"]]),
    svText("bevis","Vilka bevis är användbara?",profile.evidence,"Bra bevis är kopplat till den aktuella produkten, har datum och version och kan kontrolleras av en annan person. En katalog, allmän certifikatbild eller obekräftad säljuppgift kan väcka en fråga men ska inte ensam stänga den.","Spara godkända filer och fysiska referenser så att nästa order kan jämföras. När material, verktyg, underleverantör eller process ändras ska leverantören flagga ändringen innan produktionen fortsätter."),
    svText("tillverkarkunskap","Förstahandskunskap från tillverkning","PowerBaseFits erfarenhet är att sena problem ofta börjar som små otydligheter i RFQ:n: en enhet saknas, ett foto används som ritning, logometoden är inte vald eller kartongen antas ingå. Därför separeras produktkrav, prov, kontroll och logistik i offertflödet.","Ett prov visar att en version kan tillverkas. Produktionskontroll visar om partiet upprepar den. Slutinspektion visar vad som är färdigt för leverans. Dessa tre nivåer ska inte blandas ihop.",planningAngles[(index+2)%planningAngles.length]),
    svText("jamforelse","Jämförelse och avvägning",profile.comparison,"Skapa en jämförelsematris där varje alternativ bedöms mot samma användning och samma kommersiella omfattning. Notera när ett alternativ kräver annan förvaring, reservdel, emballage eller utbildning.","Välj inte automatiskt högsta specifikation. Rätt nivå ger tillräcklig funktion, verifiering och livscykelvärde utan onödig kostnad eller artikelkomplexitet."),
    svText("risker","Vanliga risker och hur de minskas",profile.risk,"Gör varje större risk synlig i en risklista med sannolikhet, konsekvens, förebyggande åtgärd och ansvarig. Koppla sedan riskerna till prov, kontroll eller kommersiellt villkor.","Om leverantören föreslår en ändring ska effekten på funktion, utseende, MOQ, pris, ledtid, QC och återbeställning bedömas innan godkännande. Tyst substitution är inte en ändringsprocess."),
    ...guideDeepDive(profile),
    svText("leverantorsmote","Frågor att ta med till leverantörsmötet",`Be leverantören förklara vilket underlag som behövs för att lösa just ${profile.keyword}, vem som äger den tekniska frågan och när ett svar kan verifieras. Fråga också vilka delar som är standard, vilka som kräver kundanpassning och vilka antaganden som ligger bakom pris och ledtid.`,"Gå igenom kravlistan rad för rad och markera accepterat, avvikande eller öppet. För varje öppen punkt bestäms nästa bevis: ritning, materialuppgift, mätning, prov, packningsförslag eller kommersiellt klarläggande. Sammanfatta mötet i samma dokument och undvik parallella instruktioner i privata chattar.","Avsluta med ansvar, datum och stoppunkter före prov, materialinköp, serieproduktion, inspektion och lastning. Leverantörens snabbhet är värdefull först när svaret kan kopplas till rätt artikelversion. En fråga som saknar bevis ska förbli öppen även om båda parter tror att de menar samma sak."),
    svText("svensk-import","Svensk import och marknadsansvar","När varor importeras från ett land utanför EU behöver den svenska aktören verifiera varukod, tullvärde, tull, importmoms och eventuella restriktioner. Produkt- och kemikalieansvar kan bero på material, användning och hur varan säljs.","PowerBaseFit kan lämna produktspecifik leverantörsinformation enligt överenskommelse, men köparen ska bedöma vilka dokument och tester som krävs för den svenska marknaden. Använd Tullverket, Kemikalieinspektionen och kvalificerad rådgivning för aktuella besked."),
    svChecklist("checklista","Praktisk inköpschecklista",["Beskriv målgrupp och användningsmiljö","Lista artikel och antal per variant","Skriv mått, vikt, material och toleranser","Definiera provtyp och godkännare","Välj logo, färg, etikett och kartong","Bestäm kontrollpunkter och stickprov","Begär netto- och bruttovikt samt volym","Jämför samma Incoterm och leveranspunkt","Verifiera svenskt import- och produktansvar","Arkivera versioner för återbeställning"]),
    svText("nasta-steg","Nästa steg i inköpet","Använd checklistan för att skapa en kort brief eller RFQ. Skicka den tillsammans med artikelreferenser, volym och destination. PowerBaseFit markerar frågor som påverkar genomförbarhet, MOQ, pris, prov, inspektion eller leverans.","Nästa steg är inte alltid en offert. Om kritiska krav saknas kan ett tekniskt klargörande, materialalternativ eller provplan ge ett bättre beslut och spara tid längre fram."),
  ];
  return {locale:"sv",translationStatus:"localized",reviewStatus:"approved",publishStatus:"published",slug,publicPath:profile.path,title:profile.title,description:profile.description,h1:profile.h1,body,faq:[{id:"faq-1",question:`Vad är första steget för ${profile.keyword}?`,answer:`Börja med användning, målgrupp och vilket beslut som ska fattas. Skriv därefter produkt, volym och obligatoriska krav innan leverantör eller pris jämförs.`},{id:"faq-2",question:"Vilka uppgifter ska stå i en B2B-förfrågan?",answer:"Ange artikel, varianter, antal, material, vikt eller mått, toleranser, kundanpassning, emballage, destination, Incoterm, prov och önskad kontroll."},{id:"faq-3",question:"Räcker ett produktprov som kvalitetsbevis?",answer:"Nej. Provet blir referens för en version, men partiets jämnhet måste verifieras genom kontroll under eller efter produktion enligt avtalat urval."},{id:"faq-4",question:"När behövs tredjepartsinspektion?",answer:"Det beror på ordervärde, produktens risk, tidigare erfarenhet och köparens interna krav. Kriterier och åtkomst avtalas innan inspektionen bokas."},{id:"faq-5",question:"Vem ansvarar för svenska importkrav?",answer:"Den svenska importören och andra ekonomiska aktörer bedömer sina skyldigheter. Leverantörsdata är underlag, men ersätter inte aktuell juridisk, tull- eller produktsäkerhetsbedömning."}],author:swedishEditorialAuthor,reviewedBy:swedishTechnicalReviewer,schemaData:{brand:"PowerBaseFit",manufacturer:"PowerBaseFit",category:"B2B-inköpsguide",specifications:[{name:"Huvudämne",value:profile.keyword},{name:"Målgrupp",value:"Gymägare, distributörer, importörer och fitnessvarumärken"}],breadcrumbs:[{name:"Start",path:"/sv"},{name:"Kunskapsbank",path:"/sv/blogg"},{name:profile.h1,path:profile.path}],extra:{primaryKeyword:profile.keyword,searchIntent:"Informativ B2B-research med kommersiell nästa åtgärd"}},images,internalLinks:[...profile.links.map(([targetContentId,label])=>({targetContentId,label})),{targetContentId:"products-hub",label:"Se alla produkter"},{targetContentId:"oem-private-label",label:"OEM och eget varumärke"}],canonicalData:{mode:"self"},hreflangData:{include:true},updatedAt:"2026-07-20T12:00:00.000Z",publishedAt:"2026-07-20T12:00:00.000Z",version:1};
}
