import type { PtPageContent } from "./PtSeoPage";

export const ptOem: PtPageContent = {
  path: "/pt/oem-private-label/", englishPath: "/factory", eyebrow: "OEM e marca própria para equipamentos fitness", h1: "Equipamentos fitness OEM e private label direto da fábrica", intro: "Desenvolva halteres, anilhas, bumper plates e acessórios com sua marca, cores, especificações e embalagem para distribuição no Brasil, em Portugal e em outros mercados.", image: "/assets/pt/equipamentos-fitness-oem-marca-propria.webp", imageAlt: "Equipamentos fitness OEM e private label com marca personalizada", cta: "Falar sobre meu projeto OEM", schemaType: "Service",
  sections: [
    { eyebrow: "Serviço OEM", title: "Transforme uma especificação em uma linha de marca própria", paragraphs: ["OEM significa fabricar um produto de acordo com requisitos definidos pelo comprador, enquanto private label normalmente usa uma base de produto existente com identidade própria. Na prática, muitos projetos combinam as duas abordagens: selecionam um modelo já validado, ajustam material, cores ou detalhes e aplicam logo, marcações e embalagem. A PowerBaseFit conduz esse processo para halteres, anilhas de peso, bumper plates e outras categorias de academia.", "O desenvolvimento começa com mercado, canal de venda e faixa de preço. Uma linha para redes de academias pode priorizar durabilidade e padronização; uma marca de varejo pode precisar de embalagem, fotografia e códigos; um distribuidor pode buscar variedade e reposição. Entender a finalidade evita personalizações caras que não melhoram a proposta comercial."], bullets: ["Logo moldado, impresso, gravado ou aplicado conforme o material", "Cores, marcações em KG ou LB e detalhes de acabamento", "Caixas, etiquetas, códigos e embalagem de marca própria", "Planejamento de linha para atacado, academia e varejo"] },
    { eyebrow: "Aplicações comerciais", title: "Projetos para distribuidores, redes e novas marcas fitness", paragraphs: ["Distribuidores estabelecidos podem atualizar uma linha existente, corrigir lacunas de pesos ou criar uma família premium. Redes de academias podem padronizar identidade entre unidades e facilitar reposição. Novas marcas podem começar com poucos produtos de alta procura, desde que quantidade, investimento e diferenciação sejam realistas.", "Para o Brasil, consideramos linguagem local, preferência por quilogramas, ambiente comercial e desafios de transporte de produtos pesados. Em Portugal, a apresentação pode ser adaptada à distribuição europeia e ao público de ginásios, sem perder a prioridade de conteúdo em português brasileiro definida para este site. Em ambos os mercados, a especificação técnica precisa sustentar a promessa da marca." ] },
    { eyebrow: "Etapas principais", title: "Do briefing à produção em série", paragraphs: ["Primeiro recebemos a lista de produtos, referências, quantidades, destino e objetivo comercial. Em seguida, alinhamos materiais, faixas de peso, técnica de logo e embalagem. Quando necessário, produzimos ou selecionamos uma amostra para confirmação. Artes, cores, dimensões e marcações são aprovadas antes do lote.", "Durante a produção, os pontos de controle dependem da categoria e podem incluir acabamento, peso, montagem, impressão e embalagem. Antes do embarque, o comprador pode combinar o escopo de inspeção. Mudanças depois da aprovação podem afetar custo e prazo; por isso, uma confirmação cuidadosa no início é a forma mais eficiente de proteger o projeto."], bullets: ["Briefing de produto, mercado e quantidade", "Confirmação de especificações e viabilidade", "Aprovação de arte, amostra e embalagem", "Produção, inspeção e preparação do embarque"] },
    { eyebrow: "Especificações técnicas", title: "Decisões que precisam constar na ficha do produto", paragraphs: ["A ficha deve registrar material, dimensões, faixa de pesos, tolerâncias acordadas, cores, posição e tamanho do logo, método de marcação, embalagem e critérios de inspeção. Fotografias ajudam a comunicar intenção, mas não substituem medidas e materiais. Para produtos pesados, também definimos quantidade por caixa, proteção interna e identificação externa.", "Em linhas com vários pesos, a consistência visual merece atenção. Tipografia, escala do logo e lógica de cores devem funcionar tanto em itens pequenos quanto grandes. Os arquivos finais precisam estar em formato adequado ao processo. A equipe revisa a aplicação para reduzir problemas de legibilidade ou fabricação." ] },
    { eyebrow: "Opções de personalização", title: "Branding com equilíbrio entre impacto e custo", paragraphs: ["Nem toda personalização exige um molde novo. Impressão, placa, gravação, etiqueta e embalagem podem criar diferenciação com investimento inicial menor, dependendo do produto. Moldes e cores exclusivas podem fazer sentido para volumes maiores ou uma estratégia de longo prazo. A recomendação é escolher os elementos que o cliente final realmente percebe e valoriza.", "A embalagem também faz parte da experiência. Para venda online, proteção e clareza de identificação são essenciais; para projetos de academia, caixas funcionais e organização por peso podem ser mais importantes que apresentação de varejo. A PowerBaseFit propõe soluções adequadas ao canal, sempre sujeitas à confirmação de quantidade e transporte." ] },
    { eyebrow: "Por que PowerBaseFit", title: "Um parceiro de fabricação, não apenas aplicação de logo", paragraphs: ["Desde 2008, a PowerBaseFit trabalha com equipamentos de pesos livres e projetos de exportação. Essa experiência ajuda a relacionar personalização com processo produtivo, inspeção e embalagem. O comprador pode desenvolver halteres e anilhas dentro de uma identidade comum e combinar categorias em um plano de fornecimento.", "Nossa comunicação é orientada às decisões: o que será fabricado, como será verificado e o que o comprador precisa aprovar. Não prometemos uma solução universal. Apresentamos alternativas de material e branding para que a marca escolha com base em uso, custo e posicionamento." ] },
    { eyebrow: "Início do projeto", title: "Como pedir uma cotação OEM eficiente", paragraphs: ["Envie nome da empresa, mercado, canal de venda, produtos, pesos, quantidades estimadas e prazo desejado. Anexe logo vetorial e referências, se disponíveis. Informe se precisa de embalagem de varejo, etiquetas, códigos ou manual em português. Quanto mais claro o briefing, mais precisa será a análise de viabilidade.", "Se ainda estiver na fase de ideia, comece pelo cliente alvo e pela faixa de preço. Podemos sugerir uma seleção inicial, mas a decisão de importação deve considerar custos logísticos, impostos e requisitos locais com profissionais responsáveis no país de destino." ] }
  ],
  faqs: [
    { question: "O que é OEM em equipamentos fitness?", answer: "É a fabricação conforme especificações do comprador, que podem incluir material, medidas, cores, logo, marcações e embalagem. O nível de desenvolvimento varia de uma personalização simples a alterações de produto." },
    { question: "Qual é a quantidade mínima para colocar minha marca?", answer: "A quantidade mínima varia por produto e técnica de personalização. Impressão ou etiqueta pode exigir um volume diferente de molde ou cor exclusiva. Envie a lista e a equipe confirmará a condição aplicável." },
    { question: "Vocês ajudam com embalagem de marca própria?", answer: "Sim. Podemos avaliar caixas, etiquetas, identificação de peso e outros elementos. A solução deve considerar canal de venda, proteção necessária, quantidade e transporte internacional." },
    { question: "Como proteger a qualidade em um pedido OEM?", answer: "Use uma ficha técnica clara, aprove arte e amostra quando necessário e defina critérios de inspeção antes do lote. Mudanças devem ser registradas para que produção e comprador trabalhem com a mesma referência." }
  ]
};

export const ptFactory: PtPageContent = {
  path: "/pt/factory/", englishPath: "/factory", eyebrow: "Fábrica de equipamentos fitness na China", h1: "Fabricante de equipamentos fitness e pesos livres desde 2008", intro: "Conheça a capacidade da PowerBaseFit para fabricar halteres, anilhas de peso, bumper plates e linhas OEM destinadas a importadores, distribuidores e academias.", image: "/assets/pt/fabrica-equipamentos-fitness-china.webp", imageAlt: "Fábrica de equipamentos fitness e pesos livres PowerBaseFit na China", cta: "Solicitar preço de fábrica", schemaType: "Organization",
  sections: [
    { eyebrow: "Fábrica", title: "Produção de pesos livres para compradores internacionais", paragraphs: ["A PowerBaseFit atua na fabricação de equipamentos fitness desde 2008, com foco em halteres, anilhas, bumper plates e produtos relacionados à área de pesos livres. A unidade em Shandong, China, reúne atividades de preparação, fabricação, acabamento, inspeção, embalagem e coordenação de exportação. Atendemos projetos B2B, não vendas unitárias ao consumidor.", "Para um importador, conhecer a fábrica significa entender quais processos são controlados, como as especificações são confirmadas e como o produto é preparado para transporte. Nossa página apresenta uma visão prática da capacidade, sem substituir auditorias ou inspeções que o comprador considere necessárias."], bullets: ["Experiência de fabricação desde 2008", "Área de fábrica de aproximadamente 8.000 m²", "Halteres, anilhas, bumper plates, racks e acessórios", "Suporte a pedidos OEM e preparação para exportação"] },
    { eyebrow: "Aplicações comerciais", title: "Fornecimento para academias, distribuidores e marcas", paragraphs: ["A produção atende linhas de atacado, redes de academias, lojas, projetos de instalação e marcas próprias. Cada perfil exige uma combinação diferente de produtos e controle. Uma rede pode valorizar consistência entre unidades; um distribuidor precisa equilibrar giro, margem e reposição; uma marca premium pode exigir acabamento e embalagem superiores.", "O briefing comercial é traduzido em decisões de material, faixa de peso, quantidade, personalização e inspeção. Também avaliamos pedidos mistos com várias categorias, considerando peso e volume. Esse planejamento reduz compras desconectadas e ajuda o comprador a formar uma oferta completa." ] },
    { eyebrow: "Processo produtivo", title: "Da matéria-prima ao produto embalado", paragraphs: ["O fluxo muda conforme o produto. Halteres podem envolver preparação do núcleo, formação ou revestimento, acabamento do cabo, aplicação de marcações e montagem. Anilhas podem passar por moldagem, usinagem ou tratamento de superfície, montagem do inserto e identificação de peso. Racks exigem corte, solda, acabamento e testes de montagem.", "Em cada categoria, a ficha aprovada orienta a produção. A equipe verifica pontos relevantes como aparência, montagem, peso, marcação e embalagem. Registros e amostras de referência podem ser usados quando acordados. O objetivo é manter consistência suficiente para o uso comercial e para a apresentação da marca."], bullets: ["Preparação de materiais e componentes", "Moldagem, usinagem, solda ou acabamento conforme o produto", "Aplicação de logo, marcações e detalhes", "Inspeção, embalagem, paletização e carregamento"] },
    { eyebrow: "Controle de qualidade", title: "Inspeção baseada na especificação aprovada", paragraphs: ["Qualidade não deve ser definida apenas por uma fotografia. Antes da produção, comprador e fábrica precisam concordar sobre material, dimensões, faixa de peso, aparência, embalagem e tolerâncias relevantes. Durante e após o lote, os controles são ajustados ao risco da categoria.", "A inspeção pode verificar acabamento superficial, legibilidade, união de componentes, peso, quantidade, estado das caixas e preparação do embarque. Testes específicos devem ser definidos previamente. O comprador também pode organizar inspeção independente quando isso fizer parte de sua política de aquisição." ] },
    { eyebrow: "OEM e marca própria", title: "Capacidade de personalização integrada à produção", paragraphs: ["A fábrica apoia logo, cores, marcações, detalhes de acabamento e embalagem personalizada. A técnica varia: moldagem, impressão, gravação, inserto ou etiqueta podem ser adequados a diferentes materiais. A viabilidade e a quantidade mínima são confirmadas por projeto.", "Para linhas com várias categorias, buscamos consistência de identidade entre produtos. Artes e amostras precisam ser aprovadas antes do lote. Esse processo permite que distribuidores e marcas construam uma apresentação própria sem perder de vista resistência, custo e prazo." ] },
    { eyebrow: "Exportação", title: "Embalagem e comunicação para pedidos internacionais", paragraphs: ["Pesos livres exigem atenção especial porque concentram muita massa em pouco volume. Caixas, proteção, pallets e carregamento precisam ser planejados para limitar danos e facilitar a conferência. O método varia com produto, quantidade, rota e exigências do comprador.", "Nossa equipe comercial coordena dados de produto e preparação do embarque com compradores internacionais. Prazo depende do lote, da personalização, da disponibilidade de materiais e do cronograma confirmado. Informações completas no início ajudam a produzir uma estimativa mais confiável." ] },
    { eyebrow: "Por que PowerBaseFit", title: "Experiência e transparência para avaliar um fornecedor", paragraphs: ["Escolher uma fábrica envolve capacidade técnica, comunicação, estabilidade, documentação e disposição para confirmar detalhes. A experiência da PowerBaseFit em pesos livres permite discutir alternativas de materiais e construção com foco no uso final. Também oferecemos uma linha ampla para compradores que precisam consolidar categorias.", "Recomendamos que todo comprador compare amostras, especificações, condições comerciais e critérios de inspeção. Nosso objetivo é fornecer informações claras para essa avaliação e construir relações de fornecimento sustentáveis com distribuidores, academias e marcas do Brasil e de Portugal." ] }
  ],
  faqs: [
    { question: "Onde fica a fábrica da PowerBaseFit?", answer: "A fábrica fica em Ningjin, Dezhou, província de Shandong, China. A PowerBaseFit atende compradores internacionais de equipamentos fitness e pesos livres." },
    { question: "Quais produtos a fábrica produz?", answer: "O foco inclui halteres, anilhas de peso, bumper plates, racks, bancos e acessórios relacionados. A disponibilidade e a configuração são confirmadas conforme a lista do projeto." },
    { question: "Como a fábrica controla a qualidade?", answer: "Os controles podem incluir material, acabamento, peso, montagem, marcação, quantidade e embalagem, conforme a especificação aprovada. Testes ou inspeções adicionais devem ser combinados antes do pedido." },
    { question: "A fábrica envia equipamentos para o Brasil e Portugal?", answer: "Sim. A equipe apoia projetos internacionais e prepara a mercadoria para exportação. Frete, impostos, documentação e requisitos locais devem ser confirmados para cada destino." }
  ]
};
