import type { PtPageContent } from "./PtSeoPage";

export const ptHome: PtPageContent = {
  path: "/pt/", englishPath: "/", eyebrow: "Equipamentos profissionais para academias",
  h1: "Fabricante de equipamentos fitness para academias e marcas",
  intro: "A PowerBaseFit fabrica halteres, anilhas de peso, bumper plates e acessórios para distribuidores, importadores, redes de academias e projetos de marca própria no Brasil e em Portugal.",
  image: "/assets/pt/equipamentos-profissionais-academias.webp", imageAlt: "Equipamentos profissionais para academias fabricados pela PowerBaseFit", cta: "Pedir catálogo e cotação", schemaType: "Organization",
  sections: [
    { eyebrow: "Produto", title: "Linha de pesos livres para uso profissional", paragraphs: ["Nossa linha foi organizada para compradores que precisam montar uma área completa de musculação, abastecer lojas especializadas ou desenvolver uma coleção própria. Produzimos halteres sextavados de borracha, halteres redondos em PU ou TPU, anilhas olímpicas, bumper plates, barras, bancos, racks e acessórios. Cada projeto começa pela aplicação, faixa de peso, sistema em quilogramas ou libras, posicionamento de preço e frequência de uso esperada.", "Para o mercado brasileiro, ajudamos a selecionar produtos com boa resistência ao uso intenso, identificação clara de peso e manutenção simples. Para Portugal, também planejamos marcações, embalagem e documentação adequadas à distribuição europeia. O objetivo não é oferecer um catálogo genérico, mas transformar a necessidade comercial do comprador em uma linha coerente, fácil de vender e de recomprar."], bullets: ["Halteres profissionais em borracha, PU, TPU, aço e ferro fundido", "Anilhas de peso e anilhas olímpicas para barras de 50 mm", "Bumper plates para levantamento olímpico e treinamento funcional", "Racks, bancos e acessórios para áreas completas de musculação"] },
    { eyebrow: "Aplicações comerciais", title: "Soluções para academias, distribuidores e projetos fitness", paragraphs: ["Uma academia de alto fluxo precisa de equipamentos diferentes de um estúdio boutique, condomínio ou loja. Por isso avaliamos número de usuários, tipo de treino, espaço disponível, faixa de pesos e expectativa de vida útil. Distribuidores podem combinar produtos de giro rápido com itens premium; redes de academias podem padronizar medidas, cores e identidade visual entre unidades; marcas digitais podem começar com uma seleção enxuta e embalagem própria.", "Também apoiamos pedidos mistos para aproveitar melhor o contêiner. Halteres, anilhas, suportes e acessórios podem ser planejados como um programa comercial único, reduzindo lacunas no portfólio. Antes da produção, confirmamos especificações, artes de logo, cores e método de embalagem para que o produto recebido corresponda ao posicionamento definido pelo cliente." ] },
    { eyebrow: "Características principais", title: "Desenvolvimento pensado para compras B2B", paragraphs: ["A compra profissional exige consistência entre lotes, comunicação clara e controle de detalhes. A PowerBaseFit trabalha com confirmação de amostra quando necessário, inspeção de acabamento, verificação de marcações e revisão da embalagem antes do embarque. Materiais e processos variam conforme a categoria, mas o fluxo comercial mantém pontos de controle para reduzir diferenças entre o pedido aprovado e a produção em série.", "Nossa equipe atende solicitações de distribuidores e fabricantes de marcas fitness que precisam comparar alternativas de material, custo e durabilidade. Em vez de indicar sempre a opção mais cara, relacionamos cada acabamento ao ambiente de uso e ao público final. Isso ajuda a construir uma oferta competitiva tanto para academias populares quanto para clubes premium."], bullets: ["Planejamento de faixas em KG ou LB", "Inspeção visual, marcação de peso e conferência de embalagem", "Pedidos para atacado, projetos de academia e marca própria", "Comunicação de exportação e preparação para transporte internacional"] },
    { eyebrow: "Especificações técnicas", title: "Configurações definidas conforme a categoria", paragraphs: ["As especificações incluem material externo, núcleo, diâmetro de pegada, tolerância de peso, sistema de marcação, cor, dimensões e embalagem. Em anilhas e bumper plates, confirmamos o diâmetro do furo central, compatibilidade com barras olímpicas e composição. Em halteres, avaliamos formato da cabeça, acabamento da empunhadura, união entre cabeça e cabo e sequência de pesos.", "Como os requisitos mudam entre linhas econômicas, comerciais e premium, os valores finais são registrados na ficha do projeto. O comprador recebe uma proposta baseada na configuração solicitada, e não apenas em uma foto de catálogo. Essa abordagem facilita a comparação de fornecedores e reduz dúvidas durante a inspeção." ] },
    { eyebrow: "OEM e marca própria", title: "Personalização para construir uma linha reconhecível", paragraphs: ["O programa OEM pode incluir logo em relevo, impressão, placa de identificação, cores personalizadas, marcações em português, embalagem individual, etiquetas de caixa e manual. A viabilidade depende do material, do processo e da quantidade. Primeiro analisamos a arte e o produto; depois indicamos a técnica de aplicação com melhor equilíbrio entre aparência, resistência e custo.", "Para marcas que estão entrando no mercado, também podemos organizar uma família visual consistente entre halteres e anilhas. A mesma paleta, tipografia de peso e lógica de embalagem reforçam a identidade na loja e na academia. Antes do lote, as artes e posições de logo precisam ser aprovadas para evitar alterações tardias." ] },
    { eyebrow: "Por que PowerBaseFit", title: "Experiência de fábrica com foco em exportação", paragraphs: ["Desde 2008, a PowerBaseFit atende compradores internacionais de pesos livres e equipamentos fitness. A fábrica em Shandong integra produção, acabamento, inspeção e preparação de embarques. Essa experiência é relevante para quem precisa coordenar produtos pesados, embalagens resistentes e cronogramas de contêiner.", "Nosso papel é tornar a compra mais previsível: entender o mercado, confirmar especificações, apresentar opções de personalização e preparar a mercadoria para inspeção e transporte. Compradores do Brasil e de Portugal recebem atendimento para projetos comerciais, atacado e marca própria, com comunicação orientada às decisões necessárias antes da produção." ] },
    { eyebrow: "Próximos passos", title: "Como solicitar uma proposta útil", paragraphs: ["Informe o país de destino, categorias desejadas, faixa de pesos, quantidade aproximada, necessidade de logo e tipo de cliente final. Se houver referências visuais ou especificações obrigatórias, anexe os arquivos. Com essas informações, conseguimos selecionar produtos compatíveis e explicar o que pode ser personalizado.", "Para projetos de academia, inclua o número de unidades e uma estimativa do espaço. Para distribuição, indique o posicionamento de preço e os canais de venda. Uma solicitação completa acelera a cotação e permite comparar soluções de forma mais precisa." ] }
  ],
  faqs: [
    { question: "Como escolher um fornecedor de equipamentos fitness?", answer: "Comece avaliando experiência na categoria, capacidade de personalização, controle de qualidade e comunicação de exportação. Depois confirme amostras, especificações, embalagem, prazo e critérios de inspeção antes de aprovar o pedido em série." },
    { question: "A PowerBaseFit atende compradores do Brasil?", answer: "Sim. Atendemos importadores, distribuidores, redes de academias e marcas brasileiras com linhas em quilogramas, opções OEM, embalagem de exportação e planejamento de pedidos mistos." },
    { question: "É possível comprar produtos com marca própria?", answer: "Sim. Dependendo do produto e da quantidade, é possível personalizar logo, cores, marcações, etiquetas e embalagem. A equipe confirma a técnica e o custo após analisar a arte e a especificação." },
    { question: "Posso combinar halteres e anilhas no mesmo pedido?", answer: "Sim. Pedidos mistos podem reunir halteres, anilhas, bumper plates, racks e acessórios. A combinação precisa considerar peso, volume, proteção de embalagem e aproveitamento do contêiner." }
  ]
};

export const ptDumbbells: PtPageContent = {
  path: "/pt/products/dumbbells/", englishPath: "/products/dumbbells", eyebrow: "Halteres para academias e atacado", h1: "Halteres profissionais com fabricação OEM e marca própria", intro: "Halteres sextavados de borracha, redondos em PU e TPU, cromados e ajustáveis para academias, distribuidores e marcas fitness que buscam fornecimento direto de fábrica.", image: "/assets/pt/halteres-borracha-profissionais.webp", imageAlt: "Halteres sextavados de borracha profissionais para academia", cta: "Solicitar cotação de halteres", schemaType: "Product", productCategory: "Halteres profissionais",
  sections: [
    { eyebrow: "Produto", title: "Halteres para uso comercial e linhas de distribuição", paragraphs: ["Halteres são um dos produtos mais utilizados em academias, estúdios e áreas de treinamento funcional. Para compras profissionais, formato e preço não são os únicos critérios: material externo, segurança da união entre cabeça e cabo, conforto da pegada, legibilidade do peso e consistência do conjunto influenciam a experiência diária. A PowerBaseFit produz modelos para diferentes níveis de uso e posicionamento comercial.", "A linha inclui halteres sextavados de borracha, modelos redondos em PU, TPU ou CPU, halteres cromados, ferro fundido, neoprene e opções ajustáveis. Podemos planejar sequências em quilogramas ou libras, pares avulsos, jogos completos e combinação com racks. O modelo recomendado depende do ambiente, do orçamento e do público da marca."], bullets: ["Halteres sextavados que reduzem o rolamento no piso", "Modelos redondos em PU, TPU e CPU para academias premium", "Opções cromadas, em ferro fundido, neoprene e ajustáveis", "Faixas em KG ou LB com racks compatíveis"] },
    { eyebrow: "Aplicações comerciais", title: "Qual halter funciona melhor em cada academia?", paragraphs: ["Em academias de alto fluxo, a prioridade costuma ser resistência, manutenção simples e reposição previsível. Halteres sextavados de borracha são versáteis para treinamento funcional e musculação; modelos redondos em PU ou TPU oferecem acabamento mais uniforme e boa apresentação em clubes premium. Estúdios menores podem combinar pesos leves e médios, enquanto academias completas precisam de uma progressão mais longa.", "Distribuidores devem considerar não apenas o usuário final, mas também transporte, exposição e reposição. Uma sequência bem planejada evita excesso de pesos pouco procurados e falta dos pesos de maior giro. Para redes de academias, padronizar logo, marcações e racks facilita a implantação em várias unidades e fortalece a identidade visual." ] },
    { eyebrow: "Características principais", title: "Construção, pegada e acabamento para uso frequente", paragraphs: ["A sensação de qualidade começa na empunhadura. Diâmetro, textura, largura e acabamento precisam oferecer aderência sem desconforto. A cabeça deve permanecer firme durante movimentos repetidos e impactos compatíveis com o uso previsto. No processo de desenvolvimento, confirmamos material, tipo de cabo, formato, marcação e requisitos de inspeção.", "Borracha, PU e TPU apresentam diferenças de aparência, odor, resistência e custo. A escolha deve considerar ventilação do ambiente, intensidade de uso e posicionamento do produto. A PowerBaseFit apresenta alternativas para que o comprador compare vantagens reais, evitando especificações excessivas que não geram valor para o mercado alvo."], bullets: ["Empunhaduras recartilhadas e opções de acabamento cromado", "Identificação de peso legível para organização do salão", "Formatos sextavados, redondos, quadrados e de doze lados", "Verificação visual e de montagem antes da embalagem"] },
    { eyebrow: "Especificações técnicas", title: "Faixas de peso, materiais e apresentação", paragraphs: ["As faixas podem ser configuradas em quilogramas ou libras conforme o destino. O comprador define incrementos, peso inicial e peso máximo; a fábrica confirma a disponibilidade do modelo. Também são definidos material da cabeça, composição do revestimento, tipo de cabo, cores, logo, marcação e embalagem. Quando o conjunto inclui rack, avaliamos capacidade, espaçamento e organização.", "A tolerância de peso e os métodos de teste devem ser acordados para cada projeto. Produtos destinados a treinamento comercial exigem critérios diferentes de halteres decorativos ou residenciais. Registrar os requisitos na aprovação da amostra cria uma referência objetiva para produção e inspeção." ] },
    { eyebrow: "OEM e marca própria", title: "Logo, cores, marcações e embalagem personalizadas", paragraphs: ["Halteres oferecem várias possibilidades de marca própria: logo moldado na cabeça, placa ou inserto, impressão, gravação no cabo, cores de detalhes e etiquetas de embalagem. A melhor técnica depende do revestimento e da quantidade. Avaliamos a arte para preservar legibilidade e resistência durante o uso.", "Também podemos alinhar a apresentação do conjunto ao restante da linha fitness. Tipografia de peso, paleta de cores, caixas e etiquetas podem seguir o padrão da marca. Para reduzir retrabalho, o comprador aprova dimensões, posição do logo e arquivos de impressão antes do início da produção em série." ] },
    { eyebrow: "Por que PowerBaseFit", title: "Fornecedor de halteres com visão de projeto completo", paragraphs: ["A PowerBaseFit combina experiência em pesos livres, produção OEM e preparação de pedidos internacionais. Isso permite planejar não só um modelo isolado, mas a sequência de pesos, racks, anilhas e acessórios que formam uma área comercial. Compradores recebem orientação sobre opções de material, embalagem e aproveitamento de carga.", "Durante o projeto, mantemos pontos de confirmação para especificações e artes. A inspeção considera aparência, marcação, montagem e proteção da embalagem. Essa disciplina ajuda distribuidores e academias a receber uma linha consistente e adequada ao posicionamento definido." ] },
    { eyebrow: "Compra profissional", title: "Informações necessárias para cotar halteres", paragraphs: ["Envie o tipo de halter, faixa completa de pesos, quantidade por peso, sistema KG ou LB, país de destino e necessidade de logo. Informe também se precisa de rack, embalagem para varejo ou embalagem comercial. Fotos de referência ajudam a identificar o acabamento desejado, mas a especificação final deve confirmar materiais e dimensões.", "Para uma academia, indique o número esperado de usuários e o perfil do espaço. Para distribuição, compartilhe o nível de preço e o canal de venda. Esses dados permitem sugerir um conjunto mais adequado e preparar uma cotação comparável." ] }
  ],
  faqs: [
    { question: "Qual é o melhor halter para uma academia profissional?", answer: "Para uso intenso, halteres sextavados de borracha e modelos redondos em PU ou TPU são escolhas frequentes. O melhor modelo depende do fluxo de usuários, do tipo de treino, do orçamento e da importância do acabamento visual." },
    { question: "Halter sextavado de borracha vale a pena?", answer: "Sim. O formato reduz o rolamento e funciona bem em musculação e treino funcional. Antes da compra, verifique qualidade da borracha, fixação do cabo, conforto da pegada, marcação de peso e política de reposição." },
    { question: "Posso colocar minha marca nos halteres?", answer: "Sim. Logo moldado, impressão, placa, gravação e embalagem personalizada podem ser avaliados. A técnica disponível depende do modelo, do material e da quantidade do pedido." },
    { question: "Quais informações preciso enviar para receber preço?", answer: "Envie o modelo, faixa em KG ou LB, quantidade por peso, logo, embalagem, rack desejado e país de destino. Assim a fábrica pode calcular uma proposta adequada ao projeto." }
  ]
};

export const ptWeightPlates: PtPageContent = {
  path: "/pt/products/weight-plates/", englishPath: "/products/weight-plates", eyebrow: "Anilhas de peso para uso profissional", h1: "Anilhas olímpicas e anilhas de peso direto do fabricante", intro: "Anilhas de borracha, ferro fundido, PU e TPU para academias, distribuidores e marcas próprias, com opções em KG ou LB e personalização OEM.", image: "/assets/pt/anilhas-olimpicas-profissionais.webp", imageAlt: "Anilhas olímpicas profissionais para academias e distribuidores", cta: "Pedir cotação de anilhas", schemaType: "Product", productCategory: "Anilhas de peso e anilhas olímpicas",
  sections: [
    { eyebrow: "Produto", title: "Anilhas de peso para barras, máquinas e áreas de musculação", paragraphs: ["Anilhas de peso são usadas em barras olímpicas, equipamentos plate loaded e estações de força. Uma linha profissional precisa combinar compatibilidade, identificação rápida, acabamento resistente e boa experiência de manuseio. A PowerBaseFit fabrica anilhas olímpicas com diferentes materiais e desenhos para projetos de academia, atacado e marca própria.", "O portfólio inclui anilhas de borracha, ferro fundido, aço, PU, TPU, modelos com pegadas e versões coloridas. Também fornecemos bumper plates, tratados em uma página específica por terem aplicação e construção próprias. Para cada projeto, definimos faixa de peso, diâmetro central, marcações, cores e embalagem."], bullets: ["Anilhas olímpicas com furo para barras de 50 mm", "Modelos de borracha, ferro fundido, aço, PU e TPU", "Anilhas com pegada para movimentação no salão", "Sistemas em KG ou LB para diferentes mercados"] },
    { eyebrow: "Aplicações comerciais", title: "Como escolher anilhas para academias e revenda", paragraphs: ["Academias convencionais costumam buscar anilhas resistentes, fáceis de identificar e de movimentar entre barras e máquinas. Modelos com pegada ajudam no manuseio; revestimentos de borracha podem proteger melhor o ambiente e reduzir ruído em comparação com ferro sem revestimento. Clubes premium podem priorizar acabamento em PU ou TPU e uma identidade visual mais refinada.", "Para distribuidores, a decisão deve considerar demanda local, faixa de preços, peso de transporte e disponibilidade de reposição. Uma coleção pode reunir anilhas econômicas e uma família premium, mas cada uma precisa ter uma proposta clara. A PowerBaseFit ajuda a estruturar pesos e quantidades para evitar um mix desequilibrado." ] },
    { eyebrow: "Características principais", title: "Centro, revestimento e marcações que influenciam o uso", paragraphs: ["O furo central deve ser compatível com a barra e manter um encaixe adequado. Inserto, acabamento da borda, espessura e distribuição do material afetam manuseio e durabilidade. Em modelos revestidos, a aderência entre núcleo e camada externa também merece atenção. Confirmamos os pontos técnicos conforme o desenho escolhido.", "Marcações legíveis melhoram a organização da academia. Cores podem seguir convenções de peso ou identidade da marca, desde que sejam aprovadas com referência visual. Antes do embarque, a inspeção pode incluir acabamento, identificação, furo central, peso e condição da embalagem."], bullets: ["Furo central e inserto adequados a barras olímpicas", "Identificação clara de peso e opções de cores", "Formatos com pegadas para facilitar carga e armazenamento", "Proteção de embalagem para produtos densos e pesados"] },
    { eyebrow: "Especificações técnicas", title: "Peso, dimensões e materiais definidos por projeto", paragraphs: ["As especificações incluem pesos disponíveis, tolerância, diâmetro do furo, diâmetro externo, espessura, material do núcleo, revestimento e método de marcação. Em pedidos em libras, ajustamos a sequência e a apresentação ao mercado. Em pedidos em quilogramas, planejamos incrementos compatíveis com academias e lojas do Brasil ou de Portugal.", "Nem toda anilha deve ter o mesmo diâmetro externo; isso depende do tipo e da aplicação. Bumper plates normalmente seguem dimensões próprias para levantamento. Anilhas convencionais podem variar para reduzir volume. A ficha aprovada evita comparar produtos apenas pela aparência." ] },
    { eyebrow: "OEM e marca própria", title: "Anilhas personalizadas para marcas fitness", paragraphs: ["A personalização pode incluir logo em relevo, impressão, placa, cor do revestimento, marcação em português e embalagem. Também é possível desenvolver uma linguagem visual coerente entre diferentes pesos e entre anilhas e halteres. A equipe confirma o processo adequado depois de analisar arte, material e volume.", "Para distribuidores, etiquetas de caixa, códigos e organização por peso facilitam recebimento e estoque. Esses detalhes devem ser definidos antes da produção. Quando necessário, uma amostra ou imagem de aprovação serve de referência para posição, escala e cor do logo." ] },
    { eyebrow: "Por que PowerBaseFit", title: "Experiência em pesos livres e logística internacional", paragraphs: ["Anilhas são produtos compactos, densos e exigentes para transporte. A PowerBaseFit combina conhecimento de fabricação com planejamento de embalagem e carga, ajudando o comprador a proteger acabamento e organizar caixas. Pedidos podem incluir outras categorias para formar uma oferta completa de pesos livres.", "Atendemos projetos de academia, importadores e marcas próprias com confirmação de especificações e suporte de exportação. O foco é entregar uma linha coerente com o uso, a faixa de preço e o mercado de destino, sem depender de descrições genéricas de catálogo." ] },
    { eyebrow: "Compra profissional", title: "Prepare uma solicitação de cotação completa", paragraphs: ["Informe o tipo de anilha, material desejado, pesos e quantidades, sistema KG ou LB, diâmetro central, logo e embalagem. Se o produto será usado em barras, máquinas ou levantamento, explique a aplicação. O país e o porto de destino também ajudam a planejar proposta e transporte.", "Caso ainda não tenha uma especificação fechada, compartilhe o público alvo e a faixa de preço. Podemos apresentar alternativas e explicar diferenças entre ferro fundido, borracha, PU e TPU para que a decisão seja comercialmente justificável." ] }
  ],
  faqs: [
    { question: "Qual a diferença entre anilha olímpica e anilha comum?", answer: "A anilha olímpica normalmente utiliza furo central compatível com barras de 50 mm. Anilhas comuns podem usar outros diâmetros. Sempre confirme barra, máquina e aplicação antes de definir o produto." },
    { question: "Qual material de anilha é melhor para academia?", answer: "Borracha oferece uma solução versátil; PU e TPU são usados em linhas premium; ferro fundido pode ser econômico e compacto. A melhor escolha depende de fluxo, ambiente, orçamento e posicionamento." },
    { question: "É possível fabricar anilhas com logo próprio?", answer: "Sim. Logo, cores, marcações e embalagem podem ser personalizados conforme o modelo e a quantidade. A arte deve ser avaliada e aprovada antes do lote." },
    { question: "As anilhas podem ser fornecidas em quilogramas e libras?", answer: "Sim. A faixa pode ser planejada em KG ou LB. Pesos, incrementos, marcações e quantidades precisam ser confirmados na especificação do pedido." }
  ]
};

export const ptBumperPlates: PtPageContent = {
  path: "/pt/products/bumper-plates/", englishPath: "/products/weight-plates", eyebrow: "Bumper plates para treinamento profissional", h1: "Bumper plates olímpicos para academias e marca própria", intro: "Bumper plates de borracha para levantamento olímpico, boxes, estúdios funcionais e distribuidores, com séries em KG ou LB, logo e cores personalizados.", image: "/assets/pt/bumper-plates-olimpicos.webp", imageAlt: "Bumper plates olímpicos de borracha para academia profissional", cta: "Solicitar cotação de bumper plates", schemaType: "Product", productCategory: "Bumper plates olímpicos",
  sections: [
    { eyebrow: "Produto", title: "Discos desenvolvidos para levantamento e treino funcional", paragraphs: ["Bumper plates são anilhas de diâmetro externo uniforme, produzidas para exercícios em que a barra pode retornar ao piso de forma controlada. São comuns em levantamento olímpico, treinamento funcional, boxes e áreas específicas de academias. O desempenho depende da composição da borracha, construção do centro, dureza, tolerância de peso e qualidade do acabamento.", "A PowerBaseFit fornece modelos de treino, coloridos, pretos, compactos e de competição conforme disponibilidade e requisitos do projeto. Compradores podem definir séries em quilogramas ou libras, identidade visual e embalagem. Para escolher corretamente, é importante informar o tipo de uso e a frequência esperada, não apenas a cor."], bullets: ["Bumper plates pretos ou coloridos", "Séries em KG e LB para academias e distribuidores", "Opções para treino funcional e levantamento olímpico", "Logo, marcação de peso e embalagem OEM"] },
    { eyebrow: "Aplicações comerciais", title: "Bumper plates para boxes, academias e centros esportivos", paragraphs: ["Boxes e áreas de levantamento precisam considerar piso, plataforma, ruído, volume de treino e comportamento dos usuários. Bumper plates ajudam a criar uma solução apropriada para movimentos do solo, mas não eliminam a necessidade de técnica e piso adequados. A seleção deve equilibrar durabilidade, espessura e custo por conjunto.", "Academias generalistas podem usar uma série enxuta em uma zona funcional, enquanto centros de performance exigem mais pares e reposição planejada. Para distribuição, versões pretas costumam atender uma faixa ampla de preço; linhas coloridas ou de competição podem ocupar um posicionamento mais especializado. A especificação correta evita vender um produto de treino como se fosse certificado para competição." ] },
    { eyebrow: "Características principais", title: "Rebote, dureza e inserto central sob controle", paragraphs: ["A composição do material afeta odor, aparência, rebote e resistência ao desgaste. O inserto central precisa permanecer estável e encaixar corretamente na barra. Espessura também influencia quantos discos cabem na manga durante cargas altas. Esses fatores devem ser comparados junto com a tolerância de peso.", "Na inspeção, podem ser verificados acabamento, marcação, furo central, peso e consistência do lote. A embalagem precisa proteger bordas e superfícies sem criar volume desnecessário. Para projetos OEM, cores e logo são avaliados dentro das limitações do processo escolhido."], bullets: ["Diâmetro externo uniforme conforme o modelo", "Inserto central para barras olímpicas", "Opções de dureza e formulação para diferentes níveis de uso", "Marcação visual clara para seleção rápida"] },
    { eyebrow: "Especificações técnicas", title: "Defina a série pelo uso, não somente pela aparência", paragraphs: ["Uma especificação de bumper plate deve registrar pesos, sistema KG ou LB, diâmetro externo, espessura por peso, diâmetro central, tolerância, dureza, material e método de marcação. Se houver exigências normativas ou de competição, elas precisam ser declaradas e documentadas, pois um disco colorido não é automaticamente um disco de competição.", "Também é importante informar o tipo de piso e a altura provável de queda. Nenhum bumper plate é indestrutível, e uso inadequado reduz a vida útil. A combinação entre produto, plataforma, barra e orientação ao usuário cria um sistema mais durável." ] },
    { eyebrow: "OEM e marca própria", title: "Cores e branding para diferenciar a linha", paragraphs: ["Bumper plates podem receber logo, marcação de peso, combinação de cores e embalagem de marca própria. A personalização pode ser moldada, impressa ou aplicada por outra técnica compatível com o modelo. Quantidades mínimas e custos variam, por isso avaliamos cada arte antes de confirmar.", "Uma família bem planejada mantém legibilidade entre pesos e coerência nas fotografias de produto. Para o Brasil e Portugal, textos e etiquetas podem ser organizados em português. Códigos de caixa e identificação externa facilitam a separação de pesos no recebimento." ] },
    { eyebrow: "Por que PowerBaseFit", title: "Produção OEM integrada à linha de pesos livres", paragraphs: ["A PowerBaseFit fabrica e fornece bumper plates junto com halteres, anilhas, barras, racks e bancos. Essa amplitude ajuda distribuidores a completar o portfólio e academias a montar uma área coordenada. O pedido pode ser planejado com produtos complementares e embalagem adequada ao transporte internacional.", "Nossa equipe confirma aplicação, série, personalização e inspeção antes do lote. Esse processo reduz ambiguidades e permite que o comprador compare configurações reais. A experiência desde 2008 oferece uma base prática para projetos de atacado e marca própria." ] },
    { eyebrow: "Compra profissional", title: "O que enviar para receber uma proposta", paragraphs: ["Informe se o uso será em box, academia, centro de performance ou revenda; envie pesos, quantidades, KG ou LB, cor, logo e país de destino. Se deseja modelo de treino ou competição, explique os requisitos técnicos. Fotografias podem orientar o estilo, mas não substituem a ficha de especificação.", "Inclua barras, plataformas ou racks caso queira uma solução combinada. Com uma lista completa, a fábrica consegue sugerir melhor distribuição de quantidades e preparar uma cotação mais próxima da operação real." ] }
  ],
  faqs: [
    { question: "O que é bumper plate e para que serve?", answer: "É uma anilha de diâmetro externo uniforme, geralmente produzida com borracha, destinada a movimentos de levantamento em que a barra pode voltar ao piso de forma controlada. Deve ser usada com barra e piso adequados." },
    { question: "Qual bumper plate escolher para uma academia?", answer: "Avalie frequência de uso, composição, dureza, rebote, espessura, inserto central e tolerância de peso. Para uma zona funcional, um modelo de treino resistente costuma ser mais adequado que uma opção escolhida apenas pela cor." },
    { question: "Bumper plate colorido é sempre de competição?", answer: "Não. A cor pode apenas identificar o peso. Se o projeto exige padrão de competição, confirme dimensões, tolerâncias e documentação específica com o fornecedor." },
    { question: "É possível personalizar bumper plates com logo?", answer: "Sim. Logo, cores, marcações e embalagem podem ser personalizados conforme o processo e a quantidade. A arte e a técnica precisam ser aprovadas antes da produção." }
  ]
};
