import fs from "node:fs/promises";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const outputPath = "C:/Users/Kloe/Desktop/Daily_Fitness_B2B_Lead_Report.xlsx";
const previewDir = "C:/Users/Kloe/Documents/chinafreeweight独立站/.codex_work/lead_report_20260722/previews";

const headers = [
  "No", "Name", "Country", "Position", "Company", "LinkedIn URL", "Website",
  "Facebook", "Instagram", "YouTube", "Main Products", "Customer Type",
  "Quality Score", "Why Suitable", "WhatsApp Development Angle", "WhatsApp Message",
];

const leads = [
  [1, "Juan Carlos Gonzalez", "United States", "CEO", "Best Used Gym Equipment", "https://www.linkedin.com/in/juan-carlos-gonzalez-67b87038", "https://www.bestusedgymequipment.com/", "https://www.facebook.com/BUGYMEQUIPMENT/", "https://www.instagram.com/bestusedgymequipment/", "http://www.youtube.com/@bestusedgymequipmentusa", "Free weights, benches, plate-loaded strength, cardio equipment and accessories", "International new and pre-owned commercial gym equipment distributor", "A", "CEO-level contact at a worldwide commercial equipment distributor with strong reputation and a catalog that already includes free weights and custom gym packages.", "Complement used-equipment packages with factory-direct new and private-label free weights.", "Hi Juan, I noticed Best Used Gym Equipment supplies complete new and pre-owned commercial packages worldwide. ChinaFreeWeight is a dumbbell, weight-plate and free-weight factory with OEM capability, and we could complement your packages with reliable new private-label lines. Would you be open to discussing cooperation?"],
  [2, "David K.", "United States", "Founder & President", "Body Basics Fitness Equipment", "https://www.linkedin.com/in/david-k-4b55184", "https://bodybasics.com/", "https://www.facebook.com/BodyBasicsFitnessEquipment/", "https://www.instagram.com/bodybasicsomaha/", "", "Dumbbells, kettlebells, medicine balls, weight plates, strength and cardio equipment", "Established commercial and residential fitness equipment dealer", "A+", "Founder-led dealer established in 1986 with an excellent local reputation and a direct category fit across dumbbells, plates and commercial strength equipment.", "Develop an OEM or private-label free-weight range for Body Basics' commercial and home clients.", "Hi David, Body Basics' long history and broad dumbbell, plate and strength range stood out to me. ChinaFreeWeight is a dumbbell, weight-plate and free-weight factory offering OEM and private-label production. Could we discuss a cooperation fit for your commercial and home-gym customers?"],
  [3, "Leo Chang", "United States", "President", "BodyKore Fitness Equipment", "https://www.linkedin.com/in/leo-chang-71200619a", "https://www.bodykore.com/", "https://www.facebook.com/BodyKore/", "https://www.instagram.com/bodykore/", "https://www.youtube.com/user/BodyKore", "Plate-loaded equipment, weights, benches, racks and accessories", "Commercial/home fitness wholesaler and dealer-network brand", "A", "President of a verified wholesaler with a dealer network, commercial positioning and adjacent plate-loaded and free-weight categories.", "Extend BodyKore's dealer assortment with OEM dumbbells, plates and coordinated storage.", "Hi Leo, BodyKore's dealer network and plate-loaded product range look closely aligned with our capabilities. ChinaFreeWeight manufactures dumbbells, weight plates and other free weights with OEM options. Would you be interested in discussing a coordinated product line for your dealers and commercial customers?"],
  [4, "Roman Dombrovsky", "United States", "Founder & CEO", "Equip Your Gym", "https://www.linkedin.com/in/roman-dombrovsky-09552a226", "https://equipyourgym.com/", "https://www.facebook.com/EquipYourGym/", "https://www.instagram.com/EquipYourGym/", "https://www.youtube.com/equipyourgym", "Olympic plates, bars, racks, strength/cardio equipment, flooring and accessories", "Wholesale, remanufactured and rental commercial equipment dealer", "A", "Founder-level contact at a verified wholesale commercial supplier whose gym packages already include Olympic plates, bars, racks and accessories.", "Add consistent new OEM free weights to remanufactured and wholesale facility packages.", "Hi Roman, Equip Your Gym's wholesale and remanufactured facility packages are a strong match for factory-direct free weights. ChinaFreeWeight produces OEM dumbbells, weight plates and complete free-weight lines. Could we discuss supplying new private-label products alongside your commercial packages?"],
  [5, "Avi Freedman", "United States", "Founder & CEO", "The Fitness Outlet", "https://www.linkedin.com/in/avi-freedman", "https://thefitnessoutlet.com/", "https://www.facebook.com/TheFitnessOutlet", "https://www.instagram.com/thefitnessoutlet_/", "", "Commercial and residential strength, cardio and recovery equipment", "Multi-location commercial and residential fitness dealer", "A", "Founder of a multi-location dealer operating since 1993 with more than 50 represented brands, commercial services and strong review signals.", "Create a dependable private-label free-weight line for its retail and commercial channels.", "Hi Avi, The Fitness Outlet's multi-location commercial and residential business looks well suited to a reliable private-label strength range. ChinaFreeWeight is a dumbbell, weight-plate and free-weight factory with OEM capability. Would you be open to discussing cooperation on products for your stores and facility projects?"],
  [6, "Stuart Glenn", "United States", "CEO", "Body-Solid Inc.", "https://www.linkedin.com/in/stuartglenn", "https://bodysolid.com/", "https://www.facebook.com/BodySolidInc/", "https://www.instagram.com/bodysolidfit", "https://www.youtube.com/user/bodysoliddotcom", "Bars, weights, kettlebells, racks, functional, strength and cardio equipment", "Manufacturer-distributor with an established dealer network", "A+", "CEO of a major manufacturer-distributor with a large dealer network, extensive verified reviews and direct overlap across free-weight categories.", "Offer OEM overflow, alternate specifications or complementary free-weight SKUs.", "Hi Stuart, Body-Solid's established dealer network and broad bars-and-weights range are closely aligned with our factory capabilities. ChinaFreeWeight manufactures dumbbells, weight plates and free weights with OEM support. Could we explore cooperation on overflow production, new specifications or complementary SKUs?"],
  [7, "Martin Bruder", "United States", "President", "Push Pedal Pull", "https://www.linkedin.com/in/martin-bruder-76783536", "https://pushpedalpull.com/pages/commercial", "https://www.facebook.com/pushpedalpull", "https://www.instagram.com/push_pedal_pull/", "https://www.youtube.com/@pushpedalpull9371", "Commercial strength/cardio equipment, functional training, flooring and accessories", "Multi-state dealer and commercial facility integrator", "A", "President of a multi-state dealer operating since 1985 with procurement, design, installation and ongoing service for commercial facilities.", "Support regional project procurement with custom-branded bulk dumbbells and plates.", "Hi Martin, Push Pedal Pull's multi-state commercial projects and full facility service make dependable free-weight supply especially relevant. ChinaFreeWeight manufactures OEM dumbbells, weight plates and complete free-weight ranges. Could we discuss custom-branded bulk supply for your upcoming installations?"],
  [8, "Gordy Gronkowski", "United States", "President", "G&G Fitness Equipment, Inc.", "https://www.linkedin.com/in/gordy-gronkowski-94739130", "https://livefit.com/", "", "https://www.instagram.com/ggfitnesseq", "", "Dumbbells, weights, functional trainers, cardio equipment and storage", "Commercial/residential multi-location dealer with a private brand", "A", "President of an established dealer with a private fitness brand and direct demand for dumbbells, weights and storage products.", "Develop OEM dumbbell and plate products for G&G and Gronk-branded channels.", "Hi Gordy, G&G's commercial network and Gronk Fitness range appear well matched to factory-direct free weights. ChinaFreeWeight produces OEM dumbbells, weight plates and related free-weight products. Would you be open to discussing a branded line or additional specifications for your customers?"],
  [9, "Donnie Salum", "United States", "President", "Fitness Gallery", "https://www.linkedin.com/in/donnie-salum-54a89149", "https://www.fitnessgallery.com/", "https://www.facebook.com/fitnessequipmentdenver/", "https://www.instagram.com/fitnessgalleryshop/", "", "Home gyms, strength/cardio equipment, functional training and accessories", "Seven-location commercial and home fitness dealer", "A", "President of a seven-location Colorado dealer with commercial facility design, installation and service capability and positive location reviews.", "Broaden the strength portfolio with a coordinated private-label free-weight range.", "Hi Donnie, Fitness Gallery's seven locations and commercial design projects provide a strong channel for a coordinated free-weight assortment. ChinaFreeWeight is a dumbbell, weight-plate and free-weight factory offering OEM production. Could we discuss a private-label range for your retail and commercial customers?"],
  [10, "Frank Giannone", "United States", "President/Founder", "Fitnessmith Equipment Sales", "https://www.linkedin.com/in/frank-giannone-10549156", "https://fitnessmith.com/", "https://www.facebook.com/Fitnessmith360/", "https://www.instagram.com/fitnessmith360/", "", "Commercial strength/cardio equipment, functional training and facility solutions", "National commercial procurement, design and installation integrator", "A+", "Founder of a national commercial integrator with 125+ manufacturer relationships, distribution centers and project coverage across all 50 states.", "Provide scalable OEM free-weight supply and custom branding for large commercial projects.", "Hi Frank, Fitnessmith's national procurement and large commercial projects look like an excellent fit for scalable factory supply. ChinaFreeWeight manufactures OEM dumbbells, weight plates and full free-weight lines with custom branding. Could we discuss cooperation for upcoming facility rollouts?"],
  [11, "John Murray", "United States", "Owner", "Advantage Sport & Fitness, Inc.", "https://www.linkedin.com/in/john-murray-a1ab2915", "https://advantagefitness.com/", "https://www.facebook.com/AdvantageSportFitness/", "https://www.instagram.com/advantagesportandfitness/", "https://www.youtube.com/channel/UCa6qisK1YCamQauujUh8Tlg", "Commercial strength/cardio equipment, custom-branded products and facility services", "East Coast commercial equipment and facility-design provider", "A", "Owner of a verified East Coast commercial provider that offers custom branding, design, installation, maintenance and leasing.", "Supply custom-branded dumbbells and plates for facility design projects.", "Hi John, Advantage Sport & Fitness already supports custom-branded commercial facilities, which is a strong fit for our manufacturing. ChinaFreeWeight produces OEM dumbbells, weight plates and complete free-weight ranges. Would you be open to discussing custom products and reliable project supply?"],
  [12, "Richard Roberts", "United States", "President & CEO", "US Fitness Products", "https://www.linkedin.com/in/therichardroberts", "https://www.usfitness.com/", "https://www.facebook.com/usfitnessproducts/", "https://www.instagram.com/usfitnessproducts/", "https://www.youtube.com/user/usfitnessproducts/videos", "Strength/cardio equipment, flooring and commercial facility solutions", "Established multi-location commercial and residential dealer", "A+", "CEO of a well-reviewed, multi-location dealer with 45+ brands and full design, procurement, installation and service capabilities.", "Build an OEM free-weight range for multi-location retail and commercial procurement.", "Hi Richard, US Fitness Products' multi-location business and full commercial procurement service align well with a reliable OEM strength line. ChinaFreeWeight manufactures dumbbells, weight plates and other free weights. Could we discuss adding private-label products to your retail and facility projects?"],
  [13, "Christa Davis", "United States", "President", "Marathon Fitness", "https://www.linkedin.com/in/christa-davis-2b537016", "https://www.marathonfitness.com/", "https://www.facebook.com/TeamMarathonFitness/", "https://www.instagram.com/teammarathon_fitness", "https://www.youtube.com/channel/UC8NnlcyzoMYakUVLU4TWE-A/videos", "Commercial strength/cardio equipment, free weights and facility services", "Large commercial equipment provider and facility integrator", "A+", "President of a large provider serving more than 1,000 enterprise, institutional and hospitality facilities with strong reputation and procurement access.", "Offer reliable bulk OEM free weights for institutional and enterprise rollouts.", "Hi Christa, Marathon Fitness' large institutional and commercial projects are well suited to reliable bulk free-weight supply. ChinaFreeWeight manufactures OEM dumbbells, weight plates and complete free-weight lines with custom branding. Could we discuss cooperation for future facility rollouts?"],
  [14, "Jason Joseph", "United States", "Owner", "Commercial Fitness Products", "https://www.linkedin.com/in/jason-joseph-193649261", "https://commfitnessproducts.com/", "https://www.facebook.com/CommercialFitnessProducts", "https://www.instagram.com/commercialfitness/", "https://www.youtube.com/channel/UC2KQYYL01p7w7P3E7-f051A", "Plate-loaded equipment, plates, dumbbells, racks, accessories and group training", "Commercial fitness supplier and facility integrator", "B", "Owner of a verified commercial supplier whose catalog directly includes plates and dumbbells, with design, leasing, service and multiple facility segments.", "Expand the catalog with factory-direct OEM plates and dumbbells at project volumes.", "Hi Jason, Commercial Fitness Products already supplies plates, dumbbells and complete facility solutions, so our factory capabilities are directly relevant. ChinaFreeWeight produces OEM dumbbells, weight plates and free-weight ranges. Would you be open to discussing factory-direct supply for your commercial projects?"],
  [15, "Tim Brennan", "United States", "Founder", "Direct Fitness Solutions", "https://www.linkedin.com/in/tim-brennan-bb8790a", "https://directfitnesssolutions.com/", "https://www.facebook.com/DFSGetEquipped/", "https://www.instagram.com/dfsgetequipped/", "", "Commercial fitness equipment, flooring, facility design, installation and maintenance", "Midwest commercial equipment and flooring distributor", "A+", "Founder of a multi-state Midwest distributor established in 1998 with facility design, equipment, flooring, installation and maintenance capability.", "Add OEM free-weight packages to Midwest commercial facility solutions.", "Hi Tim, Direct Fitness Solutions' full facility and flooring projects are a strong channel for coordinated free-weight packages. ChinaFreeWeight manufactures OEM dumbbells, weight plates and free-weight products. Could we discuss a private-label or project-supply partnership for your Midwest customers?"],
  [16, "Leo Marangi", "United States", "CEO", "Primo Fitness", "https://www.linkedin.com/in/leomarangi", "https://primofitnessusa.com/", "https://www.facebook.com/primofitnessusa", "https://www.instagram.com/primofitnessusa/", "https://www.youtube.com/@PrimoFitnessUSA", "New/used commercial strength/cardio equipment, gym packages and customization", "Worldwide new and used commercial equipment supplier", "A", "CEO of a worldwide supplier offering wholesale equipment, customization, gym packages, delivery and installation with over 20 years of staff experience.", "Complement new and used packages with consistent OEM free-weight inventory.", "Hi Leo, Primo Fitness' worldwide new and used gym packages are a strong fit for consistent factory-direct free weights. ChinaFreeWeight manufactures OEM dumbbells, weight plates and related products. Could we discuss supplying a private-label range alongside your commercial packages?"],
  [17, "Michael Citrone", "United States", "Owner/Founder", "Global Fitness Inc.", "https://www.linkedin.com/in/michaelcitrone", "https://www.globalfitness.com/", "https://www.facebook.com/globalfitness", "https://www.instagram.com/globalfitnessinc/", "https://www.youtube.com/@Globalfitnessinc", "New, refurbished and used strength/cardio equipment, gym packages and customization", "Global remanufacturer and commercial equipment distributor", "A", "Founder of a verified distributor established in 1996 with a 120,000-square-foot warehouse, global clientele, remanufacturing and customization capability.", "Pair remanufactured equipment with new OEM dumbbells and plates for complete gym packages.", "Hi Michael, Global Fitness' remanufactured equipment and worldwide gym packages could benefit from a consistent new free-weight component. ChinaFreeWeight manufactures OEM dumbbells, weight plates and complete free-weight lines. Would you be open to discussing cooperation on private-label packages?"],
  [18, "Tim Adams", "United States", "Founder", "RX Fitness Equipment", "https://www.linkedin.com/in/tim-adams-172675b5", "https://rxfitnessequipment.com/", "https://www.facebook.com/Rxfitnessequipment/", "https://www.instagram.com/rxfitnessequipment/", "https://www.youtube.com/user/RXFitnessEquipment", "Premium cardio, strength equipment and fitness accessories", "Southern California commercial and home fitness retailer", "A+", "Founder of a multi-location retailer with exceptionally strong review signals and a verified premium commercial/home product range.", "Introduce branded or exclusive dumbbell and plate sets for two retail locations and commercial clients.", "Hi Tim, RX Fitness Equipment's premium product mix and excellent customer reputation make it a strong channel for an exclusive free-weight range. ChinaFreeWeight manufactures OEM dumbbells, weight plates and free weights. Could we discuss branded products for your retail and commercial customers?"],
  [19, "Nicholas Pugh", "United States", "President & CEO", "Fit4Sale.com", "https://www.linkedin.com/in/nicholas-pugh-80935b9", "https://fit4sale.com/", "https://www.facebook.com/fit4sale", "https://www.instagram.com/fit4sale/", "", "New/remanufactured equipment, weights, dumbbells, strength and cardio", "California commercial fitness equipment dealer and outlet", "A", "CEO of an established new and remanufactured equipment dealer with a 20,000-square-foot outlet and direct weights and dumbbells categories.", "Add new factory-direct OEM free weights beside remanufactured equipment inventory.", "Hi Nicholas, Fit4Sale's new and remanufactured commercial equipment mix is a natural fit for fresh factory-direct free weights. ChinaFreeWeight produces OEM dumbbells, weight plates and full free-weight lines. Could we discuss a private-label range for your outlet and commercial customers?"],
  [20, "Oliver Leith", "United States", "Owner", "Buy And Sell Fitness", "https://www.linkedin.com/in/oliverleith", "https://www.buyandsellfitness.com/", "https://www.facebook.com/BuyAndSellFitness/", "https://www.instagram.com/buyandsellfitness/", "https://www.youtube.com/user/BuyAndSellFitness", "New/used commercial gym equipment, installations, shipping and liquidations", "Worldwide commercial equipment purchaser and distributor", "B", "Owner of a worldwide equipment purchaser and distributor with nationwide shipping, installation capability and a large official social following.", "Combine liquidated equipment with new OEM free-weight packages for entrepreneurs opening gyms.", "Hi Oliver, Buy And Sell Fitness' work with entrepreneurs opening and expanding gyms is a strong fit for new factory-direct free weights. ChinaFreeWeight manufactures OEM dumbbells, weight plates and complete free-weight ranges. Could we discuss adding private-label products to your worldwide packages?"],
  [21, "Eric Swanson", "United States", "President", "American Home Fitness", "https://www.linkedin.com/in/eric-swanson-56394a15", "https://americanhomefitness.com/", "https://www.facebook.com/AmericanHomeFitness/", "", "", "Premium strength, cardio, free weights and home/commercial equipment", "Michigan multi-location home and commercial equipment provider", "B", "President of a verified multi-location provider with established Michigan coverage, premium equipment and both home and commercial positioning.", "Build a dependable private-label dumbbell and plate assortment for store and commercial sales.", "Hi Eric, American Home Fitness' multi-location strength and commercial offering appears well suited to a dependable private-label free-weight range. ChinaFreeWeight is a dumbbell, weight-plate and free-weight factory with OEM capability. Could we discuss products for your stores and commercial customers?"],
  [22, "Tom Noon", "United States", "President/Founder", "Fitness Exchange, Inc.", "https://www.linkedin.com/in/tom-noon-187b997", "https://fitnessexchange.com/", "https://www.facebook.com/FitnessExchange", "https://www.instagram.com/thefitnessexchange/", "https://www.youtube.com/channel/UCeCdBO4910-Uh68dMEvWTQw", "New/pre-owned free weights, benches, strength/cardio equipment and commercial services", "Multi-location home and commercial fitness dealer", "A+", "Founder of a highly rated multi-location dealer with commercial services and direct free-weight categories across new and pre-owned equipment.", "Add exclusive new OEM free weights to retail stores and commercial packages.", "Hi Tom, Fitness Exchange's strong reputation, multiple locations and direct free-weight category make it an excellent OEM fit. ChinaFreeWeight manufactures dumbbells, weight plates and complete free-weight lines. Could we discuss an exclusive or private-label range for your stores and commercial projects?"],
  [23, "Bob Lachniet", "United States", "Co-Owner/President", "Fitness 4 Home Superstore, Inc.", "https://www.linkedin.com/in/bob-lachniet-2102305", "https://fitness4home.com/", "https://www.facebook.com/Fitness4HomeSuperstore/", "https://www.instagram.com/fitness4homesuperstore/", "https://www.youtube.com/user/fitness4home", "Cardio, strength, functional trainers, free weights and facility services", "Arizona commercial and home dealer and facility integrator", "A", "Co-owner of a well-reviewed dealer offering free weights, commercial design, installation, financing and service across its Arizona market.", "Develop branded free weights for commercial installations and home-gym retail.", "Hi Bob, Fitness 4 Home's commercial installations and existing free-weight category are closely aligned with our manufacturing. ChinaFreeWeight produces OEM dumbbells, weight plates and complete free-weight ranges. Could we discuss a branded line for your Arizona stores and facility projects?"],
  [24, "Dusty Schlotfeldt", "United States", "Vice President", "Top Fitness Store", "https://www.linkedin.com/in/dustyschlotfeldt", "https://www.topfitness.com/", "https://www.facebook.com/topfitnessstores/", "https://www.instagram.com/topfitnessstore/", "", "Commercial/home strength and cardio equipment, planning, delivery and installation", "Multi-brand commercial and home fitness dealer group", "A", "Vice president across Top Fitness, Utah Home Fitness and Sacramento Exercise, with verified commercial planning, delivery and installation and strong reviews.", "Supply a coordinated OEM free-weight line across several regional retail brands.", "Hi Dusty, your role across Top Fitness, Utah Home Fitness and Sacramento Exercise creates a strong opportunity for a coordinated product line. ChinaFreeWeight manufactures OEM dumbbells, weight plates and free weights. Could we discuss a private-label range for the group's stores and commercial customers?"],
  [25, "Danny Valdez", "United States", "Owner", "Specialty Fitness Inc.", "https://www.linkedin.com/in/danny-valdez-3a38298", "https://www.specialtyfitnessequipment.com/", "https://www.facebook.com/SpecialtyFitnessEquipment/", "https://www.instagram.com/specialtyfitnessequipment", "", "Commercial, medical and residential equipment, dumbbells, benches and heavy-duty weights", "Commercial equipment supplier and amenity-design specialist", "B", "Owner of a verified commercial supplier with facility planning, design, education and financing; direct product overlap includes dumbbells, benches and heavy-duty weights.", "Provide OEM dumbbells and plates for designed commercial and residential amenities.", "Hi Danny, Specialty Fitness' commercial amenity design and heavy-duty weight range are a direct fit for our factory. ChinaFreeWeight manufactures OEM dumbbells, weight plates and complete free-weight products. Would you be open to discussing cooperation for your commercial and residential projects?"],
];

if (leads.length !== 25) throw new Error(`Expected 25 leads, found ${leads.length}`);
if (leads.some((row, index) => row.length !== 16 || row[0] !== index + 1)) throw new Error("Lead row shape or numbering is invalid");

const normalizedLinkedIn = leads.map((row) => row[5].toLowerCase().replace(/\/$/, ""));
const normalizedCompanies = leads.map((row) => row[4].toLowerCase().replace(/[^a-z0-9]/g, ""));
const personCompany = leads.map((row) => `${row[1].toLowerCase()}|${row[4].toLowerCase()}`);
for (const [label, values] of [["LinkedIn", normalizedLinkedIn], ["company", normalizedCompanies], ["person-company", personCompany]]) {
  if (new Set(values).size !== 25) throw new Error(`Duplicate ${label} detected`);
}
if (leads.some((row) => !["A+", "A", "B"].includes(row[12]))) throw new Error("Invalid quality score");
if (leads.some((row) => row.join(" ").includes("已添加至LC"))) throw new Error("Excluded LC label found");

const workbook = Workbook.create();
const daily = workbook.worksheets.add("Daily Report");
const history = workbook.worksheets.add("Lead History");
workbook.comments.setSelf({ displayName: "Kloe Du" });

daily.showGridLines = false;
history.showGridLines = false;
daily.getRange("A1:P26").values = [headers, ...leads];
const historyRows = leads.map((row) => [...row, new Date("2026-07-22T00:00:00+08:00")]);
history.getRange("A1:Q26").values = [[...headers, "Collection Date"], ...historyRows];

const dailyTable = daily.tables.add("A1:P26", true, "DailyLeadReport");
dailyTable.style = "TableStyleMedium2";
dailyTable.showFilterButton = true;
dailyTable.showBandedRows = true;
const historyTable = history.tables.add("A1:Q26", true, "LeadHistoryTable");
historyTable.style = "TableStyleMedium2";
historyTable.showFilterButton = true;
historyTable.showBandedRows = true;

const headerFormat = {
  fill: "#12304A",
  font: { bold: true, color: "#FFFFFF", size: 10 },
  horizontalAlignment: "center",
  verticalAlignment: "center",
  wrapText: true,
  borders: { bottom: { style: "medium", color: "#0B2032" } },
};
const bodyFormat = {
  font: { name: "Aptos", size: 10, color: "#1F2937" },
  verticalAlignment: "top",
  wrapText: true,
  borders: { insideHorizontal: { style: "thin", color: "#D9E2EA" } },
};

daily.getRange("A1:P1").format = headerFormat;
history.getRange("A1:Q1").format = headerFormat;
daily.getRange("A2:P26").format = bodyFormat;
history.getRange("A2:Q26").format = bodyFormat;
daily.getRange("A1:P1").format.rowHeight = 34;
history.getRange("A1:Q1").format.rowHeight = 34;
daily.getRange("A2:P26").format.rowHeight = 72;
history.getRange("A2:Q26").format.rowHeight = 72;
daily.freezePanes.freezeRows(1);
history.freezePanes.freezeRows(1);

const widths = [5, 20, 14, 22, 29, 43, 34, 34, 34, 34, 38, 35, 11, 55, 48, 72];
const letters = "ABCDEFGHIJKLMNOP".split("");
for (let i = 0; i < letters.length; i++) {
  daily.getRange(`${letters[i]}1:${letters[i]}26`).format.columnWidth = widths[i];
  history.getRange(`${letters[i]}1:${letters[i]}26`).format.columnWidth = widths[i];
}
history.getRange("Q1:Q26").format.columnWidth = 16;
history.getRange("Q2:Q26").format.numberFormat = "yyyy-mm-dd";

for (const range of [daily.getRange("A2:A26"), daily.getRange("C2:C26"), daily.getRange("M2:M26"), history.getRange("A2:A26"), history.getRange("C2:C26"), history.getRange("M2:M26"), history.getRange("Q2:Q26")]) {
  range.format.horizontalAlignment = "center";
}
for (const range of [daily.getRange("F2:J26"), history.getRange("F2:J26")]) {
  range.format.font = { name: "Aptos", size: 9, color: "#0563C1" };
}
for (const sheet of [daily, history]) {
  const scoreRange = sheet.getRange("M2:M26");
  scoreRange.conditionalFormats.addCustom('=$M2="A+"', { fill: "#C6EFCE", font: { bold: true, color: "#006100" } });
  scoreRange.conditionalFormats.addCustom('=$M2="A"', { fill: "#DDEBF7", font: { bold: true, color: "#1F4E78" } });
  scoreRange.conditionalFormats.addCustom('=$M2="B"', { fill: "#FFF2CC", font: { bold: true, color: "#7F6000" } });
}

await fs.mkdir(previewDir, { recursive: true });
const dailyInspect = await workbook.inspect({ kind: "table", range: "Daily Report!A1:P26", include: "values,formulas", tableMaxRows: 30, tableMaxCols: 16, maxChars: 12000 });
const historyInspect = await workbook.inspect({ kind: "table", range: "Lead History!A1:Q26", include: "values,formulas", tableMaxRows: 6, tableMaxCols: 17, maxChars: 5000 });
const errors = await workbook.inspect({ kind: "match", searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A", options: { useRegex: true, maxResults: 300 }, summary: "final formula error scan", maxChars: 4000 });
console.log("DAILY_INSPECT", dailyInspect.ndjson);
console.log("HISTORY_INSPECT", historyInspect.ndjson);
console.log("ERROR_SCAN", errors.ndjson);

for (const [sheetName, fileName] of [["Daily Report", "daily-report.png"], ["Lead History", "lead-history.png"]]) {
  const preview = await workbook.render({ sheetName, range: sheetName === "Daily Report" ? "A1:P10" : "A1:Q10", scale: 0.8, format: "png" });
  await fs.writeFile(`${previewDir}/${fileName}`, new Uint8Array(await preview.arrayBuffer()));
}

const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(outputPath);
console.log(`SAVED ${outputPath}`);

