import { contentAutomationConfig } from "./config";
import type {
  AutomatedContentDocument,
  DocumentQualityResult,
  QualityIssue,
  VersionQualityResult,
} from "./types";
import type { LocalizedContentVersion } from "../lib/content/types";

const forbiddenToken = /(^|[^\p{L}\p{N}])(SEO|GEO|AIO|AI)(?=$|[^\p{L}\p{N}])/giu;
const forbiddenPhrases = [
  "search engine optimization", "generative engine optimization", "answer engine optimization", "artificial intelligence",
  "otimização para mecanismos de busca", "inteligência artificial",
  "optimización para motores de búsqueda", "inteligencia artificial",
  "suchmaschinenoptimierung", "künstliche intelligenz",
  "optimisation pour les moteurs de recherche", "intelligence artificielle",
  "tối ưu hóa công cụ tìm kiếm", "trí tuệ nhân tạo",
  "sökmotoroptimering", "artificiell intelligens",
  "ottimizzazione per i motori di ricerca", "intelligenza artificiale",
  "zoekmachineoptimalisatie", "kunstmatige intelligentie",
  "검색 엔진 최적화", "인공 지능",
  "optimasi mesin pencari", "kecerdasan buatan",
  "optymalizacja dla wyszukiwarek", "sztuczna inteligencja",
];
const processPhrases = [
  "generated by", "generation prompt", "writing prompt", "draft copy", "ranking guarantee", "indexing guarantee",
  "backend note", "developer note", "seo analysis", "keyword stuffing",
];

function visibleFields(version: LocalizedContentVersion) {
  return [
    ["title", version.title], ["description", version.description], ["h1", version.h1],
    ...version.body.flatMap((block) => [
      [`body.${block.id}.heading`, block.heading || ""],
      [`body.${block.id}.content`, block.content || ""],
      [`body.${block.id}.data`, JSON.stringify(block.data || {})],
    ] as Array<[string, string]>),
    ...version.faq.flatMap((item) => [[`faq.${item.id}.question`, item.question], [`faq.${item.id}.answer`, item.answer]] as Array<[string, string]>),
    ...version.images.flatMap((item) => [[`image.${item.id}.src`, item.src], [`image.${item.id}.alt`, item.alt], [`image.${item.id}.caption`, item.caption || ""]] as Array<[string, string]>),
    ...version.internalLinks.map((item) => [`link.${item.targetContentId}`, item.label] as [string, string]),
    ["schemaData", JSON.stringify(version.schemaData)],
  ] as Array<[string, string]>;
}

export function scanCustomerVisibleText(version: LocalizedContentVersion): QualityIssue[] {
  const issues: QualityIssue[] = [];
  for (const [field, value] of visibleFields(version)) {
    forbiddenToken.lastIndex = 0;
    const lower = value.normalize("NFKC").toLocaleLowerCase();
    const tokenMatch = forbiddenToken.exec(value);
    const phrase = [...forbiddenPhrases, ...processPhrases].find((item) => lower.includes(item));
    if (tokenMatch || phrase) {
      issues.push({ code: "visible-forbidden-term", field, hard: true, message: `Forbidden customer-visible language in ${field}.` });
    }
  }
  return issues;
}

function paragraphCount(version: LocalizedContentVersion) {
  return version.body.reduce((count, block) => {
    const parts = (block.content || "").split(/\n\s*\n|<\/p>/i).map((part) => part.replace(/<[^>]+>/g, "").trim()).filter(Boolean);
    return count + parts.length;
  }, 0);
}

function sameLocaleLinkCount(version: LocalizedContentVersion) {
  return version.internalLinks.length;
}

function wordCount(version: LocalizedContentVersion) {
  return version.body.map((block) => `${block.heading || ""} ${block.content || ""}`).join(" ").trim().split(/\s+/).filter(Boolean).length;
}

function koreanCharacterCount(version: LocalizedContentVersion) {
  return (version.body.map((block) => `${block.heading || ""}${block.content || ""}`).join("").match(/[\uac00-\ud7a3]/g) || []).length;
}

function components(version: LocalizedContentVersion) {
  return new Set(version.body.map((block) => block.data?.component).filter((value): value is string => typeof value === "string"));
}

function add(issues: QualityIssue[], condition: boolean, code: string, message: string, hard = true) {
  if (!condition) issues.push({ code, message, hard });
}

export function validateVersion(document: AutomatedContentDocument, version: LocalizedContentVersion): VersionQualityResult {
  const issues = scanCustomerVisibleText(version);
  const sectionCount = version.body.filter((block) => block.heading?.trim()).length;
  add(issues, version.title.trim().length > 0 && version.h1.trim().length > 0, "missing-title", "Title and H1 are required.");
  add(issues, version.title.trim() !== version.description.trim(), "metadata-duplicate", "Title and description must be distinct.");
  add(issues, version.canonicalData.mode === "self", "canonical", "Canonical must be self-referencing.");
  add(issues, version.hreflangData.include, "hreflang", "Equivalent localized versions must opt into hreflang.");
  add(issues, sectionCount >= 6, "sections", "At least six substantive sections are required.");
  add(issues, paragraphCount(version) >= 12, "paragraphs", "At least twelve substantive paragraphs are required.");
  add(issues, version.faq.length === 5, "faq-count", "Exactly five substantive FAQ entries are required.");
  add(issues, sameLocaleLinkCount(version) >= 4 && sameLocaleLinkCount(version) <= 8, "internal-links", "Four to eight same-language internal links are required.");
  add(issues, document.sources.length >= 3, "sources", "At least three traceable sources are required.");
  add(issues, document.sources.some((source) => source.confidence === "primary"), "primary-source", "At least one primary or official source is required.");
  add(issues, version.images.length >= 1, "images", "At least one relevant image is required.");
  add(issues, version.images.every((image) => Boolean(image.alt.trim()) && /\.(avif|webp)(\?.*)?$/i.test(image.src)), "image-format", "Every image needs ALT text and WebP or AVIF format.");
  add(issues, version.images.every((image) => document.assets.some((asset) => asset.src === image.src && asset.httpStatus === 200 && asset.licenseOrOwner && asset.checksum)), "image-evidence", "Every image needs ownership, checksum, dimensions, and HTTP verification.");
  add(issues, version.images.every((image) => document.assets.some((asset) => asset.src === image.src && asset.width >= 800 && asset.height >= 450 && asset.bytes <= 500_000)), "image-size", "Every image must meet dimension and compressed-size limits.");
  add(issues, version.images.every((image) => /^[a-z0-9]+(?:-[a-z0-9]+)*\.(?:webp|avif)(?:\?.*)?$/i.test(image.src.split("/").pop() || "")), "image-filename", "Image filenames must be descriptive, lowercase, and hyphenated.");
  const uniqueHeadings = new Set([version.h1, ...version.body.map((block) => block.heading).filter(Boolean)].map((value) => value?.trim().toLocaleLowerCase()));
  add(issues, uniqueHeadings.size === sectionCount + 1, "duplicate-headings", "H1 and section headings must be unique.");
  const contentComponents = components(version);
  if (document.entity.type === "blog") {
    if (version.locale === "ko") add(issues, koreanCharacterCount(version) >= 3000, "localized-depth", "Korean editorial depth is below the required equivalent threshold.");
    else add(issues, wordCount(version) >= 1400 && wordCount(version) <= 2400, "word-depth", "Latin-script blog copy must contain 1,400 to 2,400 words.");
    add(issues, contentComponents.has("quick-answer"), "direct-answer", "A direct answer section is required.");
    add(issues, version.body.some((block) => block.type === "specifications") || contentComponents.has("decision-framework"), "decision-framework", "A comparison table or decision framework is required.");
    add(issues, contentComponents.has("risk-boundary"), "risk-boundary", "A clear risk boundary is required.");
    add(issues, version.body.some((block) => block.type === "cta"), "cta", "A buyer inquiry CTA is required.");
  }
  if (document.entity.type === "case") {
    const mode = document.entity.versions[version.locale]?.schemaData.extra?.solutionMode;
    add(issues, mode === "configuration" || mode === "procurement" || mode === "application" || mode === "verified-case", "case-mode", "Solution pages must declare a truthful content mode.");
    if (mode === "verified-case") {
      add(issues, Boolean(document.realCaseEvidence?.authorized && document.realCaseEvidence.projectReference && document.realCaseEvidence.photoAssetChecksums.length), "case-evidence", "A verified case requires authorization, a project reference, and matching photos.");
    }
    for (const required of ["scenario-assumptions", "product-configuration", "specification-selection", "quantity-plan", "risk-boundary", "oem-packaging", "inquiry-checklist"]) {
      add(issues, contentComponents.has(required), `solution-${required}`, `Solution page is missing required section: ${required}.`);
    }
  }
  const hardFailures = issues.filter((issue) => issue.hard).length;
  const score = Math.max(0, 100 - hardFailures * 8);
  return { locale: version.locale, publicPath: version.publicPath, score, passed: hardFailures === 0 && score >= contentAutomationConfig.minimumQualityScore, issues };
}

function shingles(value: string, size = 4) {
  const words = value.toLocaleLowerCase().replace(/[^\p{L}\p{N}\s]/gu, " ").split(/\s+/).filter(Boolean);
  return new Set(words.length < size ? [words.join(" ")] : words.slice(0, -size + 1).map((_, i) => words.slice(i, i + size).join(" ")));
}

export function semanticSimilarity(left: string, right: string) {
  const a = shingles(left); const b = shingles(right);
  if (!a.size && !b.size) return 1;
  const intersection = [...a].filter((item) => b.has(item)).length;
  return intersection / (a.size + b.size - intersection);
}

export function validateDocument(document: AutomatedContentDocument, existing: AutomatedContentDocument[] = []): DocumentQualityResult {
  const versions = Object.values(document.entity.versions).filter(Boolean).map((version) => validateVersion(document, version!));
  for (const other of existing) {
    for (const version of Object.values(document.entity.versions).filter(Boolean)) {
      const peer = other.entity.versions[version!.locale];
      if (!peer) continue;
      const duplicateSlug = peer.slug === version!.slug || peer.publicPath === version!.publicPath;
      const duplicateTitle = peer.title.trim().toLocaleLowerCase() === version!.title.trim().toLocaleLowerCase() || peer.h1.trim().toLocaleLowerCase() === version!.h1.trim().toLocaleLowerCase();
      const intents = new Set(document.research.filter((item) => item.languageCode === version!.locale || item.languageCode === version!.locale.split("-")[0]).map((item) => item.intent.trim().toLocaleLowerCase()));
      const duplicateIntent = other.research.some((item) => intents.has(item.intent.trim().toLocaleLowerCase()));
      const left = version!.body.map((block) => `${block.heading || ""} ${block.content || ""}`).join(" ");
      const right = peer.body.map((block) => `${block.heading || ""} ${block.content || ""}`).join(" ");
      if (duplicateSlug || duplicateTitle || duplicateIntent || semanticSimilarity(left, right) > contentAutomationConfig.semanticSimilarityLimit) {
        const result = versions.find((item) => item.locale === version!.locale)!;
        result.issues.push({ code: duplicateSlug ? "duplicate-slug" : duplicateTitle ? "duplicate-title" : duplicateIntent ? "duplicate-intent" : "semantic-duplicate", message: "The localized page conflicts with existing content.", hard: true });
        result.score = Math.max(0, result.score - 8);
        result.passed = false;
      }
    }
  }
  return { entityId: document.entity.id, passed: versions.length > 0 && versions.every((version) => version.passed), versions };
}
